export type UniVisionMetrics={pixelCount:number;rMean:number;gMean:number;bMean:number;lMean:number;aMean:number;labBMean:number;lStd:number;aStd:number;bStd:number;chroma:number;hueDeg:number}
export type SegmentationConfidence='good'|'review'
export type UniVisionMaskMode='focused'|'broad'
export type UniVisionRoi={x:number;y:number;width:number;height:number;source:'tray'|'default'}
export type UniVisionSegmentation={metrics:UniVisionMetrics;usableRatio:number;borderCandidateRatio:number;confidence:SegmentationConfidence;maskMode:UniVisionMaskMode;previewDataUrl:string;retainedComponents:number;suppressedFramePixels:number;filledHolePixels:number;recoveredEdgePixels:number;roi:UniVisionRoi;segmentationVersion:'v4.1'}
type RemoteMask={cols:number;rows:number;stride:number;originX:number;originY:number;dataBase64:string}
type RemoteSegmentation=Omit<UniVisionSegmentation,'previewDataUrl'>&{mask:RemoteMask}
type Payload={segmentation?:RemoteSegmentation;error?:string}

function bytesToBase64(bytes:Uint8Array|Uint8ClampedArray){let binary='';const chunk=0x8000;for(let offset=0;offset<bytes.length;offset+=chunk)binary+=String.fromCharCode(...bytes.subarray(offset,Math.min(bytes.length,offset+chunk)));return btoa(binary)}
function base64ToBytes(value:string){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes}
function analysisCanvas(source:HTMLCanvasElement){const scale=Math.min(1,720/source.width,540/source.height),canvas=document.createElement('canvas');canvas.width=Math.max(16,Math.round(source.width*scale));canvas.height=Math.max(16,Math.round(source.height*scale));const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)throw new Error('Canvas no disponible');context.drawImage(source,0,0,canvas.width,canvas.height);return canvas}
function payloadFor(canvas:HTMLCanvasElement){const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)throw new Error('Canvas no disponible');const frame=context.getImageData(0,0,canvas.width,canvas.height);return JSON.stringify({width:canvas.width,height:canvas.height,rgbaBase64:bytesToBase64(frame.data)})}
function finalize(canvas:HTMLCanvasElement,payload:Payload){if(!payload.segmentation)throw new Error(payload.error??'No fue posible analizar la captura visual');const {mask,...segmentation}=payload.segmentation;return{...segmentation,previewDataUrl:maskPreview(canvas,mask,segmentation.roi)}}
function maskPreview(canvas:HTMLCanvasElement,mask:RemoteMask,roi:UniVisionRoi){const data=base64ToBytes(mask.dataBase64);if(data.length!==mask.cols*mask.rows)return canvas.toDataURL('image/jpeg',.86);const scale=Math.min(1,480/canvas.width,360/canvas.height),out=document.createElement('canvas');out.width=Math.max(1,Math.round(canvas.width*scale));out.height=Math.max(1,Math.round(canvas.height*scale));const context=out.getContext('2d',{willReadFrequently:true});if(!context)return canvas.toDataURL('image/jpeg',.86);context.drawImage(canvas,0,0,out.width,out.height);const image=context.getImageData(0,0,out.width,out.height);for(let y=0;y<out.height;y++)for(let x=0;x<out.width;x++){const sourceX=x/scale,sourceY=y/scale,gx=Math.floor((sourceX-mask.originX)/mask.stride),gy=Math.floor((sourceY-mask.originY)/mask.stride),inside=sourceX>=roi.x&&sourceX<roi.x+roi.width&&sourceY>=roi.y&&sourceY<roi.y+roi.height,product=inside&&gx>=0&&gy>=0&&gx<mask.cols&&gy<mask.rows&&data[gy*mask.cols+gx]===1;if(product)continue;const i=(y*out.width+x)*4;image.data[i]=Math.round(image.data[i]*.18+205);image.data[i+1]=Math.round(image.data[i+1]*.18+205);image.data[i+2]=Math.round(image.data[i+2]*.18+205)}context.putImageData(image,0,0);if(roi.source==='tray'){context.strokeStyle='rgba(120,240,220,.85)';context.lineWidth=Math.max(1,2*scale);context.strokeRect(roi.x*scale,roi.y*scale,roi.width*scale,roi.height*scale)}return out.toDataURL('image/jpeg',.86)}

export async function requestUniVisionSegmentation(source:HTMLCanvasElement):Promise<UniVisionSegmentation>{const canvas=analysisCanvas(source),response=await fetch('/api/uni-vision-segmentation',{method:'POST',headers:{'Content-Type':'application/json'},body:payloadFor(canvas)}),payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error??'No fue posible analizar la captura visual');return finalize(canvas,payload)}
export function requestUniVisionSegmentationSync(source:HTMLCanvasElement):UniVisionSegmentation{const canvas=analysisCanvas(source),request=new XMLHttpRequest();request.open('POST','/api/uni-vision-segmentation',false);request.setRequestHeader('Content-Type','application/json');request.send(payloadFor(canvas));let payload:Payload={};try{payload=JSON.parse(request.responseText||'{}') as Payload}catch{throw new Error('No fue posible analizar la captura visual')}if(request.status<200||request.status>=300)throw new Error(payload.error??'No fue posible analizar la captura visual');return finalize(canvas,payload)}
