import {expect,test,type Page} from '@playwright/test'

async function mockOperations(page:Page){
  await page.route('**/api/**',async route=>{
    const path=new URL(route.request().url()).pathname
    if(path==='/api/auth')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,operator:{id:'qa-operations',fullName:'QA Operaciones',email:'operations@example.test',role:'operations',plantIds:['ancud']}})})
    if(path==='/api/receptions')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({receptions:[]})})
    if(path==='/api/history')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({records:[],summary:{total:0,guide_kg:0,received_kg:0,flagged:0}})})
    if(path==='/api/status')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,platform:'vercel-functions',environment:'test',persistence:{database:true,files:true},metrics:{pendingDecisions:0,pendingCredits:0,activeOperators:1,receptions:0},commit:'qa',checkedAt:new Date().toISOString()})})
    if(path==='/api/production-lines')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({lines:[]})})
    if(path==='/api/operations-overview')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({balances:[],inventory:{coverage:'live',items:[],summary:{totalKg:0,rawKg:0,processedKg:0}},economics:{marginAvailable:false,reason:'Sin ventas vinculadas',historicalCoverage:{operationalRecords:0,pricedRecords:0,pricedPct:0,pricedKg:0,rawMaterialCostClp:0},historicalBySupplier:[]}})})
    if(path==='/api/inventory')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({locations:[],lots:[],movements:[],permissions:{canWrite:true}})})
    if(path==='/api/canonical-inventory-evidence')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({stock:[],packing:[],lotLinks:[],summary:{stockRows:0,packingBoxes:0,packingKg:0,packingLots:0,matchedLots:0,unmatchedLots:0},governance:{rule:'Evidencia separada'}})})
    if(path==='/api/credits')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,credits:[]})})
    if(path==='/api/canonical-finance-evidence')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ledger:{rows:0,flagged:0,inflow_clp:0,outflow_clp:0,final_balance_clp:0},transfers:{rows:0,flagged:0,amount_clp:0},matching:{transfers:0,exact_matches:0,unmatched:0,ambiguous:0,exact_match_amount_clp:0},governance:{rule:'Evidencia separada'}})})
    return route.fulfill({status:200,contentType:'application/json',body:'{}'})
  })
}

test('820px shell uses the navigation drawer instead of an icon-only rail',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-chromium','Tablet-width regression is exercised once on Chromium')
  await page.setViewportSize({width:820,height:900})
  await mockOperations(page)
  await page.goto('/lineas')
  const trigger=page.getByRole('button',{name:'Abrir menú'})
  await expect(trigger).toBeVisible()
  const sidebar=page.locator('.sidebar')
  expect(await sidebar.evaluate(element=>getComputedStyle(element).position)).toBe('fixed')
  expect(await sidebar.evaluate(element=>Number.parseFloat(getComputedStyle(element).width))).toBeLessThanOrEqual(320)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)
  await trigger.click()
  await expect(sidebar).toHaveClass(/is-open/)
  await expect(page.getByRole('link',{name:'Operación',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Cerrar menú'})).toBeVisible()
  await page.screenshot({path:testInfo.outputPath('tablet-production-drawer.png'),fullPage:true})
})

test('production live workspace precedes analytical balance and nested KPI framing is flat',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-chromium','Visual hierarchy contract is exercised once on Chromium')
  await mockOperations(page)
  await page.goto('/lineas/detalle')
  const workspace=page.locator('.production-workspace'),balance=page.locator('.balance-panel')
  await expect(workspace).toBeVisible()
  await expect(balance).toBeVisible()
  const [workspaceBox,balanceBox]=await Promise.all([workspace.boundingBox(),balance.boundingBox()])
  expect(workspaceBox&&balanceBox?workspaceBox.y<balanceBox.y:false).toBe(true)
  const firstKpi=balance.locator('.balance-summary>div').first()
  expect(await firstKpi.evaluate(element=>getComputedStyle(element).borderRadius)).toBe('0px')
  expect(await firstKpi.evaluate(element=>getComputedStyle(element).backgroundColor)).toBe('rgba(0, 0, 0, 0)')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)
  await page.screenshot({path:testInfo.outputPath('production-live-before-analysis.png'),fullPage:true})
})

test('inventory live position precedes one canonical read-only evidence section',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-chromium','Visual hierarchy contract is exercised once on Chromium')
  await mockOperations(page)
  await page.goto('/inventario/detalle')
  const workspace=page.locator('.inventory-workspace'),evidence=page.locator('.canonical-inventory-evidence')
  await expect(workspace).toBeVisible()
  await expect(evidence).toHaveCount(1)
  await expect(evidence).toBeVisible()
  const [workspaceBox,evidenceBox]=await Promise.all([workspace.boundingBox(),evidence.boundingBox()])
  expect(workspaceBox&&evidenceBox?workspaceBox.y<evidenceBox.y:false).toBe(true)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBe(false)
  await page.screenshot({path:testInfo.outputPath('inventory-live-before-evidence.png'),fullPage:true})
})

test('credits show operational requests before one canonical finance evidence section',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-chromium','Visual hierarchy contract is exercised once on Chromium')
  await mockOperations(page)
  await page.goto('/creditos')
  const workspace=page.locator('.credit-layout'),evidence=page.getByRole('region',{name:'Evidencia canónica CUENTA2'})
  await expect(workspace).toBeVisible()
  await expect(evidence).toHaveCount(1)
  await expect(evidence).toBeVisible()
  const [workspaceBox,evidenceBox]=await Promise.all([workspace.boundingBox(),evidence.boundingBox()])
  expect(workspaceBox&&evidenceBox?workspaceBox.y<evidenceBox.y:false).toBe(true)
  await page.screenshot({path:testInfo.outputPath('credits-operational-before-evidence.png'),fullPage:true})
})

test('reception provenance band remains secondary and unframed',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-chromium','Visual hierarchy contract is exercised once on Chromium')
  await mockOperations(page)
  await page.goto('/recepciones')
  const history=page.locator('details.receptions-history')
  await expect(history).toBeVisible()
  await history.locator('summary').click()
  await expect(history).toHaveAttribute('open','')
  const band=history.locator('.data-continuity-banner.compact')
  await expect(band).toBeVisible()
  expect(await band.evaluate(element=>getComputedStyle(element).borderRadius)).toBe('0px')
  expect(await band.evaluate(element=>getComputedStyle(element).backgroundColor)).toBe('rgba(0, 0, 0, 0)')
  await page.screenshot({path:testInfo.outputPath('receptions-provenance-band.png'),fullPage:true})
})
