import { AlertTriangle, Check, Clock3, MessageSquareText, Scale, Snowflake, X } from 'lucide-react'
import { useState } from 'react'
import { PageHeader } from '../components/PageHeader'

type Decision='Pendiente'|'Aprobado'|'Rechazado'
type Approval={id:string;title:string;detail:string;module:string;priority:'Alta'|'Normal';owner:string;time:string;decision:Decision;icon:typeof Scale}
const seed:Approval[]=[
  {id:'APR-377',title:'Recepción superior a la guía',detail:'Lote md330080925 · 399,6 kg en guía y 482,0 kg recibidos.',module:'Recepción',priority:'Alta',owner:'Jefe de planta',time:'Dato canónico 2025',decision:'Pendiente',icon:Scale},
  {id:'APR-143',title:'Guía usada como respaldo',detail:'Lote md137170625 · documento utilizado para reempacar sin producto nuevo.',module:'Producción',priority:'Alta',owner:'Administración',time:'Dato canónico 2025',decision:'Pendiente',icon:Snowflake},
  {id:'APR-006',title:'Hallazgo de cuerpo extraño',detail:'Lote mo04080425 · observación registra vidrio y tijereta.',module:'Calidad',priority:'Alta',owner:'Calidad',time:'Dato canónico 2025',decision:'Pendiente',icon:AlertTriangle}
]

export function Approvals(){const [items,setItems]=useState(seed);const [comments,setComments]=useState<Record<string,string>>({});const decide=(id:string,decision:Decision)=>setItems(current=>current.map(item=>item.id===id?{...item,decision}:item));const pending=items.filter(item=>item.decision==='Pendiente').length;return <><PageHeader eyebrow="Trabajo por excepción" title="Bandeja de aprobaciones" description="Una sola cola para aprobar, rechazar o comentar decisiones de todos los módulos."/><section className="approval-summary"><div><b>{pending}</b><span>Pendientes</span></div><div><b>2</b><span>Alta prioridad</span></div><div><b>6 min</b><span>Tiempo medio</span></div><div><b>5</b><span>Responsables</span></div></section><section className="approval-list">{items.map(item=>{const Icon=item.icon;return <article className={`panel approval-card ${item.decision!=='Pendiente'?'resolved':''}`} key={item.id}><div className="approval-symbol"><Icon size={19}/></div><div className="approval-copy"><header><div><span className="overline teal">{item.module} · {item.id}</span><h2>{item.title}</h2></div><span className={`priority ${item.priority==='Alta'?'high':''}`}>{item.priority}</span></header><p>{item.detail}</p><div className="approval-meta"><span><Clock3 size={13}/>{item.time}</span><span>Decide: <b>{item.owner}</b></span></div>{item.decision==='Pendiente'?<div className="decision-row"><label><MessageSquareText size={15}/><input value={comments[item.id]??''} onChange={event=>setComments(current=>({...current,[item.id]:event.target.value}))} placeholder="Agregar comentario o instrucción…"/></label><button className="decision reject" onClick={()=>decide(item.id,'Rechazado')}><X size={15}/>Rechazar</button><button className="decision approve" onClick={()=>decide(item.id,'Aprobado')}><Check size={15}/>Aprobar</button></div>:<div className={`decision-result ${item.decision==='Aprobado'?'approved':''}`}><b>{item.decision}</b><span>{comments[item.id]||'Sin comentario adicional'}</span></div>}</div></article>})}</section></>}
