import { CircleDollarSign, FileText, Landmark, LoaderCircle, Plus, ShieldCheck, WalletCards, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { PageHeader } from '../components/PageHeader'

type CreditRow={id:string;request_number:string;fisher:string;amount_clp:string;reason:string;recovery_kind:'percentage'|'fixed_amount'|'full_balance';recovery_value:string|null;status:'pending'|'approved'|'rejected';requested_at:string;account_balance_clp:string}
type CreditsResponse={ok:boolean;credits?:CreditRow[];error?:string}
const money=(value:number)=>value.toLocaleString('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0})
const recoveryLabels={percentage:'Porcentaje por entrega',fixed_amount:'Monto fijo por entrega',full_balance:'Saldo completo'} as const
const statusLabels={pending:'Pendiente',approved:'Aprobado',rejected:'Rechazado'} as const

export function Credits(){
  const [credits,setCredits]=useState<CreditRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[saving,setSaving]=useState(false)
  const [fisher,setFisher]=useState(''),[amount,setAmount]=useState(0),[reason,setReason]=useState('')
  const [recoveryKind,setRecoveryKind]=useState<CreditRow['recovery_kind']>('percentage'),[recoveryValue,setRecoveryValue]=useState(0)
  const formRef=useRef<HTMLFormElement|null>(null),fisherRef=useRef<HTMLInputElement|null>(null),previousFocus=useRef<HTMLElement|null>(null),savingRef=useRef(false)
  const load=useCallback(async()=>{try{const response=await fetch('/api/credits',{cache:'no-store'});const data=await response.json() as CreditsResponse;if(!response.ok)throw new Error(data.error);setCredits(data.credits??[]);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible consultar los créditos')}finally{setLoading(false)}},[])
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
  useEffect(()=>{savingRef.current=saving},[saving])
  useEffect(()=>{if(!open)return;setFisher('');setAmount(0);setReason('');setRecoveryKind('percentage');setRecoveryValue(0);setError('');setSaving(false);previousFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';const frame=window.requestAnimationFrame(()=>fisherRef.current?.focus());const onKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!savingRef.current){event.preventDefault();setOpen(false);return}if(event.key!=='Tab')return;const focusable=Array.from(formRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),summary,[tabindex]:not([tabindex="-1"])')??[]).filter(element=>element.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener('keydown',onKeyDown);return()=>{window.cancelAnimationFrame(frame);document.removeEventListener('keydown',onKeyDown);document.body.style.overflow=previousOverflow;const target=previousFocus.current;if(target&&document.contains(target))target.focus()}},[open])
  const balances=useMemo(()=>new Map(credits.map(row=>[row.fisher,Number(row.account_balance_clp)])),[credits])
  const totalBalance=useMemo(()=>[...balances.values()].reduce((sum,value)=>sum+value,0),[balances])

  async function submit(event:FormEvent){
    event.preventDefault();setSaving(true);setError('')
    try{const response=await fetch('/api/credits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fisher,amount,reason,recoveryKind,recoveryValue:recoveryKind==='full_balance'?null:recoveryValue})});const data=await response.json() as CreditsResponse;if(!response.ok)throw new Error(data.error);setOpen(false);await load()}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible registrar la solicitud')}finally{setSaving(false)}
  }

  return <><PageHeader eyebrow="Cuenta corriente artesanal" title="Créditos y anticipos" description="Anticipos reales a pescadores y proveedores, recuperados mediante descuentos trazables en sus liquidaciones." actions={<button className="button primary" onClick={()=>setOpen(true)}><Plus size={16}/>Registrar solicitud</button>}/>
    <section className="credit-summary"><Summary icon={<WalletCards/>} label="Saldo documentado" value={loading?'—':money(totalBalance)} note="Movimientos contabilizados"/><Summary icon={<CircleDollarSign/>} label="Solicitudes registradas" value={loading?'—':String(credits.length)} note="Base de datos operativa"/><Summary icon={<ShieldCheck/>} label="Pendientes de aprobación" value={loading?'—':String(credits.filter(row=>row.status==='pending').length)} note="Requieren comentario"/><Summary icon={<FileText/>} label="Cuentas activas" value={loading?'—':String(balances.size)} note="Pescadores o proveedores"/></section>
    {error&&!open?<div className="notice error"><b>No se pudo cargar la fuente real.</b> {error}</div>:null}
    <section className="credit-layout"><article className="panel credit-accounts"><header className="panel-header"><h2>Solicitudes registradas</h2><span>Sin datos precargados ni demostrativos</span></header>{loading?<div className="empty-state"><LoaderCircle className="spin" size={30}/><h3>Consultando base de datos</h3></div>:credits.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Solicitud</th><th>Pescador o proveedor</th><th className="numeric">Monto</th><th>Recuperación</th><th>Estado</th></tr></thead><tbody>{credits.map(request=><tr key={request.id}><td><b>ANT-{request.request_number}</b><small>{request.reason}</small></td><td><b>{request.fisher}</b><small>{new Date(request.requested_at).toLocaleDateString('es-CL')}</small></td><td className="numeric"><b>{money(Number(request.amount_clp))}</b></td><td>{recoveryLabels[request.recovery_kind]}{request.recovery_value?<small>{request.recovery_kind==='percentage'?`${request.recovery_value}%`:money(Number(request.recovery_value))}</small>:null}</td><td><span className={`status ${request.status==='pending'?'warning':''}`}>{statusLabels[request.status]}</span></td></tr>)}</tbody></table></div>:<div className="empty-state"><Landmark size={30}/><h3>No hay créditos documentados</h3><p>La base está vacía. Registra el primer anticipo únicamente cuando exista una solicitud efectiva y respaldada.</p></div>}</article>
      <article className="panel settlement-card"><span className="overline teal">Liquidación</span><h2>Recuperación automática</h2><p>Al aprobar una liquidación, el sistema aplicará la regla del anticipo y registrará el descuento como movimiento separado. Nunca modificará el peso ni el precio del producto.</p></article></section>
    <section className="panel credit-policy"><header><Landmark size={20}/><div><h2>Política inicial configurada</h2><p>Sin intereses · recuperación configurable · desembolso solo después de aprobación de Administración/Gerencia.</p></div></header><div><span>Descuento permitido<b>Saldo completo, monto fijo o porcentaje</b></span><span>Corrección o condonación<b>Requiere segunda aprobación</b></span><span>Trazabilidad<b>Comprobante, comentario y responsable autenticado</b></span></div></section>
    {open?<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)setOpen(false)}}><form ref={formRef} className="modal-panel credit-modal" onSubmit={submit} role="dialog" aria-modal="true" aria-labelledby="credit-modal-title"><header><div><span className="overline teal">Registro real</span><h2 id="credit-modal-title">Nueva solicitud</h2><p>Ingresa únicamente información respaldada por una solicitud efectiva. El responsable se registra desde la sesión autenticada.</p></div><button type="button" className="icon-btn" onClick={()=>setOpen(false)} aria-label="Cerrar" disabled={saving}><X size={19}/></button></header><div className="form-grid"><label>Pescador o proveedor<input ref={fisherRef} required value={fisher} onChange={event=>setFisher(event.target.value)} placeholder="Nombre o razón social"/></label><label>Monto solicitado<input required type="number" min="1" step="1" value={amount||''} onChange={event=>setAmount(Number(event.target.value))}/></label><label className="full-field">Motivo<input value={reason} onChange={event=>setReason(event.target.value)} required placeholder="Motivo respaldado"/></label><label>Recuperación<select value={recoveryKind} onChange={event=>setRecoveryKind(event.target.value as CreditRow['recovery_kind'])}><option value="percentage">Porcentaje por entrega</option><option value="fixed_amount">Monto fijo por entrega</option><option value="full_balance">Saldo completo</option></select></label>{recoveryKind!=='full_balance'?<label>{recoveryKind==='percentage'?'Porcentaje':'Monto fijo'}<input required type="number" min="1" max={recoveryKind==='percentage'?100:undefined} step="1" value={recoveryValue||''} onChange={event=>setRecoveryValue(Number(event.target.value))}/></label>:null}</div>{error?<p className="form-error" role="alert">{error}</p>:null}<footer><button type="button" className="button secondary" onClick={()=>setOpen(false)} disabled={saving}>Cancelar</button><button className="button primary" type="submit" disabled={saving}>{saving?'Guardando…':'Enviar a aprobación'}</button></footer></form></div>:null}</>
}

function Summary({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <article><span>{icon}</span><div><small>{label}</small><b>{value}</b><em>{note}</em></div></article>}
