import {AlertTriangle,ArrowRight,CalendarCheck2,DollarSign,Factory,PackageCheck,RefreshCw,ShieldCheck,Truck} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import {useAuth} from '../auth'
import {PageHeader} from '../components/PageHeader'
import {plants as configuredPlants} from '../plants'

type QualityAction={reception_id:string;reception_number:string|number;plant_id:string|null;species:string;quality_status:string;blocked_labels:number|string;pending_labels:number|string}
type OrderAction={id:string;order_number:string|number;plant_id:string|null;species:string;product:string;delivery_date:string;committed_kg:number|string;allocated_kg:number|string}
type SettlementAction={settlement_id:string;status:string;reception_id:string;reception_number:string|number;plant_id:string|null;species:string;created_at?:string}
type RiskItem={kind:'quality'|'order'|'settlement';level:'critical'|'today'|'follow_up';reason:string;impact:number;reference:string;receptionId?:string;orderId?:string;detail:string}
type RiskSummary={critical:number;today:number;followUp:number;total:number;items:RiskItem[]}
type Snapshot={date:string;plantId:string|null;generatedAt:string;receptions:{count:number;kg:number};production:{events:number;inputKg:number;outputKg:number;yieldPct:number|null};dispatches:{count:number;kg:number};sales:{count:number;revenueClp:number;knownContributionClp:number;knownContributionSales:number};commitments:{dueOrders:number;dueKg:number;allocatedKg:number;producedCoverageKg:number;allocationCoveragePct:number|null;producedCoveragePct:number|null};pending:{settlements:number;qualityAlerts:number};inventory:{locatedKg:number};transformation:{costClp:number};risk:RiskSummary;actionItems:{quality:QualityAction[];orders:OrderAction[];settlements:SettlementAction[]}}
type SavedClose={id:string;generated_by:string;generated_at:string;notes:string|null;snapshot?:Snapshot}
type CloseHistoryItem={id:string;close_date:string;plant_id:string|null;generated_by:string;generated_at:string;notes:string|null;snapshot?:Snapshot}
type Payload={snapshot?:Snapshot;saved?:SavedClose|null;history?:CloseHistoryItem[];permissions?:{canClose:boolean};error?:string}
type PlantPerformance={plant_id:string;lots:number|string;received_kg:number|string;produced_kg:number|string;available_kg:number|string;revenue_clp:number|string;contribution_clp:number|string;contribution_pct:number|string|null}
type HistoricalPlant={historical_key:string;display_name:string;source_rows:number|string;reception_rows:number|string;received_kg:number|string|null;difference_kg:number|string|null;reception_variance_pct:number|string|null;reception_coverage_pct:number|string;timing_coverage_pct:number|string;quality_coverage_pct:number|string;avg_total_days:number|string|null;review_rows:number|string}
type PlantPerformancePayload={plants?:PlantPerformance[];historicalPlants?:HistoricalPlant[]}
const kg=(v:number)=>`${v.toLocaleString('es-CL',{maximumFractionDigits:1})} kg`
const pct=(v:number|string|null|undefined)=>v==null?'—':`${Number(v).toLocaleString('es-CL',{maximumFractionDigits:1})}%`
const clp=(v:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(v)
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const riskText=(risk:RiskSummary|undefined)=>{if(!risk||!risk.total)return 'sin excepciones';return [risk.critical?`${risk.critical} crítico${risk.critical===1?'':'s'}`:null,risk.today?`${risk.today} para hoy`:null,risk.followUp?`${risk.followUp} seguimiento`:null].filter(Boolean).join(' · ')}

export function DailyClose(){
 const {operator}=useAuth()
 const accessiblePlants=useMemo(()=>operator?.role==='admin'?configuredPlants:configuredPlants.filter(plant=>operator?.plantIds.includes(plant.id)),[operator])
 const defaultPlant=operator?.role!=='admin'&&accessiblePlants.length===1?accessiblePlants[0].id:''
 const [date,setDate]=useState(today),[plantId,setPlantId]=useState(defaultPlant),[data,setData]=useState<Payload|null>(null),[plantPerformance,setPlantPerformance]=useState<PlantPerformance[]>([]),[historicalPlants,setHistoricalPlants]=useState<HistoricalPlant[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false)
 async function load(nextDate=date,nextPlant=plantId){setLoading(true);try{const q=new URLSearchParams({date:nextDate});if(nextPlant)q.set('plantId',nextPlant);const [daily,performance]=await Promise.all([fetch(`/api/daily-close?${q}`,{cache:'no-store'}).then(async r=>{const p=await r.json() as Payload;if(!r.ok)throw new Error(p.error??'No fue posible construir el estado del día');return p}),operator?.role==='admin'?fetch('/api/plant-performance',{cache:'no-store'}).then(async r=>r.ok?await r.json() as PlantPerformancePayload:{plants:[],historicalPlants:[]}):Promise.resolve({plants:[],historicalPlants:[]} as PlantPerformancePayload)]);setData(daily);setPlantPerformance(performance.plants??[]);setHistoricalPlants(performance.historicalPlants??[]);setNotes(daily.saved?.notes??'');setError('')}catch(e){setError(e instanceof Error?e.message:'No fue posible construir el estado del día')}finally{setLoading(false)}}
 useEffect(()=>{void load(date,defaultPlant)},[])
 async function closeDay(){if(!data?.snapshot)return;setBusy(true);setError('');try{const r=await fetch('/api/daily-close',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date,plantId:plantId||null,notes})}),p=await r.json() as Payload;if(!r.ok)throw new Error(p.error??'No fue posible cerrar el día');await load()}catch(e){setError(e instanceof Error?e.message:'No fue posible cerrar el día')}finally{setBusy(false)}}
 const s=data?.snapshot,role=operator?.role??'viewer'
 const narrative=role==='admin'?{eyebrow:'Red Pescamar · Hoy',title:'Estado de la operación',description:'Lo importante del día, las excepciones que requieren decisión y el estado de cada planta.'}:role==='operations'?{eyebrow:'Operaciones · Hoy',title:'Qué requiere acción',description:'Producción, inventario, cumplimiento y excepciones de tus plantas, ordenados para decidir qué resolver primero.'}:role==='quality'?{eyebrow:'Calidad · Hoy',title:'Liberación y excepciones',description:'Desviaciones, alertas abiertas y continuidad operacional antes de que el producto avance.'}:role==='finance'?{eyebrow:'Finanzas · Hoy',title:'Resultado y pendientes',description:'Ventas, contribución conocida, costos registrados, liquidaciones y compromisos comerciales.'}:{eyebrow:'Hoy',title:'Resumen operativo',description:'Estado diario de la operación dentro de tu alcance.'}
 const attentionCount=s?.risk.total??0
 const hasLiveActivity=Boolean(s&&(s.receptions.count||s.production.events||s.dispatches.count||s.sales.count||s.risk.total))
 const actions=<div className="page-actions"><label className="inline-field">Fecha<input type="date" value={date} onChange={e=>{setDate(e.target.value);void load(e.target.value,plantId)}}/></label><label className="inline-field">Planta<select value={plantId} onChange={e=>{const next=e.target.value;setPlantId(next);void load(date,next)}}>{operator?.role==='admin'||accessiblePlants.length>1?<option value="">Toda la red accesible</option>:null}{accessiblePlants.map(plant=><option key={plant.id} value={plant.id}>{plant.name}</option>)}</select></label><button className="button" onClick={()=>void load()}><RefreshCw size={15}/>Actualizar</button></div>
 return <><PageHeader eyebrow={narrative.eyebrow} title={narrative.title} description={narrative.description} actions={actions}/>{error?<div className="system-banner error">{error}</div>:null}{loading?<div className="system-banner">Construyendo estado del día desde la Base de Datos Pescamar…</div>:null}{s?<>
  {role==='quality'?<QualityLead s={s}/>:role==='finance'?<FinanceLead s={s}/>:<OperationsLead s={s} attentionCount={attentionCount}/>} 
  <DecisionQueue s={s}/>
  <PhysicalFlow s={s}/>
  {role==='admin'&&!plantId?(plantPerformance.length?<PlantStrip rows={plantPerformance}/>:!hasLiveActivity?<HistoricalPlantStrip rows={historicalPlants}/>:null):null}
  <section className="close-grid">{role==='finance'?<FinanceResult s={s}/>:role==='quality'?<QualityPanel s={s}/>:<Commitments s={s}/>}</section>
  <CloseHistory rows={data?.history??[]}/>
  <CloseBar data={data} s={s} notes={notes} setNotes={setNotes} busy={busy} closeDay={closeDay}/>
 </>:null}</>
}

function OperationsLead({s,attentionCount}:{s:Snapshot;attentionCount:number}){return <section className="signal-grid"><article className="signal-card"><span><Factory size={16}/>Producción</span><b>{kg(s.production.outputKg)}</b><small>{s.production.yieldPct==null?'Sin rendimiento del día':`${s.production.yieldPct.toFixed(1)}% rendimiento observado hoy`}</small></article><article className="signal-card"><span><PackageCheck size={16}/>Inventario ubicado</span><b>{kg(s.inventory.locatedKg)}</b><small>Posición física registrada</small></article><article className={`signal-card ${attentionCount?'attention':''}`}><span><AlertTriangle size={16}/>Requieren acción</span><b>{attentionCount}</b><small>{attentionCount?riskText(s.risk):'Sin excepciones abiertas'}</small></article></section>}
function QualityLead({s}:{s:Snapshot}){return <section className="signal-grid"><article className="signal-card"><span><AlertTriangle size={16}/>Alertas de calidad</span><b>{s.pending.qualityAlerts}</b><small>{s.pending.qualityAlerts?'Requieren resolución':'Sin alertas abiertas'}</small></article><article className="signal-card"><span><Factory size={16}/>Producción</span><b>{kg(s.production.outputKg)}</b><small>{s.production.yieldPct==null?'Rendimiento pendiente':`${s.production.yieldPct.toFixed(1)}% rendimiento observado`}</small></article><article className="signal-card"><span><ShieldCheck size={16}/>Despachado</span><b>{kg(s.dispatches.kg)}</b><small>{s.dispatches.count} salidas confirmadas</small></article></section>}
function FinanceLead({s}:{s:Snapshot}){return <section className="signal-grid"><article className="signal-card"><span><DollarSign size={16}/>Ventas</span><b>{clp(s.sales.revenueClp)}</b><small>{s.sales.count} ventas confirmadas</small></article><article className="signal-card"><span><DollarSign size={16}/>Contribución conocida</span><b>{s.sales.knownContributionSales?clp(s.sales.knownContributionClp):'—'}</b><small>{s.sales.knownContributionSales?'Con costos conocidos':'Faltan costos para calcular'}</small></article><article className="signal-card"><span><AlertTriangle size={16}/>Liquidaciones pendientes</span><b>{s.pending.settlements}</b><small>Requieren cierre económico</small></article></section>}
function DecisionQueue({s}:{s:Snapshot}){const items=(s.risk?.items??[]).slice(0,8),levelLabel=(level:RiskItem['level'])=>level==='critical'?'Crítico':level==='today'?'Hoy':'Seguimiento',target=(item:RiskItem)=>item.kind==='quality'&&item.receptionId?`/etiquetas?receptionId=${encodeURIComponent(item.receptionId)}`:item.kind==='order'&&item.orderId?`/ordenes-venta?orderId=${encodeURIComponent(item.orderId)}&action=allocate`:item.kind==='settlement'&&item.receptionId?`/liquidaciones?receptionId=${encodeURIComponent(item.receptionId)}`:'/';const action=(item:RiskItem)=>item.kind==='quality'?'Resolver calidad':item.kind==='order'?'Cubrir pedido':'Cerrar costo';return <section className="panel executive-queue"><div className="section-heading"><div><span className="overline">Decisiones del día</span><h2>{items.length?'Prioridad operacional':'Operación sin excepciones críticas'}</h2><p className="source-note">La prioridad viene del mismo modelo que quedará congelado en el cierre diario.</p></div><span>{items.length}</span></div>{items.length?<div className="queue-list">{items.map((item,index)=><Link className={`queue-row ${item.level!=='follow_up'?'attention':''}`} to={target(item)} key={`${item.kind}-${item.reference}-${index}`}><span className="queue-priority">{index+1}</span><div><b>{item.reference}</b><small>{levelLabel(item.level)} · {item.reason} · {item.detail}</small></div><strong>{action(item)}</strong><ArrowRight size={15}/></Link>)}</div>:<div className="empty-inline"><ShieldCheck size={20}/><div><b>No hay decisiones críticas pendientes</b><small>Puedes seguir operando. Si no hay actividad viva, abajo verás contexto histórico validado de la red.</small></div></div>}</section>}
function PhysicalFlow({s}:{s:Snapshot}){const released=Math.max(0,s.production.outputKg-s.inventory.locatedKg<0?s.production.outputKg:s.inventory.locatedKg);return <section className="panel lifecycle-panel"><div className="section-heading"><div><span className="overline">Flujo físico del día</span><h2>De recepción a despacho</h2></div></div><div className="lifecycle-track four"><div className="lifecycle-stage"><span>1</span><div><b>{kg(s.receptions.kg)}</b><small>Recibido · {s.receptions.count} ingresos</small></div></div><div className="lifecycle-stage"><span>2</span><div><b>{kg(s.production.outputKg)}</b><small>Producido · {s.production.events} eventos</small></div></div><div className="lifecycle-stage"><span>3</span><div><b>{kg(released)}</b><small>Ubicado / disponible</small></div></div><div className="lifecycle-stage"><span>4</span><div><b>{kg(s.dispatches.kg)}</b><small>Despachado · {s.dispatches.count} salidas</small></div></div></div></section>}
function PlantStrip({rows}:{rows:PlantPerformance[]}){if(!rows.length)return null;return <section className="panel"><div className="section-heading"><div><span className="overline">Red Pescamar</span><h2>Operación viva por planta</h2></div><Link className="source-link compact" to="/plantas">Ver todas</Link></div><div className="plant-mini-grid">{rows.slice(0,6).map(row=>{const plant=configuredPlants.find(p=>p.id===row.plant_id),margin=row.contribution_pct==null?null:Number(row.contribution_pct),attention=margin!=null&&margin<0;return <Link to={`/plantas/${row.plant_id}`} className={`plant-mini ${attention?'attention':''}`} key={row.plant_id}><div><b>{plant?.name??row.plant_id}</b><small>{plant?.location??'Planta'}</small></div><strong>{kg(Number(row.produced_kg))}</strong><span>{Number(row.lots)} lotes · {margin==null?'sin margen':`${margin.toFixed(1)}% contrib.`}</span><ArrowRight size={14}/></Link>})}</div></section>}
function HistoricalPlantStrip({rows}:{rows:HistoricalPlant[]}){if(!rows.length)return null;return <section className="panel"><div className="section-heading"><div><span className="overline">Base histórica validada</span><h2>Contexto por planta / sitio</h2><p className="source-note">No es la operación de hoy. Resume únicamente evidencia histórica elegible para cada KPI.</p></div><Link className="source-link compact" to="/plantas">Abrir desempeño</Link></div><div className="plant-mini-grid">{rows.slice(0,6).map(row=>{const variance=Number(row.reception_variance_pct??0),review=Number(row.review_rows??0);return <Link to="/plantas" className={`plant-mini ${Math.abs(variance)>=2||review>0?'attention':''}`} key={row.historical_key}><div><b>{row.display_name}</b><small>{Number(row.reception_rows)} recepciones válidas · cobertura {pct(row.reception_coverage_pct)}</small></div><strong>{kg(Number(row.received_kg??0))}</strong><span>Dif. guía {pct(row.reception_variance_pct)} · ciclo {row.avg_total_days==null?'—':`${Number(row.avg_total_days).toFixed(1)} días`} · {review} revisión(es)</span><ArrowRight size={14}/></Link>})}</div></section>}
function FinanceResult({s}:{s:Snapshot}){return <article className="panel"><div className="section-heading"><div><span className="overline">Resultado conocido</span><h2>Ventas, costos y contribución</h2></div></div><div className="balance-summary"><div><small>Ventas</small><b>{clp(s.sales.revenueClp)}</b></div><div><small>Contribución conocida</small><b>{s.sales.knownContributionSales?clp(s.sales.knownContributionClp):'—'}</b></div><div><small>Transformación</small><b>{clp(s.transformation.costClp)}</b></div></div></article>}
function QualityPanel({s}:{s:Snapshot}){return <article className="panel"><div className="section-heading"><div><span className="overline">Calidad y liberación</span><h2>Estado de continuidad</h2></div></div><div className="close-lines"><p className={s.pending.qualityAlerts?'attention':''}><AlertTriangle size={15}/><span>Alertas de calidad abiertas</span><b>{s.pending.qualityAlerts}</b></p><p><Factory size={15}/><span>Eventos de producción</span><b>{s.production.events}</b></p><p><PackageCheck size={15}/><span>Rendimiento observado</span><b>{s.production.yieldPct==null?'—':`${s.production.yieldPct.toFixed(1)}%`}</b></p><p><Truck size={15}/><span>Salidas confirmadas</span><b>{s.dispatches.count}</b></p></div></article>}
function Commitments({s}:{s:Snapshot}){return <article className="panel"><div className="section-heading"><div><span className="overline">Cobertura comercial</span><h2>Pedidos y producto comprometido</h2></div></div><div className="balance-summary"><div><small>Comprometido</small><b>{kg(s.commitments.dueKg)}</b></div><div><small>Reservado</small><b>{s.commitments.allocationCoveragePct==null?'—':`${s.commitments.allocationCoveragePct.toFixed(0)}%`}</b></div><div><small>Producido</small><b>{s.commitments.producedCoveragePct==null?'—':`${s.commitments.producedCoveragePct.toFixed(0)}%`}</b></div></div></article>}
function CloseHistory({rows}:{rows:CloseHistoryItem[]}){return <section className="panel"><div className="section-heading"><div><span className="overline">Memoria operacional</span><h2>Cierres recientes</h2><p className="source-note">Cada registro conserva el estado congelado de operación y riesgo al momento del cierre.</p></div><span>{rows.length}</span></div>{rows.length?<div className="queue-list">{rows.slice(0,6).map(row=>{const snap=row.snapshot,plant=row.plant_id?configuredPlants.find(p=>p.id===row.plant_id)?.name??row.plant_id:'Toda la red',date=new Date(`${row.close_date}T12:00:00`).toLocaleDateString('es-CL');return <div className={`queue-row ${snap?.risk?.critical?'attention':''}`} key={row.id}><span className="queue-priority"><CalendarCheck2 size={14}/></span><div><b>{date} · {plant}</b><small>{snap?`${kg(snap.receptions.kg)} recibidos · ${kg(snap.production.outputKg)} producidos · ${riskText(snap.risk)}`:`Cierre auditado · ${row.generated_by}`}</small></div><strong>{snap?.risk?.critical?'Con críticos':'Cerrado'}</strong></div>})}</div>:<div className="empty-inline"><CalendarCheck2 size={20}/><div><b>Aún no hay cierres guardados</b><small>La serie comenzará con el primer cierre real. No se generan tendencias ni comparaciones artificiales.</small></div></div>}</section>}
function CloseBar({data,s,notes,setNotes,busy,closeDay}:{data:Payload;s:Snapshot;notes:string;setNotes:(v:string)=>void;busy:boolean;closeDay:()=>Promise<void>}){const hasActivity=Boolean(s.receptions.count||s.production.events||s.dispatches.count||s.sales.count),live=s.risk,saved=data.saved?.snapshot?.risk,savedText=riskText(saved),liveText=riskText(live),title=data.saved?`Jornada cerrada · ${savedText}`:hasActivity?live.total?liveText:'Jornada lista para cerrar':'Día sin operación registrada',description=data.saved?`Snapshot guardado por ${data.saved.generated_by}. Estado vivo actual: ${liveText}.`:hasActivity?live.critical?'Hay bloqueos o vencimientos abiertos. Puedes cerrar, pero conviene resolverlos o documentar explícitamente por qué quedan pendientes.':live.today?'Quedan acciones que deberían resolverse hoy. Puedes cerrar con observación si continúan abiertas.':live.followUp?'Sólo quedan seguimientos que no bloquean la continuidad inmediata.':'Congela el estado actual como snapshot auditable.':'No hay actividad para esta fecha y alcance.';return <section className={`panel close-bar ${(!data.saved&&live.critical)||saved?.critical?'attention':''}`}><div><span className="overline">Cierre auditable</span><h2>{title}</h2><p>{description}</p></div>{data.permissions?.canClose&&hasActivity?<div className="close-form compact"><textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)} placeholder={live.critical?'Observación recomendada si cierras con críticos':'Observación opcional'}/><button className="button primary" onClick={()=>void closeDay()} disabled={busy}><CalendarCheck2 size={15}/>{busy?'Guardando…':data.saved?'Regenerar':'Cerrar jornada'}</button></div>:null}</section>}
