import {AlertTriangle,ArrowRight,CheckCheck,Factory,History,Info,Plus,Scale,ShieldAlert} from "lucide-react";
import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {canAccessPath,canCreateReception} from "../access";
import {useAuth} from "../auth";
import {DataContinuityBanner} from "../components/DataContinuityBanner";
import {useLot360} from "../components/Lot360Context";
import {PageHeader} from "../components/PageHeader";
import {usePlatformStatus} from "../hooks/usePlatformStatus";
import type {Lot} from "../types";

type QueueItem={receptionId:string;receptionNumber:number;plantId:string|null;supplier:string;species:string;lifecycle:string;qualityStatus:string;nextAction:string;priority:'normal'|'attention';receivedAt:string;lastActivityAt:string}
type ManagementAlert={id:string;severity:'critical'|'warning'|'info';kind:string;receptionId?:string;title:string;detail:string}
type Overview={lifecycle?:Record<string,number>;queue?:QueueItem[];alerts?:ManagementAlert[];summary?:{openLots:number;attention:number;liveProductionKg:number;historicalProductionKg:number};economics?:{marginAvailable:boolean;reason:string;historicalCoverage:{operationalRecords:number;pricedRecords:number;pricedPct:number;pricedKg:number;rawMaterialCostClp:number}};inventory?:{summary:{totalKg:number;rawKg:number;processedKg:number}};error?:string}
const stages=[['recepcion','Recepción'],['calidad','Calidad'],['produccion','Producción'],['liquidacion','Liquidación'],['cerrado','Cerrado']] as const;
const kg=(value:number)=>`${value.toLocaleString('es-CL',{maximumFractionDigits:1})} kg`;
export function Dashboard({lots,onNewReception}:{lots:Lot[];onNewReception:()=>void}){
  const {operator}=useAuth();const {openLive,summary}=useLot360();const {status,error}=usePlatformStatus();const [overview,setOverview]=useState<Overview|null>(null),[overviewError,setOverviewError]=useState('');
  useEffect(()=>{let active=true;fetch('/api/operations-overview',{cache:'no-store'}).then(async response=>{const payload=await response.json() as Overview;if(!response.ok)throw new Error(payload.error??'No fue posible cargar el control operacional');if(active)setOverview(payload)}).catch(cause=>{if(active)setOverviewError(cause instanceof Error?cause.message:'No fue posible cargar el control operacional')});return()=>{active=false}},[]);
  const pending=status?.metrics.pendingDecisions??0;const reviewCount=lots.filter(lot=>lot.status==="Revisión"||lot.status==="Alerta calibre").length;const platformIssue=Boolean(error)||Boolean(status&&(!status.ok||!status.persistence.database));const mayCreate=operator?canCreateReception(operator.role):false;const mayApprove=operator?canAccessPath(operator.role,"/aprobaciones"):false;const mayConfigure=operator?canAccessPath(operator.role,"/modulos"):false;const queue=overview?.queue??[];const alerts=overview?.alerts??[];const attention=overview?.summary?.attention??0;const inventory=overview?.inventory?.summary;const coverage=overview?.economics?.historicalCoverage;const canonicalCount=Number(summary?.total??0);const canonicalReady=canonicalCount===394;const databaseReady=Boolean(status?.persistence.database);const scopeReady=Boolean(operator&&(operator.role==='admin'||operator.plantIds.length>0));const liveStarted=lots.length>0;
  return <><PageHeader eyebrow="Centro de mando" title="Operación de hoy" description="2025 conserva la memoria canónica; desde la primera recepción nueva, este mismo sistema continúa la operación sin volver a cortar la historia." actions={mayCreate?<button className="button primary" onClick={onNewReception}><Plus size={15}/>Nueva recepción</button>:undefined}/>
    <DataContinuityBanner/>
    {!liveStarted?<section className="operational-start" aria-labelledby="operational-start-title"><div className="operational-start-copy"><span className="overline">Arranque operacional</span><h2 id="operational-start-title">El sistema está listo para comenzar la continuidad viva.</h2><p>La historia 2025 permanece intacta como referencia canónica. El siguiente dato real no se importa como otro año histórico: nace aquí como recepción viva y desde ahí acumula calidad, producción, inventario, costos, despacho, venta y cierre.</p><div className="operational-start-actions">{mayCreate?<button className="button primary" onClick={onNewReception}><Plus size={15}/>Registrar primera recepción viva</button>:null}<Link className="button secondary" to="/timeline"><History size={15}/>Ver origen 2025</Link></div></div><div className="readiness-list" aria-label="Preparación para iniciar operación"><Readiness ready={canonicalReady} label="Base canónica 2025" detail={canonicalReady?'394 registros auditados disponibles':`${canonicalCount} registros disponibles; revisar fuente`}/><Readiness ready={databaseReady} label="Persistencia operacional" detail={databaseReady?'Neon conectado y escribible':'Conexión pendiente de validar'}/><Readiness ready={scopeReady} label="Alcance del operador" detail={scopeReady?'Plantas asignadas para operar':'Falta asignar alcance de planta'}/><Readiness ready={liveStarted} current={!liveStarted&&canonicalReady&&databaseReady&&scopeReady} label="Primera recepción viva" detail={liveStarted?'Continuidad iniciada':'Es el siguiente paso; no se crea ningún dato ficticio'}/></div></section>:null}
    <section className={`command-deck ${pending||reviewCount||attention?"":"idle"}`} aria-labelledby="command-title"><div className="command-copy"><span className="system-label">PESCAMAR // CONTROL POR EXCEPCIÓN</span><h2 id="command-title">{attention?`${attention} señal${attention===1?' requiere':'es requieren'} revisión.`:queue.length?`${queue.length} lote${queue.length===1?' tiene':'s tienen'} trabajo pendiente.`:"La operación viva no tiene pendientes."}</h2><p>{mayApprove?"La cola combina ciclo real, calidad, rendimiento, peso y tiempo sin convertir heurísticas en reglas contables.":"Tu vista conserva el ciclo completo sin exponer acciones reservadas."}</p>{queue[0]?<button className="command-action" onClick={()=>openLive(queue[0].receptionId)}><CheckCheck size={17}/>Abrir siguiente lote<ArrowRight size={16}/></button>:<Link className="command-action" to="/timeline"><History size={17}/>Revisar continuidad<ArrowRight size={16}/></Link>}</div>{pending||reviewCount||queue.length||alerts.length?<div className="command-metrics" aria-label="Resumen operacional"><Metric label="Lotes abiertos" value={queue.length} detail="Con siguiente acción"/><Metric label="Alertas" value={attention} detail="Críticas o preventivas"/>{pending?<Metric label="Decisiones" value={pending} detail="Esperando resolución"/>:null}</div>:null}</section>
    <section className="signal-grid" aria-label="Posición operacional"><article className="signal-card"><span><Scale size={17}/>Posición física viva</span><b>{inventory?kg(inventory.totalKg):'—'}</b><small>{inventory?`${kg(inventory.rawKg)} materia prima · ${kg(inventory.processedKg)} salida productiva`:'Sin lotes vivos; 2025 no se presenta como inventario actual.'}</small></article><article className="signal-card"><span><ShieldAlert size={17}/>Referencia económica 2025</span><b>{coverage?`${coverage.pricedPct.toFixed(1)}%`:'—'}</b><small>{coverage?`${coverage.pricedRecords} de ${coverage.operationalRecords} registros canónicos tienen precio de guía.`:'Cargando cobertura.'}</small></article><article className="signal-card"><span><Info size={17}/>Resultado vivo</span><b>No calculable aún</b><small>Se activará sólo con ventas y costos reales registrados en la continuidad viva.</small></article></section>
    <section className="panel lifecycle-panel"><div className="section-heading"><div><span className="overline">Ciclo de vida vivo</span><h2>Del ingreso al cierre</h2></div><Link to="/timeline">Ver línea completa <ArrowRight size={14}/></Link></div><div className="lifecycle-track">{stages.map(([key,label],index)=><div key={key} className="lifecycle-stage"><span>{String(index+1).padStart(2,'0')}</span><div><b>{overview?.lifecycle?.[key]??0}</b><small>{label}</small></div></div>)}</div></section>
    <section className="panel executive-queue"><div className="section-heading"><div><span className="overline">Alertas gerenciales</span><h2>Desviaciones que merecen criterio</h2></div><small className="rule-note">Señales de operación viva; no se fabrican desde el histórico.</small></div>{overviewError?<div className="notice error"><AlertTriangle size={15}/>{overviewError}</div>:alerts.length?<div className="alert-list">{alerts.slice(0,8).map(item=>{const row=<><span className={`alert-icon ${item.severity}`}>{item.severity==='info'?<Info size={16}/>:<AlertTriangle size={16}/>}</span><div><b>{item.title}</b><small>{item.detail}</small></div><span className={`status ${item.severity==='critical'?'danger':item.severity==='warning'?'warning':'info'}`}>{item.kind}</span></>;return item.receptionId?<button key={item.id} className="alert-row" onClick={()=>openLive(item.receptionId!)}>{row}<ArrowRight size={15}/></button>:<div key={item.id} className="alert-row static">{row}<span/></div>})}</div>:<div className="empty-inline"><CheckCheck size={20}/><div><b>Sin alertas gerenciales activas</b><small>Las señales aparecerán cuando la operación viva genere desviaciones o falten datos críticos.</small></div></div>}</section>
    <section className="panel executive-queue"><div className="section-heading"><div><span className="overline">Cola ejecutiva</span><h2>Qué hacer ahora</h2></div><Link to="/lineas"><Factory size={14}/> Producción</Link></div>{queue.length?<div className="queue-list">{queue.slice(0,6).map(item=><button key={item.receptionId} className={`queue-row ${item.priority}`} onClick={()=>openLive(item.receptionId)}><span className="queue-priority">{item.priority==='attention'?<AlertTriangle size={16}/>:<Scale size={16}/>}</span><div><b>REC-{item.receptionNumber} · {item.supplier}</b><small>{item.species} · {item.plantId??'Sin planta'} · etapa {item.lifecycle}</small></div><strong>{item.nextAction}</strong><ArrowRight size={15}/></button>)}</div>:<div className="empty-inline"><CheckCheck size={20}/><div><b>Sin trabajo vivo pendiente</b><small>Cuando ingrese la primera recepción nueva, aparecerá aquí automáticamente con su siguiente acción.</small></div></div>}</section>
    {platformIssue?<section className="system-alert" role="alert"><span className="health-pulse"/><p><b>La plataforma requiere revisión</b><small>Comprueba la conexión antes de continuar.</small></p>{mayConfigure?<Link to="/modulos">Ver configuración <ArrowRight size={14}/></Link>:null}</section>:null}
    <section className="secondary-action"><div><span className="overline">Memoria continua</span><p>Los 394 registros canónicos de 2025 son el origen. Cada registro nuevo continúa la misma secuencia y queda identificado como operación viva.</p></div><Link className="source-link compact" to="/timeline"><History size={14}/>Abrir línea de tiempo</Link></section>
  </>;
}
function Metric({label,value,detail}:{label:string;value:number;detail:string}){return <div><small>{label}</small><b>{value}</b><span>{detail}</span></div>}
function Readiness({ready,current=false,label,detail}:{ready:boolean;current?:boolean;label:string;detail:string}){return <div className={`readiness-item ${ready?'ready':''} ${current?'current':''}`}><span>{ready?'✓':'○'}</span><div><b>{label}</b><small>{detail}</small></div></div>}
