import {AlertTriangle,ArrowRight,CheckCheck,Factory,History,Plus,Scale} from "lucide-react";
import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {canAccessPath,canCreateReception} from "../access";
import {useAuth} from "../auth";
import {useLot360} from "../components/Lot360Context";
import {PageHeader} from "../components/PageHeader";
import {usePlatformStatus} from "../hooks/usePlatformStatus";
import type {Lot} from "../types";

type QueueItem={receptionId:string;receptionNumber:number;plantId:string|null;supplier:string;species:string;lifecycle:string;qualityStatus:string;nextAction:string;priority:'normal'|'attention';receivedAt:string;lastActivityAt:string}
type Overview={lifecycle?:Record<string,number>;queue?:QueueItem[];summary?:{openLots:number;attention:number;liveProductionKg:number;historicalProductionKg:number};error?:string}
const stages=[['recepcion','Recepción'],['calidad','Calidad'],['produccion','Producción'],['liquidacion','Liquidación'],['cerrado','Cerrado']] as const;
export function Dashboard({lots,onNewReception}:{lots:Lot[];onNewReception:()=>void}){
  const {operator}=useAuth();const {openLive}=useLot360();const {status,error}=usePlatformStatus();const [overview,setOverview]=useState<Overview|null>(null),[overviewError,setOverviewError]=useState('');
  useEffect(()=>{let active=true;fetch('/api/operations-overview',{cache:'no-store'}).then(async response=>{const payload=await response.json() as Overview;if(!response.ok)throw new Error(payload.error??'No fue posible cargar el control operacional');if(active)setOverview(payload)}).catch(cause=>{if(active)setOverviewError(cause instanceof Error?cause.message:'No fue posible cargar el control operacional')});return()=>{active=false}},[]);
  const pending=status?.metrics.pendingDecisions??0;const reviewCount=lots.filter(lot=>lot.status==="Revisión"||lot.status==="Alerta calibre").length;const platformIssue=Boolean(error)||Boolean(status&&(!status.ok||!status.persistence.database));const mayCreate=operator?canCreateReception(operator.role):false;const mayApprove=operator?canAccessPath(operator.role,"/aprobaciones"):false;const mayConfigure=operator?canAccessPath(operator.role,"/modulos"):false;const queue=overview?.queue??[];const attention=overview?.summary?.attention??0;
  return <><PageHeader eyebrow="Centro de mando" title="Operación de hoy" description="Un solo flujo: recepción, calidad, producción, liquidación y cierre. La pantalla prioriza el siguiente trabajo real por lote." actions={mayCreate?<button className="button primary" onClick={onNewReception}><Plus size={15}/>Nueva recepción</button>:undefined}/>
    <section className={`command-deck ${pending||reviewCount||attention?"":"idle"}`} aria-labelledby="command-title"><div className="command-copy"><span className="system-label">PESCAMAR // CONTROL POR EXCEPCIÓN</span><h2 id="command-title">{attention?`${attention} lote${attention===1?' requiere':'s requieren'} atención.`:queue.length?`${queue.length} lote${queue.length===1?' tiene':'s tienen'} trabajo pendiente.`:"La operación viva no tiene pendientes."}</h2><p>{mayApprove?"La cola combina el ciclo real del lote con las decisiones compatibles con tu rol y plantas.":"Tu vista conserva el ciclo completo sin exponer acciones reservadas."}</p>{queue[0]?<button className="command-action" onClick={()=>openLive(queue[0].receptionId)}><CheckCheck size={17}/>Abrir siguiente lote<ArrowRight size={16}/></button>:<Link className="command-action" to="/timeline"><History size={17}/>Revisar continuidad<ArrowRight size={16}/></Link>}</div>{pending||reviewCount||queue.length?<div className="command-metrics" aria-label="Resumen operacional"><Metric label="Lotes abiertos" value={queue.length} detail="Con siguiente acción"/><Metric label="Excepciones" value={attention} detail="Calidad requiere criterio"/>{pending?<Metric label="Decisiones" value={pending} detail="Esperando resolución"/>:null}</div>:null}</section>
    <section className="panel lifecycle-panel"><div className="section-heading"><div><span className="overline">Ciclo de vida</span><h2>Del ingreso al cierre</h2></div><Link to="/timeline">Ver línea completa <ArrowRight size={14}/></Link></div><div className="lifecycle-track">{stages.map(([key,label],index)=><div key={key} className="lifecycle-stage"><span>{String(index+1).padStart(2,'0')}</span><div><b>{overview?.lifecycle?.[key]??0}</b><small>{label}</small></div></div>)}</div></section>
    <section className="panel executive-queue"><div className="section-heading"><div><span className="overline">Cola ejecutiva</span><h2>Qué hacer ahora</h2></div><Link to="/lineas"><Factory size={14}/> Producción</Link></div>{overviewError?<div className="notice error"><AlertTriangle size={15}/>{overviewError}</div>:queue.length?<div className="queue-list">{queue.slice(0,6).map(item=><button key={item.receptionId} className={`queue-row ${item.priority}`} onClick={()=>openLive(item.receptionId)}><span className="queue-priority">{item.priority==='attention'?<AlertTriangle size={16}/>:<Scale size={16}/>}</span><div><b>REC-{item.receptionNumber} · {item.supplier}</b><small>{item.species} · {item.plantId??'Sin planta'} · etapa {item.lifecycle}</small></div><strong>{item.nextAction}</strong><ArrowRight size={15}/></button>)}</div>:<div className="empty-inline"><CheckCheck size={20}/><div><b>Sin trabajo vivo pendiente</b><small>Cuando ingrese una recepción, aparecerá aquí automáticamente con su siguiente acción.</small></div></div>}</section>
    {platformIssue?<section className="system-alert" role="alert"><span className="health-pulse"/><p><b>La plataforma requiere revisión</b><small>Comprueba la conexión antes de continuar.</small></p>{mayConfigure?<Link to="/modulos">Ver configuración <ArrowRight size={14}/></Link>:null}</section>:null}
    <section className="secondary-action"><div><span className="overline">Memoria continua</span><p>Los 394 registros auditados de 2025 y la operación viva permanecen en una sola secuencia.</p></div><Link className="source-link compact" to="/timeline"><History size={14}/>Abrir línea de tiempo</Link></section>
  </>;
}
function Metric({label,value,detail}:{label:string;value:number;detail:string}){return <div><small>{label}</small><b>{value}</b><span>{detail}</span></div>}
