import { ArrowRight, Camera, CircleAlert, Download, Scale, Sparkles, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { LotTable } from '../components/LotTable'
import { standards } from '../data'
import type { Lot } from '../types'

export function Dashboard({lots,onNew}:{lots:Lot[];onNew:()=>void}) {
  const gross=lots.reduce((s,l)=>s+l.gross,0),accepted=lots.reduce((s,l)=>s+l.accepted,0),acceptance=gross?accepted/gross*100:0
  const classified=lots.filter(l=>l.gonadYield!==null),gonad=classified.reduce((s,l)=>s+(l.gonadYield??0),0)/(classified.length||1),premium=classified.reduce((s,l)=>s+(l.premiumYield??0),0)/(classified.length||1)
  const standard=standards[0]
  return <><PageHeader eyebrow="Planta Pescamar · Ancud" title="Control de calidad y rendimiento" description="Una vista viva de recepción, proceso y estándar de exportación." actions={<><button className="button secondary"><Download size={16}/>Reporte de turno</button><button className="button primary" onClick={onNew}>+ Nueva recepción</button></>}/>
    <section className="metric-grid"><Metric label="Recibido hoy" value={`${gross.toLocaleString('es-CL')} kg`} delta="8,4% sobre promedio" icon={<Scale/>}/><Metric label="Peso neto aceptado" value={`${accepted.toLocaleString('es-CL')} kg`} delta={`${acceptance.toFixed(1)}% de recepción`} icon={<TrendingUp/>}/><Metric label="Rendimiento gónada" value={`${gonad.toFixed(1)}%`} delta="0,7 puntos esta semana" icon={<Sparkles/>}/><Metric label="Calidad Japón A" value={`${premium.toFixed(1)}%`} delta="3 lotes requieren revisión" icon={<CircleAlert/>} warning/></section>
    <section className="dashboard-grid"><article className="panel mass-panel"><PanelHeader title="Balance de masa" meta="Turno mañana · Actualizado 10:42"/><div className="mass-flow"><FlowStep label="Recepción" value={`${gross.toFixed(0)} kg`} detail="100% registrado" width={100}/><FlowStep label="Aceptado" value={`${accepted.toFixed(0)} kg`} detail={`${(gross-accepted).toFixed(0)} kg explicados`} width={acceptance}/><FlowStep label="Gónada limpia" value="102,7 kg" detail={`${gonad.toFixed(1)}% rendimiento`} width={61}/><FlowStep label="Japón A" value="70,0 kg" detail={`${premium.toFixed(1)}% premium`} width={premium}/></div><div className="mass-note"><Sparkles size={16}/><span>El escurrido estandarizado explicó <b>74 kg</b> que antes se registraban como merma general.</span></div></article>
      <article className="panel color-panel"><PanelHeader title="Lectura UniColor" meta="Cámara 01 · En línea"/><div className="color-reading"><div className="pantone-card" style={{background:standard.hex}}><span>{standard.name}</span><b>{standard.id}</b><small>{standard.pantone}</small></div><div className="lab-readings"><span><small>L*</small><b>{standard.l}</b></span><span><small>a*</small><b>{standard.a}</b></span><span><small>b*</small><b>{standard.b}</b></span></div></div><div className="match"><div><span>Coincidencia con patrón</span><b>94,7%</b></div><div className="progress"><i style={{width:'94.7%'}}/></div></div><Link to="/estandares" className="inline-link">Abrir estándar Japón <ArrowRight size={15}/></Link></article>
      <article className="panel lots-panel"><PanelHeader title="Recepciones activas" meta={`${lots.length} lotes hoy`}/><LotTable lots={lots} compact/><Link to="/recepciones" className="view-all">Ver todas las recepciones <ArrowRight size={15}/></Link></article>
      <article className="panel intelligence-panel"><PanelHeader title="Inteligencia de temporada" meta="Actualizado por UniGrade IA"/><div className="insight-list"><Insight icon={<TrendingUp/>} title="Origen con mejor rendimiento" text="Bahía de Ancud promedia 11,2% de gónada limpia esta semana."/><Insight icon={<Camera/>} title="Modelo ganando precisión" text="La concordancia con inspectores japoneses subió a 92,8%."/><Insight icon={<CircleAlert/>} title="Atención en Quemchi" text="Dos lotes presentan merma superior al rango esperado."/></div></article></section></>
}
function Metric({label,value,delta,icon,warning=false}:{label:string;value:string;delta:string;icon:React.ReactNode;warning?:boolean}){return <article className="metric"><div className={`metric-icon ${warning?'warning':''}`}>{icon}</div><span>{label}</span><strong>{value}</strong><small className={warning?'warning-text':''}>{delta}</small></article>}
function PanelHeader({title,meta}:{title:string;meta:string}){return <header className="panel-header"><h2>{title}</h2><span>{meta}</span></header>}
function FlowStep({label,value,detail,width}:{label:string;value:string;detail:string;width:number}){return <div className="flow-step"><span>{label}</span><b>{value}</b><div><i style={{width:`${Math.min(width,100)}%`}}/></div><small>{detail}</small></div>}
function Insight({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="insight-item"><span>{icon}</span><div><b>{title}</b><p>{text}</p></div></div>}
