import {ArrowRight,Camera,CheckCircle2,CircleDashed,GitBranch,ScanLine,ShieldCheck,Target} from 'lucide-react'
import {Link} from 'react-router-dom'
import {canAccessPath} from '../access'
import {useAuth} from '../auth'
import {PageHeader} from '../components/PageHeader'
import {edgeVisionAdapters,edgeVisionCapabilities,edgeVisionEvidenceContract,type EdgeVisionCapabilityStatus} from '../edgevision'
import {organizationContext} from '../organization'

const statusLabel:Record<EdgeVisionCapabilityStatus,string>={available:`Disponible en ${organizationContext.implementationName}`,foundation:'Fundación',planned:'Planificado'}
const statusClass:Record<EdgeVisionCapabilityStatus,string>={available:'success',foundation:'info',planned:'info'}

export function EdgeVision(){
 const {operator}=useAuth()
 const available=edgeVisionCapabilities.filter(item=>item.status==='available').length
 const foundation=edgeVisionCapabilities.filter(item=>item.status==='foundation').length
 const planned=edgeVisionCapabilities.filter(item=>item.status==='planned').length
 const mayOpenStations=operator?canAccessPath(operator.role,'/estaciones'):false
 return <><PageHeader eyebrow="Seafood Intelligence OS · Vision" title="EdgeVision" description="Evidencia visual atribuible al lote y al proceso. Medir, clasificar y detectar sin separar la visión del contexto operacional." actions={<div className="row-actions"><Link className="button secondary" to="/lineage"><GitBranch size={14}/>Seafood Event Graph</Link>{mayOpenStations?<Link className="button secondary" to="/estaciones"><Camera size={14}/>Estaciones</Link>:null}</div>}/>
 <section className="signal-grid"><article className="signal-card"><span><CheckCircle2 size={16}/>Capacidades existentes</span><b>{available}</b><small>adapter de {organizationContext.implementationName} con evidencia real de software</small></article><article className="signal-card"><span><Target size={16}/>Fundación</span><b>{foundation}</b><small>contratos listos para ampliar</small></article><article className="signal-card"><span><CircleDashed size={16}/>Planificadas</span><b>{planned}</b><small>no se presentan como operativas</small></article><article className="signal-card"><span><ScanLine size={16}/>Adapters</span><b>{edgeVisionAdapters.length}</b><small>fuentes Vision actualmente registradas</small></article></section>
 <section className="panel"><div className="section-heading"><div><span className="overline teal">Capability registry</span><h2>Qué debe observar EdgeVision</h2></div><span>{edgeVisionCapabilities.length} capacidades</span></div><div className="compact-ledger">{edgeVisionCapabilities.map(capability=><div className="alert-row static" key={capability.id}><span><ScanLine size={15}/></span><div><b>{capability.label}</b><small>{capability.outcome}</small><p className="source-note">{capability.currentEvidence}</p></div><span className={`status ${statusClass[capability.status]}`}>{statusLabel[capability.status]}</span></div>)}</div></section>
 <section className="panel"><div className="section-heading"><div><span className="overline teal">Adapter activo</span><h2>{organizationContext.implementationName} · Uni Vision</h2></div><Link className="source-link compact" to="/proceso-erizo">Abrir proceso erizo <ArrowRight size={13}/></Link></div>{edgeVisionAdapters.map(adapter=><div className="governance-note" key={adapter.id}><ShieldCheck size={19}/><div><b>{adapter.label}</b><p>{adapter.executionMode} Capacidades: {adapter.capabilities.join(' · ')}. Autoridad: revisión humana obligatoria. Versionado reusable de modelo/engine: {adapter.modelVersioning==='implemented'?'implementado':'pendiente'}.</p><small>{adapter.notes} Evidencia fuente: {adapter.evidenceEntity}. Organización: {adapter.implementationId}.</small></div></div>)}</section>
 <section className="panel"><div className="section-heading"><div><span className="overline teal">Evidence contract</span><h2>Todo resultado visual debe poder explicarse</h2></div></div><div className="os-stage-modules">{edgeVisionEvidenceContract.map((field,index)=><div className="alert-row static" key={field}><span className="os-module-step">{String(index+1).padStart(2,'0')}</span><div><b>{field}</b><small>{index<4?'Contexto operacional':'Provenance, medición y autoridad'}</small></div></div>)}</div><div className="notice"><ShieldCheck size={16}/><div><b>Guardrail de producto</b><small>EdgeVision no libera calidad, regula ni toma decisiones financieras por sí solo. Un modelo sólo puede automatizar una decisión después de tener dataset real, métricas, threshold, versionado, análisis de errores y fallback humano aprobados.</small></div></div></section>
 </>}
