import { AlertTriangle, CheckCircle2, FileSpreadsheet, ShieldCheck, Upload } from 'lucide-react'
import { useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { plants } from '../plants'
import { usePlatformStatus } from '../hooks/usePlatformStatus'

type Inspection={fileName:string;sheet:string;rows:number;columns:number;validRows:number;errors:string[];warnings:string[]}
const schema=[
  {column:4,label:'Guía / N°',top:'Guia',sub:'N°'},
  {column:5,label:'Proveedor / Nombre',top:'Proveedor',sub:'Nombre'},
  {column:6,label:'Lugar extracción / Zona',top:'Lugar extraccion',sub:'Zona'},
  {column:8,label:'Planta / Proceso',top:'Planta',sub:'Proceso'},
  {column:9,label:'Lote / N°',top:'Lote',sub:'N°'},
  {column:10,label:'Kilos guía',sub:'Kilos Guia'},
  {column:11,label:'Kilos recibidos',sub:'kilos recep.'}
]

export function Imports(){
  const [inspection,setInspection]=useState<Inspection|null>(null),[busy,setBusy]=useState(false),[plant,setPlant]=useState('')
  const {status,error}=usePlatformStatus()
  async function inspect(file:File){setBusy(true);try{const XLSX=await import('xlsx'),data=await file.arrayBuffer(),book=XLSX.read(data,{type:'array',cellDates:true}),sheetName=book.SheetNames[0],sheet=book.Sheets[sheetName];const matrix=XLSX.utils.sheet_to_json<(string|number|null)[]>(sheet,{header:1,defval:null,raw:true});const top=(matrix[0]||[]).map(value=>String(value??'').trim()),sub=(matrix[1]||[]).map(value=>String(value??'').trim());const missing=schema.filter(field=>(field.top&&!top[field.column].toLowerCase().includes(field.top.toLowerCase()))||(field.sub&&!sub[field.column].toLowerCase().includes(field.sub.toLowerCase())));const rows=matrix.slice(2).filter(row=>row.some(value=>value!==null&&value!==''));const validRows=rows.filter(row=>row[4]&&row[5]&&row[9]&&typeof row[10]==='number'&&typeof row[11]==='number').length;const warnings:string[]=[];if(book.SheetNames.length>1)warnings.push(`El archivo contiene ${book.SheetNames.length} hojas; se procesará primero “${sheetName}”.`);if(validRows<rows.length)warnings.push(`${rows.length-validRows} filas requieren revisión por campos obligatorios o kilos no numéricos.`);setInspection({fileName:file.name,sheet:sheetName,rows:rows.length,columns:sub.filter(Boolean).length,validRows,errors:missing.map(field=>`No se reconoció el campo obligatorio “${field.label}” en la columna esperada.`),warnings})}catch{setInspection({fileName:file.name,sheet:'No disponible',rows:0,columns:0,validRows:0,errors:['No fue posible leer el archivo. Verifica que sea un Excel válido.'],warnings:[]})}finally{setBusy(false)}}
  const publishable=inspection&&inspection.errors.length===0&&inspection.validRows>0&&plant
  return <><PageHeader eyebrow="Gobierno de datos" title="Importar planilla" description="Valida el archivo antes de asociarlo a una planta. La inspección no publica ni altera información operacional."/>
    <section className="platform-strip"><div><span className={`platform-dot ${status?.ok?'online':'pending'}`}/><span><small>Vercel Functions</small><b>{status?.ok?'Conectado':error?'No disponible':'Comprobando…'}</b></span></div><div><small>Base de datos</small><b>{status?.persistence.database?'Conectada':'Pendiente'}</b></div><div><small>Archivos privados</small><b>{status?.persistence.files?'Conectados':'Pendiente'}</b></div><div><small>Entorno</small><b>{status?.environment??'—'}</b></div></section>
    <section className="import-layout"><article className="panel import-upload"><div className="import-step"><span>01</span><div><h2>Seleccionar fuente</h2><p>Formato Excel `.xlsx` o `.xls`. El archivo permanece sin publicar durante la validación.</p></div></div><label className="file-drop"><Upload size={28}/><b>{busy?'Analizando archivo…':'Seleccionar planilla real'}</b><small>No se aceptan datos demostrativos</small><input type="file" accept=".xlsx,.xls" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void inspect(file)}}/></label>{inspection?<InspectionResult inspection={inspection}/>:null}</article>
      <aside className="panel import-assignment"><div className="import-step"><span>02</span><div><h2>Asignar contexto</h2><p>La planta debe ser confirmada por una persona responsable.</p></div></div><label>Planta<select value={plant} onChange={event=>setPlant(event.target.value)}><option value="">Seleccionar planta…</option>{plants.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div className="governance-note"><ShieldCheck size={19}/><div><b>Publicación controlada</b><p>El siguiente paso guardará archivo original, hash, responsable, fecha y resultado de validación. La persistencia se habilitará al conectar la base de datos.</p></div></div><button className="button primary full-button" disabled={!publishable}>Preparar publicación</button><small className="disabled-note">{publishable?'Archivo válido y listo para la siguiente etapa.':'Selecciona un archivo válido y confirma su planta.'}</small></aside></section>
    <section className="panel import-history"><header className="panel-header"><h2>Historial de importaciones</h2><span>Persistencia pendiente</span></header><div className="empty-state"><FileSpreadsheet size={30}/><h3>No hay importaciones publicadas</h3><p>La planilla canónica 2025 está disponible como referencia histórica, pero aún no se encuentra registrada como lote de importación ni asignada a una planta.</p></div></section></>
}

function InspectionResult({inspection}:{inspection:Inspection}){const valid=inspection.errors.length===0;return <div className={`inspection-result ${valid?'valid':'invalid'}`}><header>{valid?<CheckCircle2 size={19}/>:<AlertTriangle size={19}/>}<div><b>{valid?'Estructura compatible':'Archivo con errores'}</b><small>{inspection.fileName} · Hoja “{inspection.sheet}”</small></div></header><div className="inspection-metrics"><span>Filas detectadas<b>{inspection.rows}</b></span><span>Filas válidas<b>{inspection.validRows}</b></span><span>Columnas con nombre<b>{inspection.columns}</b></span></div>{inspection.errors.map(error=><p className="validation-error" key={error}>{error}</p>)}{inspection.warnings.map(warning=><p className="validation-warning" key={warning}>{warning}</p>)}</div>}
