import { AlertCircle, ArrowRight, CheckCircle2, Download, FileSpreadsheet, ShieldCheck, Upload } from 'lucide-react'
import { useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { createImportBatch, readPlantWorkbook, type ImportBatch, type PlantState, type ValidatedImport } from '../plantImport'
import { plants } from '../plants'
import { usePlatformStatus } from '../hooks/usePlatformStatus'

const sample='planta,periodo,produccion_kg,meta_kg,inventario_kg,producto_terminado_kg,fecha_actualizacion,observacion\nancud,2026-08,18420,18000,6250,3120,2026-08-20T08:45:00,Operación normal\nquellon,2026-08,26880,28000,9340,4820,2026-08-20T09:10:00,Sin novedades'

export function Imports(){
  const input=useRef<HTMLInputElement>(null)
  const [rows,setRows]=useState<ValidatedImport[]>([]),[fileName,setFileName]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[published,setPublished]=useState<ImportBatch|null>(null)
  const {status,error}=usePlatformStatus()
  const valid=rows.filter(row=>!row.errors.length),invalid=rows.length-valid.length
  const reset=()=>{setRows([]);setFileName('');setMessage('');setPublished(null);if(input.current)input.current.value=''}
  const choose=async(file?:File)=>{if(!file)return;setBusy(true);setMessage('');setPublished(null);try{const parsed=await readPlantWorkbook(file,plants);setRows(parsed);setFileName(file.name);if(!parsed.length)setMessage('La primera hoja no contiene filas de datos.')}catch{setRows([]);setMessage('No fue posible leer el archivo. Verifica que sea XLSX, XLS o CSV.')}finally{setBusy(false)}}
  const publish=()=>{if(!valid.length||invalid)return;const current=readLocal<PlantState[]>('pescamar.plants.v2',plants),history=readLocal<ImportBatch[]>('pescamar.imports.v2',[]),batch=createImportBatch(current,valid);localStorage.setItem('pescamar.plants.v2',JSON.stringify(batch.resultingPlants));localStorage.setItem('pescamar.imports.v2',JSON.stringify([batch,...history].slice(0,10)));setPublished(batch)}
  return <><PageHeader eyebrow="Gobierno de datos" title="Importar planilla" description="Un único flujo para validar y publicar el resumen operacional de las plantas." actions={<Link className="button secondary" to="/"><ArrowRight size={15}/>Volver al control</Link>}/>
    <section className="platform-strip"><div><span className={`platform-dot ${status?.ok?'online':'pending'}`}/><span><small>Vercel Functions</small><b>{status?.ok?'Conectado':error?'No disponible':'Comprobando…'}</b></span></div><div><small>Persistencia actual</small><b>Navegador local</b></div><div><small>Base multiusuario</small><b>{status?.persistence.database?'Conectada':'Pendiente'}</b></div><div><small>Entorno</small><b>{status?.environment??'—'}</b></div></section>
    <div className="local-data-warning"><ShieldCheck/><span><b>Modo demostración controlada</b><small>La publicación queda sólo en este navegador. No es compartida, auditable ni respaldada hasta conectar la base de datos.</small></span></div>
    {published?<section className="panel publish-success"><CheckCircle2/><div><span className="overline teal">Publicación completada</span><h2>{published.rowCount} plantas actualizadas</h2><p>{published.fileName} · {published.id}</p></div><Link className="button primary" to="/">Ver centro de control</Link></section>:<section className="import-layout"><article className="panel import-upload"><div className="import-step"><span>01</span><div><h2>Seleccionar y validar</h2><p>Usa la plantilla del MVP. El archivo no modifica datos durante esta etapa.</p></div></div>{!rows.length?<><button className="file-drop file-drop-button" onClick={()=>input.current?.click()} disabled={busy}><Upload size={28}/><b>{busy?'Analizando archivo…':'Seleccionar Excel o CSV'}</b><small>.xlsx, .xls o .csv · primera hoja</small></button><input ref={input} hidden type="file" accept=".xlsx,.xls,.csv" onChange={event=>void choose(event.target.files?.[0])}/><a className="button secondary template-download" download="plantilla_resumen_pescamar.csv" href={`data:text/csv;charset=utf-8,${encodeURIComponent(sample)}`}><Download size={15}/>Descargar plantilla</a>{message?<p className="validation-error import-page-error"><AlertCircle/>{message}</p>:null}</>:<ImportPreview rows={rows} fileName={fileName} onReset={reset}/>}</article>
      <aside className="panel import-assignment"><div className="import-step"><span>02</span><div><h2>Publicar resumen</h2><p>La planta se reconoce desde cada fila y el semáforo se recalcula automáticamente.</p></div></div><div className="publish-checks"><span className={rows.length?'done':''}><CheckCircle2/>Archivo seleccionado</span><span className={valid.length?'done':''}><CheckCircle2/>{valid.length} filas válidas</span><span className={invalid?'failed':rows.length?'done':''}><CheckCircle2/>{invalid?`${invalid} filas con error`:'Sin errores bloqueantes'}</span></div><button className="button primary full-button" disabled={!valid.length||invalid>0} onClick={publish}>Publicar {valid.length||''} plantas</button><small className="disabled-note">{invalid?'Corrige todas las filas antes de publicar.':valid.length?'Publicará un snapshot reversible en este navegador.':'Selecciona una planilla para continuar.'}</small></aside></section>}
    <section className="panel import-contract-panel"><header className="panel-header"><h2>Contrato mínimo de datos</h2><span>Versión MVP</span></header><div className="contract-fields">{['planta','periodo','produccion_kg','meta_kg','inventario_kg','producto_terminado_kg','fecha_actualizacion'].map(field=><code key={field}>{field}</code>)}</div><p>Una fila por planta y período. Las seis plantas pueden cargarse juntas; una planta no puede repetirse dentro del mismo archivo.</p></section>
  </>
}

function ImportPreview({rows,fileName,onReset}:{rows:ValidatedImport[];fileName:string;onReset:()=>void}){return <><div className="import-file"><FileSpreadsheet/><span><b>{fileName}</b><small>{rows.length} filas detectadas</small></span><button className="button secondary" onClick={onReset}>Cambiar archivo</button></div><div className="import-table-wrap"><table className="import-table"><thead><tr><th>Fila</th><th>Planta</th><th>Período</th><th>Producción</th><th>Meta</th><th>Inventario</th><th>Validación</th></tr></thead><tbody>{rows.map(row=><tr key={row.rowNumber} className={row.errors.length?'has-error':''}><td>{row.rowNumber}</td><td>{row.plant?.name??row.plantId}</td><td>{row.period||'—'}</td><td>{format(row.productionKg)}</td><td>{format(row.targetKg)}</td><td>{format(row.inventoryKg)}</td><td>{row.errors.length?<span className="import-errors"><AlertCircle/>{row.errors.join(' · ')}</span>:<span className="import-ok"><CheckCircle2/>Lista para publicar</span>}</td></tr>)}</tbody></table></div></>}
const format=(value:number)=>Number.isFinite(value)?value.toLocaleString('es-CL'):'—'
function readLocal<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)??'null')??fallback}catch{return fallback}}
