import {Activity,ArrowRight,CheckCircle2,CircleDashed,GitBranch,ShieldCheck} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import {useAuth} from '../auth'
import {PageHeader} from '../components/PageHeader'
import {TechnicalGlossary} from '../components/TechnicalGlossary'
import {useLocale} from '../i18n'
import {integrationAdapters,integrationContract,type IntegrationAdapter,type IntegrationStatus} from '../integrations'
import {organizationContext} from '../organization'

type RegistryPayload={ok?:boolean;schemaVersion?:string;organization?:{id:string;implementationId:string;implementationName:string;isolationMode:string};adapters?:Array<IntegrationAdapter&{organizationId:string;mutationEnabled:boolean}>;guardrails?:string[];writePlane?:Record<string,boolean>;message?:string;error?:string}
type HumanCopy={es:{label:string;summary:string};en:{label:string;summary:string}}
const statusClass:Record<IntegrationStatus,string>={evidenced:'success',foundation:'info',planned:'info'}
const adapterCopy:Record<string,HumanCopy>={
 'pescamar-canonical-workbook':{es:{label:'Archivos históricos auditados de Pescamar',summary:'Incorpora información histórica conservando archivo de origen, identidad y trazabilidad.'},en:{label:'Audited Pescamar historical files',summary:'Loads historical information while preserving source file, identity and lineage.'}},
 'pescamar-univision':{es:{label:'Uni Vision · evidencia visual',summary:'Convierte una captura visual en evidencia vinculada al evento y al lote correspondiente.'},en:{label:'Uni Vision · visual evidence',summary:'Turns a visual capture into evidence linked to the corresponding event and lot.'}},
 'pescamar-cold-sensor-rest':{es:{label:'Sensores de cadena de frío',summary:'Base preparada para recibir temperaturas desde sensores autenticados. No declara hardware real conectado.'},en:{label:'Cold-chain sensors',summary:'Foundation prepared to receive temperatures from authenticated sensors. It does not claim real hardware is connected.'}},
 'seafood-rest-inbound':{es:{label:'Entrada desde otros sistemas por API',summary:'Contrato preparado para recibir datos de software externo; la escritura genérica permanece apagada.'},en:{label:'Inbound data from other systems by API',summary:'Contract prepared to receive external software data; generic writes remain disabled.'}},
 'seafood-webhook-inbound':{es:{label:'Avisos automáticos desde otros sistemas',summary:'Base para que un sistema externo avise a Pescamar cuando ocurra un evento. La recepción automática aún no está habilitada.'},en:{label:'Automatic notifications from other systems',summary:'Foundation for external systems to notify Pescamar when an event occurs. Automatic ingestion is not enabled yet.'}},
 'seafood-event-export':{es:{label:'Salida de eventos canónicos',summary:'Base para entregar eventos de trazabilidad de Pescamar a otros sistemas sin modificar la operación.'},en:{label:'Canonical event export',summary:'Foundation for sharing Pescamar traceability events with other systems without changing operations.'}},
 'mqtt-edge':{es:{label:'Sensores y dispositivos livianos',summary:'Conexión futura para telemetría y mediciones de equipos mediante MQTT.'},en:{label:'Lightweight sensors and devices',summary:'Future connection for equipment telemetry and measurements using MQTT.'}},
 'industrial-opcua':{es:{label:'Máquinas industriales mediante OPC UA',summary:'Conexión futura para leer variables y estados de equipos industriales de forma estándar.'},en:{label:'Industrial machines through OPC UA',summary:'Future connection for reading machine variables and states through an industrial standard.'}},
 'industrial-modbus':{es:{label:'Sensores y PLC mediante Modbus',summary:'Conexión futura para leer registros de equipos industriales cuando exista un mapa real del dispositivo.'},en:{label:'Sensors and PLCs through Modbus',summary:'Future connection for reading industrial equipment registers when a real device map exists.'}},
 'vision-rtsp-onvif':{es:{label:'Cámaras IP para Uni / EdgeVision',summary:'Conexión futura de video en vivo y control de cámaras compatibles mediante RTSP y ONVIF.'},en:{label:'IP cameras for Uni / EdgeVision',summary:'Future live-video and compatible-camera connection using RTSP and ONVIF.'}},
 'traceability-epcis-gdst':{es:{label:'Trazabilidad internacional de seafood',summary:'Base para traducir eventos de Pescamar al lenguaje internacional GDST/EPCIS. Aún no habilita intercambio externo ni certifica compatibilidad.'},en:{label:'International seafood traceability',summary:'Foundation for translating Pescamar events into GDST/EPCIS. It does not yet enable external exchange or certify compatibility.'}},
}
const fieldCopy:Record<string,{es:string;en:string}>={organizationId:{es:'Organización que envía o recibe el dato',en:'Organization sending or receiving the data'},sourceSystem:{es:'Sistema de origen',en:'Source system'},adapterId:{es:'Conector utilizado',en:'Connector used'},externalEventId:{es:'Identificador del evento en el sistema de origen',en:'Event identifier in the source system'},occurredAt:{es:'Cuándo ocurrió',en:'When it happened'},eventType:{es:'Qué tipo de evento es',en:'What kind of event it is'},payload:{es:'Contenido recibido',en:'Received content'}}
function protocolLabel(protocol:string,en:boolean){const labels:Record<string,[string,string]>={file:['Archivo','File'],rest:['API web (REST)','Web API (REST)'],webhook:['Aviso automático (webhook)','Automatic notification (webhook)'],mqtt:['Mensajería de sensores (MQTT)','Sensor messaging (MQTT)'],'opc-ua':['Conexión industrial (OPC UA)','Industrial connection (OPC UA)'],modbus:['Conexión industrial (Modbus)','Industrial connection (Modbus)'],'rtsp/onvif':['Video / cámaras IP (RTSP + ONVIF)','Video / IP cameras (RTSP + ONVIF)'],'event-api':['API de eventos','Event API'],'epcis/gdst':['Trazabilidad estándar (EPCIS + GDST)','Standard traceability (EPCIS + GDST)']};return (labels[protocol]??[protocol,protocol])[en?1:0]}

export function Integrations(){
 const {operator}=useAuth(),{locale}=useLocale(),en=locale==='en',organizationId=operator?.organizationId??organizationContext.organizationId
 const [payload,setPayload]=useState<RegistryPayload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{let active=true;setLoading(true);void fetch('/api/integrations',{cache:'no-store',headers:{'x-seafood-organization-id':organizationId}}).then(async response=>{const data=await response.json() as RegistryPayload;if(!response.ok)throw new Error(data.error??(en?'Could not load connections':'No fue posible cargar conexiones'));if(active){setPayload(data);setError('')}}).catch(cause=>{if(active){setPayload(null);setError(cause instanceof Error?cause.message:(en?'Could not load connections':'No fue posible cargar conexiones'))}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[organizationId,en])
 const adapters=payload?.adapters??integrationAdapters.map(adapter=>({...adapter,organizationId,mutationEnabled:false}))
 const counts=useMemo(()=>({evidenced:adapters.filter(item=>item.status==='evidenced').length,foundation:adapters.filter(item=>item.status==='foundation').length,planned:adapters.filter(item=>item.status==='planned').length}),[adapters])
 const writeEnabled=Object.values(payload?.writePlane??{}).some(Boolean)
 const statusLabel:Record<IntegrationStatus,string>=en?{evidenced:'Verified',foundation:'Prepared',planned:'Future'}:{evidenced:'Verificado',foundation:'Preparado',planned:'Futuro'}
 const directionLabel=en?{southbound:'Receives data',northbound:'Shares data',internal:'Internal connection'} as const:{southbound:'Recibe datos',northbound:'Entrega datos',internal:'Conexión interna'} as const
 return <><PageHeader eyebrow={en?'Seafood Intelligence OS · Connections':'Seafood Intelligence OS · Conexiones'} title={en?'Connections with other systems':'Conexiones con otros sistemas'} description={en?'Shows what can exchange information with Pescamar, what is already verified, what is only prepared, and what remains future. Technical names are secondary and explained below.':'Muestra qué puede intercambiar información con Pescamar, qué ya está verificado, qué está sólo preparado y qué sigue siendo futuro. Los nombres técnicos quedan en segundo plano y se explican abajo.'} actions={<div className="row-actions"><Link className="button secondary" to="/organization">{en?'Organization':'Organización'} <ArrowRight size={13}/></Link><Link className="button secondary" to="/lineage"><GitBranch size={14}/>{en?'Traceability':'Trazabilidad'}</Link></div>}/>
 <section className="signal-grid"><article className="signal-card"><span><CheckCircle2 size={16}/>{en?'Verified':'Verificados'}</span><b>{counts.evidenced}</b><small>{en?'real sources or flows already evidenced':'fuentes o flujos reales ya evidenciados'}</small></article><article className="signal-card"><span><Activity size={16}/>{en?'Prepared':'Preparados'}</span><b>{counts.foundation}</b><small>{en?'structure ready; connection or write still off':'estructura lista; conexión o escritura aún apagada'}</small></article><article className="signal-card"><span><CircleDashed size={16}/>{en?'Future':'Futuros'}</span><b>{counts.planned}</b><small>{en?'no real connection is claimed':'no se declara conexión real'}</small></article><article className="signal-card"><span><ShieldCheck size={16}/>{en?'External writes':'Escritura externa'}</span><b>{writeEnabled?'ON':'OFF'}</b><small>{en?'generic writes remain disabled':'las escrituras genéricas siguen deshabilitadas'}</small></article></section>
 {error?<div className="notice error">{error}</div>:null}
 <section className="panel"><div className="section-heading"><div><span className="overline teal">{en?'Available connectors':'Conectores disponibles'}</span><h2>{en?'What comes in, what goes out, and why':'Qué entra, qué sale y para qué sirve'}</h2></div><span>{loading?(en?'Checking…':'Verificando…'):`${adapters.length} ${en?'connectors':'conectores'}`}</span></div><div className="compact-ledger">{adapters.map(adapter=>{const copy=adapterCopy[adapter.id]?.[locale]??{label:adapter.label,summary:adapter.evidence};return <div className="alert-row static" key={adapter.id}><span><GitBranch size={15}/></span><div><b>{copy.label}</b><small>{directionLabel[adapter.direction]} · {protocolLabel(adapter.protocol,en)}</small><p className="source-note">{copy.summary}</p><small>{en?'Technical mapping':'Mapa técnico'}: {adapter.mapsTo}</small></div><span className={`status ${statusClass[adapter.status]}`}>{statusLabel[adapter.status]}</span></div>})}</div></section>
 <section className="panel"><div className="section-heading"><div><span className="overline teal">{en?'Minimum data contract':'Contrato mínimo de datos'}</span><h2>{en?'What every inbound event must carry':'Qué debe traer cada evento que entra'}</h2></div><span className="status info">{en?'read only':'sólo lectura'}</span></div><div className="os-stage-modules">{integrationContract.required.map((field,index)=><div className="alert-row static" key={field}><span className="os-module-step">{String(index+1).padStart(2,'0')}</span><div><b>{fieldCopy[field]?.[locale]??field}</b><small>{en?'Technical field':'Campo técnico'}: {field}</small></div></div>)}</div></section>
 <section className="panel"><div className="section-heading"><div><span className="overline teal">{en?'Safety before automation':'Seguridad antes de automatizar'}</span><h2>{en?'Before an external system can write':'Antes de permitir que un sistema externo escriba'}</h2></div></div><div className="governance-note"><ShieldCheck size={19}/><div><b>{en?'External writes remain disabled until every control is verified.':'La escritura externa permanece apagada hasta verificar todos los controles.'}</b><p>{en?'Pescamar must know which organization sends the data, which connector is authorized, whether the event was already received, whether its structure is valid, and what to do when it is rejected.':'Pescamar debe saber qué organización envía el dato, qué conector está autorizado, si el evento ya fue recibido, si su estructura es válida y qué hacer cuando es rechazado.'}</p><small>{en?'No unknown value is silently converted into zero or into a confirmed fact.':'Ningún valor desconocido se convierte silenciosamente en cero ni en un hecho confirmado.'}</small></div></div></section>
 <TechnicalGlossary locale={locale} terms={['api','rest','webhook','mqtt','opc_ua','modbus','rtsp','onvif','gdst','epcis','cte','kde','json_ld','digital_link']}/>
 </>}
