import {Activity,ArrowRight,CheckCircle2,CircleDashed,GitBranch,ShieldCheck} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import {useAuth} from '../auth'
import {PageHeader} from '../components/PageHeader'
import {integrationAdapters,integrationContract,type IntegrationAdapter,type IntegrationStatus} from '../integrations'
import {organizationContext} from '../organization'

type RegistryPayload={ok?:boolean;schemaVersion?:string;organization?:{id:string;implementationId:string;implementationName:string;isolationMode:string};adapters?:Array<IntegrationAdapter&{organizationId:string;mutationEnabled:boolean}>;guardrails?:string[];writePlane?:Record<string,boolean>;message?:string;error?:string}
const statusLabel:Record<IntegrationStatus,string>={evidenced:'Evidenciado',foundation:'Fundación',planned:'Planificado'}
const statusClass:Record<IntegrationStatus,string>={evidenced:'success',foundation:'info',planned:'info'}
const directionLabel={southbound:'Entrada',northbound:'Salida',internal:'Interno'} as const

export function Integrations(){
 const {operator}=useAuth(),organizationId=operator?.organizationId??organizationContext.organizationId
 const [payload,setPayload]=useState<RegistryPayload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{let active=true;setLoading(true);void fetch('/api/integrations',{cache:'no-store',headers:{'x-seafood-organization-id':organizationId}}).then(async response=>{const data=await response.json() as RegistryPayload;if(!response.ok)throw new Error(data.error??'No fue posible cargar integraciones');if(active){setPayload(data);setError('')}}).catch(cause=>{if(active){setPayload(null);setError(cause instanceof Error?cause.message:'No fue posible cargar integraciones')}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[organizationId])
 const adapters=payload?.adapters??integrationAdapters.map(adapter=>({...adapter,organizationId,mutationEnabled:false}))
 const counts=useMemo(()=>({evidenced:adapters.filter(item=>item.status==='evidenced').length,foundation:adapters.filter(item=>item.status==='foundation').length,planned:adapters.filter(item=>item.status==='planned').length}),[adapters])
 const writeEnabled=Object.values(payload?.writePlane??{}).some(Boolean)
 return <><PageHeader eyebrow="Seafood Intelligence OS · Data Plane" title="Integrations" description="Registro de adapters y contratos de interoperabilidad. El objetivo es conectar sistemas existentes sin convertir el core en un fork por cliente o hardware." actions={<div className="row-actions"><Link className="button secondary" to="/organization">Organization Context <ArrowRight size={13}/></Link><Link className="button secondary" to="/lineage"><GitBranch size={14}/>Event Graph</Link></div>}/>
 <section className="signal-grid"><article className="signal-card"><span><CheckCircle2 size={16}/>Evidenciados</span><b>{counts.evidenced}</b><small>fuentes con evidencia existente</small></article><article className="signal-card"><span><Activity size={16}/>Fundación</span><b>{counts.foundation}</b><small>contrato listo, writer no habilitado</small></article><article className="signal-card"><span><CircleDashed size={16}/>Planificados</span><b>{counts.planned}</b><small>sin claim de conexión real</small></article><article className="signal-card"><span><ShieldCheck size={16}/>Write plane</span><b>{writeEnabled?'ON':'OFF'}</b><small>generic inbound permanece deshabilitado</small></article></section>
 {error?<div className="notice error">{error}</div>:null}
 <section className="panel"><div className="section-heading"><div><span className="overline teal">Adapter registry</span><h2>Southbound, internal y northbound</h2></div><span>{loading?'Verificando…':`${adapters.length} adapters`}</span></div><div className="compact-ledger">{adapters.map(adapter=><div className="alert-row static" key={adapter.id}><span><GitBranch size={15}/></span><div><b>{adapter.label}</b><small>{directionLabel[adapter.direction]} · {adapter.protocol} · {adapter.mapsTo}</small><p className="source-note">{adapter.evidence}</p></div><span className={`status ${statusClass[adapter.status]}`}>{statusLabel[adapter.status]}</span></div>)}</div></section>
 <section className="panel"><div className="section-heading"><div><span className="overline teal">Canonical ingress contract</span><h2>{payload?.schemaVersion??integrationContract.schemaVersion}</h2></div><span className="status info">read-only foundation</span></div><div className="os-stage-modules">{integrationContract.required.map((field,index)=><div className="alert-row static" key={field}><span className="os-module-step">{String(index+1).padStart(2,'0')}</span><div><b>{field}</b><small>{index<2?'Tenant + source boundary':'Canonical ingress envelope'}</small></div></div>)}</div></section>
 <section className="panel"><div className="section-heading"><div><span className="overline teal">Safety plane</span><h2>Antes de habilitar cualquier writer</h2></div></div><div className="governance-note"><ShieldCheck size={19}/><div><b>{payload?.message??'Registry read-only: ningún adapter genérico de escritura está habilitado.'}</b><p>Una integración externa no puede escribir sólo por declarar un protocolo. Debe resolver organización autenticada, adapter allowlist, idempotencia, schema validation y tratamiento explícito de payload rechazado.</p><small>{(payload?.guardrails??[...integrationContract.safety]).join(' · ')}</small></div></div></section>
 </>}
