import {ArrowRight,CheckCircle2,CircleDashed,GitBranch,History,ShieldCheck} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {PageHeader} from '../components/PageHeader'
import {useLots} from '../store'
import '../lineage.css'

type EventType='reception'|'evidence'|'quality'|'production'|'note'|'inventory'|'commercial_commitment'|'dispatch'|'sale'
type LineageEvent={id:string;schemaVersion:string;organizationId:string;siteId:string|null;lotId:string;type:EventType;occurredAt:string|null;title:string;detail:string|null;actor:string|null;metrics:Record<string,unknown>;source:{system:string;entityType:string;entityId:string}}
type Coverage={reception:boolean;evidence:boolean;quality:boolean;production:boolean;inventory:boolean;commercialCommitment:boolean;dispatch:boolean;sale:boolean|null}
type Payload={schemaVersion?:string;organizationId?:string;siteId?:string|null;lotId?:string;events?:LineageEvent[];coverage?:Coverage;permissions?:{canSeeCommercial?:boolean};error?:string}
const stageLabels:Record<keyof Coverage,string>={reception:'Recepción',evidence:'Evidencia',quality:'Calidad',production:'Producción',inventory:'Inventario',commercialCommitment:'Comercial',dispatch:'Despacho',sale:'Venta'}
const typeLabels:Record<EventType,string>={reception:'Recepción',evidence:'Evidencia',quality:'Calidad',production:'Producción',note:'Nota',inventory:'Inventario',commercial_commitment:'Compromiso',dispatch:'Despacho',sale:'Venta'}
const dt=(value:string|null)=>value?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Sin fecha'
function summary(event:LineageEvent){const m=event.metrics??{};switch(event.type){case'reception':return [m.supplier,m.species,m.grossKg!=null?`${Number(m.grossKg).toLocaleString('es-CL')} kg`:null].filter(Boolean).join(' · ');case'quality':return [m.qualityStatus,m.defectPct!=null?`${Number(m.defectPct).toFixed(1)}% defectos`:null].filter(Boolean).join(' · ');case'production':return [m.lineName,m.outputKg!=null?`${Number(m.outputKg).toLocaleString('es-CL')} kg salida`:null,m.yieldPct!=null?`${Number(m.yieldPct).toFixed(1)}% yield`:null].filter(Boolean).join(' · ');case'inventory':return [m.movedKg!=null?`${Number(m.movedKg).toLocaleString('es-CL')} kg`:null,m.fromLocation?String(m.fromLocation):'Ingreso',m.toLocation?`→ ${String(m.toLocation)}`:null].filter(Boolean).join(' · ');case'commercial_commitment':return [m.customer,m.allocatedKg!=null?`${Number(m.allocatedKg).toLocaleString('es-CL')} kg`:null,m.status].filter(Boolean).join(' · ');case'dispatch':return [m.customer,m.dispatchedKg!=null?`${Number(m.dispatchedKg).toLocaleString('es-CL')} kg`:null,m.status].filter(Boolean).join(' · ');case'sale':return [m.customer,m.soldKg!=null?`${Number(m.soldKg).toLocaleString('es-CL')} kg`:null,m.status].filter(Boolean).join(' · ');default:return event.detail??''}}

export function Lineage(){
 const {lots,loading:lotsLoading,error:lotsError}=useLots(),[params,setParams]=useSearchParams();
 const requested=params.get('receptionId')??'',selectedId=requested||lots[0]?.receptionId||'';
 const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!selectedId){setData(null);return}let active=true;setLoading(true);void fetch(`/api/lot-lineage?receptionId=${encodeURIComponent(selectedId)}`,{cache:'no-store'}).then(async response=>{const payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error??'No fue posible cargar el lineage');if(active){setData(payload);setError('')}}).catch(cause=>{if(active){setData(null);setError(cause instanceof Error?cause.message:'No fue posible cargar el lineage')}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[selectedId]);
 const selectedLot=lots.find(lot=>lot.receptionId===selectedId),events=data?.events??[],coverage=data?.coverage;
 const coverageEntries=useMemo(()=>coverage?Object.entries(coverage).filter(([,value])=>value!==null) as [keyof Coverage,boolean][]:[],[coverage]);
 const complete=coverageEntries.filter(([,value])=>value).length,total=coverageEntries.length;
 return <><PageHeader eyebrow="Seafood Event Graph" title="Lineage operacional del lote" description="Una vista canónica y ordenada de la evidencia que conecta recepción, calidad, producción, inventario y outcome comercial." actions={<div className="lineage-selector"><label htmlFor="lineage-lot">Lote</label><select id="lineage-lot" value={selectedId} onChange={event=>setParams({receptionId:event.target.value})} disabled={lotsLoading||!lots.length}>{lots.map(lot=><option key={lot.receptionId} value={lot.receptionId}>{lot.id} · {lot.supplier} · {lot.species}</option>)}</select></div>}/>
 {lotsError?<div className="notice error">{lotsError}</div>:null}
 {!selectedId&&!lotsLoading?<section className="panel lineage-empty"><GitBranch size={28}/><h2>Sin lotes disponibles</h2><p>El Event Graph aparecerá cuando exista una recepción accesible para tu usuario.</p></section>:null}
 {selectedId?<><section className="lineage-overview"><article className="panel"><span>Implementación</span><strong>Pescamar</strong><small>{data?.organizationId??'pescamar'} · {data?.siteId??selectedLot?.plantId??'sin planta'}</small></article><article className="panel"><span>Lote</span><strong>{selectedLot?.id??selectedId.slice(0,8)}</strong><small>{selectedLot?`${selectedLot.supplier} · ${selectedLot.species}`:'Identidad canónica'}</small></article><article className="panel"><span>Cobertura</span><strong>{total?`${complete}/${total}`:'—'}</strong><small>etapas con evidencia visible</small></article><article className="panel"><span>Eventos</span><strong>{events.length}</strong><small>{data?.schemaVersion??'seafood.lineage.v1'}</small></article></section>
 <section className="panel lineage-coverage"><div className="section-heading"><div><span className="overline teal">Cobertura canónica</span><h2>Qué puede explicar hoy este lote</h2></div>{total&&complete===total?<span className="status success"><ShieldCheck size={12}/>Completo</span>:<span className="status info"><CircleDashed size={12}/>Parcial</span>}</div><div className="lineage-stage-grid">{coverageEntries.map(([key,value])=><div className={`lineage-stage ${value?'present':'missing'}`} key={key}>{value?<CheckCircle2 size={15}/>:<CircleDashed size={15}/>}<span>{stageLabels[key]}</span><small>{value?'Con evidencia':'Sin evento'}</small></div>)}</div></section>
 <section className="panel lineage-events"><div className="section-heading"><div><span className="overline teal">Event stream</span><h2>Secuencia atribuible</h2></div><Link className="source-link compact" to={`/recepciones?receptionId=${encodeURIComponent(selectedId)}`}>Abrir recepción <ArrowRight size={13}/></Link></div>{loading&&!data?<div className="lineage-loading"><History size={18}/>Construyendo lineage…</div>:error?<div className="notice error">{error}</div>:events.length?<ol>{events.map(event=><li key={event.id}><span className={`lineage-event-marker ${event.type}`}><GitBranch size={14}/></span><div><div className="lineage-event-head"><b>{event.title}</b><span>{typeLabels[event.type]}</span></div>{summary(event)?<p>{summary(event)}</p>:null}<small>{dt(event.occurredAt)}{event.actor?` · ${event.actor}`:''} · {event.source.entityType}</small></div></li>)}</ol>:<div className="lineage-loading"><CircleDashed size={18}/>Sin eventos disponibles</div>}</section></>:null}</>}
