import {AlertTriangle,ArrowRight,CheckCircle2,CircleDashed,GitBranch,History,ShieldCheck} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {useAuth} from '../auth'
import {PageHeader} from '../components/PageHeader'
import {organizationContext} from '../organization'
import {useLots} from '../store'
import '../lineage.css'

type EventType='reception'|'evidence'|'quality'|'production'|'vision'|'note'|'inventory'|'commercial_commitment'|'dispatch'|'sale'
type LineageEvent={id:string;schemaVersion:string;organizationId:string;siteId:string|null;lotId:string;type:EventType;occurredAt:string|null;title:string;detail:string|null;actor:string|null;metrics:Record<string,unknown>;source:{system:string;entityType:string;entityId:string}}
type Coverage={reception:boolean;evidence:boolean;quality:boolean;production:boolean;vision:boolean;inventory:boolean;commercialCommitment:boolean;dispatch:boolean;sale:boolean|null}
type OperationalSignal={priority:1|2|3;kind:string;title:string;detail:string;confidence:'observed'|'derived';action:string;evidenceEventIds:string[];blockers:string[]}
type OperationalIntelligence={schemaVersion:string;mode:'live';lotId:string|null;organizationId:string|null;generatedFromEvents:number;highestPriority:1|2|3|null;counts:{p1:number;p2:number;p3:number};signals:OperationalSignal[];boundary:{writesOperationalState:false;rule:string}}
type Payload={schemaVersion?:string;organizationId?:string;organization?:{id:string;implementationId:string;implementationName:string;isolationMode:string};siteId?:string|null;lotId?:string;recordId?:string;mode?:string;events?:LineageEvent[];coverage?:Coverage;intelligence?:OperationalIntelligence;permissions?:{canSeeCommercial?:boolean};boundary?:{organizationScoped?:boolean;readOnly?:boolean;canonicalHistorical?:boolean;liveInventory?:boolean};error?:string}
type HistoricalRecord={id:string;lotCode:string|null;sourceFile:string|null;sourceRow:number|null;eventDate:string|null;receptionDate:string|null;processDate:string|null;productionDate:string|null;guideNumber:string|null;supplier:string|null;extractionZone:string|null;processSite:string|null;plantId:string|null;guideKg:number|null;receivedKg:number|null;differenceKg:number|null;qualityFlags:unknown[]}
type HistoricalIndex={records?:HistoricalRecord[];count?:number;year?:number;error?:string}
const stageLabels:Record<keyof Coverage,string>={reception:'Recepción',evidence:'Evidencia',quality:'Calidad',production:'Producción',vision:'Vision',inventory:'Inventario',commercialCommitment:'Comercial',dispatch:'Despacho',sale:'Venta'}
const typeLabels:Record<EventType,string>={reception:'Recepción',evidence:'Evidencia',quality:'Calidad',production:'Producción',vision:'Vision',note:'Nota',inventory:'Inventario',commercial_commitment:'Compromiso',dispatch:'Despacho',sale:'Venta'}
const priorityLabels:Record<1|2|3,string>={1:'P1 · Crítico',2:'P2 · Revisar',3:'P3 · Completar'}
const confidenceLabels:Record<OperationalSignal['confidence'],string>={observed:'Observado',derived:'Derivado'}
const dt=(value:string|null)=>value?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Sin fecha'
const shortDate=(value:string|null)=>value?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium'}).format(new Date(value)):'sin fecha'
function summary(event:LineageEvent){const m=event.metrics??{};switch(event.type){case'reception':return [m.supplier,m.species,m.receivedKg!=null?`${Number(m.receivedKg).toLocaleString('es-CL')} kg recibidos`:m.grossKg!=null?`${Number(m.grossKg).toLocaleString('es-CL')} kg`:null].filter(Boolean).join(' · ');case'quality':return [m.qualityStatus,m.qualityDiscount!=null?`descuento ${Number(m.qualityDiscount).toLocaleString('es-CL')}`:null,m.defectPct!=null?`${Number(m.defectPct).toFixed(1)}% defectos`:null].filter(Boolean).join(' · ');case'production':return [m.lineName,m.processSite,m.outputKg!=null?`${Number(m.outputKg).toLocaleString('es-CL')} kg salida`:null,m.yieldPct!=null?`${Number(m.yieldPct).toFixed(1)}% yield`:null,m.historical?'evidencia histórica':null].filter(Boolean).join(' · ');case'vision':return [m.operatorGrade?`Grade ${String(m.operatorGrade)}`:m.suggestedGrade?`Sugerido ${String(m.suggestedGrade)}`:null,m.deltaE!=null?`ΔE ${Number(m.deltaE).toFixed(2)}`:null,m.decision?String(m.decision):null,m.deviceLabel?String(m.deviceLabel):null].filter(Boolean).join(' · ');case'inventory':return [m.movedKg!=null?`${Number(m.movedKg).toLocaleString('es-CL')} kg`:null,m.fromLocation?String(m.fromLocation):'Ingreso',m.toLocation?`→ ${String(m.toLocation)}`:null].filter(Boolean).join(' · ');case'commercial_commitment':return [m.customer,m.allocatedKg!=null?`${Number(m.allocatedKg).toLocaleString('es-CL')} kg`:null,m.status].filter(Boolean).join(' · ');case'dispatch':return [m.customer,m.dispatchedKg!=null?`${Number(m.dispatchedKg).toLocaleString('es-CL')} kg`:null,m.status].filter(Boolean).join(' · ');case'sale':return [m.customer,m.soldKg!=null?`${Number(m.soldKg).toLocaleString('es-CL')} kg`:null,m.status].filter(Boolean).join(' · ');case'evidence':return [m.sourceFile,m.sourceRow!=null?`fila ${String(m.sourceRow)}`:null].filter(Boolean).join(' · ');default:return event.detail??''}}

export function Lineage(){
 const {operator}=useAuth(),{lots,loading:lotsLoading,error:lotsError}=useLots(),[params,setParams]=useSearchParams();
 const requestOrganizationId=operator?.organizationId??organizationContext.organizationId,mode=params.get('mode')==='historical'||(!lotsLoading&&!lots.length&&params.get('mode')!=='live')?'historical':'live',year=Number(params.get('year')??'2026');
 const requested=params.get('receptionId')??'',selectedId=requested||lots[0]?.receptionId||'';
 const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [historicalIndex,setHistoricalIndex]=useState<HistoricalIndex|null>(null),[historicalLoading,setHistoricalLoading]=useState(false),[historicalError,setHistoricalError]=useState('');
 const historicalRecords=historicalIndex?.records??[],requestedRecord=params.get('recordId')??'',selectedHistoricalId=requestedRecord||historicalRecords[0]?.id||'';

 useEffect(()=>{if(mode!=='historical')return;let active=true;setHistoricalLoading(true);void fetch(`/api/historical-lineage?year=${encodeURIComponent(String(year))}`,{cache:'no-store',headers:{'x-seafood-organization-id':requestOrganizationId}}).then(async response=>{const payload=await response.json() as HistoricalIndex;if(!response.ok)throw new Error(payload.error??'No fue posible cargar la trazabilidad histórica');if(active){setHistoricalIndex(payload);setHistoricalError('')}}).catch(cause=>{if(active){setHistoricalIndex(null);setHistoricalError(cause instanceof Error?cause.message:'No fue posible cargar la trazabilidad histórica')}}).finally(()=>{if(active)setHistoricalLoading(false)});return()=>{active=false}},[mode,year,requestOrganizationId]);

 useEffect(()=>{const targetId=mode==='historical'?selectedHistoricalId:selectedId;if(!targetId){setData(null);setError('');return}let active=true;setLoading(true);const url=mode==='historical'?`/api/historical-lineage?recordId=${encodeURIComponent(targetId)}`:`/api/lot-lineage?receptionId=${encodeURIComponent(targetId)}`;void fetch(url,{cache:'no-store',headers:{'x-seafood-organization-id':requestOrganizationId}}).then(async response=>{const payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error??'No fue posible cargar la trazabilidad');if(active){setData(payload);setError('')}}).catch(cause=>{if(active){setData(null);setError(cause instanceof Error?cause.message:'No fue posible cargar la trazabilidad')}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[mode,selectedId,selectedHistoricalId,requestOrganizationId]);

 const selectedLot=lots.find(lot=>lot.receptionId===selectedId),selectedHistorical=historicalRecords.find(record=>record.id===selectedHistoricalId),events=useMemo(()=>data?.events??[],[data?.events]),coverage=data?.coverage;
 const coverageEntries=useMemo(()=>coverage?Object.entries(coverage).filter(([,value])=>value!==null) as [keyof Coverage,boolean][]:[],[coverage]);
 const eventById=useMemo(()=>new Map(events.map(event=>[event.id,event])),[events]);
 const intelligence=mode==='live'?data?.intelligence:undefined,signals=intelligence?.signals??[];
 const complete=coverageEntries.filter(([,value])=>value).length,total=coverageEntries.length;
 const implementationName=data?.organization?.implementationName??organizationContext.implementationName,organizationId=data?.organizationId??requestOrganizationId;
 const changeMode=(next:'live'|'historical')=>{const nextParams=new URLSearchParams();nextParams.set('mode',next);if(next==='historical')nextParams.set('year',String(year));setParams(nextParams)};
 const changeYear=(nextYear:number)=>{const nextParams=new URLSearchParams();nextParams.set('mode','historical');nextParams.set('year',String(nextYear));setParams(nextParams)};
 const changeHistoricalRecord=(id:string)=>{const nextParams=new URLSearchParams();nextParams.set('mode','historical');nextParams.set('year',String(year));nextParams.set('recordId',id);setParams(nextParams)};
 const actions=<div className="lineage-selector"><label htmlFor="lineage-mode">Vista</label><select id="lineage-mode" value={mode} onChange={event=>changeMode(event.target.value as 'live'|'historical')}><option value="live">Actual</option><option value="historical">Histórica</option></select>{mode==='live'?<><label htmlFor="lineage-lot">Lote</label><select id="lineage-lot" value={selectedId} onChange={event=>setParams({mode:'live',receptionId:event.target.value})} disabled={lotsLoading||!lots.length}>{lots.map(lot=><option key={lot.receptionId} value={lot.receptionId}>{lot.id} · {lot.supplier} · {lot.species}</option>)}</select></>:<><label htmlFor="lineage-year">Año</label><select id="lineage-year" value={year} onChange={event=>changeYear(Number(event.target.value))}><option value={2026}>2026</option><option value={2025}>2025</option></select><label htmlFor="lineage-historical-record">Registro</label><select id="lineage-historical-record" value={selectedHistoricalId} onChange={event=>changeHistoricalRecord(event.target.value)} disabled={historicalLoading||!historicalRecords.length}>{historicalRecords.map(record=><option key={record.id} value={record.id}>{record.lotCode??`fila ${record.sourceRow??'—'}`} · {record.supplier??'sin proveedor'} · {shortDate(record.eventDate)}</option>)}</select></>}</div>;

 const noSelection=mode==='live'?!selectedId&&!lotsLoading:!selectedHistoricalId&&!historicalLoading;
 return <><PageHeader eyebrow="Trazabilidad" title={mode==='live'?'Trazabilidad actual':'Trazabilidad histórica'} description={mode==='live'?'Sigue un lote desde la recepción hasta sus eventos de calidad, producción, inventario y comercial. Powered by Seafood Event Graph.':'Navega la evidencia histórica validada sin convertirla en operación live. Powered by Seafood Event Graph.'} actions={actions}/>
 {mode==='live'&&lotsError?<div className="notice error">{lotsError}</div>:null}
 {mode==='historical'&&historicalError?<div className="notice error">{historicalError}</div>:null}
 {mode==='historical'?<div className="notice info">Histórico canónico · solo lectura. {historicalIndex?.count??0} registros operacionales en {year}. No modifica ni completa artificialmente la operación live.</div>:null}
 {noSelection?<section className="panel lineage-empty"><GitBranch size={28}/><h2>{mode==='live'?'Sin lotes disponibles':'Sin registros históricos disponibles'}</h2><p>{mode==='live'?'No hay recepciones live accesibles. Puedes abrir la vista Histórica para navegar la evidencia ya construida.':'No existe evidencia operacional canónica para este año.'}</p></section>:null}
 {!noSelection?<><section className="lineage-overview"><article className="panel"><span>Implementación</span><strong>{implementationName}</strong><small>{organizationId} · {data?.siteId??selectedLot?.plantId??selectedHistorical?.processSite??'sin planta'}</small></article><article className="panel"><span>{mode==='live'?'Lote':'Registro histórico'}</span><strong>{mode==='live'?(selectedLot?.id??selectedId.slice(0,8)):(selectedHistorical?.lotCode??selectedHistoricalId.slice(0,8))}</strong><small>{mode==='live'?(selectedLot?`${selectedLot.supplier} · ${selectedLot.species}`:'Identidad canónica'):`${selectedHistorical?.supplier??'sin proveedor'} · ${selectedHistorical?.sourceFile??'fuente canónica'}`}</small></article><article className="panel"><span>Cobertura</span><strong>{total?`${complete}/${total}`:'—'}</strong><small>etapas con evidencia visible</small></article><article className="panel"><span>Eventos</span><strong>{events.length}</strong><small>{data?.schemaVersion??(mode==='live'?'seafood.lineage.v1':'seafood.historical-lineage.v1')}</small></article></section>
 <section className="panel lineage-coverage"><div className="section-heading"><div><span className="overline teal">Cobertura</span><h2>{mode==='live'?'Qué sabemos de este lote':'Qué sabemos de este registro'}</h2></div>{total&&complete===total?<span className="status success"><ShieldCheck size={12}/>Completo</span>:<span className="status info"><CircleDashed size={12}/>Parcial</span>}</div><div className="lineage-stage-grid">{coverageEntries.map(([key,value])=><div className={`lineage-stage ${value?'present':'missing'}`} key={key}>{value?<CheckCircle2 size={15}/>:<CircleDashed size={15}/>}<span>{stageLabels[key]}</span><small>{value?'Con evidencia':'Sin evento'}</small></div>)}</div></section>
 {mode==='live'&&intelligence?<section className="panel lineage-intelligence" aria-labelledby="lineage-intelligence-title"><div className="section-heading"><div><span className="overline teal">Operational Intelligence</span><h2 id="lineage-intelligence-title">Qué requiere atención</h2><p className="lineage-intelligence-intro">Señales derivadas únicamente de los {intelligence.generatedFromEvents} eventos visibles del Seafood Event Graph. Orientan revisión humana; no modifican estado operacional.</p></div><div className="lineage-intelligence-counts" aria-label="Resumen de señales"><span className="p1">P1 {intelligence.counts.p1}</span><span className="p2">P2 {intelligence.counts.p2}</span><span className="p3">P3 {intelligence.counts.p3}</span></div></div>{signals.length?<div className="lineage-signal-list">{signals.map((signal,index)=>{const evidence=signal.evidenceEventIds.map(id=>eventById.get(id)).filter((event):event is LineageEvent=>Boolean(event));return <article className={`lineage-signal p${signal.priority}`} key={`${signal.kind}:${signal.title}:${index}`}><div className="lineage-signal-top"><span className={`lineage-priority p${signal.priority}`}><AlertTriangle size={12}/>{priorityLabels[signal.priority]}</span><span className="lineage-confidence">{confidenceLabels[signal.confidence]}</span></div><h3>{signal.title}</h3><p>{signal.detail}</p><div className="lineage-signal-action"><b>Acción</b><span>{signal.action}</span></div><div className="lineage-signal-evidence"><b>Evidencia</b>{evidence.length?<span>{evidence.map(event=>event.title).join(' · ')}</span>:<span>{signal.evidenceEventIds.length} evento(s) atribuible(s)</span>}</div>{signal.blockers.length?<div className="lineage-signal-blockers"><b>Bloquea</b><span>{signal.blockers.join(' · ')}</span></div>:null}</article>})}</div>:<div className="lineage-intelligence-clear"><CheckCircle2 size={16}/><span>Sin señales operacionales para este lote con la evidencia actualmente visible.</span></div>}<small className="lineage-intelligence-boundary">{intelligence.boundary.rule}</small></section>:null}
 <section className="panel lineage-events"><div className="section-heading"><div><span className="overline teal">Secuencia</span><h2>Eventos atribuibles</h2></div>{mode==='live'?<Link className="source-link compact" to={`/recepciones?receptionId=${encodeURIComponent(selectedId)}`}>Abrir recepción <ArrowRight size={13}/></Link>:<span className="status info">HISTÓRICO · SOLO LECTURA</span>}</div>{loading&&!data?<div className="lineage-loading"><History size={18}/>Construyendo trazabilidad…</div>:error?<div className="notice error">{error}</div>:events.length?<ol>{events.map(event=><li key={event.id}><span className={`lineage-event-marker ${event.type}`}><GitBranch size={14}/></span><div><div className="lineage-event-head"><b>{event.title}</b><span>{typeLabels[event.type]}</span></div>{summary(event)?<p>{summary(event)}</p>:null}<small>{dt(event.occurredAt)}{event.actor?` · ${event.actor}`:''} · {event.source.entityType}</small></div></li>)}</ol>:<div className="lineage-loading"><CircleDashed size={18}/>Sin eventos disponibles</div>}</section></>:null}</>}
