import {AlertTriangle,ArrowRight,CheckCircle2,CircleDashed,FileCheck2,GitBranch,Scale,ShieldCheck,Sparkles} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link,useNavigate,useParams} from 'react-router-dom'
import {PageHeader} from '../components/PageHeader'
import './lot-360.css'

type LotEvent={id:string;event_type:'quality'|'production'|'note';title:string;detail:string|null;metrics:Record<string,unknown>;created_by:string;occurred_at:string}
type Reception={id:string;reception_number:string|number;plant_id:string;species:string;extraction_zone:string;source_reference:string|null;guide_kg:string|number|null;gross_kg:string|number|null;tare_kg:string|number|null;drained_kg:string|number|null;accepted_kg:string|number|null;temperature_c:string|number|null;quality_status:string;status:string;source:string;received_at:string;supplier:string;evidence:Array<{id?:string;kind?:string;label:string;url:string;note?:string|null;createdAt?:string}>}
type Commercial={visible?:boolean;physicalKg:number;dispatchedKg:number;availableKg:number;soldKg:number|null;revenueClp:number|null;allocatedCostClp:number|null;marginClp:number|null;marginPct:number|null}
type LotPayload={reception?:Reception;events?:LotEvent[];commercial?:Commercial;error?:string}
type Tone='ready'|'attention'|'pending'|'info'
type ControlCard={schemaVersion?:string;state:{code:string;label:string;tone:Tone};blocker:string|null;blockers:string[];nextAction:string;nextRoute:string;signals:{quality:{label:string;detail:string|null;tone:Tone};balance:{inputKg:number|null;outputKg:number|null;yieldPct:number|null;lossKg:number|null;tone:Tone};release:{label:string;tone:Tone;kind:'japan'|'evidence'}};evidence:{count:number};diagnosis:{state:'attention'|'clear';blockers:string[];nextAction:string;unknowns:string[]};error?:string}
type NodeStatus='pass'|'attention'|'pending'|'info'
type GraphNode={id:string;group:string;label:string;status:NodeStatus;detail:string;at:string|null;metrics?:Record<string,unknown>}
type GraphPayload={schemaVersion?:string;nodes?:GraphNode[];summary?:{nodes:number;attention:number;pending:number;japanReleasable:boolean|null};error?:string}
type State={lot:LotPayload;control:ControlCard;graph:GraphPayload|null}

const statusLabel:Record<NodeStatus,string>={pass:'OK',attention:'REVISAR',pending:'PENDIENTE',info:'INFO'}
const kg=(value:number|null)=>value==null?'—':`${value.toLocaleString('es-CL',{maximumFractionDigits:1})} kg`
const pct=(value:number|null)=>value==null?'—':`${value.toLocaleString('es-CL',{maximumFractionDigits:1})}%`
const clp=(value:number|null)=>value==null?'—':new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(value)
const dt=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'
const numberOrNull=(value:unknown)=>{if(value==null||value==='')return null;const number=Number(value);return Number.isFinite(number)?number:null}
async function readJson<T>(url:string){const response=await fetch(url,{cache:'no-store'});const payload=await response.json() as T&{error?:string};if(!response.ok)throw new Error(payload.error??'No fue posible cargar la ficha');return payload}
function StatusIcon({status}:{status:NodeStatus}){return status==='pass'?<CheckCircle2 size={15}/>:status==='attention'?<AlertTriangle size={15}/>:<CircleDashed size={15}/>}

export function Lot360(){
 const {receptionId=''}=useParams(),navigate=useNavigate()
 const [state,setState]=useState<State|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{if(!receptionId)return;let active=true;const load=async()=>{setLoading(true);try{const [lot,control]=await Promise.all([readJson<LotPayload>(`/api/lot-360?receptionId=${encodeURIComponent(receptionId)}`),readJson<ControlCard>(`/api/lot-control-card?receptionId=${encodeURIComponent(receptionId)}`)]),isUrchin=/eriz|urchin/i.test(lot.reception?.species??''),graphUrl=isUrchin?'/api/sea-urchin-graph':'/api/lot-graph';let graph:GraphPayload|null=null;const graphResult=await Promise.allSettled([readJson<GraphPayload>(`${graphUrl}?receptionId=${encodeURIComponent(receptionId)}`)]);if(graphResult[0]?.status==='fulfilled')graph=graphResult[0].value;if(active){setState({lot,control,graph});setError('')}}catch(cause){if(active){setState(null);setError(cause instanceof Error?cause.message:'No fue posible cargar la ficha')}}finally{if(active)setLoading(false)}};void load();const refresh=()=>void load();window.addEventListener('pescamar:data-updated',refresh);return()=>{active=false;window.removeEventListener('pescamar:data-updated',refresh)}},[receptionId])
 const r=state?.lot.reception,events=state?.lot.events??[],control=state?.control,graph=state?.graph,isUrchin=/eriz|urchin/i.test(r?.species??'')
 const evidenceCount=r?.evidence?.length??control?.evidence.count??0,recentEvents=events.slice(0,6)
 const graphGroups=useMemo(()=>{const nodes=graph?.nodes??[],order=['Origen','Recepción','Proceso','EdgeVision','Packing','Logística','Frío','Regulatorio','Exportación','Despacho','Economía'];return order.map(group=>({group,nodes:nodes.filter(node=>node.group===group)})).filter(item=>item.nodes.length)},[graph?.nodes])
 function askAi(){if(isUrchin){window.dispatchEvent(new CustomEvent('pescamar:open-urchin-ai',{detail:{receptionId}}));return}navigate(`/pescamar-ia?receptionId=${encodeURIComponent(receptionId)}`)}
 if(loading)return <div className="system-banner">Construyendo Ficha 360 del lote…</div>
 if(error||!r||!control)return <><PageHeader eyebrow="Lote 360" title="Ficha no disponible" description="No fue posible construir la vista canónica de este lote." actions={<Link className="button secondary" to="/recepciones">Volver</Link>}/><div className="system-banner error" role="alert">{error||'Lote no disponible'}</div></>
 const balance=control.signals.balance,release=control.signals.release
 return <div className="lot360-page">
  <PageHeader eyebrow="Lote 360 · Digital Twin" title={`REC-${r.reception_number}`} description={`${r.supplier} · ${r.species} · ${r.plant_id}`} actions={<Link className="button secondary" to="/recepciones">Volver a recepción</Link>}/>
  <section className={`lot360-hero ${control.blocker?'has-attention':'is-clear'}`} aria-label="Estado actual del lote">
   <div className="lot360-hero-copy"><span className="overline">Estado actual</span><h2>{control.state.label}</h2><p>{control.blocker??'Sin bloqueos visibles en la evidencia disponible.'}</p><div className="lot360-next"><small>Siguiente</small><b>{control.nextAction}</b></div><div className="lot360-actions"><Link className="button primary" to={control.nextRoute}>Continuar operación <ArrowRight size={15}/></Link><button className="button secondary" type="button" onClick={askAi}><Sparkles size={15}/>Preguntar IA</button></div></div>
   <div className="lot360-identity"><small>Origen</small><b>{r.extraction_zone||'—'}</b><small>Guía</small><b>{r.source_reference||'—'}</b><small>Recepción</small><b>{dt(r.received_at)}</b></div>
  </section>
  <section className="lot360-signals" aria-label="Indicadores esenciales"><article><span>Calidad</span><b>{control.signals.quality.label}</b><small>{control.signals.quality.detail??r.quality_status}</small></article><article><span>Balance</span><b>{pct(balance.yieldPct)}</b><small>{balance.yieldPct==null?'Pendiente de salida':'yield observado'}</small></article><article><span>{release.kind==='japan'?'Japón':'Evidencia'}</span><b>{release.label}</b><small>{release.kind==='japan'?'release gate':`${evidenceCount} respaldo${evidenceCount===1?'':'s'}`}</small></article></section>
  <section className="lot360-balance" aria-label="Balance de masa"><div className="lot360-section-head"><div><span className="overline teal">Balance de masa</span><h3>Entrada → salida</h3></div><Scale size={20}/></div><div className="lot360-balance-grid"><div><small>Entrada aceptada</small><b>{kg(balance.inputKg)}</b></div><div><small>Salida observada</small><b>{kg(balance.outputKg)}</b></div><div><small>Merma observada</small><b>{kg(balance.lossKg)}</b></div></div>{balance.inputKg==null?<p className="lot360-caveat">Sin kg aceptados confirmados: el sistema no calcula yield ni merma.</p>:null}</section>
  <details className="lot360-fold"><summary><span><GitBranch size={17}/><b>Ver trazabilidad</b></span><small>{graph?`${graph.summary?.nodes??graph.nodes?.length??0} nodos conectados`:`${events.length+1} eventos conocidos`}</small></summary><div className="lot360-fold-body">{graphGroups.length?graphGroups.map(group=><section className="lot360-flow-group" key={group.group}><h4>{group.group}</h4><div>{group.nodes.map(node=><article key={node.id}><span className={`lot360-node-icon ${node.status}`}><StatusIcon status={node.status}/></span><div><b>{node.label}</b><small>{node.detail||'Sin detalle adicional'}</small>{node.at?<small>{dt(node.at)}</small>:null}</div><span className={`status ${node.status==='pass'?'success':node.status==='attention'?'danger':'info'}`}>{statusLabel[node.status]}</span></article>)}</div></section>):<div className="lot360-empty"><GitBranch size={20}/><div><b>Lineage detallado aún no disponible para este lote</b><small>La recepción y su memoria operacional siguen siendo canónicas.</small></div></div>}{isUrchin?<Link className="button secondary" to={`/proceso-erizo/grafo?receptionId=${encodeURIComponent(receptionId)}`}>Abrir grafo completo</Link>:null}</div></details>
  <details className="lot360-fold"><summary><span><FileCheck2 size={17}/><b>Ver evidencia y memoria</b></span><small>{evidenceCount} evidencia{evidenceCount===1?'':'s'} · {events.length} evento{events.length===1?'':'s'}</small></summary><div className="lot360-fold-body"><section><span className="overline teal">Evidencia</span><div className="lot360-evidence">{evidenceCount?r.evidence.map((item,index)=><a key={item.id??`${item.url}-${index}`} href={item.url} target="_blank" rel="noreferrer"><FileCheck2 size={14}/><span><b>{item.label}</b>{item.note?<small>{item.note}</small>:null}</span></a>):<div className="lot360-empty"><FileCheck2 size={19}/><div><b>Sin evidencia adjunta</b><small>El dato ausente permanece explícitamente ausente.</small></div></div>}</div></section><section><span className="overline teal">Memoria reciente</span><div className="lot360-memory">{recentEvents.length?recentEvents.map(event=><article key={event.id}><span>{event.event_type==='quality'?<CheckCircle2 size={15}/>:event.event_type==='production'?<Scale size={15}/>:<CircleDashed size={15}/>}</span><div><b>{event.title}</b>{event.detail?<p>{event.detail}</p>:null}<small>{dt(event.occurred_at)} · {event.created_by}</small></div></article>):<div className="lot360-empty"><CircleDashed size={19}/><div><b>Sin eventos posteriores a la recepción</b><small>La recepción es el primer evento conocido.</small></div></div>}</div></section></div></details>
  {state.lot.commercial?.visible!==false?<details className="lot360-fold"><summary><span><ShieldCheck size={17}/><b>Ver resultado comercial</b></span><small>{state.lot.commercial?.soldKg?`${kg(state.lot.commercial.soldKg)} vendidos`:'Sin venta confirmada'}</small></summary><div className="lot360-fold-body"><div className="lot360-balance-grid"><div><small>Disponible</small><b>{kg(numberOrNull(state.lot.commercial?.availableKg))}</b></div><div><small>Ingresos</small><b>{clp(numberOrNull(state.lot.commercial?.revenueClp))}</b></div><div><small>Contribución observada</small><b>{clp(numberOrNull(state.lot.commercial?.marginClp))}</b></div></div><p className="lot360-caveat">Sólo se muestran valores observados y autorizados para el rol actual. Ausencia de costo o venta no se interpreta como cero.</p></div></details>:null}
 </div>
}
