import {AlertTriangle,ArrowRight,CheckCircle2,CircleDashed,FileCheck2,GitBranch,Scale,ShieldCheck,Sparkles} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link,useNavigate,useParams} from 'react-router-dom'
import {PageHeader} from '../components/PageHeader'
import './lot-360.css'

type LotEvent={id:string;event_type:'quality'|'production'|'note';title:string;detail:string|null;metrics:Record<string,unknown>;created_by:string;occurred_at:string}
type Reception={id:string;reception_number:string|number;plant_id:string;species:string;extraction_zone:string;source_reference:string|null;guide_kg:string|number|null;gross_kg:string|number|null;tare_kg:string|number|null;drained_kg:string|number|null;accepted_kg:string|number|null;temperature_c:string|number|null;quality_status:string;status:string;source:string;received_at:string;supplier:string;evidence:Array<{id?:string;kind?:string;label:string;url:string;note?:string|null;createdAt?:string}>}
type Dispatch={id:string;dispatch_number:string|number;destination:string;dispatched_kg:string|number;status:string;dispatched_at:string;customer:string|null}
type Sale={id:string;sold_kg:string|number;price_per_kg_clp:string|number;status:string;sold_at:string;customer:string}
type Commercial={visible?:boolean;physicalKg:number;dispatchedKg:number;availableKg:number;soldKg:number|null;revenueClp:number|null;allocatedCostClp:number|null;marginClp:number|null;marginPct:number|null}
type LotPayload={reception?:Reception;events?:LotEvent[];dispatches?:Dispatch[];sales?:Sale[];commercial?:Commercial;error?:string}
type ControlCard={process?:{id?:string;grade?:string|null;colorStatus?:string|null;xrayStatus?:string|null}|null;diagnosis?:{state?:string;blockers?:string[];nextAction?:string;unknowns?:string[]}|null;summary?:{japanReleasable?:boolean|null;deviations?:number;blockingHolds?:number}|null;error?:string}
type NodeStatus='pass'|'attention'|'pending'|'info'
type GraphNode={id:string;group:string;label:string;status:NodeStatus;detail:string;at:string|null;metrics?:Record<string,unknown>}
type GraphPayload={schemaVersion?:string;nodes?:GraphNode[];summary?:{nodes:number;attention:number;pending:number;japanReleasable:boolean|null};error?:string}

type State={lot:LotPayload;control:ControlCard|null;graph:GraphPayload|null}
const statusLabel:Record<NodeStatus,string>={pass:'OK',attention:'REVISAR',pending:'PENDIENTE',info:'INFO'}
const kg=(value:number|null)=>value==null?'—':`${value.toLocaleString('es-CL',{maximumFractionDigits:1})} kg`
const pct=(value:number|null)=>value==null?'—':`${value.toLocaleString('es-CL',{maximumFractionDigits:1})}%`
const clp=(value:number|null)=>value==null?'—':new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(value)
const dt=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'
const numberOrNull=(value:unknown)=>{if(value==null||value==='')return null;const number=Number(value);return Number.isFinite(number)?number:null}
async function readJson<T>(url:string){const response=await fetch(url,{cache:'no-store'});const payload=await response.json() as T&{error?:string};if(!response.ok)throw new Error(payload.error??'No fue posible cargar la ficha');return payload}
function routeForNext(text:string,isUrchin:boolean,receptionId:string){const value=text.toLowerCase(),query=`?receptionId=${encodeURIComponent(receptionId)}`;if(/fr[ií]o|temperat/.test(value))return `/frio${query}`;if(/etiquet/.test(value))return `/etiquetas${query}`;if(/pallet/.test(value))return `/pallets${query}`;if(/packing|empaque|caja/.test(value))return `/floor${query}`;if(/regulator|sernapesca|jap[oó]n|export/.test(value))return `/control-regulatorio${query}`;if(/despach/.test(value))return `/despachos-ventas${query}`;if(isUrchin&&/color|grade|xray|rayos|proceso|calidad/.test(value))return `/proceso-erizo/detalle${query}`;return `/recepciones${query}`}
function StatusIcon({status}:{status:NodeStatus}){return status==='pass'?<CheckCircle2 size={15}/>:status==='attention'?<AlertTriangle size={15}/>:<CircleDashed size={15}/>}

export function Lot360(){
 const {receptionId=''}=useParams(),navigate=useNavigate()
 const [state,setState]=useState<State|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{if(!receptionId)return;let active=true;const load=async()=>{setLoading(true);try{const lot=await readJson<LotPayload>(`/api/lot-360?receptionId=${encodeURIComponent(receptionId)}`),species=lot.reception?.species??'',isUrchin=/eriz|urchin/i.test(species);let control:ControlCard|null=null,graph:GraphPayload|null=null;if(isUrchin){const [controlResult,graphResult]=await Promise.allSettled([readJson<ControlCard>(`/api/sea-urchin-control-card?receptionId=${encodeURIComponent(receptionId)}`),readJson<GraphPayload>(`/api/sea-urchin-graph?receptionId=${encodeURIComponent(receptionId)}`)]);if(controlResult.status==='fulfilled')control=controlResult.value;if(graphResult.status==='fulfilled')graph=graphResult.value}if(active){setState({lot,control,graph});setError('')}}catch(cause){if(active){setState(null);setError(cause instanceof Error?cause.message:'No fue posible cargar la ficha')}}finally{if(active)setLoading(false)}};void load();const refresh=()=>void load();window.addEventListener('pescamar:data-updated',refresh);return()=>{active=false;window.removeEventListener('pescamar:data-updated',refresh)}},[receptionId])
 const r=state?.lot.reception,events=state?.lot.events??[],control=state?.control,graph=state?.graph,isUrchin=/eriz|urchin/i.test(r?.species??'')
 const latestProduction=events.find(event=>event.event_type==='production'&&numberOrNull(event.metrics?.outputKg)!=null),inputKg=numberOrNull(r?.accepted_kg),outputKg=latestProduction?numberOrNull(latestProduction.metrics?.outputKg):null
 const yieldPct=inputKg!=null&&inputKg>0&&outputKg!=null?outputKg/inputKg*100:null,lossKg=inputKg!=null&&outputKg!=null?Math.max(0,inputKg-outputKg):null
 const blockers=control?.diagnosis?.blockers??[],graphAttention=graph?.nodes?.find(node=>node.status==='attention')
 const primaryState=useMemo(()=>{if(isUrchin&&control?.summary?.japanReleasable===true)return'APTO JAPÓN';if(isUrchin&&control?.summary?.japanReleasable===false)return'NO LIBERADO JAPÓN';if(r?.quality_status==='Revisión'||r?.quality_status==='Alerta calibre')return'REQUIERE CALIDAD';if(r?.quality_status!=='Clasificado')return'PENDIENTE DE CALIDAD';if(outputKg==null)return'LISTO PARA PRODUCCIÓN';return'LOTE EN CURSO'},[isUrchin,control?.summary?.japanReleasable,r?.quality_status,outputKg])
 const blocker=blockers[0]??graphAttention?.label??(r?.quality_status==='Revisión'||r?.quality_status==='Alerta calibre'?`Calidad: ${r.quality_status}`:r?.quality_status!=='Clasificado'?'Falta clasificación de Calidad':outputKg==null?'Aún no hay salida de producción registrada':null)
 const nextAction=control?.diagnosis?.nextAction??(r?.quality_status==='Revisión'||r?.quality_status==='Alerta calibre'?'Resolver criterio de Calidad.':r?.quality_status!=='Clasificado'?'Completar clasificación de Calidad.':outputKg==null?'Registrar producción del lote.':'Continuar packing, inventario o despacho según el plan.')
 const primaryRoute=routeForNext(nextAction,isUrchin,receptionId)
 const evidenceCount=r?.evidence?.length??0,qualitySignal=control?.process?.grade?`Grade ${control.process.grade}`:r?.quality_status??'—',japanSignal=isUrchin?(control?.summary?.japanReleasable===true?'PASS':control?.summary?.japanReleasable===false?'HOLD':'—'):`${evidenceCount}`
 const recentEvents=events.slice(0,6),graphGroups=useMemo(()=>{const nodes=graph?.nodes??[],order=['Origen','Recepción','Proceso','EdgeVision','Packing','Logística','Frío','Regulatorio','Exportación','Despacho','Economía'];return order.map(group=>({group,nodes:nodes.filter(node=>node.group===group)})).filter(item=>item.nodes.length)},[graph?.nodes])
 function askAi(){if(isUrchin){window.dispatchEvent(new CustomEvent('pescamar:open-urchin-ai',{detail:{receptionId}}));return}navigate(`/pescamar-ia?receptionId=${encodeURIComponent(receptionId)}`)}
 if(loading)return <div className="system-banner">Construyendo Ficha 360 del lote…</div>
 if(error||!r)return <><PageHeader eyebrow="Lote 360" title="Ficha no disponible" description="No fue posible construir la vista canónica de este lote." actions={<Link className="button secondary" to="/recepciones">Volver</Link>}/><div className="system-banner error" role="alert">{error||'Lote no disponible'}</div></>
 return <div className="lot360-page">
  <PageHeader eyebrow="Lote 360 · Digital Twin" title={`REC-${r.reception_number}`} description={`${r.supplier} · ${r.species} · ${r.plant_id}`} actions={<Link className="button secondary" to="/recepciones">Volver a recepción</Link>}/>
  <section className={`lot360-hero ${blocker?'has-attention':'is-clear'}`} aria-label="Estado actual del lote">
   <div className="lot360-hero-copy"><span className="overline">Estado actual</span><h2>{primaryState}</h2><p>{blocker?blocker:'Sin bloqueos visibles en la evidencia disponible.'}</p><div className="lot360-next"><small>Siguiente</small><b>{nextAction}</b></div><div className="lot360-actions"><Link className="button primary" to={primaryRoute}>Continuar operación <ArrowRight size={15}/></Link><button className="button secondary" type="button" onClick={askAi}><Sparkles size={15}/>Preguntar IA</button></div></div>
   <div className="lot360-identity"><small>Origen</small><b>{r.extraction_zone||'—'}</b><small>Guía</small><b>{r.source_reference||'—'}</b><small>Recepción</small><b>{dt(r.received_at)}</b></div>
  </section>
  <section className="lot360-signals" aria-label="Indicadores esenciales"><article><span>Calidad</span><b>{qualitySignal}</b><small>{control?.process?.colorStatus?`Color ${control.process.colorStatus}`:r.quality_status}</small></article><article><span>Balance</span><b>{pct(yieldPct)}</b><small>{yieldPct==null?'Pendiente de salida':'yield observado'}</small></article><article><span>{isUrchin?'Japón':'Evidencia'}</span><b>{japanSignal}</b><small>{isUrchin?'release gate':`${evidenceCount} respaldo${evidenceCount===1?'':'s'}`}</small></article></section>
  <section className="lot360-balance" aria-label="Balance de masa"><div className="lot360-section-head"><div><span className="overline teal">Balance de masa</span><h3>Entrada → salida</h3></div><Scale size={20}/></div><div className="lot360-balance-grid"><div><small>Entrada aceptada</small><b>{kg(inputKg)}</b></div><div><small>Salida observada</small><b>{kg(outputKg)}</b></div><div><small>Merma observada</small><b>{kg(lossKg)}</b></div></div>{inputKg==null?<p className="lot360-caveat">Sin kg aceptados confirmados: el sistema no calcula yield ni merma.</p>:null}</section>
  <details className="lot360-fold"><summary><span><GitBranch size={17}/><b>Ver trazabilidad</b></span><small>{graph?`${graph.summary?.nodes??graph.nodes?.length??0} nodos conectados`:`${events.length+1} eventos conocidos`}</small></summary><div className="lot360-fold-body">{graphGroups.length?graphGroups.map(group=><section className="lot360-flow-group" key={group.group}><h4>{group.group}</h4><div>{group.nodes.map(node=><article key={node.id}><span className={`lot360-node-icon ${node.status}`}><StatusIcon status={node.status}/></span><div><b>{node.label}</b><small>{node.detail||'Sin detalle adicional'}</small>{node.at?<small>{dt(node.at)}</small>:null}</div><span className={`status ${node.status==='pass'?'success':node.status==='attention'?'danger':'info'}`}>{statusLabel[node.status]}</span></article>)}</div></section>):<div className="lot360-empty"><GitBranch size={20}/><div><b>Lineage detallado aún no disponible para este lote</b><small>La recepción y su memoria operacional siguen siendo canónicas.</small></div></div>}{isUrchin?<Link className="button secondary" to={`/proceso-erizo/grafo?receptionId=${encodeURIComponent(receptionId)}`}>Abrir grafo completo</Link>:<Link className="button secondary" to={`/lineage?receptionId=${encodeURIComponent(receptionId)}`}>Abrir trazabilidad</Link>}</div></details>
  <details className="lot360-fold"><summary><span><FileCheck2 size={17}/><b>Ver evidencia y memoria</b></span><small>{evidenceCount} evidencia{evidenceCount===1?'':'s'} · {events.length} evento{events.length===1?'':'s'}</small></summary><div className="lot360-fold-body"><section><span className="overline teal">Evidencia</span><div className="lot360-evidence">{evidenceCount?r.evidence.map((item,index)=><a key={item.id??`${item.url}-${index}`} href={item.url} target="_blank" rel="noreferrer"><FileCheck2 size={14}/><span><b>{item.label}</b>{item.note?<small>{item.note}</small>:null}</span></a>):<div className="lot360-empty"><FileCheck2 size={19}/><div><b>Sin evidencia adjunta</b><small>El dato ausente permanece explícitamente ausente.</small></div></div>}</div></section><section><span className="overline teal">Memoria reciente</span><div className="lot360-memory">{recentEvents.length?recentEvents.map(event=><article key={event.id}><span>{event.event_type==='quality'?<CheckCircle2 size={15}/>:event.event_type==='production'?<Scale size={15}/>:<CircleDashed size={15}/>}</span><div><b>{event.title}</b>{event.detail?<p>{event.detail}</p>:null}<small>{dt(event.occurred_at)} · {event.created_by}</small></div></article>):<div className="lot360-empty"><CircleDashed size={19}/><div><b>Sin eventos posteriores a la recepción</b><small>La recepción es el primer evento conocido.</small></div></div>}</div></section></div></details>
  {state?.lot.commercial?.visible!==false?<details className="lot360-fold"><summary><span><ShieldCheck size={17}/><b>Ver resultado comercial</b></span><small>{state?.lot.commercial?.soldKg?`${kg(state.lot.commercial.soldKg)} vendidos`:'Sin venta confirmada'}</small></summary><div className="lot360-fold-body"><div className="lot360-balance-grid"><div><small>Disponible</small><b>{kg(numberOrNull(state?.lot.commercial?.availableKg))}</b></div><div><small>Ingresos</small><b>{clp(numberOrNull(state?.lot.commercial?.revenueClp))}</b></div><div><small>Contribución observada</small><b>{clp(numberOrNull(state?.lot.commercial?.marginClp))}</b></div></div><p className="lot360-caveat">Sólo se muestran valores observados y autorizados para el rol actual. Ausencia de costo o venta no se interpreta como cero.</p></div></details>:null}
 </div>
}
