import {AlertTriangle,ArrowRight,CheckCircle2,CircleDashed,FileCheck2,GitBranch,Scale,ShieldCheck,Sparkles} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link,useNavigate,useParams} from 'react-router-dom'
import {LotLifecycleControl} from '../components/LotLifecycleControl'
import {PageHeader} from '../components/PageHeader'
import {useLocale} from '../i18n'
import './lot-360.css'

type LotEvent={id:string;event_type:'quality'|'production'|'note';title:string;detail:string|null;metrics:Record<string,unknown>;created_by:string;occurred_at:string}
type Reception={id:string;reception_number:string|number;plant_id:string;species:string;extraction_zone:string;source_reference:string|null;guide_kg:string|number|null;gross_kg:string|number|null;tare_kg:string|number|null;drained_kg:string|number|null;accepted_kg:string|number|null;temperature_c:string|number|null;quality_status:string;status:string;source:string;received_at:string;supplier:string;evidence:Array<{id?:string;kind?:string;label:string;url:string;note?:string|null;createdAt?:string}>}
type Commercial={visible?:boolean;physicalKg:number;dispatchedKg:number;availableKg:number;soldKg:number|null;revenueClp:number|null;allocatedCostClp:number|null;marginClp:number|null;marginPct:number|null}
type LotPayload={reception?:Reception;events?:LotEvent[];commercial?:Commercial;error?:string}
type Tone='ready'|'attention'|'pending'|'info'
type ControlCard={schemaVersion?:string;state:{code:string;label:string;tone:Tone};blocker:string|null;blockers:string[];nextAction:string;nextRoute:string;signals:{quality:{label:string;detail:string|null;tone:Tone};balance:{inputKg:number|null;outputKg:number|null;yieldPct:number|null;lossKg:number|null;tone:Tone};release:{label:string;tone:Tone;kind:'japan'|'evidence'}};evidence:{count:number};diagnosis:{state:'attention'|'clear';blockers:string[];nextAction:string;unknowns:string[]};error?:string}
type NodeStatus='pass'|'attention'|'pending'|'info'
type GraphNode={id:string;group:string;label:string;status:NodeStatus;detail:string;at:string|null;metrics?:Record<string,unknown>}
type GraphPayload={schemaVersion?:string;nodes?:GraphNode[];summary?:{nodes:number;attention:number;pending:number;japanReleasable:boolean|null};error?:string}
type State={lot:LotPayload;control:ControlCard;graph:GraphPayload|null}

const statusLabel=(status:NodeStatus)=>status==='pass'?'lot360.statusOk':status==='attention'?'lot360.statusAttention':status==='pending'?'lot360.statusPending':'lot360.statusInfo'
const kg=(value:number|null)=>value==null?'—':`${value.toLocaleString('es-CL',{maximumFractionDigits:1})} kg`
const pct=(value:number|null)=>value==null?'—':`${value.toLocaleString('es-CL',{maximumFractionDigits:1})}%`
const clp=(value:number|null)=>value==null?'—':new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(value)
const dt=(value:string|null|undefined)=>value?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'
const numberOrNull=(value:unknown)=>{if(value==null||value==='')return null;const number=Number(value);return Number.isFinite(number)?number:null}
async function readJson<T>(url:string,fallback:string){const response=await fetch(url,{cache:'no-store'});const payload=await response.json() as T&{error?:string};if(!response.ok)throw new Error(payload.error??fallback);return payload}
function StatusIcon({status}:{status:NodeStatus}){return status==='pass'?<CheckCircle2 size={15}/>:status==='attention'?<AlertTriangle size={15}/>:<CircleDashed size={15}/>}

export function Lot360(){
 const {t}=useLocale()
 const {receptionId=''}=useParams(),navigate=useNavigate()
 const [state,setState]=useState<State|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{if(!receptionId)return;let active=true;const load=async()=>{setLoading(true);try{const [lot,control]=await Promise.all([readJson<LotPayload>(`/api/lot-360?receptionId=${encodeURIComponent(receptionId)}`,t('lot360.loadError')),readJson<ControlCard>(`/api/lot-control-card?receptionId=${encodeURIComponent(receptionId)}`,t('lot360.loadError'))]),isUrchin=/eriz|urchin/i.test(lot.reception?.species??''),graphUrl=isUrchin?'/api/sea-urchin-graph':'/api/lot-graph';let graph:GraphPayload|null=null;const graphResult=await Promise.allSettled([readJson<GraphPayload>(`${graphUrl}?receptionId=${encodeURIComponent(receptionId)}`,t('lot360.loadError'))]);if(graphResult[0]?.status==='fulfilled')graph=graphResult[0].value;if(active){setState({lot,control,graph});setError('')}}catch(cause){if(active){setState(null);setError(cause instanceof Error?cause.message:t('lot360.loadError'))}}finally{if(active)setLoading(false)}};void load();const refresh=()=>void load();window.addEventListener('pescamar:data-updated',refresh);return()=>{active=false;window.removeEventListener('pescamar:data-updated',refresh)}},[receptionId,t])
 const r=state?.lot.reception,events=state?.lot.events??[],control=state?.control,graph=state?.graph,isUrchin=/eriz|urchin/i.test(r?.species??'')
 const evidenceCount=r?.evidence?.length??control?.evidence.count??0,recentEvents=events.slice(0,6)
 const graphGroups=useMemo(()=>{const nodes=graph?.nodes??[],order=['Origen','Recepción','Proceso','EdgeVision','Packing','Logística','Frío','Regulatorio','Exportación','Despacho','Economía'];return order.map(group=>({group,nodes:nodes.filter(node=>node.group===group)})).filter(item=>item.nodes.length)},[graph?.nodes])
 function askAi(){if(isUrchin){window.dispatchEvent(new CustomEvent('pescamar:open-urchin-ai',{detail:{receptionId}}));return}navigate(`/pescamar-ia?receptionId=${encodeURIComponent(receptionId)}`)}
 if(loading)return <div className="system-banner">{t('lot360.loading')}</div>
 if(error||!r||!control)return <><PageHeader eyebrow={t('lot360.eyebrow')} title={t('lot360.unavailableTitle')} description={t('lot360.unavailableDescription')} actions={<Link className="button secondary" to="/recepciones">{t('lot360.back')}</Link>}/><div className="system-banner error" role="alert">{error||t('lot360.unavailableBanner')}</div></>
 const balance=control.signals.balance,release=control.signals.release,isClosed=control.state.code==='closed'
 return <div className="lot360-page">
  <PageHeader eyebrow={t('lot360.eyebrow')} title={`REC-${r.reception_number}`} description={`${r.supplier} · ${r.species} · ${r.plant_id}`} actions={<Link className="button secondary" to="/recepciones">{t('lot360.backToReception')}</Link>}/>
  <section className={`lot360-hero ${control.blocker?'has-attention':'is-clear'}`} aria-label={t('lot360.heroAria')}>
   <div className="lot360-hero-copy"><span className="overline">{t('lot360.currentState')}</span><h2>{control.state.label}</h2><p>{control.blocker??(isClosed?t('lot360.closedSummary'):t('lot360.clearSummary'))}</p><div className="lot360-next"><small>{t('home.next')}</small><b>{control.nextAction}</b></div><div className="lot360-actions">{!isClosed?<Link className="button primary" to={control.nextRoute}>{t('lot360.continueOperation')} <ArrowRight size={15}/></Link>:null}<button className="button secondary" type="button" onClick={askAi}><Sparkles size={15}/>{t('home.askAssistant')}</button></div></div>
   <div className="lot360-identity"><small>{t('lot360.fieldOrigin')}</small><b>{r.extraction_zone||'—'}</b><small>{t('lot360.fieldGuide')}</small><b>{r.source_reference||'—'}</b><small>{t('lot360.fieldReception')}</small><b>{dt(r.received_at)}</b></div>
  </section>
  <section className="lot360-signals" aria-label={t('lot360.signalsAria')}><article><span>{t('nav.quality')}</span><b>{control.signals.quality.label}</b><small>{control.signals.quality.detail??r.quality_status}</small></article><article><span>{t('lot360.balance')}</span><b>{pct(balance.yieldPct)}</b><small>{balance.yieldPct==null?t('lot360.pendingOutput'):t('lot360.observedYield')}</small></article><article><span>{release.kind==='japan'?t('lot360.japan'):t('lot360.evidence')}</span><b>{release.label}</b><small>{release.kind==='japan'?t('lot360.outputReview'):t(evidenceCount===1?'lot360.backingOne':'lot360.backingOther',{count:evidenceCount})}</small></article></section>
  <section className="lot360-balance" aria-label={t('lot360.massBalanceAria')}><div className="lot360-section-head"><div><span className="overline teal">{t('lot360.massBalance')}</span><h3>{t('lot360.inputToOutput')}</h3></div><Scale size={20}/></div><div className="lot360-balance-grid"><div><small>{t('lot360.acceptedInput')}</small><b>{kg(balance.inputKg)}</b></div><div><small>{t('lot360.observedOutput')}</small><b>{kg(balance.outputKg)}</b></div><div><small>{t('lot360.observedLoss')}</small><b>{kg(balance.lossKg)}</b></div></div>{balance.inputKg==null?<p className="lot360-caveat">{t('lot360.noAcceptedKg')}</p>:null}</section>
  <details className="lot360-fold"><summary><span><GitBranch size={17}/><b>{t('lot360.viewTraceability')}</b></span><small>{graph?t('lot360.connectedPoints',{count:graph.summary?.nodes??graph.nodes?.length??0}):t('lot360.knownRecords',{count:events.length+1})}</small></summary><div className="lot360-fold-body">{graphGroups.length?graphGroups.map(group=><section className="lot360-flow-group" key={group.group}><h4>{group.group}</h4><div>{group.nodes.map(node=><article key={node.id}><span className={`lot360-node-icon ${node.status}`}><StatusIcon status={node.status}/></span><div><b>{node.label}</b><small>{node.detail||t('lot360.noExtraDetail')}</small>{node.at?<small>{dt(node.at)}</small>:null}</div><span className={`status ${node.status==='pass'?'success':node.status==='attention'?'danger':'info'}`}>{t(statusLabel(node.status))}</span></article>)}</div></section>):<div className="lot360-empty"><GitBranch size={20}/><div><b>{t('lot360.noTraceability')}</b><small>{t('lot360.noTraceabilityDetail')}</small></div></div>}{isUrchin?<Link className="button secondary" to={`/proceso-erizo/grafo?receptionId=${encodeURIComponent(receptionId)}`}>{t('lot360.viewFullProcess')}</Link>:null}</div></details>
  <details className="lot360-fold"><summary><span><FileCheck2 size={17}/><b>{t('lot360.viewEvidence')}</b></span><small>{`${t(evidenceCount===1?'lot360.evidenceCountOne':'lot360.evidenceCountOther',{count:evidenceCount})} · ${t(events.length===1?'lot360.recordsCountOne':'lot360.recordsCountOther',{count:events.length})}`}</small></summary><div className="lot360-fold-body"><section><span className="overline teal">{t('lot360.evidence')}</span><div className="lot360-evidence">{evidenceCount?r.evidence.map((item,index)=><a key={item.id??`${item.url}-${index}`} href={item.url} target="_blank" rel="noreferrer"><FileCheck2 size={14}/><span><b>{item.label}</b>{item.note?<small>{item.note}</small>:null}</span></a>):<div className="lot360-empty"><FileCheck2 size={19}/><div><b>{t('lot360.noEvidence')}</b><small>{t('lot360.noEvidenceDetail')}</small></div></div>}</div></section><section><span className="overline teal">{t('lot360.recentActivity')}</span><div className="lot360-memory">{recentEvents.length?recentEvents.map(event=><article key={event.id}><span>{event.event_type==='quality'?<CheckCircle2 size={15}/>:event.event_type==='production'?<Scale size={15}/>:<CircleDashed size={15}/>}</span><div><b>{event.title}</b>{event.detail?<p>{event.detail}</p>:null}<small>{dt(event.occurred_at)} · {event.created_by}</small></div></article>):<div className="lot360-empty"><CircleDashed size={19}/><div><b>{t('lot360.noRecords')}</b><small>{t('lot360.noRecordsDetail')}</small></div></div>}</div></section></div></details>
  <LotLifecycleControl receptionId={receptionId}/>
  {state.lot.commercial?.visible!==false?<details className="lot360-fold"><summary><span><ShieldCheck size={17}/><b>{t('lot360.viewCommercial')}</b></span><small>{state.lot.commercial?.soldKg?t('lot360.soldKg',{value:kg(state.lot.commercial.soldKg)}):t('lot360.noSale')}</small></summary><div className="lot360-fold-body"><div className="lot360-balance-grid"><div><small>{t('lot360.available')}</small><b>{kg(numberOrNull(state.lot.commercial?.availableKg))}</b></div><div><small>{t('lot360.revenue')}</small><b>{clp(numberOrNull(state.lot.commercial?.revenueClp))}</b></div><div><small>{t('lot360.observedMargin')}</small><b>{clp(numberOrNull(state.lot.commercial?.marginClp))}</b></div></div><p className="lot360-caveat">{t('lot360.commercialCaveat')}</p></div></details>:null}
 </div>
}
