import { Boxes, BrainCircuit, CheckCircle2, ClipboardCheck, Factory, FileCheck2, PackageCheck, Scale, Settings2, Snowflake, Truck, Users } from 'lucide-react'
import { PageHeader } from '../components/PageHeader'

const groups=[
  {name:'Operación',modules:[['Abastecimiento y recepción','Origen, pesaje, tara, escurrido y liquidación justa',Scale,'Operativo'],['Planificación y producción','Órdenes, turnos, recetas, rutas y captura en piso',Factory,'Operativo'],['Inventario y frío','Lotes, ubicaciones, FEFO, cámaras y cadena de frío',Snowflake,'Diseñado'],['Despacho y exportación','Packing list, contenedores, certificados y documentos',Truck,'Diseñado']]},
  {name:'Calidad y cumplimiento',modules:[['Calidad e inocuidad','HACCP, PCC, muestreos, laboratorio y no conformidades',ClipboardCheck,'Operativo'],['Trazabilidad total','Genealogía del lote desde origen hasta cliente',Boxes,'Operativo'],['UniGrade IA','Color, calibre, integridad, evidencia y aprendizaje humano',BrainCircuit,'Piloto'],['Certificación','Expediente sanitario y reglas por mercado de destino',FileCheck2,'Diseñado']]},
  {name:'Gestión',modules:[['Proveedores artesanales','Contratos, desempeño, liquidaciones y transparencia',Users,'Diseñado'],['Costos y rendimiento','Balance de masa, mermas, costo real y margen por lote',PackageCheck,'Operativo'],['Datos maestros','Recursos, productos, formatos, clientes y especificaciones',Settings2,'Operativo'],['Gobierno y alertas','Roles, aprobaciones, excepciones y bitácora auditable',CheckCircle2,'Diseñado']]}
] as const

export function Modules(){return <><PageHeader eyebrow="Arquitectura tipo ERPminia" title="Sistema modular Pescamar" description="Un solo dato operacional alimenta producción, calidad, costos, trazabilidad y exportación."/><div className="module-groups">{groups.map(group=><section key={group.name}><header className="section-heading"><h2>{group.name}</h2><span>{group.modules.length} módulos</span></header><div className="module-grid">{group.modules.map(([name,description,Icon,status])=><article className="panel module-card" key={name}><div className="module-icon"><Icon size={20}/></div><div><h3>{name}</h3><p>{description}</p></div><span className={`module-state ${status==='Operativo'?'ready':''}`}>{status}</span></article>)}</div></section>)}</div></>}
