import { ArrowRight, BrainCircuit, ClipboardCheck, Factory, PackageCheck, Scale, Truck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { canAccessPath } from '../access'
import { useAuth } from '../auth'
import { PageHeader } from '../components/PageHeader'
import { osStages } from '../os'
const stageIcons={intake:Scale,production:Factory,quality:ClipboardCheck,inventory:PackageCheck,commercial:Truck,control:BrainCircuit} as const
const operators=['Jefe de planta','Encargado de calidad','Recepción y abastecimiento','Bodega y despacho','Administración y gerencia']
export function Modules(){const {operator}=useAuth();const visible=operator?osStages.map(stage=>({...stage,modules:stage.modules.filter(module=>canAccessPath(operator.role,module.path))})).filter(stage=>stage.modules.length):[];return <><PageHeader eyebrow="Pescamar OS" title="Una operación. Seis sistemas conectados." description="Cada lote avanza por una sola cadena de evidencia. Los módulos comparten identidad, planta, estado, responsables y auditoría; las excepciones llegan a una bandeja común de decisiones." actions={operator?.role==='admin'?<Link className="button secondary" to="/estaciones">Estaciones y dispositivos</Link>:undefined}/><section className="os-stage-grid" aria-label="Mapa operativo de Pescamar OS">{visible.map(stage=>{const Icon=stageIcons[stage.id as keyof typeof stageIcons];const entry=stage.modules.some(module=>module.path===stage.entry)?stage.entry:stage.modules[0].path;return <article className="panel os-stage" key={stage.id}><header><span className="os-module-step"><Icon size={19}/></span><div><small>Sistema {String(stage.order).padStart(2,'0')}</small><h2>{stage.label}</h2></div></header><p>{stage.description}</p><div className="os-stage-modules">{stage.modules.map(module=><Link to={module.path} key={module.path}><span>{module.label}</span><small>{module.description}</small><ArrowRight size={13}/></Link>)}</div><footer><span>{stage.owner}</span><Link to={entry}>Abrir sistema <ArrowRight size={14}/></Link></footer></article>})}</section><section className="panel five-team"><div><span className="overline teal">Modelo operativo</span><h2>El sistema coordina; las personas deciden</h2><p>La operación normal fluye entre módulos sin recaptura. Diferencias de peso, bloqueos regulatorios, alertas de calidad y decisiones comerciales quedan visibles, asignadas y auditadas.</p><div className="row-actions"><Link className="button primary" to="/">Abrir control de hoy</Link><Link className="button secondary" to="/aprobaciones">Ver decisiones</Link><Link className="button secondary" to="/auditoria">Ver auditoría</Link></div></div><ol>{operators.map((operatorName,index)=><li key={operatorName}><span>{index+1}</span>{operatorName}</li>)}</ol></section></>}
