import {Building2,Handshake,Plus,Save,ShieldCheck,UsersRound,X} from 'lucide-react'
import {useEffect,useMemo,useState,type FormEvent} from 'react'
import {CanonicalSupplierIdentity,type CanonicalSupplierDraft} from '../components/CanonicalSupplierIdentity'
import {PageHeader} from '../components/PageHeader'
import {Party360Drawer,type Party360Metric,type Party360Party} from '../components/Party360Drawer'
import {SupplierIntelligence} from '../components/SupplierIntelligence'

type Party=Party360Party
type Metric=Party360Metric
type Payload={parties?:Party[];suppliers?:Metric[];customers?:Metric[];purchases?:unknown[];invoices?:unknown[];permissions?:{canWrite:boolean};error?:string}
const clp=(v:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(v||0)
const kg=(v:number)=>`${Number(v||0).toLocaleString('es-CL',{maximumFractionDigits:1})} kg`
const blank=(kind:'supplier'|'customer',legalName=''):Party=>({id:'',kind,legal_name:legalName,tax_id:null,phone:null,contact_name:null,email:null,address:null,city:null,country:null,payment_terms:null,notes:null,tags:[]})

export function Partners(){
 const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[kind,setKind]=useState<'supplier'|'customer'>('supplier'),[viewing,setViewing]=useState<Party|null>(null),[editing,setEditing]=useState<Party|null>(null),[canonicalDraft,setCanonicalDraft]=useState<CanonicalSupplierDraft|null>(null)
 async function load(){setLoading(true);try{const r=await fetch('/api/partners',{cache:'no-store'}),p=await r.json() as Payload;if(!r.ok)throw new Error(p.error??'No fue posible cargar proveedores y clientes');setData(p);setError('')}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar proveedores y clientes')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const parties=useMemo(()=>data?.parties?.filter(p=>p.kind===kind)??[],[data,kind])
 const metricFor=(party:Party)=>(party.kind==='supplier'?data?.suppliers:data?.customers)?.find(m=>(m.supplier_id??m.customer_id)===party.id)
 const closeEditor=()=>{setEditing(null);setCanonicalDraft(null)}
 const prepareCanonicalSupplier=(draft:CanonicalSupplierDraft)=>{setKind('supplier');setCanonicalDraft(draft);setEditing(blank('supplier',draft.supplierName))}
 return <>
  <PageHeader eyebrow="Red comercial" title="Proveedores y clientes" description="Abre una ficha para ver identidad, actividad y relación comercial en un solo lugar." actions={data?.permissions?.canWrite?<button className="button primary" onClick={()=>{setCanonicalDraft(null);setEditing(blank(kind))}}><Plus size={15}/>Nueva ficha</button>:undefined}/>
  {error?<div className="system-banner error">{error}</div>:null}{loading?<div className="system-banner">Cargando fichas…</div>:null}
  <div className="event-kind-tabs"><button className={kind==='supplier'?'active':''} onClick={()=>{setKind('supplier');setViewing(null)}}>Proveedores</button><button className={kind==='customer'?'active':''} onClick={()=>{setKind('customer');setViewing(null)}}>Clientes</button></div>
  <section className="signal-grid"><article className="signal-card"><span><Handshake size={16}/>{kind==='supplier'?'Proveedores':'Clientes'}</span><b>{parties.length}</b><small>Fichas disponibles</small></article><article className="signal-card"><span><Building2 size={16}/>Documentos</span><b>{kind==='supplier'?data?.purchases?.length??0:data?.invoices?.length??0}</b><small>{kind==='supplier'?'Órdenes de compra':'Facturas de exportación'}</small></article><article className="signal-card"><span><UsersRound size={16}/>Con actividad</span><b>{(kind==='supplier'?data?.suppliers:data?.customers)?.filter(m=>Number(m.revenue_clp??0)>0||Number(m.received_kg??0)>0).length??0}</b><small>Con información asociada</small></article></section>
  {kind==='supplier'?<><SupplierIntelligence/><CanonicalSupplierIdentity canPrepare={Boolean(data?.permissions?.canWrite)} onPrepareSupplier={prepareCanonicalSupplier}/></>:null}
  <section className="panel"><div className="section-heading"><div><span className="overline">Directorio</span><h2>{kind==='supplier'?'Proveedores':'Clientes'}</h2></div><span>{parties.length}</span></div><div className="compact-ledger">{parties.map(p=>{const metric=metricFor(p);const summary=kind==='supplier'?(metric?.received_kg!=null?kg(Number(metric.received_kg)):'Ver ficha'):(metric?.revenue_clp!=null?clp(Number(metric.revenue_clp)):'Ver ficha');return <button key={p.id} onClick={()=>setViewing(p)}><span><Building2 size={14}/></span><div><b>{p.legal_name}</b><small>{[p.city,p.country,p.contact_name].filter(Boolean).join(' · ')||'Ficha'}</small></div><strong>{summary}</strong></button>})}</div></section>
  <Party360Drawer party={viewing} metric={viewing?metricFor(viewing):undefined} canEdit={Boolean(data?.permissions?.canWrite)} onClose={()=>setViewing(null)} onEdit={()=>{if(viewing){setCanonicalDraft(null);setEditing(viewing);setViewing(null)}}}/>
  {editing?<PartyEditor party={editing} canonicalDraft={canonicalDraft} onClose={closeEditor} onSaved={async()=>{closeEditor();await load()}}/>:null}
 </>
}

function PartyEditor({party,canonicalDraft,onClose,onSaved}:{party:Party;canonicalDraft:CanonicalSupplierDraft|null;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [form,setForm]=useState({...party}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const set=(field:keyof Party,value:Party[keyof Party])=>setForm(current=>({...current,[field]:value}))
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/partners',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({partyId:form.id||null,kind:form.kind,legalName:form.legal_name,taxId:form.tax_id,phone:form.phone,contactName:form.contact_name,email:form.email,address:form.address,city:form.city,country:form.country,paymentTerms:form.payment_terms,notes:form.notes,tags:form.tags})}),p=await r.json() as {error?:string};if(!r.ok)throw new Error(p.error??'No fue posible guardar');await onSaved()}catch(e){setError(e instanceof Error?e.message:'No fue posible guardar')}finally{setBusy(false)}}
 return <div className="modal-backdrop"><form className="modal-panel commercial-form" onSubmit={submit}><header><div><span className="overline">Ficha comercial</span><h2>{form.id?'Editar':'Crear'} {form.kind==='supplier'?'proveedor':'cliente'}</h2></div><button type="button" className="icon-btn" onClick={onClose}><X size={18}/></button></header>{canonicalDraft?<div className="governance-note"><ShieldCheck size={19}/><div><b>Alta preparada desde historial</b><p>Se precargó sólo el nombre normalizado <strong>{canonicalDraft.supplierName}</strong>, observado en {canonicalDraft.sourceRows} filas y {kg(canonicalDraft.receivedKg)} históricos. Verifica razón social, RUT y datos de contacto antes de guardar. Guardar crea la ficha maestra y no modifica el historial.</p></div></div>:null}<div className="commercial-form-grid"><label>Razón social<input value={form.legal_name} onChange={e=>set('legal_name',e.target.value)} required/></label><label>RUT / Tax ID<input value={form.tax_id??''} onChange={e=>set('tax_id',e.target.value)} required={!form.id}/><small>{form.id?'Identificador tributario de la entidad.':'Obligatorio para crear la identidad maestra; puede ser RUT u otro Tax ID verificable.'}</small></label><label>Contacto<input value={form.contact_name??''} onChange={e=>set('contact_name',e.target.value)}/></label><label>Email<input type="email" value={form.email??''} onChange={e=>set('email',e.target.value)}/></label><label>Teléfono<input value={form.phone??''} onChange={e=>set('phone',e.target.value)}/></label><label>País<input value={form.country??''} onChange={e=>set('country',e.target.value)}/></label><label>Ciudad<input value={form.city??''} onChange={e=>set('city',e.target.value)}/></label><label>Dirección<input value={form.address??''} onChange={e=>set('address',e.target.value)}/></label><label>Condiciones pago<input value={form.payment_terms??''} onChange={e=>set('payment_terms',e.target.value)}/></label><label>Notas<input value={form.notes??''} onChange={e=>set('notes',e.target.value)}/></label></div>{error?<p className="form-error">{error}</p>:null}<footer><button type="button" className="button" onClick={onClose}>Cancelar</button><button className="button primary" disabled={busy}><Save size={15}/>{busy?'Guardando…':'Guardar ficha'}</button></footer></form></div>
}
