import {Building2,Handshake,Plus,Save,UsersRound,X} from 'lucide-react'
import {useEffect,useMemo,useState,type FormEvent} from 'react'
import {CanonicalSupplierIdentity} from '../components/CanonicalSupplierIdentity'
import {PageHeader} from '../components/PageHeader'
import {SupplierIntelligence} from '../components/SupplierIntelligence'

type Party={id:string;kind:'supplier'|'customer';legal_name:string;tax_id:string|null;phone:string|null;contact_name:string|null;email:string|null;address:string|null;city:string|null;country:string|null;payment_terms:string|null;notes:string|null;tags:string[]}
type Metric={supplier_id?:string;customer_id?:string;supplier?:string;customer?:string;receptions?:number;received_kg?:number;sold_kg?:number;revenue_clp?:number;contribution_clp?:number;contribution_pct?:number}
type Payload={parties?:Party[];suppliers?:Metric[];customers?:Metric[];purchases?:unknown[];invoices?:unknown[];permissions?:{canWrite:boolean};error?:string}
const clp=(v:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(v||0)
const kg=(v:number)=>`${Number(v||0).toLocaleString('es-CL',{maximumFractionDigits:1})} kg`

export function Partners(){
 const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[kind,setKind]=useState<'supplier'|'customer'>('supplier'),[editing,setEditing]=useState<Party|null>(null)
 async function load(){setLoading(true);try{const r=await fetch('/api/partners',{cache:'no-store'}),p=await r.json() as Payload;if(!r.ok)throw new Error(p.error??'No fue posible cargar proveedores y clientes');setData(p);setError('')}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar proveedores y clientes')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const parties=useMemo(()=>data?.parties?.filter(p=>p.kind===kind)??[],[data,kind])
 return <>
  <PageHeader eyebrow="Red comercial" title="Proveedores y clientes" description="Una ficha por contraparte, conectada a compras, recepciones, ventas, calidad, rendimiento y rentabilidad." actions={data?.permissions?.canWrite?<button className="button primary" onClick={()=>setEditing({id:'',kind,legal_name:'',tax_id:null,phone:null,contact_name:null,email:null,address:null,city:null,country:null,payment_terms:null,notes:null,tags:[]})}><Plus size={15}/>Nueva ficha</button>:undefined}/>
  {error?<div className="system-banner error">{error}</div>:null}{loading?<div className="system-banner">Sincronizando red comercial…</div>:null}
  <div className="event-kind-tabs"><button className={kind==='supplier'?'active':''} onClick={()=>setKind('supplier')}>Proveedores</button><button className={kind==='customer'?'active':''} onClick={()=>setKind('customer')}>Clientes</button></div>
  <section className="signal-grid"><article className="signal-card"><span><Handshake size={16}/>{kind==='supplier'?'Proveedores':'Clientes'}</span><b>{parties.length}</b><small>Entidades activas</small></article><article className="signal-card"><span><Building2 size={16}/>Documentos</span><b>{kind==='supplier'?data?.purchases?.length??0:data?.invoices?.length??0}</b><small>{kind==='supplier'?'Órdenes de compra':'Facturas de exportación'}</small></article><article className="signal-card"><span><UsersRound size={16}/>Con actividad</span><b>{(kind==='supplier'?data?.suppliers:data?.customers)?.filter(m=>Number(m.revenue_clp??0)>0||Number(m.received_kg??0)>0).length??0}</b><small>Con trazabilidad económica</small></article></section>
  {kind==='supplier'?<><SupplierIntelligence/><CanonicalSupplierIdentity/></>:null}
  <section className="panel"><div className="section-heading"><div><span className="overline">Directorio</span><h2>{kind==='supplier'?'Proveedores':'Clientes'}</h2></div><span>{parties.length} fichas</span></div><div className="compact-ledger">{parties.map(p=>{const metric=(kind==='supplier'?data?.suppliers:data?.customers)?.find(m=>(m.supplier_id??m.customer_id)===p.id);return <button key={p.id} onClick={()=>setEditing(p)}><span><Building2 size={14}/></span><div><b>{p.legal_name}</b><small>{[p.city,p.country,p.contact_name,p.email].filter(Boolean).join(' · ')||'Ficha básica'}</small></div><strong>{kind==='supplier'?`${kg(Number(metric?.received_kg??0))} · ${clp(Number(metric?.contribution_clp??0))}`:clp(Number(metric?.revenue_clp??0))}</strong></button>})}</div></section>
  {editing?<PartyEditor party={editing} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load()}}/>:null}
 </>
}

function PartyEditor({party,onClose,onSaved}:{party:Party;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [form,setForm]=useState({...party}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const set=(field:keyof Party,value:Party[keyof Party])=>setForm(current=>({...current,[field]:value}))
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/partners',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({partyId:form.id||null,kind:form.kind,legalName:form.legal_name,taxId:form.tax_id,phone:form.phone,contactName:form.contact_name,email:form.email,address:form.address,city:form.city,country:form.country,paymentTerms:form.payment_terms,notes:form.notes,tags:form.tags})}),p=await r.json() as {error?:string};if(!r.ok)throw new Error(p.error??'No fue posible guardar');await onSaved()}catch(e){setError(e instanceof Error?e.message:'No fue posible guardar')}finally{setBusy(false)}}
 return <div className="modal-backdrop"><form className="modal-panel commercial-form" onSubmit={submit}><header><div><span className="overline">Ficha comercial</span><h2>{form.id?'Editar':'Crear'} {form.kind==='supplier'?'proveedor':'cliente'}</h2></div><button type="button" className="icon-btn" onClick={onClose}><X size={18}/></button></header><div className="commercial-form-grid"><label>Razón social<input value={form.legal_name} onChange={e=>set('legal_name',e.target.value)} required/></label><label>RUT / Tax ID<input value={form.tax_id??''} onChange={e=>set('tax_id',e.target.value)}/></label><label>Contacto<input value={form.contact_name??''} onChange={e=>set('contact_name',e.target.value)}/></label><label>Email<input type="email" value={form.email??''} onChange={e=>set('email',e.target.value)}/></label><label>Teléfono<input value={form.phone??''} onChange={e=>set('phone',e.target.value)}/></label><label>País<input value={form.country??''} onChange={e=>set('country',e.target.value)}/></label><label>Ciudad<input value={form.city??''} onChange={e=>set('city',e.target.value)}/></label><label>Dirección<input value={form.address??''} onChange={e=>set('address',e.target.value)}/></label><label>Condiciones pago<input value={form.payment_terms??''} onChange={e=>set('payment_terms',e.target.value)}/></label><label>Notas<input value={form.notes??''} onChange={e=>set('notes',e.target.value)}/></label></div>{error?<p className="form-error">{error}</p>:null}<footer><button type="button" className="button" onClick={onClose}>Cancelar</button><button className="button primary" disabled={busy}><Save size={15}/>{busy?'Guardando…':'Guardar ficha'}</button></footer></form></div>
}
