import { AlertTriangle, ArrowLeft, ArrowRight, Boxes, Building2, CheckCircle2, Clock3, FileQuestion, FileSpreadsheet, History, Link2Off, PackageCheck, RotateCcw, Scale, TrendingUp } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { isOperationalPlant, type ImportBatch, type PlantState } from '../plantImport'
import { canonicalSource, plants as configuredPlants, type Plant } from '../plants'
import { fetchSharedPlantState, revertSharedPlantState } from '../plantApi'

const kg=(value:number)=>`${value.toLocaleString('es-CL')} kg`
export function PlantControl(){
  const {plantId}=useParams()
  const [plants,setPlants]=useState<PlantState[]>(()=>{try{return JSON.parse(localStorage.getItem('pescamar.plants.v2')??'null')??configuredPlants}catch{return configuredPlants}})
  const [history,setHistory]=useState<ImportBatch[]>(()=>{try{return JSON.parse(localStorage.getItem('pescamar.imports.v2')??'null')??[]}catch{return []}})
  const [shared,setShared]=useState(false)
  useEffect(()=>localStorage.setItem('pescamar.plants.v2',JSON.stringify(plants)),[plants])
  useEffect(()=>localStorage.setItem('pescamar.imports.v2',JSON.stringify(history)),[history])
  useEffect(()=>{let active=true;fetchSharedPlantState().then(data=>{if(!active)return;if(data.plants)setPlants(data.plants);setHistory(data.history);setShared(true)}).catch(()=>setShared(false));return()=>{active=false}},[])
  const revertLatest=async()=>{const batch=history.find(item=>!item.revertedAt);if(!batch)return;let restored=batch.previousPlants;if(shared){try{restored=(await revertSharedPlantState(batch.id)).plants}catch{return}}setPlants(restored);setHistory(items=>items.map(item=>item.id===batch.id?{...item,revertedAt:new Date().toISOString()}:item))}
  const selected=plants.find(plant=>plant.id===plantId)
  if(selected)return <PlantDetail plant={selected}/>
  const linked=plants.filter(isOperationalPlant)
  const totalProduction=linked.reduce((sum,plant)=>sum+plant.productionKg,0),totalTarget=linked.reduce((sum,plant)=>sum+plant.targetKg,0),totalInventory=linked.reduce((sum,plant)=>sum+plant.inventoryKg,0)
  const criticalCount=linked.reduce((sum,plant)=>sum+plant.alerts.filter(alert=>alert.severity==='Crítica').length,0),attentionCount=linked.reduce((sum,plant)=>sum+plant.alerts.filter(alert=>alert.severity==='Atención').length,0)
  return <><PageHeader eyebrow="Centro de control multiplanta" title="Fuentes operacionales" description="El tablero solo publica indicadores provenientes de archivos validados y asignados a una planta." actions={<Link className="button primary" to="/importaciones"><FileSpreadsheet size={16}/>Importar planilla</Link>}/>
    <section className="plant-summary"><Summary icon={<Building2/>} label="Plantas configuradas" value={String(plants.length)} note={`${linked.length} con datos publicados`}/><Summary icon={<Scale/>} label="Producción publicada" value={linked.length?kg(totalProduction):'—'} note={linked.length&&totalTarget?`${Math.round(totalProduction/totalTarget*100)}% de cumplimiento global`:'Sin datos calculados'}/><Summary icon={<Boxes/>} label="Inventario informado" value={linked.length?kg(totalInventory):'—'} note="Sólo fuentes publicadas"/><Summary icon={<AlertTriangle/>} label="Alertas abiertas" value={String(criticalCount+attentionCount)} note={`${criticalCount} críticas · ${attentionCount} de atención`} warning/></section>
    <article className="panel source-banner"><div className="source-icon"><FileSpreadsheet size={22}/></div><div><span className="overline teal">Fuente real disponible</span><h2>{canonicalSource.name}</h2><p>{canonicalSource.records} registros · {canonicalSource.period}</p></div><span className="status warning">{canonicalSource.status}</span><Link className="button secondary" to="/operacion-2025">Ver datos</Link></article>
    <section className="control-heading"><div><span className="overline teal">Red configurada</span><h2>Estado por planta</h2></div><div className="status-legend"><span><i className="healthy"/>Normal</span><span><i className="attention"/>Atención</span><span><i className="critical"/>Crítica</span><span><i className="offline"/>Sin fuente</span></div></section>
    <section className="plant-grid">{plants.map(plant=><PlantCard plant={plant} key={plant.id}/>)}</section><ImportHistory history={history} onRevert={()=>void revertLatest()} shared={shared}/>
  </>
}

function PlantCard({plant}:{plant:PlantState}){if(!isOperationalPlant(plant))return <Link className="panel plant-card status-offline" to={`/plantas/${plant.id}`}><header><div className="plant-signal offline"><span/></div><div><span className="overline">{plant.mode}</span><h2>{plant.name}</h2><small>{plant.location}</small></div><ArrowRight size={18}/></header><div className="plant-status-copy"><b>Sin datos publicados</b><span>No existe una importación validada y asignada a esta planta.</span></div><div className="plant-kpis"><div><small>Producción</small><b>—</b></div><div><small>Cumplimiento</small><b>—</b></div><div><small>Inventario</small><b>—</b></div></div><div className="product-tags">{plant.products.slice(0,3).map(product=><span key={product}>{product}</span>)}</div><footer><span><Link2Off size={13}/>Fuente no vinculada</span><span>0 alertas</span></footer></Link>
  const progress=Math.min(100,Math.round(plant.productionKg/plant.targetKg*100));return <Link className={`panel plant-card status-${plant.status}`} to={`/plantas/${plant.id}`}><header><div className={`plant-signal ${plant.status}`}><span/></div><div><span className="overline">{plant.mode}</span><h2>{plant.name}</h2><small>{plant.location}</small></div><ArrowRight size={18}/></header><div className="plant-status-copy"><b>{plant.statusLabel}</b><span>{plant.statusReason}</span></div><div className="plant-kpis"><div><small>Producción</small><b>{kg(plant.productionKg)}</b></div><div><small>Cumplimiento</small><b>{progress}%</b></div><div><small>Inventario</small><b>{kg(plant.inventoryKg)}</b></div></div><div className="plant-progress"><i style={{width:`${progress}%`}}/></div><div className="product-tags">{plant.products.slice(0,3).map(product=><span key={product}>{product}</span>)}</div><footer><span><Clock3 size={13}/>{plant.updatedAt}</span><span>{plant.alerts.length} alertas</span></footer></Link>}

function PlantDetail({plant}:{plant:PlantState}){if(!isOperationalPlant(plant))return <><Link to="/" className="back-link"><ArrowLeft size={15}/>Volver al centro de control</Link><PageHeader eyebrow={`${plant.mode} · ${plant.location}`} title={plant.name} description="Esta planta está configurada, pero todavía no tiene una fuente operacional validada." actions={<Link className="button primary" to="/importaciones"><FileSpreadsheet size={16}/>Asignar planilla</Link>}/><section className="plant-detail-banner offline"><div className="plant-signal offline"><span/></div><div><small>Estado de datos</small><b>Sin fuente asignada</b><p>No se muestran indicadores hasta publicar una importación válida.</p></div></section><section className="plant-detail-grid"><ProductCatalog plant={plant}/><article className="panel plant-empty"><Link2Off size={30}/><b>Indicadores bloqueados</b><span>Asigna y publica una fuente válida para habilitar los KPI.</span></article></section></>
  const progress=Math.round(plant.productionKg/plant.targetKg*100);return <><Link to="/" className="back-link"><ArrowLeft size={15}/>Volver al centro de control</Link><PageHeader eyebrow={`${plant.mode} · ${plant.location}`} title={plant.name} description={plant.statusReason} actions={<Link className="button secondary" to="/importaciones"><FileSpreadsheet size={16}/>Ver importaciones</Link>}/><section className={`plant-detail-banner ${plant.status}`}><div className={`plant-signal ${plant.status}`}><span/></div><div><small>Estado actual</small><b>{plant.statusLabel}</b><p>{plant.statusReason}</p></div><div><small>Última actualización</small><b>{plant.updatedAt}</b><span>{plant.source}</span></div></section><section className="metric-grid"><DetailMetric icon={<TrendingUp/>} label="Producción" value={kg(plant.productionKg)} note={`Meta ${kg(plant.targetKg)}`}/><DetailMetric icon={<CheckCircle2/>} label="Cumplimiento" value={`${progress}%`} note={progress>=95?'Dentro de rango':'Bajo objetivo'}/><DetailMetric icon={<Boxes/>} label="Inventario total" value={kg(plant.inventoryKg)} note="Último archivo publicado"/><DetailMetric icon={<PackageCheck/>} label="Producto terminado" value={kg(plant.inventoryFinishedKg)} note={plant.inventoryKg?`${Math.round(plant.inventoryFinishedKg/plant.inventoryKg*100)}% del inventario`:'Sin inventario'}/></section><section className="plant-detail-grid"><ProductCatalog plant={plant}/><article className="panel"><header className="panel-header"><h2>Alertas y observaciones</h2><span>{plant.alerts.length} registradas</span></header>{plant.alerts.length?<div className="detail-alerts">{plant.alerts.map(alert=><div key={alert.id} className={alert.severity==='Crítica'?'critical':''}><AlertTriangle size={17}/><span><b>{alert.title}</b><small>{alert.detail}</small></span><em>{alert.severity}</em></div>)}</div>:<div className="plant-empty"><CheckCircle2 size={27}/><b>Sin alertas abiertas</b><span>La operación informada se encuentra dentro de los rangos definidos.</span></div>}</article></section></>}

function ProductCatalog({plant}:{plant:Plant}){return <article className="panel"><header className="panel-header"><h2>Catálogo de productos</h2><span>{plant.products.length} categorías</span></header><div className="product-list">{plant.products.map((product,index)=><div key={product}><span>{String(index+1).padStart(2,'0')}</span><b>{product}</b><em>{isOperationalPlant(plant)?'Incluido en última planilla':'Configuración por validar'}</em></div>)}</div></article>}
function Summary({icon,label,value,note,warning=false}:{icon:React.ReactNode;label:string;value:string;note:string;warning?:boolean}){return <article className={warning?'warning':''}><span>{icon}</span><div><small>{label}</small><b>{value}</b><em>{note}</em></div></article>}
function DetailMetric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <article className="metric"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function ImportHistory({history,onRevert,shared}:{history:ImportBatch[];onRevert:()=>void;shared:boolean}){const latest=history.find(item=>!item.revertedAt);return <section className="panel local-import-history"><header className="panel-header"><div><span className="overline teal">{shared?'Trazabilidad compartida':'Trazabilidad local'}</span><h2>Publicaciones de resumen</h2></div><span>{history.length} lotes</span></header>{history.length?<div className="history-list">{history.slice(0,5).map(batch=><article key={batch.id} className={batch.revertedAt?'reverted':''}><span className="history-icon"><History/></span><div><b>{batch.fileName}</b><small>{batch.id} · {batch.periods.join(', ')} · {batch.rowCount} plantas</small></div><div><b>{new Date(batch.publishedAt).toLocaleString('es-CL',{dateStyle:'short',timeStyle:'short'})}</b><small>{batch.publishedBy}</small></div><em>{batch.revertedAt?'Revertida':'Publicada'}</em></article>)}</div>:<div className="history-empty"><FileQuestion/><span><b>Sin resúmenes publicados</b><small>La carga cruda en Gobierno de datos se mantiene separada.</small></span></div>}<footer><span>{shared?'Se muestran los últimos 10 lotes compartidos.':'Se conservan los últimos 10 lotes en este navegador.'}</span><button className="button secondary" disabled={!latest} onClick={onRevert}><RotateCcw size={14}/>Revertir última</button></footer></section>}
