import {AlertTriangle,ArrowLeft,ArrowRight,Boxes,CheckCircle2,Clock3,FileSpreadsheet,Link2Off,PackageCheck,TrendingUp} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {Link,useNavigate,useParams} from "react-router-dom";
import {PlantImportModal} from "../components/PlantImportModal";
import {PageHeader} from "../components/PageHeader";
import {fetchSharedPlantState,publishSharedPlantState} from "../plantApi";
import {createImportBatch,isOperationalPlant,type PlantState,type ValidatedImport} from "../plantImport";
import {plants as configuredPlants,type Plant} from "../plants";

type Performance={plant_id:string;lots:number|string;received_kg:number|string;produced_kg:number|string;available_kg:number|string;revenue_clp:number|string;purchase_cost_clp:number|string;transformation_cost_clp:number|string;contribution_clp:number|string;contribution_pct:number|string|null}
type PerformancePayload={plants?:Performance[];error?:string}
const kg=(value:number|string)=>`${Number(value).toLocaleString("es-CL",{maximumFractionDigits:0})} kg`;
const clp=(value:number|string)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(value));

export function PlantControl(){
  const {plantId}=useParams();const navigate=useNavigate();
  const [plants,setPlants]=useState<PlantState[]>(configuredPlants),[performance,setPerformance]=useState<Performance[]>([]),[importOpen,setImportOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{let active=true;Promise.all([fetchSharedPlantState(),fetch('/api/plant-performance',{cache:'no-store'}).then(async r=>{const p=await r.json() as PerformancePayload;if(!r.ok)throw new Error(p.error??'No fue posible cargar desempeño');return p})]).then(([state,perf])=>{if(!active)return;setPlants(Array.isArray(state.plants)&&state.plants.length?state.plants:configuredPlants);setPerformance(perf.plants??[]);setError('')}).catch((cause:unknown)=>{if(!active)return;setPlants(configuredPlants);setError(cause instanceof Error?cause.message:'No fue posible sincronizar plantas')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
  const publish=async(rows:ValidatedImport[])=>{const operator=import.meta.env.VITE_OPERATOR_NAME?.trim();if(!operator)throw new Error('Falta configurar la identidad del operador');const batch=createImportBatch(plants,rows,operator);await publishSharedPlantState(batch);setPlants(batch.resultingPlants);setError('')}
  const perfMap=useMemo(()=>new Map(performance.map(row=>[row.plant_id,row])),[performance]);
  const selected=plants.find(plant=>plant.id===plantId),selectedPerformance=selected?perfMap.get(selected.id):undefined;
  if(selected)return <><nav className="plant-detail-toolbar" aria-label="Navegación de plantas"><Link to="/plantas" className="back-link"><ArrowLeft size={15}/>Todas las plantas</Link><PlantScopeSelector plants={plants} value={selected.id} onChange={id=>{localStorage.setItem('pescamar-active-plant',id);navigate(`/plantas/${id}`)}}/></nav><PlantDetail plant={selected} performance={selectedPerformance}/><PlantImportModal open={importOpen} plants={configuredPlants} onClose={()=>setImportOpen(false)} onPublish={publish}/></>;
  const linkedCount=plants.filter(isOperationalPlant).length;
  return <>{loading?<div className="system-banner">Calculando desempeño de plantas…</div>:null}{error?<div className="system-banner error" role="alert">{error}</div>:null}<PageHeader eyebrow="Desempeño por planta" title="Plantas" description="Compara la red en segundos. Cada tarjeta muestra sólo los KPI esenciales; abre una planta para entender producción, rentabilidad, inventario y excepciones." actions={<Link className="button secondary" to="/importaciones"><FileSpreadsheet size={16}/>Gestionar fuentes</Link>}/><section className="plant-directory-summary" aria-label="Resumen de la red"><div><small>Plantas</small><b>{plants.length}</b></div><div><small>Con actividad</small><b>{performance.filter(row=>Number(row.lots)>0).length}</b></div><div><small>Con fuente operacional</small><b>{linkedCount}</b></div><p>La portada muestra desempeño. El detalle explica por qué una planta está bien, bajo objetivo o perdiendo contribución.</p></section><section className="plant-grid corporate-plant-grid">{plants.map(plant=><PlantCard plant={plant} performance={perfMap.get(plant.id)} key={plant.id}/>)}</section><PlantImportModal open={importOpen} plants={configuredPlants} onClose={()=>setImportOpen(false)} onPublish={publish}/></>
}

function PlantCard({plant,performance}:{plant:PlantState;performance?:Performance}){
  const operational=isOperationalPlant(plant),progress=operational&&plant.targetKg?Math.min(100,Math.round(plant.productionKg/plant.targetKg*100)):null,contributionPct=performance?.contribution_pct==null?null:Number(performance.contribution_pct),alerts=operational?plant.alerts.length:0;
  const health=alerts>0?'attention':contributionPct!=null&&contributionPct<0?'critical':operational?'healthy':'offline';
  return <Link className={`panel plant-card corporate-plant-card status-${health}`} to={`/plantas/${plant.id}`}><header><div><span className="overline">{plant.location}</span><h2>{plant.name}</h2><small>{plant.mode}</small></div><ArrowRight size={18}/></header><div className="plant-kpis executive"><div><small>Producción</small><b>{operational?kg(plant.productionKg):performance?kg(performance.produced_kg):'—'}</b></div><div><small>Cumplimiento</small><b>{progress==null?'—':`${progress}%`}</b></div><div><small>Disponible</small><b>{performance?kg(performance.available_kg):operational?kg(plant.inventoryKg):'—'}</b></div><div><small>Contribución</small><b>{performance&&Number(performance.revenue_clp)>0?clp(performance.contribution_clp):'—'}</b><small>{contributionPct==null?'Costo/venta incompletos':`${contributionPct.toFixed(1)}%`}</small></div><div><small>Alertas</small><b>{alerts}</b></div></div><footer><span>{operational?<><Clock3 size={13}/>{plant.updatedAt}</>:performance?<><CheckCircle2 size={13}/>{Number(performance.lots)} lotes</>:<><Link2Off size={13}/>Sin actividad</>}</span><span>Ver detalle <ArrowRight size={13}/></span></footer></Link>
}

function PlantScopeSelector({plants,value,onChange}:{plants:PlantState[];value:string;onChange:(id:string)=>void}){return <label className="plant-scope-selector"><span>Cambiar planta</span><select aria-label="Cambiar planta" value={value} onChange={e=>onChange(e.target.value)}><option value="" disabled>Seleccionar planta</option>{plants.map(plant=><option value={plant.id} key={plant.id}>{plant.name} · {plant.location}</option>)}</select></label>}

function PlantDetail({plant,performance}:{plant:PlantState;performance?:Performance}){
  const operational=isOperationalPlant(plant),progress=operational&&plant.targetKg?Math.round(plant.productionKg/plant.targetKg*100):null;
  return <><PageHeader eyebrow={`${plant.mode} · ${plant.location}`} title={plant.name} description={operational?plant.statusReason:'Detalle ejecutivo de desempeño, operación y rentabilidad de la planta.'} actions={<Link className="button secondary" to="/rentabilidad"><TrendingUp size={16}/>Ver rentabilidad</Link>}/><section className="metric-grid"><DetailMetric icon={<TrendingUp/>} label="Producción" value={operational?kg(plant.productionKg):performance?kg(performance.produced_kg):'—'} note={operational?`Meta ${kg(plant.targetKg)}`:'Sin meta publicada'}/><DetailMetric icon={<CheckCircle2/>} label="Cumplimiento" value={progress==null?'—':`${progress}%`} note={progress==null?'Sin meta publicada':progress>=95?'Dentro de rango':'Bajo objetivo'}/><DetailMetric icon={<Boxes/>} label="Inventario disponible" value={performance?kg(performance.available_kg):operational?kg(plant.inventoryKg):'—'} note="Después de despachos confirmados"/><DetailMetric icon={<PackageCheck/>} label="Contribución conocida" value={performance&&Number(performance.revenue_clp)>0?clp(performance.contribution_clp):'—'} note={performance?.contribution_pct==null?'Faltan costos o ventas':`${Number(performance.contribution_pct).toFixed(1)}% de ingresos`}/></section>{performance?<section className="panel"><header className="panel-header"><div><span className="overline">Economía de la planta</span><h2>De operación a contribución</h2></div><span>{Number(performance.lots)} lotes</span></header><div className="balance-summary"><div><small>Ingresos conocidos</small><b>{clp(performance.revenue_clp)}</b></div><div><small>Compra materia prima</small><b>{clp(performance.purchase_cost_clp)}</b></div><div><small>Transformación</small><b>{clp(performance.transformation_cost_clp)}</b></div><div><small>Contribución</small><b>{clp(performance.contribution_clp)}</b></div></div></section>:null}<section className="plant-detail-grid"><ProductCatalog plant={plant}/><article className="panel"><header className="panel-header"><h2>Alertas y observaciones</h2><span>{operational?plant.alerts.length:0} registradas</span></header>{operational&&plant.alerts.length?<div className="detail-alerts">{plant.alerts.map(alert=><div key={alert.id} className={alert.severity==='Crítica'?'critical':''}><AlertTriangle size={17}/><span><b>{alert.title}</b><small>{alert.detail}</small></span><em>{alert.severity}</em></div>)}</div>:<div className="plant-empty"><CheckCircle2 size={27}/><b>Sin alertas abiertas</b><span>No hay excepciones operacionales publicadas para esta planta.</span></div>}</article></section></>
}
function ProductCatalog({plant}:{plant:Plant}){return <article className="panel"><header className="panel-header"><h2>Productos</h2><span>{plant.products.length} categorías</span></header><div className="product-list">{plant.products.map((product,index)=><div key={product}><span>{String(index+1).padStart(2,'0')}</span><b>{product}</b><em>{isOperationalPlant(plant)?'Operación configurada':'Configuración por validar'}</em></div>)}</div></article>}
function DetailMetric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <article className="metric"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
