import {AlertTriangle,CheckCircle2,Clock3,Factory,Target} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {useLot360} from '../components/Lot360Context'
import {PageHeader} from '../components/PageHeader'

type Candidate={id:string;reception_number:string|number;plant_id:string|null;species:string;supplier:string;confirmedAvailableKg:number;potentialAvailableKg:number;isProduced:boolean}
type Recommendation={orderId:string;orderNumber:string|number;plantId?:string|null;customer:string;product:string;species:string;deliveryDate:string;daysToDelivery:number;priority:string;priorityLabel:string;remainingKg:number;candidates:Candidate[]}
type BlockedLot={id:string;receptionNumber:string|number;plantId:string|null;species:string;supplier:string;producedKg:number|null;reasons:string[]}
type DailyPlan={orderId:string;orderNumber:string|number;customer:string;product:string;species:string;deliveryDate:string;daysToDelivery:number;priority:string;priorityLabel:string;remainingKg:number;action:'blocked'|'allocate_finished'|'produce';recommendedKg:number;estimatedInputKg:number|null;receptionId:string|null;receptionNumber:string|number|null;supplier:string|null;plantId:string|null;lineId:string|null;lineName:string|null;lineConfigured:boolean;confidence:string}
type Payload={scope?:{plantId:string|null};historicalYieldPct?:number;historicalRows?:number;recommendations?:Recommendation[];blockedLots?:BlockedLot[];dailyPlan?:DailyPlan[];plannerReadiness?:{capacityConfigured:boolean;activeLines:number;message:string};error?:string}
const kg=(v:number)=>`${v.toLocaleString('es-CL',{maximumFractionDigits:1})} kg`
const actionLabel=(v:DailyPlan['action'])=>v==='allocate_finished'?'Asignar producto terminado':v==='produce'?'Producir':'Resolver bloqueo'
const urgency=(v:string)=>v==='critical'?'danger':v==='high'?'warning':v==='medium'?'info':'success'

export function Planning(){
 const {openLive}=useLot360();const [params]=useSearchParams();const plantId=params.get('plantId')??''
 const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let active=true;const q=plantId?`?plantId=${encodeURIComponent(plantId)}`:'';setLoading(true);void fetch(`/api/planning${q}`,{cache:'no-store'}).then(async r=>{const p=await r.json() as Payload;if(!r.ok)throw new Error(p.error??'No fue posible construir el plan');if(active){setData(p);setError('')}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'No fue posible construir el plan')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[plantId])
 const recs=useMemo(()=>data?.recommendations??[],[data?.recommendations]),blocked=data?.blockedLots??[],daily=useMemo(()=>data?.dailyPlan??[],[data?.dailyPlan])
 const pendingKg=useMemo(()=>recs.reduce((sum,rec)=>sum+rec.remainingKg,0),[recs]);const plannedKg=useMemo(()=>daily.reduce((sum,row)=>sum+row.recommendedKg,0),[daily])
 const first=daily[0]??null,firstBlocked=blocked[0]??null
 const actions=plantId?<Link className="button secondary" to={`/plantas/${plantId}`}>Volver a planta</Link>:undefined;const scope=plantId?`&plantId=${encodeURIComponent(plantId)}`:''
 return <>
  <PageHeader eyebrow="Operación" title="Planificación" description="Qué hacer después. El detalle de capacidad, cumplimiento y candidatos queda disponible cuando lo necesitas." actions={actions}/>
  {error?<div className="system-banner error">{error}</div>:null}{loading?<div className="system-banner">Calculando siguiente acción…</div>:null}
  {!loading&&!error?<section className="panel" aria-label="Siguiente acción recomendada"><div className="section-heading"><div><span className="overline teal">Siguiente acción</span><h2>{first?actionLabel(first.action):firstBlocked?'Resolver bloqueo':'Sin acciones pendientes'}</h2></div>{first?<span className={`status ${urgency(first.priority)}`}>{first.priorityLabel}</span>:null}</div>{first?<div className="daily-plan-row"><div className="daily-plan-order"><b>OV-{first.orderNumber} · {first.customer}</b><small>{first.product} · {kg(first.remainingKg)} pendientes</small></div><div className="daily-plan-action"><b>{actionLabel(first.action)}</b>{first.receptionId?<button className="lot-link" onClick={()=>openLive(first.receptionId!)}>REC-{first.receptionNumber} · {first.supplier}</button>:<small>Sin lote liberado compatible</small>}</div><div className="daily-plan-mass"><strong>{kg(first.recommendedKg)}</strong><small>{first.daysToDelivery<0?`${Math.abs(first.daysToDelivery)} d atrasada`:first.daysToDelivery===0?'Entrega hoy':`${first.daysToDelivery} d para entrega`}</small></div></div>:firstBlocked?<div className="alert-row static"><span><AlertTriangle size={16}/></span><div><b>REC-{firstBlocked.receptionNumber} · {firstBlocked.supplier}</b><small>{firstBlocked.reasons[0]??'Requiere revisión'}</small></div><Link className="source-link compact" to={`/proceso-erizo?receptionId=${encodeURIComponent(firstBlocked.id)}${scope}`}>Resolver</Link></div>:<div className="empty-inline"><Target size={20}/><div><b>Todo en orden</b><small>El plan comenzará cuando exista una orden o excepción que requiera acción.</small></div></div>}</section>:null}

  <details className="panel list-panel"><summary><span><b>Ver plan completo</b><small>{recs.length} órdenes · {kg(pendingKg)} pendientes · {blocked.length} bloqueos</small></span><span>Leer más</span></summary><div className="receptions-history-body">
   {plantId?<div className="notice"><Factory size={16}/><div><b>Plan filtrado por planta</b><small>Órdenes, lotes y excepciones se mantienen dentro del alcance seleccionado.</small></div></div>:null}
   <section className="operational-strip" aria-label="Resumen de planificación"><div><small>Órdenes abiertas</small><b>{recs.length}</b></div><div><small>Kilos pendientes</small><b>{kg(pendingKg)}</b></div><div><small>Plan recomendado</small><b>{kg(plannedKg)}</b><span>{daily.filter(x=>x.action!=='blocked').length} acciones ejecutables</span></div><div><small>Lotes bloqueados</small><b>{blocked.length}</b></div></section>
   {data?.plannerReadiness&&!data.plannerReadiness.capacityConfigured?<div className="notice"><Clock3 size={16}/><div><b>Capacidad horaria aún no configurada</b><small>{data.plannerReadiness.message}</small></div><Link className="source-link compact" to="/lineas">Configurar líneas</Link></div>:null}
   {daily.length?<section><div className="section-heading"><div><span className="overline">Prioridades</span><h2>Plan recomendado</h2></div><span>{daily.length}</span></div><div className="daily-plan-list">{daily.map(row=><article className="daily-plan-row" key={row.orderId}><div className="daily-plan-priority"><span className={`status ${urgency(row.priority)}`}>{row.priorityLabel}</span><small>{row.daysToDelivery<0?`${Math.abs(row.daysToDelivery)} d atrasada`:row.daysToDelivery===0?'Entrega hoy':`${row.daysToDelivery} d`}</small></div><div className="daily-plan-order"><b>OV-{row.orderNumber} · {row.customer}</b><small>{row.product} · {kg(row.remainingKg)} pendientes</small></div><div className="daily-plan-action"><b>{actionLabel(row.action)}</b>{row.receptionId?<button className="lot-link" onClick={()=>openLive(row.receptionId!)}>REC-{row.receptionNumber} · {row.supplier}</button>:<small>Sin lote liberado compatible</small>}</div><div className="daily-plan-mass"><strong>{kg(row.recommendedKg)}</strong><small>{row.estimatedInputKg!=null?`Entrada ${kg(row.estimatedInputKg)}`:row.action==='allocate_finished'?'Producto confirmado':'Pendiente'}</small></div></article>)}</div></section>:null}
   {blocked.length?<section><div className="section-heading"><div><span className="overline">Excepciones</span><h2>Bloqueos</h2></div><span>{blocked.length}</span></div><div className="compact-ledger">{blocked.map(l=><div className="alert-row static" key={l.id}><span><AlertTriangle size={16}/></span><div><b>REC-{l.receptionNumber} · {l.supplier}</b><small>{l.reasons.join(' · ')}</small></div><Link className="source-link compact" to={`/proceso-erizo?receptionId=${encodeURIComponent(l.id)}${scope}`}>Resolver</Link></div>)}</div></section>:null}
   <section className="planning-workspace"><div className="section-heading"><div><span className="overline">Evidencia</span><h2>Órdenes y lotes compatibles</h2></div><span>{recs.length?`${recs.length} por resolver`:'Sin pendientes'}</span></div>{recs.length?<div className="planning-list">{recs.map(rec=><article className="planning-order" key={rec.orderId}><header><div><b>OV-{rec.orderNumber} · {rec.customer}</b><small>{rec.product} · {rec.species} · entrega {rec.deliveryDate}</small></div><strong>{kg(rec.remainingKg)} pendientes</strong></header>{rec.candidates.length?<div className="planning-candidates">{rec.candidates.map(c=><button key={c.id} onClick={()=>openLive(c.id)} aria-label={`Abrir ficha 360 de REC-${c.reception_number}`}><span className={c.isProduced?'confirmed':'estimated'}>{c.isProduced?<CheckCircle2 size={14}/>:<Factory size={14}/>}</span><div><b>REC-{c.reception_number} · {c.supplier}</b><small>{c.plant_id??'Sin planta'} · {c.isProduced?'producto confirmado':'materia prima por producir'}</small></div><strong>{kg(c.isProduced?c.confirmedAvailableKg:c.potentialAvailableKg)}</strong><em>{c.isProduced?'confirmado':'estimado'}</em></button>)}</div>:<p className="source-note">No hay lotes liberados compatibles.</p>}</article>)}</div>:<div className="empty-state"><Target size={30}/><h2>Sin órdenes abiertas</h2><p>El plan diario comenzará con la primera orden real.</p></div>}</section>
  </div></details>
 </>
}
