import {Building2,Database,Landmark,PackageCheck,TrendingDown,TrendingUp,UsersRound} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {PageHeader} from '../components/PageHeader'

type LiveRow={supplier_id?:string;supplier?:string;customer_id?:string;customer?:string;plant_id?:string;receptions?:number;lots?:number;received_kg?:number;sold_kg?:number;revenue_clp?:number;purchase_cost_clp?:number;transformation_cost_clp?:number;contribution_clp?:number;contribution_pct?:number}
type HistRow={supplier?:string;customer?:string;plant_id?:string;product_family?:string;lots?:number;received_kg?:number;source_kg?:number;stock_rows?:number;stock_kg?:number;difference_kg?:number;avg_quality_discount?:number;avg_price_clp?:number;estimated_purchase_clp?:number;flagged_rows?:number;first_date?:string;last_date?:string}
type Payload={live?:{suppliers?:LiveRow[];plants?:LiveRow[];customers?:LiveRow[]};historical?:{suppliers?:HistRow[];plants?:HistRow[];customers?:HistRow[];products?:HistRow[]};documents?:{purchase_orders?:number;purchase_orders_clp?:number;export_invoices?:number;export_invoices_usd?:number;export_kg?:number;packing_boxes?:number;packing_kg?:number};coverage?:{historical_rows?:number;historical_flagged?:number;stock_rows?:number;account_rows?:number;transfer_rows?:number};sourceCoverage?:Array<{source_kind:string;files:number}>;error?:string}

const clp=(v:number|null|undefined)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(v??0))
const num=(v:number|null|undefined,d=0)=>Number(v??0).toLocaleString('es-CL',{maximumFractionDigits:d})
const pct=(v:number|null|undefined)=>v==null?'—':`${Number(v).toFixed(1)}%`
const sourceDate=(value:string)=>{const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'UTC'}).format(date)}
const sourceRange=(first?:string,last?:string)=>first&&last?`${sourceDate(first)} → ${sourceDate(last)}`:'Historia disponible'

export function Profitability(){
 const[data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[view,setView]=useState<'supplier'|'plant'|'customer'>('supplier')
 useEffect(()=>{fetch('/api/profitability',{cache:'no-store'}).then(async r=>{const p=await r.json() as Payload;if(!r.ok)throw new Error(p.error??'No fue posible calcular inteligencia');setData(p)}).catch(e=>setError(e instanceof Error?e.message:'No fue posible calcular inteligencia')).finally(()=>setLoading(false))},[])
 const liveRows=view==='supplier'?data?.live?.suppliers??[]:view==='plant'?data?.live?.plants??[]:data?.live?.customers??[]
 const historyRows=view==='supplier'?data?.historical?.suppliers??[]:view==='plant'?data?.historical?.plants??[]:data?.historical?.customers??[]
 const hasLive=liveRows.some(r=>Number(r.revenue_clp??0)>0||Number(r.receptions??r.lots??0)>0)
 const revenue=useMemo(()=>liveRows.reduce((a,r)=>a+Number(r.revenue_clp??0),0),[liveRows]),contribution=useMemo(()=>liveRows.reduce((a,r)=>a+Number(r.contribution_clp??0),0),[liveRows])
 const topHistory=historyRows[0]
 return <>
  <PageHeader eyebrow="Inteligencia económica" title="Desempeño y rentabilidad" description="El sistema usa desde ahora dos capas: historia Pescamar para aprender desde el primer día y operación viva para calcular rentabilidad trazable a medida que nacen nuevos lotes."/>
  {error?<div className="system-banner error">{error}</div>:null}
  {loading?<div className="system-banner">Leyendo historia y operación viva…</div>:null}
  <section className="signal-grid">
   <article className="signal-card"><span><Database size={16}/>Historia disponible</span><b>{num(data?.coverage?.historical_rows)}</b><small>registros productivos · {num(data?.coverage?.account_rows)} contables</small></article>
   <article className="signal-card"><span><PackageCheck size={16}/>Packing e inventario</span><b>{num(data?.documents?.packing_boxes)}</b><small>cajas · {num(data?.documents?.packing_kg,1)} kg empacados</small></article>
   <article className="signal-card"><span><Landmark size={16}/>Operación comercial documentada</span><b>{Number(data?.documents?.export_invoices??0)+Number(data?.documents?.purchase_orders??0)}</b><small>{num(data?.documents?.export_kg,1)} kg exportados en documentos cargados</small></article>
  </section>
  <div className="event-kind-tabs"><button className={view==='supplier'?'active':''} onClick={()=>setView('supplier')}>Proveedores</button><button className={view==='plant'?'active':''} onClick={()=>setView('plant')}>Plantas</button><button className={view==='customer'?'active':''} onClick={()=>setView('customer')}>Clientes</button></div>
  <section className="panel"><div className="section-heading"><div><span className="overline">Historia Pescamar</span><h2>{view==='supplier'?'Desempeño histórico de proveedores':view==='plant'?'Desempeño histórico de plantas':'Actividad histórica por cliente'}</h2></div><span>{historyRows.length} entidades</span></div>{historyRows.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>{view==='supplier'?'Proveedor':view==='plant'?'Planta':'Cliente'}</th><th className="numeric">Lotes</th><th className="numeric">Kg</th>{view!=='customer'?<><th className="numeric">Diferencia kg</th><th className="numeric">Filas observadas</th></>:<th className="numeric">Filas observadas</th>}</tr></thead><tbody>{historyRows.map((r,i)=><tr key={`${r.supplier??r.plant_id??r.customer}-${i}`}><td><b>{r.supplier??r.plant_id??r.customer??'Sin identificar'}</b><small>{sourceRange(r.first_date,r.last_date)}</small></td><td className="numeric">{num(r.lots)}</td><td className="numeric">{num(r.received_kg??r.source_kg,1)}</td>{view!=='customer'?<><td className="numeric">{num(r.difference_kg,1)}</td><td className="numeric">{num(r.flagged_rows)}</td></>:<td className="numeric">{num(r.flagged_rows)}</td>}</tr>)}</tbody></table></div>:<p className="source-note">No hay historia suficiente para esta dimensión.</p>}</section>
  <section className="panel"><div className="section-heading"><div><span className="overline">Operación viva</span><h2>{hasLive?'Rentabilidad trazable':'La rentabilidad viva empieza con los próximos lotes'}</h2></div></div>{hasLive?<><section className="signal-grid"><article className="signal-card"><span><Landmark size={16}/>Ingresos trazados</span><b>{clp(revenue)}</b></article><article className="signal-card"><span>{contribution>=0?<TrendingUp size={16}/>:<TrendingDown size={16}/>}Contribución conocida</span><b>{clp(contribution)}</b></article><article className="signal-card"><span><UsersRound size={16}/>Entidades con operación</span><b>{liveRows.length}</b></article></section><div className="table-scroll"><table className="data-table"><thead><tr><th>Entidad</th><th className="numeric">Ingresos</th>{view!=='customer'?<><th className="numeric">Compra</th><th className="numeric">Transformación</th><th className="numeric">Contribución</th><th className="numeric">%</th></>:<th className="numeric">Kg vendidos</th>}</tr></thead><tbody>{liveRows.map((r,i)=><tr key={r.supplier_id??r.plant_id??r.customer_id??i}><td><b>{r.supplier??r.customer??r.plant_id??'Sin identificar'}</b></td><td className="numeric">{clp(r.revenue_clp)}</td>{view!=='customer'?<><td className="numeric">{clp(r.purchase_cost_clp)}</td><td className="numeric">{clp(r.transformation_cost_clp)}</td><td className="numeric"><b>{clp(r.contribution_clp)}</b></td><td className="numeric">{pct(r.contribution_pct)}</td></>:<td className="numeric">{num(r.sold_kg,1)} kg</td>}</tr>)}</tbody></table></div></>:<div className="empty-state"><TrendingUp size={28}/><h2>No hay que esperar para obtener inteligencia</h2><p>La historia ya permite comparar volumen, diferencias y cobertura. La rentabilidad completa se activa automáticamente cuando los nuevos lotes conecten compra, transformación y venta.</p></div>}</section>
  <section className="panel"><div className="section-heading"><div><span className="overline">Lectura automática</span><h2>Qué mirar ahora</h2></div><Building2 size={18}/></div><div className="compact-ledger"><div className="alert-row static"><span>01</span><div><b>{topHistory?`${view==='supplier'?topHistory.supplier:view==='plant'?topHistory.plant_id:topHistory.customer} concentra el mayor volumen histórico de esta vista`:'Priorizar cobertura histórica'}</b><small>{topHistory?`${num(topHistory.received_kg??topHistory.source_kg,1)} kg en ${num(topHistory.lots)} lotes. Úsalo como referencia operativa, no como margen hasta completar costos y ventas.`:'Faltan registros suficientes para comparar.'}</small></div></div><div className="alert-row static"><span>02</span><div><b>Separar desempeño de rentabilidad</b><small>Volumen, diferencias y calidad histórica sirven desde hoy; margen sólo se muestra cuando compra, proceso y venta están trazados.</small></div></div><div className="alert-row static"><span>03</span><div><b>La nueva operación alimentará la misma vista</b><small>No habrá que mantener dos reportes: historia y operación viva convergen aquí automáticamente.</small></div></div></div></section>
 </>
}