import {Activity,ArrowRight,Database,FlaskConical,PackageCheck,ScanLine} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {PageHeader} from '../components/PageHeader'

type Stage={stage:string;status:string}
type Label={status:string}
type Run={reception_id:string;reception_number:string|number;supplier:string;status:string;grade:string|null;color_status:string;xray_status:string;stages:Stage[];labels:Label[]}
type Candidate={id:string;reception_number:string|number;supplier:string}
type Payload={runs?:Run[];candidates?:Candidate[];error?:string}
type Economics={traceableLots:number;revenueClp:number;contributionClp:number;contributionPct:number|null}
type CalibrationSummary={captures:number;confirmed:number;accepted:number;lots:number;agreement:{matched:number;total:number;ratio:number}|null;references:Array<{plant_id:string;grade:string;count:number|string}>;yield?:{lots:number;inputKg:number;outputKg:number;pct:number|null};economics?:Economics|null}
type GradePerformance={grade:string;lots:number;inputKg:number;outputKg:number;yieldPct:number|null;economics?:Economics|null}
type SupplierPerformance={supplier:string;lots:number;captures:number;confirmed:number;accepted:number;grades:Record<string,number>;yieldLots:number;inputKg:number;outputKg:number;yieldPct:number|null;economics?:Economics|null}
type ProcessCohort={lots:number;avgTemperatureC:number|null;avgDurationSeconds:number|null;yieldPct:number|null}
type ProcessPerformance={stage:string;lots:number;deviations:number;avgTemperatureC:number|null;avgDurationSeconds:number|null;ab:ProcessCohort;other:ProcessCohort}
type CalibrationPayload={summary?:CalibrationSummary;gradePerformance?:GradePerformance[];bySupplier?:SupplierPerformance[];processPerformance?:ProcessPerformance[];error?:string}
type RangeStats={count:number;avg:number|null;min:number|null;max:number|null}
type GradeProfile={grade:string;lots:number;yield:{lots:number;inputKg:number;outputKg:number;pct:number|null;observedRangePct:{min:number;max:number}|null};color:{confirmedCaptures:number;meanLab:{l:number;a:number;b:number}|null;meanDispersion:number|null;meanDeltaE:number|null};stages:Array<{stage:string;lots:number;deviations:number;temperatureC:RangeStats;durationSeconds:RangeStats}>;coverage:{measuredStages:number;totalStages:number};status:'observed'}
type ProfilesPayload={profiles?:GradeProfile[];disclaimer?:string;error?:string}
type ControlAssessment={runId:string;receptionId:string;receptionNumber:string;supplier:string;grade:string;status:string;level:'high'|'watch'|'normal';highSignals:number;watchSignals:number}
type ControlPayload={summary?:{eligibleRuns:number;high:number;watch:number;normal:number};assessments?:ControlAssessment[];policy?:{minimumBaselineLots:number;watchZ:number;highZ:number;automaticAction:boolean};disclaimer?:string;error?:string}
const clp=new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0})
const stageNames:Record<string,string>={blanching:'Escaldado',thermal_shock:'Shock térmico',dripping:'Goteo',draining:'Draining',molding:'Moldeo',freezing:'Congelado'}

export function SeaUrchinFocus(){
 const [params]=useSearchParams(),plantId=params.get('plantId')??''
 const [data,setData]=useState<Payload|null>(null),[calibration,setCalibration]=useState<CalibrationPayload|null>(null),[profiles,setProfiles]=useState<ProfilesPayload|null>(null),[control,setControl]=useState<ControlPayload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[showCalibration,setShowCalibration]=useState(false),[showProfiles,setShowProfiles]=useState(false)
 useEffect(()=>{let active=true;const q=plantId?`?plantId=${encodeURIComponent(plantId)}`:'';Promise.all([fetch(`/api/sea-urchin-process${q}`,{cache:'no-store'}),fetch(`/api/sea-urchin-calibration${q}`,{cache:'no-store'}),fetch(`/api/sea-urchin-grade-profiles${q}`,{cache:'no-store'}),fetch(`/api/sea-urchin-process-control${q}`,{cache:'no-store'})]).then(async([processResponse,calibrationResponse,profilesResponse,controlResponse])=>{const processPayload=await processResponse.json() as Payload,calibrationPayload=await calibrationResponse.json() as CalibrationPayload,profilesPayload=await profilesResponse.json() as ProfilesPayload,controlPayload=await controlResponse.json() as ControlPayload;if(!active)return;if(!processResponse.ok)throw new Error(processPayload.error??'No fue posible cargar proceso de erizo');setData(processPayload);setCalibration(calibrationResponse.ok?calibrationPayload:null);setProfiles(profilesResponse.ok?profilesPayload:null);setControl(controlResponse.ok?controlPayload:null);setError('')}).catch(e=>{if(active)setError(e instanceof Error?e.message:'No fue posible cargar proceso de erizo')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[plantId])
 const runs=data?.runs??[],candidates=data?.candidates??[],summary=calibration?.summary
 const deviations=useMemo(()=>runs.reduce((n,r)=>n+r.stages.filter(s=>['deviation','hold'].includes(s.status)).length+r.labels.filter(l=>['mismatch','blocked'].includes(l.status)).length,0),[runs])
 const active=runs.filter(r=>r.status!=='closed'),ready=runs.filter(r=>r.status==='ready_for_packing')
 const colorAttention=active.filter(r=>['ng','review'].includes(r.color_status)||r.xray_status==='failed'||r.stages.some(s=>s.stage==='color'&&['deviation','hold'].includes(s.status)))
 const priority=colorAttention[0]??active.find(r=>r.stages.some(s=>['deviation','hold'].includes(s.status))||r.labels.some(l=>['mismatch','blocked'].includes(l.status)))??active[0]
 const detailQuery=new URLSearchParams();if(plantId)detailQuery.set('plantId',plantId);if(priority?.reception_id)detailQuery.set('receptionId',priority.reception_id)
 const detail=`/proceso-erizo/detalle${detailQuery.toString()?`?${detailQuery.toString()}`:''}`
 const actionLabel=colorAttention.length?'Revisar Color / Grade':deviations?'Resolver control':active.length?'Continuar proceso':candidates.length?'Iniciar proceso':'Abrir detalle'
 const referenceGrades=plantId?new Set((summary?.references??[]).filter(item=>item.plant_id===plantId).map(item=>item.grade)).size:null
 const yieldPct=summary?.yield?.pct,economics=summary?.economics
 const gradeLeader=useMemo(()=>[...(calibration?.gradePerformance??[])].filter(row=>row.lots>=2&&row.yieldPct!=null).sort((a,b)=>(b.yieldPct??0)-(a.yieldPct??0))[0],[calibration?.gradePerformance])
 const supplierLeader=useMemo(()=>[...(calibration?.bySupplier??[])].map(row=>{const graded=Object.values(row.grades).reduce((sum,value)=>sum+Number(value||0),0),ab=(row.grades.A??0)+(row.grades.B??0);return {...row,abRatio:graded?ab/graded:null,gradedLots:graded}}).filter(row=>row.yieldLots>=2&&row.abRatio!=null).sort((a,b)=>(b.abRatio??0)-(a.abRatio??0)||(b.yieldPct??0)-(a.yieldPct??0))[0],[calibration?.bySupplier])
 const processSignal=useMemo(()=>[...(calibration?.processPerformance??[])].filter(row=>row.ab.lots>=2&&row.other.lots>=2&&(row.ab.avgTemperatureC!=null&&row.other.avgTemperatureC!=null||row.ab.avgDurationSeconds!=null&&row.other.avgDurationSeconds!=null)).sort((a,b)=>b.lots-a.lots)[0],[calibration?.processPerformance])
 const processText=processSignal?(()=>{const name=stageNames[processSignal.stage]??processSignal.stage,temp=processSignal.ab.avgTemperatureC!=null&&processSignal.other.avgTemperatureC!=null?` temperatura media A/B ${processSignal.ab.avgTemperatureC.toLocaleString('es-CL',{maximumFractionDigits:1})} °C vs ${processSignal.other.avgTemperatureC.toLocaleString('es-CL',{maximumFractionDigits:1})} °C`:null,duration=processSignal.ab.avgDurationSeconds!=null&&processSignal.other.avgDurationSeconds!=null?` duración media A/B ${Math.round(processSignal.ab.avgDurationSeconds)} s vs ${Math.round(processSignal.other.avgDurationSeconds)} s`:null,metric=temp??duration;return metric?` Señal de proceso: ${name},${metric}; ${processSignal.ab.lots} lotes A/B vs ${processSignal.other.lots} otros. Asociación observada, no causal.`:''})():''
 const usableProfiles=useMemo(()=>[...(profiles?.profiles??[])].filter(profile=>profile.lots>0),[profiles?.profiles])
 const controlPriority=useMemo(()=>[...(control?.assessments??[])].filter(item=>item.level!=='normal').sort((a,b)=>(a.level==='high'?0:1)-(b.level==='high'?0:1))[0],[control?.assessments])
 const controlDetail=controlPriority?(()=>{const query=new URLSearchParams();if(plantId)query.set('plantId',plantId);query.set('receptionId',controlPriority.receptionId);return `/proceso-erizo/detalle?${query.toString()}`})():detail
 return <>
  <PageHeader eyebrow="Proceso específico" title="Erizo" description="Estado, prioridad y siguiente acción. Color y Grade usan medición objetiva con confirmación humana."/>
  {error?<div className="system-banner error" role="alert">{error}</div>:null}{loading?<div className="system-banner">Actualizando proceso de erizo…</div>:null}
  {!loading&&!error?<>
   <section className={`daily-cockpit ${colorAttention.length||deviations?'has-attention':'is-clear'}`}><div className="daily-cockpit-copy"><span className="overline">Estado</span><h2>{colorAttention.length?`${colorAttention.length} lote${colorAttention.length===1?'':'s'} con color por revisar`:deviations?`${deviations} control${deviations===1?'':'es'} por revisar`:active.length?'Proceso en curso':'Sin proceso activo'}</h2><p>{colorAttention.length&&priority?`REC-${priority.reception_number} · ${priority.supplier} requiere revisión objetiva de color/Grade o rayos X antes de liberación.`:deviations&&priority?`REC-${priority.reception_number} · ${priority.supplier} tiene una desviación o bloqueo que debe resolverse antes de packing.`:active.length&&priority?`REC-${priority.reception_number} · ${priority.supplier} es el siguiente proceso activo.`:candidates.length?`${candidates.length} recepción${candidates.length===1?'':'es'} disponible${candidates.length===1?'':'s'} para iniciar.`:'No hay recepciones de erizo pendientes dentro del alcance.'}</p><div className="daily-cockpit-actions"><Link className="button primary" to={detail}>{actionLabel}<ArrowRight size={15}/></Link></div></div><div className="daily-status-mark" aria-hidden="true"><span>{colorAttention.length||deviations||'✓'}</span><small>{colorAttention.length?'color':deviations?'revisar':'sin alertas'}</small></div></section>
   <section className="signal-grid"><article className="signal-card"><span><FlaskConical size={16}/>Activos</span><b>{active.length}</b><small>procesos</small></article><article className="signal-card"><span><ScanLine size={16}/>Color / Grade</span><b>{colorAttention.length}</b><small>requieren revisión</small></article><article className="signal-card"><span><PackageCheck size={16}/>Packing</span><b>{ready.length}</b><small>listos</small></article></section>
   <div className="notice"><ScanLine size={16}/><div><b>Clasificación explicable</b><small>La estación conserva evidencia, CIELAB, dispersión y ΔE contra referencias reales de planta; Calidad confirma el resultado antes de liberar.</small></div></div>
   {controlPriority?<div className="notice"><Activity size={16}/><div><b>Control estadístico · {controlPriority.level==='high'?'desviación fuerte':'revisión recomendada'}</b><small>REC-{controlPriority.receptionNumber} · Grade {controlPriority.grade} · {controlPriority.highSignals} señal{controlPriority.highSignals===1?'':'es'} fuerte{controlPriority.highSignals===1?'':'s'} y {controlPriority.watchSignals} en observación. Baseline mínimo: {control?.policy?.minimumBaselineLots??5} lotes comparables. No bloquea ni modifica el proceso automáticamente. <Link className="source-link" to={controlDetail}>Revisar lote</Link></small></div></div>:null}
   {summary?<><button type="button" className="text-action inline-link" onClick={()=>setShowCalibration(value=>!value)}><Database size={14}/>{showCalibration?'Ocultar calibración':`Calibración · ${summary.confirmed} confirmadas`}</button>{showCalibration?<div className="notice"><Database size={16}/><div><b>Dataset Pescamar · {summary.lots} lotes</b><small>{summary.agreement?`Acuerdo operador ↔ sistema ${Math.round(summary.agreement.ratio*100)}% · ${summary.agreement.matched}/${summary.agreement.total} comparables.`:'Aún sin capturas comparables.'}{referenceGrades!=null?` Referencias de esta planta: ${referenceGrades}/5 grades.`:` ${summary.references.length} referencias activas.`}{summary.yield?.lots?` Rendimiento observado: ${yieldPct==null?'—':`${yieldPct.toLocaleString('es-CL',{maximumFractionDigits:1})}%`} en ${summary.yield.lots} lote${summary.yield.lots===1?'':'s'}, calculado una sola vez por lote.`:''}{economics?economics.traceableLots?` Economía trazada: ${economics.traceableLots} lote${economics.traceableLots===1?'':'s'}; contribución observada ${clp.format(economics.contributionClp)} sobre ${clp.format(economics.revenueClp)} de ingresos trazados.`:' Economía: todavía no hay lotes con compra + transformación + venta completas; no se calcula contribución.':''}{gradeLeader?` Señal por Grade: ${gradeLeader.grade} muestra ${gradeLeader.yieldPct?.toLocaleString('es-CL',{maximumFractionDigits:1})}% de rendimiento en ${gradeLeader.lots} lotes; es evidencia observada, no estándar.`:''}{supplierLeader?` Señal por proveedor: ${supplierLeader.supplier} tiene ${Math.round((supplierLeader.abRatio??0)*100)}% A/B en ${supplierLeader.gradedLots} lotes clasificados y ${supplierLeader.yieldPct?.toLocaleString('es-CL',{maximumFractionDigits:1})}% de rendimiento en ${supplierLeader.yieldLots} lotes.`:''}{processText} Sin umbral canónico automático todavía.</small></div></div>:null}</>:null}
   {usableProfiles.length?<><button type="button" className="text-action inline-link" onClick={()=>setShowProfiles(value=>!value)}><FlaskConical size={14}/>{showProfiles?'Ocultar firmas por Grade':'Firmas observadas por Grade'}</button>{showProfiles?<section className="signal-grid">{usableProfiles.map(profile=>{const bestStage=profile.stages.filter(stage=>stage.temperatureC.count||stage.durationSeconds.count).sort((a,b)=>b.lots-a.lots)[0];return <article className="signal-card" key={profile.grade}><span>Grade {profile.grade}</span><b>{profile.yield.pct==null?'—':`${profile.yield.pct.toLocaleString('es-CL',{maximumFractionDigits:1})}%`}</b><small>{profile.lots} lote{profile.lots===1?'':'s'} · color {profile.color.confirmedCaptures} captura{profile.color.confirmedCaptures===1?'':'s'} · cobertura {profile.coverage.measuredStages}/{profile.coverage.totalStages}{bestStage?.temperatureC.avg!=null?` · ${stageNames[bestStage.stage]??bestStage.stage} ${bestStage.temperatureC.avg.toLocaleString('es-CL',{maximumFractionDigits:1})} °C`:bestStage?.durationSeconds.avg!=null?` · ${stageNames[bestStage.stage]??bestStage.stage} ${Math.round(bestStage.durationSeconds.avg)} s`:''}</small></article>})}</section>:null}<div className="notice"><FlaskConical size={16}/><div><b>Firma operacional observada, no receta</b><small>Los rangos por Grade resumen temperatura, duración, color, homogeneidad y rendimiento ya medidos. No se usan todavía como límites automáticos ni para modificar el proceso.</small></div></div></>:null}
   <nav className="daily-footer-actions"><Link className="text-action inline-link" to={detail}>Ver proceso completo<ArrowRight size={14}/></Link></nav>
  </>:null}
 </>
}
