import {ArrowRight,CheckCircle2,Database,Target} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {PageHeader} from '../components/PageHeader'

type Summary={captures:number;confirmed:number;accepted:number;lots:number;agreement:{matched:number;total:number;ratio:number}|null;references:Array<{plant_id:string;grade:string;count:number|string}>}
type GradeRow={grade:string;captures:number;confirmed:number;accepted:number;meanLab:{l:number;a:number;b:number}|null;meanDispersion:number|null;meanDeltaE:number|null}
type SupplierRow={supplier:string;lots:number;captures:number;confirmed:number;accepted:number;grades:Record<string,number>}
type Payload={scope?:{plantId:string|null};summary?:Summary;byGrade?:GradeRow[];bySupplier?:SupplierRow[];error?:string}
const nf=new Intl.NumberFormat('es-CL',{maximumFractionDigits:2})

export function SeaUrchinCalibration(){
 const [params]=useSearchParams(),plantId=params.get('plantId')??''
 const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[expanded,setExpanded]=useState(false)
 useEffect(()=>{let active=true;const q=plantId?`?plantId=${encodeURIComponent(plantId)}`:'';fetch(`/api/sea-urchin-calibration${q}`,{cache:'no-store'}).then(async response=>({response,payload:await response.json() as Payload})).then(({response,payload})=>{if(!active)return;if(!response.ok)throw new Error(payload.error??'No fue posible cargar calibración');setData(payload);setError('')}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'No fue posible cargar calibración')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[plantId])
 const summary=data?.summary,grades=data?.byGrade??[],suppliers=data?.bySupplier??[]
 const referencedGrades=useMemo(()=>new Set((summary?.references??[]).filter(reference=>!plantId||reference.plant_id===plantId).map(reference=>reference.grade)),[summary?.references,plantId])
 const agreement=summary?.agreement?.ratio
 const detail=`/proceso-erizo/detalle${plantId?`?plantId=${encodeURIComponent(plantId)}`:''}`
 return <>
  <PageHeader eyebrow="Erizo · Inteligencia de calidad" title="Calibración Color / Grade" description="Construye evidencia Pescamar antes de fijar umbrales de clasificación."/>
  {error?<div className="system-banner error" role="alert">{error}</div>:null}{loading?<div className="system-banner">Construyendo dataset de calibración…</div>:null}
  {!loading&&!error&&summary?<>
   <section className={`daily-cockpit ${summary.confirmed?'is-clear':'has-attention'}`}><div className="daily-cockpit-copy"><span className="overline">Estado</span><h2>{summary.confirmed?`${summary.confirmed} captura${summary.confirmed===1?'':'s'} confirmada${summary.confirmed===1?'':'s'} por Calidad`:'Dataset aún sin confirmaciones'}</h2><p>{summary.confirmed?'Ya existe evidencia humana utilizable para comparar color, homogeneidad y Grade. Aún no hay un umbral canónico automático.':'La siguiente acción es capturar muestras controladas y hacer que Calidad confirme el Grade real.'}</p><div className="daily-cockpit-actions"><Link className="button primary" to={detail}>{summary.confirmed?'Seguir calibrando':'Capturar primera muestra'}<ArrowRight size={15}/></Link></div></div><div className="daily-status-mark" aria-hidden="true"><span>{summary.confirmed||'0'}</span><small>confirmadas</small></div></section>
   <section className="signal-grid"><article className="signal-card"><span><Database size={16}/>Lotes</span><b>{summary.lots}</b><small>con evidencia de color</small></article><article className="signal-card"><span><CheckCircle2 size={16}/>Acuerdo</span><b>{agreement==null?'—':`${Math.round(agreement*100)}%`}</b><small>{summary.agreement?`${summary.agreement.matched}/${summary.agreement.total} comparables`:'sin muestra comparable'}</small></article><article className="signal-card"><span><Target size={16}/>Referencias</span><b>{plantId?`${referencedGrades.size}/5`:summary.references.length}</b><small>{plantId?'Grades A–E con referencia':'referencias activas'}</small></article></section>
   <div className="notice"><Target size={16}/><div><b>Sin umbral canónico todavía</b><small>CIELAB, ΔE, dispersión y acuerdo humano/sistema son evidencia de calibración. La liberación sigue requiriendo confirmación de Calidad hasta que Pescamar valide sus propias referencias y límites.</small></div></div>
   <nav className="daily-footer-actions"><button type="button" className="text-action inline-link" onClick={()=>setExpanded(value=>!value)}>{expanded?'Ocultar detalle':'Leer más'}<ArrowRight size={14}/></button></nav>
   {expanded?<><section className="panel"><div className="section-heading"><div><span className="overline">Evidencia por Grade</span><h2>A–E observados</h2></div></div><div className="compact-ledger">{grades.map(row=><div key={row.grade} className="alert-row static"><span><Target size={15}/></span><div><b>Grade {row.grade} · {row.confirmed} confirmadas</b><small>{row.meanLab?`LAB ${nf.format(row.meanLab.l)} / ${nf.format(row.meanLab.a)} / ${nf.format(row.meanLab.b)}`:'Sin media LAB confirmable'}{row.meanDispersion!=null?` · dispersión ${nf.format(row.meanDispersion)}`:''}{row.meanDeltaE!=null?` · ΔE ${nf.format(row.meanDeltaE)}`:''}</small></div><span className="status info">{row.captures} capturas</span></div>)}</div></section><section className="panel"><div className="section-heading"><div><span className="overline">Materia prima</span><h2>Proveedores con evidencia</h2></div></div><div className="compact-ledger">{suppliers.map(row=><div key={row.supplier} className="alert-row static"><span><Database size={15}/></span><div><b>{row.supplier}</b><small>{row.lots} lotes · {row.confirmed} confirmadas · A {row.grades.A??0} · B {row.grades.B??0} · C {row.grades.C??0} · D {row.grades.D??0} · E {row.grades.E??0}</small></div><span className="status info">{row.accepted} aceptadas</span></div>)}{!suppliers.length?<div className="empty-inline"><Database size={18}/><div><b>Sin proveedores comparables todavía</b><small>La vista se completará a medida que Calidad confirme capturas reales.</small></div></div>:null}</div></section></>:null}
  </>:null}
 </>
}
