import {Activity,AlertTriangle,Boxes,CheckCheck,DollarSign,Factory,FileCheck2,Landmark,LoaderCircle,Plus,ReceiptText,Scale,Truck,X} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import type {ReceptionEvidence} from '../types'
import './live-lot-drawer.css'

type LotEvent={id:string;event_type:'quality'|'production'|'note';title:string;detail:string|null;metrics:Record<string,unknown>;created_by:string;occurred_at:string}
type Approval={id:string;entity_type:string;action:string;comment:string|null;acted_by:string;acted_at:string}
type Settlement={id:string;gross_amount_clp:string|number;net_amount_clp:string|number|null;status:string;price_per_kg_clp:string|number;credit_recovery_clp:string|number}
type Reception={id:string;reception_number:string|number;plant_id:string;species:string;extraction_zone:string;source_reference:string|null;guide_kg:string|number;gross_kg:string|number;tare_kg:string|number;drained_kg:string|number|null;accepted_kg:string|number|null;temperature_c:string|number|null;quality_status:string;status:string;source:string;received_at:string;supplier:string;evidence:ReceptionEvidence[]}
type ProductionLine={id:string;name:string;family:string;destination:string}
type Dispatch={id:string;dispatch_number:string|number;destination:string;dispatched_kg:string|number;document_ref:string|null;status:string;dispatched_at:string;created_by:string;customer:string|null}
type Sale={id:string;sold_kg:string|number;price_per_kg_clp:string|number;invoice_ref:string|null;status:string;sold_at:string;created_by:string;customer:string}
type Commercial={physicalKg:number;dispatchedKg:number;availableKg:number;soldKg:number;revenueClp:number;allocatedCostClp:number|null;marginClp:number|null;marginPct:number|null}
type Payload={reception?:Reception;events?:LotEvent[];approvals?:Approval[];settlement?:Settlement|null;productionLines?:ProductionLine[];dispatches?:Dispatch[];sales?:Sale[];commercial?:Commercial;permissions?:{canAddQuality:boolean;canAddProduction:boolean;canAddNote:boolean};error?:string}
type Kind='quality'|'production'|'note'
type QualityChoice='Clasificado'|'Revisión'|'Alerta calibre'

const kg=(v:string|number|null|undefined)=>v==null?'—':`${Number(v).toLocaleString('es-CL',{maximumFractionDigits:1})} kg`
const clp=(v:string|number|null|undefined)=>v==null?'—':new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(v))
const dt=(v:string)=>new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))
async function fetchLot(id:string){const response=await fetch(`/api/lot-360?receptionId=${encodeURIComponent(id)}`);const payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error??'No fue posible cargar la ficha');return payload}
function metricSummary(event:LotEvent){const m=event.metrics??{};if(event.event_type==='quality'){return [m.qualityStatus?String(m.qualityStatus):null,m.defectPct!=null?`${Number(m.defectPct).toFixed(1)}% defectos`:null,m.sampleCount!=null?`${Number(m.sampleCount)} muestras`:null].filter(Boolean).join(' · ')}if(event.event_type==='production'){return [m.lineName?String(m.lineName):null,m.stage?String(m.stage):null,m.outputKg!=null?`${Number(m.outputKg).toLocaleString('es-CL')} kg salida`:null,m.yieldPct!=null?`${Number(m.yieldPct).toFixed(1)}% rendimiento`:null].filter(Boolean).join(' · ')}return ''}

export function LiveLotDrawer({receptionId,onClose}:{receptionId:string|null;onClose:()=>void}){
  const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false)
  const [kind,setKind]=useState<Kind>('quality'),[qualityChoice,setQualityChoice]=useState<QualityChoice>('Clasificado'),[detail,setDetail]=useState('')
  const [temperature,setTemperature]=useState(''),[acceptedKg,setAcceptedKg]=useState(''),[defectPct,setDefectPct]=useState(''),[sampleCount,setSampleCount]=useState('')
  const [lineId,setLineId]=useState(''),[stage,setStage]=useState(''),[inputKg,setInputKg]=useState(''),[outputKg,setOutputKg]=useState(''),[noteTitle,setNoteTitle]=useState('')
  function applyPayload(payload:Payload){setData(payload);if(payload.reception){setTemperature(payload.reception.temperature_c==null?'':String(payload.reception.temperature_c));setAcceptedKg(payload.reception.accepted_kg==null?'':String(payload.reception.accepted_kg));if(payload.reception.quality_status==='Revisión'||payload.reception.quality_status==='Alerta calibre')setQualityChoice(payload.reception.quality_status)}if(payload.productionLines?.length)setLineId(current=>current||payload.productionLines?.[0]?.id||'')}
  useEffect(()=>{if(!receptionId)return;let active=true;setLoading(true);void fetchLot(receptionId).then(payload=>{if(active){applyPayload(payload);setError('')}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'No fue posible cargar la ficha')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[receptionId])
  const r=data?.reception,p=data?.permissions
  const canAdd=kind==='quality'?p?.canAddQuality:kind==='production'?p?.canAddProduction:p?.canAddNote
  const productionReady=r?.quality_status==='Clasificado'
  const nextLabel=productionReady?'Listo para Producción':r?.quality_status==='Revisión'||r?.quality_status==='Alerta calibre'?'Requiere criterio':'Pendiente de Calidad'
  const metrics=useMemo(()=>kind==='quality'?{qualityStatus:qualityChoice,temperatureC:temperature===''?null:Number(temperature),acceptedKg:acceptedKg===''?null:Number(acceptedKg),defectPct:defectPct===''?null:Number(defectPct),sampleCount:sampleCount===''?null:Number(sampleCount)}:kind==='production'?{lineId,stage,inputKg:Number(inputKg),outputKg:Number(outputKg)}:{},[kind,qualityChoice,temperature,acceptedKg,defectPct,sampleCount,lineId,stage,inputKg,outputKg])
  if(!receptionId)return null
  const activeId=receptionId
  async function reload(){setLoading(true);try{applyPayload(await fetchLot(activeId));setError('')}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible cargar la ficha')}finally{setLoading(false)}}
  async function save(){if(!canAdd)return;const title=kind==='note'?noteTitle.trim():'';if(kind==='note'&&!title)return;setSaving(true);setError('');try{const response=await fetch('/api/lot-360',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({receptionId:activeId,eventType:kind,title,detail,metrics})});const payload=await response.json() as {error?:string;next?:string};if(!response.ok)throw new Error(payload.error??'No fue posible registrar el evento');setDetail('');setDefectPct('');setSampleCount('');setStage('');setInputKg('');setOutputKg('');setNoteTitle('');if(kind==='quality'&&qualityChoice==='Clasificado'&&p?.canAddProduction)setKind('production');await reload()}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible registrar el evento')}finally{setSaving(false)}}
  return <div className="lot-drawer-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><aside className="lot-drawer live-lot" role="dialog" aria-modal="true">
    <header className="lot-drawer-header"><div><span className="overline teal">Ficha 360 · operación viva</span><h2>{r?`REC-${r.reception_number}`:'Cargando lote…'}</h2><p>{r?`${r.supplier} · ${r.species} · ${r.extraction_zone}`:'Memoria operacional del lote'}</p></div><button className="icon-button" onClick={onClose} aria-label="Cerrar ficha"><X size={20}/></button></header>
    {loading&&!data?<div className="live-loading"><LoaderCircle className="spin"/>Cargando memoria…</div>:null}{error?<div className="notice error"><AlertTriangle size={16}/>{error}</div>:null}
    {r?<>
      <section className="lot-facts"><div><small>Planta</small><b>{r.plant_id}</b></div><div><small>Guía</small><b>{r.source_reference??'—'}</b></div><div><small>Recepción</small><b>{dt(r.received_at)}</b></div><div><small>Kg guía</small><b>{kg(r.guide_kg)}</b></div><div><small>Kg aceptados</small><b>{kg(r.accepted_kg)}</b></div><div><small>Siguiente</small><b>{nextLabel}</b></div></section>
      <section className="lot-section"><div className="lot-section-title"><Activity size={18}/><h3>Qué sigue</h3></div><div className="live-event-form simple-flow"><div className="event-kind-tabs">{p?.canAddQuality?<button className={kind==='quality'?'active':''} onClick={()=>setKind('quality')}>Calidad</button>:null}{p?.canAddProduction?<button className={kind==='production'?'active':''} onClick={()=>setKind('production')}>Producción</button>:null}{p?.canAddNote?<button className={kind==='note'?'active':''} onClick={()=>setKind('note')}>Nota</button>:null}</div>
        {kind==='quality'?<><div className="quality-choice-row"><button type="button" className={`button ${qualityChoice==='Clasificado'?'primary':'secondary'}`} onClick={()=>setQualityChoice('Clasificado')}><CheckCheck size={15}/>Aprobar</button><button type="button" className={`button ${qualityChoice==='Revisión'?'primary':'secondary'}`} onClick={()=>setQualityChoice('Revisión')}><AlertTriangle size={15}/>Revisar</button><button type="button" className={`button ${qualityChoice==='Alerta calibre'?'primary':'secondary'}`} onClick={()=>setQualityChoice('Alerta calibre')}><AlertTriangle size={15}/>Alerta</button></div><p className="source-note">Una decisión. El resto es opcional.</p><details className="advanced-details"><summary>Agregar detalle</summary><div className="event-metric-grid"><label>Temperatura °C<input type="number" step="0.1" value={temperature} onChange={e=>setTemperature(e.target.value)}/></label><label>Kg aceptados<input type="number" step="0.1" min="0" value={acceptedKg} onChange={e=>setAcceptedKg(e.target.value)}/></label><label>Defectos %<input type="number" step="0.1" min="0" max="100" value={defectPct} onChange={e=>setDefectPct(e.target.value)}/></label><label>Muestras<input type="number" step="1" min="0" value={sampleCount} onChange={e=>setSampleCount(e.target.value)}/></label></div><textarea placeholder="Observación opcional" value={detail} onChange={e=>setDetail(e.target.value)} rows={2}/></details><button className="button primary" onClick={()=>void save()} disabled={saving||!canAdd}><CheckCheck size={15}/>{saving?'Guardando…':qualityChoice==='Clasificado'?'Aprobar y continuar':'Guardar decisión'}</button></>:null}
        {kind==='production'?<><div className="event-metric-grid"><label>Línea<select value={lineId} onChange={e=>setLineId(e.target.value)}>{data?.productionLines?.map(line=><option key={line.id} value={line.id}>{line.name}</option>)}</select></label><label>Kg entrada<input type="number" step="0.1" min="0" value={inputKg} onChange={e=>setInputKg(e.target.value)}/></label><label>Kg salida<input type="number" step="0.1" min="0" value={outputKg} onChange={e=>setOutputKg(e.target.value)}/></label></div><details className="advanced-details"><summary>Agregar detalle</summary><input value={stage} onChange={e=>setStage(e.target.value)} placeholder="Etapa opcional"/><textarea placeholder="Observación opcional" value={detail} onChange={e=>setDetail(e.target.value)} rows={2}/></details><button className="button primary" onClick={()=>void save()} disabled={saving||!canAdd||!lineId||!inputKg}><Factory size={15}/>{saving?'Guardando…':'Registrar producción'}</button></>:null}
        {kind==='note'?<><input placeholder="Título breve" value={noteTitle} onChange={e=>setNoteTitle(e.target.value)}/><textarea placeholder="Nota operacional" value={detail} onChange={e=>setDetail(e.target.value)} rows={3}/><button className="button primary" onClick={()=>void save()} disabled={saving||!canAdd||!noteTitle.trim()}><Plus size={15}/>{saving?'Guardando…':'Agregar nota'}</button></>:null}
      </div></section>
      <section className="lot-section"><div className="lot-section-title"><FileCheck2 size={18}/><h3>Evidencia</h3></div><div className="live-evidence">{r.evidence?.length?r.evidence.map((e,i)=><a key={e.id??i} href={e.url} target="_blank" rel="noreferrer"><FileCheck2 size={14}/><span>{e.label}</span></a>):<span>Sin evidencia adjunta</span>}</div></section>
      <section className="lot-section"><div className="lot-section-title"><Boxes size={18}/><h3>Memoria</h3></div><div className="live-event-list">{data?.events?.length?data.events.map(event=>{const summary=metricSummary(event);return <article key={event.id}><span className={`event-type ${event.event_type}`}>{event.event_type==='quality'?<CheckCheck size={14}/>:event.event_type==='production'?<Factory size={14}/>:<Boxes size={14}/>}</span><div><b>{event.title}</b>{summary?<small className="event-metrics">{summary}</small>:null}{event.detail?<p>{event.detail}</p>:null}<small>{dt(event.occurred_at)} · {event.created_by}</small></div></article>}):<p className="source-note">La recepción es el primer evento. Lo siguiente se agrega aquí.</p>}</div></section>
      {data?.approvals?.length?<section className="lot-section"><div className="lot-section-title"><CheckCheck size={18}/><h3>Decisiones</h3></div><div className="live-event-list">{data.approvals.map(a=><article key={a.id}><span className="event-type decision"><CheckCheck size={14}/></span><div><b>{a.action}</b>{a.comment?<p>{a.comment}</p>:null}<small>{dt(a.acted_at)} · {a.acted_by}</small></div></article>)}</div></section>:null}
      {data?.settlement?<section className="lot-section"><div className="lot-section-title"><ReceiptText size={18}/><h3>Liquidación</h3></div><div className="financial-grid"><div><small>Bruto</small><b>{clp(data.settlement.gross_amount_clp)}</b></div><div><small>Recuperación crédito</small><b>{clp(data.settlement.credit_recovery_clp)}</b></div><div><small>Neto</small><b>{clp(data.settlement.net_amount_clp)}</b></div><div><small>Precio/kg</small><b>{clp(data.settlement.price_per_kg_clp)}</b></div></div></section>:null}
      {(data?.dispatches?.length||data?.sales?.length||data?.commercial?.revenueClp)?<section className="lot-section"><div className="lot-section-title"><Truck size={18}/><h3>Salida y resultado</h3></div>{data?.commercial?<div className="financial-grid"><div><small>Disponible</small><b>{kg(data.commercial.availableKg)}</b></div><div><small>Despachado</small><b>{kg(data.commercial.dispatchedKg)}</b></div><div><small>Vendido</small><b>{kg(data.commercial.soldKg)}</b></div><div><small>Ventas</small><b>{clp(data.commercial.revenueClp)}</b></div></div>:null}<div className="live-event-list commercial-memory">{data?.dispatches?.filter(d=>d.status==='confirmed').map(d=><article key={d.id}><span className="event-type production"><Truck size={14}/></span><div><b>Despacho #{d.dispatch_number} · {kg(d.dispatched_kg)}</b><p>{d.destination}{d.customer?` · ${d.customer}`:''}</p><small>{dt(d.dispatched_at)} · {d.created_by}</small></div></article>)}{data?.sales?.filter(s=>s.status==='confirmed').map(s=><article key={s.id}><span className="event-type decision"><DollarSign size={14}/></span><div><b>Venta · {s.customer} · {kg(s.sold_kg)}</b><p>{clp(Number(s.sold_kg)*Number(s.price_per_kg_clp))}</p><small>{dt(s.sold_at)} · {s.created_by}</small></div></article>)}</div></section>:null}
      <section className="lot-section"><div className="lot-section-title"><Scale size={18}/><h3>Balance</h3></div><div className="lot-kpis"><div><small>Bruto</small><b>{kg(r.gross_kg)}</b></div><div><small>Tara</small><b>{kg(r.tare_kg)}</b></div><div><small>Escurrido</small><b>{kg(r.drained_kg)}</b></div><div><small>Aceptado</small><b>{kg(r.accepted_kg)}</b></div></div></section>
      {!data?.settlement?<p className="source-note"><Landmark size={14}/> La liquidación aparecerá cuando exista un hecho financiero real.</p>:null}
    </>:null}
  </aside></div>
}
