import { Building2, ChevronRight, FileCheck2, Thermometer } from 'lucide-react'
import { plants } from '../plants'
import type { Lot } from '../types'

const statusClass:Record<Lot['status'],string>={Clasificado:'success',Muestreo:'info',Revisión:'warning','Alerta calibre':'danger'}
const plantNames=new Map(plants.map(plant=>[plant.id,plant.name.replace('Planta ','')]))

export function LotTable({ lots, compact=false, onOpen }:{lots:Lot[];compact?:boolean;onOpen?:(lot:Lot)=>void}) {
  const shown=compact?lots.slice(0,5):lots
  return <div className="table-scroll"><table className="data-table"><thead><tr><th>Lote / hora</th><th>Proveedor</th><th>Planta / origen</th><th>Guía / folio</th><th className="numeric">Bruto</th><th className="numeric">Neto aceptado</th><th className="numeric">Dif. guía</th><th className="numeric">Merma</th>{compact?null:<th className="numeric">T°</th>}<th>Estado</th><th>Evidencia</th>{onOpen?<th></th>:null}</tr></thead><tbody>{shown.map(lot=><tr key={lot.id} onDoubleClick={()=>onOpen?.(lot)}><td>{onOpen?<button className="lot-code-button" onClick={()=>onOpen(lot)}>{lot.id}</button>:<b>{lot.id}</b>}<small>{lot.receivedAt}</small></td><td><div className="supplier"><span>{lot.initials}</span><b>{lot.supplier}</b></div></td><td><div className="lot-origin"><b><Building2 size={12}/>{plantNames.get(lot.plantId)??lot.plantId}</b><small>{lot.zone}</small></div></td><td><b>{lot.guide.toFixed(1)} kg</b><small>{lot.guideReference||'Sin folio'}</small></td><td className="numeric">{lot.gross.toFixed(1)} kg</td><td className="numeric"><b>{lot.accepted.toFixed(1)} kg</b></td><td className={`numeric ${lot.accepted<lot.guide?'negative':''}`}>{(lot.accepted-lot.guide).toFixed(1)} kg</td><td className={`numeric ${lot.loss>18?'negative':''}`}>{lot.loss.toFixed(1)}%</td>{compact?null:<td className="numeric"><span className="temperature"><Thermometer size={13}/>{lot.temperature.toFixed(1)}°</span></td>}<td><span className={`status ${statusClass[lot.status]}`}>{lot.status}</span></td><td>{lot.evidence.length?<div className="lot-evidence-links">{lot.evidence.slice(0,compact?1:2).map((item,index)=><a href={item.url} target="_blank" rel="noreferrer" key={`${item.url}-${index}`} title={item.label}><FileCheck2 size={13}/>{compact?lot.evidence.length:item.label}</a>)}{!compact&&lot.evidence.length>2?<small>+{lot.evidence.length-2}</small>:null}</div>:<span className="evidence-none">Sin respaldo</span>}</td>{onOpen?<td><button className="icon-button" onClick={()=>onOpen(lot)} aria-label={`Abrir ficha ${lot.id}`}><ChevronRight size={17}/></button></td>:null}</tr>)}</tbody></table></div>
}
