import {Activity,Boxes,CheckCircle2,Clock3,Factory,Printer,ShieldCheck} from 'lucide-react'
import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {plants as configuredPlants} from '../plants'
import '../readiness.css'

type Check={key:string;label:string;complete:boolean;detail:string}
type Plant={plantId:string;score:number;completed:number;total:number;hasPhysicalUatEvidence:boolean;checks:Check[];metrics:{stations:number;devices:number;printers:number;packingUnits:number;labelTemplates:number;printedLabelJobs:number;closedPallets:number;linkedColdAssets:number;coldRunsWithEvidence:number;resolvedHolds:number}}
type Payload={ok?:boolean;plants?:Plant[];rule?:string;error?:string}
const name=(id:string)=>configuredPlants.find(plant=>plant.id===id)?.name??id
const actionByCheck:Record<string,{to:string;label:string}>={station:{to:'/estaciones',label:'Configurar'},devices:{to:'/estaciones',label:'Registrar hardware'},packing:{to:'/floor',label:'Ir a piso'},label:{to:'/impresion-etiquetas',label:'Preparar impresión'},pallet:{to:'/pallets',label:'Operar pallets'},cold:{to:'/frio',label:'Operar frío'},regulatory:{to:'/control-regulatorio',label:'Ejercitar hold'}}

export function PlantExecutionReadiness(){const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let active=true;void fetch('/api/plant-execution-readiness',{cache:'no-store'}).then(async response=>{const payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error??'No fue posible calcular Plant Execution');if(active)setData(payload)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'No fue posible calcular Plant Execution')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);const plants=data?.plants??[];return <section className="panel"><div className="section-heading"><div><span className="overline">Evidencia física</span><h2>Plant Execution readiness</h2></div><Link className="button compact" to="/estaciones">Configurar estaciones</Link></div><div className="governance-note"><ShieldCheck size={19}/><div><b>Señal separada del gate LIVE</b><p>{data?.rule??'Mide configuración y evidencia física sin declarar aceptación humana.'}</p></div></div>{loading?<div className="system-banner">Calculando evidencia Plant Execution…</div>:null}{error?<div className="system-banner error">{error}</div>:null}<div className="plant-grid rollout-grid">{plants.map(plant=><article className="panel plant-card" key={plant.plantId}><header><div><span className="overline">{name(plant.plantId)}</span><h3>{plant.score}%</h3><small>{plant.completed}/{plant.total} señales observadas</small></div><span className={`status ${plant.hasPhysicalUatEvidence?'success':'info'}`}>{plant.hasPhysicalUatEvidence?'evidencia completa':'pendiente'}</span></header><div className="rollout-mini-checks">{plant.checks.map(check=>{const action=actionByCheck[check.key];return <div key={check.key} className={`readiness-check ${check.complete?'complete':''}`} title={check.detail}><span>{check.complete?<CheckCircle2 size={12}/>:<Clock3 size={12}/>} {check.label}</span>{!check.complete&&action?<Link to={action.to} aria-label={`${action.label}: ${check.label}`}>{action.label}</Link>:null}</div>})}</div><footer><span><Factory size={13}/>{plant.metrics.stations} estaciones · {plant.metrics.devices} dispositivos</span><span><Boxes size={13}/>{plant.metrics.packingUnits} cajas · {plant.metrics.closedPallets} pallets</span></footer><small><Printer size={12}/> {plant.metrics.labelTemplates} plantillas · {plant.metrics.printers} impresoras · {plant.metrics.printedLabelJobs} impresiones confirmadas</small>{plant.metrics.coldRunsWithEvidence||plant.metrics.resolvedHolds?<small><Activity size={12}/> {plant.metrics.coldRunsWithEvidence} ciclos de frío con evidencia · {plant.metrics.resolvedHolds} holds resueltos</small>:null}</article>)}</div></section>}
