import {CheckCircle2,Clock3,ShieldCheck} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'

type Check={key:string;label:string;complete:boolean;detail:string}
type Readiness={plantId:string;score:number;completed:number;total:number;latestActivityAt:string|null;metrics:{users:number;receptions:number;receptionsWithEvidence:number;qualityLots:number;productionLots:number;locatedKg:number;salesOrders:number;dispatches:number;sales:number;dailyCloses:number};checks:Check[]}
type Payload={plants?:Readiness[];disclaimer?:string;error?:string}
const dt=(value:string|null)=>value?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Sin actividad viva'
export function usePlantReadiness(){const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let active=true;void fetch('/api/plant-readiness',{cache:'no-store'}).then(async r=>{const p=await r.json() as Payload;if(!r.ok)throw new Error(p.error??'No fue posible calcular readiness');if(active)setData(p)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'No fue posible calcular readiness')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);return {data,loading,error}}
export function RolloutSummary({plants}:{plants:Readiness[]}){const stats=useMemo(()=>({started:plants.filter(p=>p.metrics.receptions>0).length,advanced:plants.filter(p=>p.score>=75).length,checks:plants.reduce((sum,p)=>sum+p.completed,0),total:plants.reduce((sum,p)=>sum+p.total,0)}),[plants]);return <section className="plant-directory-summary" aria-label="Readiness de rollout"><div><small>Plantas visibles</small><b>{plants.length}</b></div><div><small>Con operación viva</small><b>{stats.started}</b></div><div><small>Readiness ≥75%</small><b>{stats.advanced}</b></div><p>{stats.checks} de {stats.total} evidencias técnicas presentes. LIVE requiere además aceptación humana y operación sostenida.</p></section>}
export function ReadinessCard({readiness}:{readiness:Readiness}){return <div className="rollout-readiness-card"><div className="rollout-score"><span><ShieldCheck size={15}/>Readiness técnico</span><b>{readiness.score}%</b><small>{readiness.completed}/{readiness.total} evidencias</small></div><div className="rollout-mini-checks">{readiness.checks.slice(0,4).map(check=><span key={check.key} className={check.complete?'complete':''}>{check.complete?<CheckCircle2 size={12}/>:<Clock3 size={12}/>} {check.label}</span>)}</div></div>}
export function ReadinessDetail({readiness}:{readiness:Readiness}){return <section className="panel rollout-detail"><div className="section-heading"><div><span className="overline">Gate de activación</span><h2>Readiness operacional</h2></div><strong>{readiness.score}% · {readiness.completed}/{readiness.total}</strong></div><p className="data-caveat">Evidencia calculada desde Neon. No declara la planta LIVE: faltan aceptación del responsable y operación sostenida exigidas por el roadmap.</p><div className="rollout-check-grid">{readiness.checks.map(check=><div key={check.key} className={check.complete?'complete':''}><span>{check.complete?<CheckCircle2 size={15}/>:<Clock3 size={15}/>}</span><div><b>{check.label}</b><small>{check.detail}</small></div></div>)}</div><footer className="rollout-footer"><span>Última actividad: {dt(readiness.latestActivityAt)}</span><div><Link className="button compact" to="/auditoria">Auditoría</Link><Link className="button compact" to="/cierre-diario">Cierre diario</Link></div></footer></section>}
export type {Readiness}
