import {AlertTriangle,CheckCircle2,Clock3,ShieldCheck,UserCheck} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'

type Check={key:string;label:string;complete:boolean;detail:string}
type UatState='blocked'|'in_progress'|'ready_for_human_uat'
type LiveReadinessState='uat_incomplete'|'continuity_pending'|'ready_for_human_live_review'
type Blocker={key:string;label:string;detail:string}
type Readiness={plantId:string;score:number;completed:number;total:number;latestActivityAt:string|null;uat:{state:UatState;humanAcceptanceRequired:boolean;blockers:Blocker[]};liveReadiness:{state:LiveReadinessState;requiredConsecutiveCloseDays:number;consecutiveCloseDays:number;continuityEvidenceComplete:boolean;humanAcceptanceRequired:boolean;supportIndependenceRequiresHumanConfirmation:boolean;autoLive:boolean};metrics:{users:number;operationsUsers:number;operationsCredentials:number;qualityUsers:number;qualityCredentials:number;viewerUsers:number;receptions:number;receptionsWithEvidence:number;qualityLots:number;productionLots:number;locatedKg:number;salesOrders:number;dispatches:number;sales:number;endToEndReceptions:number;dailyCloses:number;distinctCloseDays:number};checks:Check[]}
type Payload={plants?:Readiness[];summary?:{blocked:number;inProgress:number;readyForHumanUat:number;readyForHumanLiveReview:number;live:number};gate?:{version:string;rule:string};disclaimer?:string;error?:string}
type BlockerAction={label:string;to:string}
const dt=(value:string|null)=>value?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Sin actividad viva'
const stateLabel:Record<UatState,string>={blocked:'Bloqueada',in_progress:'UAT en preparación',ready_for_human_uat:'Lista para UAT humano'}
const stateClass:Record<UatState,string>={blocked:'critical',in_progress:'warning',ready_for_human_uat:'healthy'}
const liveLabel:Record<LiveReadinessState,string>={uat_incomplete:'LIVE · UAT incompleto',continuity_pending:'LIVE · continuidad pendiente',ready_for_human_live_review:'Lista para revisión LIVE humana'}
const liveClass:Record<LiveReadinessState,string>={uat_incomplete:'critical',continuity_pending:'warning',ready_for_human_live_review:'healthy'}
function blockerAction(key:string,plantId:string):BlockerAction{const plant=encodeURIComponent(plantId);switch(key){case'operations-role':case'quality-role':return{label:'Configurar usuarios',to:'/operadores'};case'receptions':case'evidence':return{label:'Abrir recepciones',to:`/recepciones?plantId=${plant}`};case'quality':return{label:'Resolver calidad',to:`/recepciones?plantId=${plant}`};case'production':return{label:'Registrar producción',to:`/planificacion?plantId=${plant}`};case'inventory':return{label:'Revisar inventario',to:`/inventario?plantId=${plant}`};case'commercial':return{label:'Abrir comercial',to:`/ordenes-venta?plantId=${plant}`};case'linked-e2e':return{label:'Continuar lote',to:`/plantas/${plant}`};case'close':return{label:'Abrir cierre',to:`/?plantId=${plant}`};default:return{label:'Abrir planta',to:`/plantas/${plant}`}}}
export function usePlantReadiness(){const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let active=true;void fetch('/api/plant-readiness',{cache:'no-store'}).then(async r=>{const p=await r.json() as Payload;if(!r.ok)throw new Error(p.error??'No fue posible calcular readiness UAT');if(active)setData(p)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'No fue posible calcular readiness UAT')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);return {data,loading,error}}
export function RolloutSummary({plants}:{plants:Readiness[]}){const stats=useMemo(()=>({started:plants.filter(p=>p.metrics.receptions>0).length,blocked:plants.filter(p=>p.uat.state==='blocked').length,inProgress:plants.filter(p=>p.uat.state==='in_progress').length,ready:plants.filter(p=>p.uat.state==='ready_for_human_uat').length,liveReview:plants.filter(p=>p.liveReadiness.state==='ready_for_human_live_review').length,linked:plants.filter(p=>p.metrics.endToEndReceptions>0).length,checks:plants.reduce((sum,p)=>sum+p.completed,0),total:plants.reduce((sum,p)=>sum+p.total,0)}),[plants]);return <section className="plant-directory-summary" aria-label="Gate UAT de rollout"><div><small>Plantas visibles</small><b>{plants.length}</b></div><div><small>Bloqueadas</small><b>{stats.blocked}</b></div><div><small>UAT en preparación</small><b>{stats.inProgress}</b></div><div><small>Listas para UAT humano</small><b>{stats.ready}</b></div><p>{stats.checks} de {stats.total} gates UAT con evidencia. {stats.started} planta(s) tienen operación viva; {stats.linked} ya conectan al menos un lote E2E; {stats.liveReview} reúne(n) además 3 días consecutivos con cierre para revisión LIVE humana. Ninguna se declara LIVE automáticamente.</p></section>}
export function ReadinessCard({readiness}:{readiness:Readiness}){const firstBlocker=readiness.uat.blockers[0],live=readiness.liveReadiness;return <div className="rollout-readiness-card"><div className="rollout-score"><span><ShieldCheck size={15}/>Gate UAT</span><b>{readiness.score}%</b><small>{readiness.completed}/{readiness.total} gates</small></div><div className={`uat-state ${stateClass[readiness.uat.state]}`}><span>{readiness.uat.state==='ready_for_human_uat'?<UserCheck size={13}/>:<AlertTriangle size={13}/>} {stateLabel[readiness.uat.state]}</span>{firstBlocker?<small>Próximo bloqueo · {firstBlocker.label}</small>:<small>Falta aceptación humana antes de LIVE</small>}</div><div className={`uat-state ${liveClass[live.state]}`}><span><ShieldCheck size={13}/> {liveLabel[live.state]}</span><small>Continuidad observada · {Math.min(live.consecutiveCloseDays,live.requiredConsecutiveCloseDays)}/{live.requiredConsecutiveCloseDays} días consecutivos con cierre</small></div><div className="rollout-mini-checks">{readiness.checks.slice(0,4).map(check=><span key={check.key} className={check.complete?'complete':''}>{check.complete?<CheckCircle2 size={12}/>:<Clock3 size={12}/>} {check.label}</span>)}</div></div>}
export function ReadinessDetail({readiness}:{readiness:Readiness}){const live=readiness.liveReadiness;return <section className="panel rollout-detail"><div className="section-heading"><div><span className="overline">Gate UAT · {readiness.plantId}</span><h2>Readiness operacional verificable</h2></div><strong>{readiness.score}% · {readiness.completed}/{readiness.total}</strong></div><div className={`system-banner ${readiness.uat.state==='blocked'?'error':''}`}><ShieldCheck size={16}/><span><b>{stateLabel[readiness.uat.state]}</b> · {readiness.uat.state==='ready_for_human_uat'?'la evidencia técnica UAT está completa y enlazada por lote; falta aceptación humana explícita.':readiness.uat.blockers.length?`${readiness.uat.blockers.length} gate(s) aún bloquean el UAT completo.`:'Revisar evidencia operacional.'}</span></div><div className={`uat-state ${liveClass[live.state]}`}><span><ShieldCheck size={14}/> {liveLabel[live.state]}</span><small>{live.consecutiveCloseDays}/{live.requiredConsecutiveCloseDays} días consecutivos con cierre operacional. Esta señal demuestra continuidad observada, pero no confirma por sí sola ausencia de soporte técnico, cero P0/P1 ni aceptación del responsable.</small></div><div className="rollout-check-grid">{readiness.checks.map(check=><div key={check.key} className={check.complete?'complete':''}><span>{check.complete?<CheckCircle2 size={15}/>:<Clock3 size={15}/>}</span><div><b>{check.label}</b><small>{check.detail}</small></div></div>)}</div>{readiness.uat.blockers.length?<div className="detail-alerts" aria-label="Bloqueadores UAT">{readiness.uat.blockers.map(blocker=>{const action=blockerAction(blocker.key,readiness.plantId);return <div key={blocker.key}><AlertTriangle size={16}/><span><b>{blocker.label}</b><small>{blocker.detail}</small></span><Link className="button compact" to={action.to}>{action.label}</Link></div>})}</div>:null}<p className="data-caveat">El gate usa sólo evidencia live de Neon y cobertura real de Operaciones/Calidad. Los eventos agregados de lotes distintos no prueban E2E: al menos una recepción debe conectar evidencia, Calidad, Producción, ubicación física y comercial. Los cierres consecutivos no convierten automáticamente una planta en LIVE ni demuestran independencia del equipo técnico.</p><footer className="rollout-footer"><span>Última actividad: {dt(readiness.latestActivityAt)}</span><div><Link className="button compact" to={`/plantas/${encodeURIComponent(readiness.plantId)}`}>Abrir planta</Link><Link className="button compact" to="/auditoria">Auditoría</Link><Link className="button compact" to="/">Centro de decisión</Link></div></footer></section>}
export type {Readiness,Payload}
