import { Camera, CheckCircle2, Scale, X } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import type { Lot, Species } from '../types'

export function ReceptionModal({ open, onClose, onSave }:{open:boolean;onClose:()=>void;onSave:(lot:Lot)=>void}) {
  const [supplier,setSupplier]=useState('Juan Rain'),[zone,setZone]=useState('Bahía de Ancud')
  const [species]=useState<Species>('Erizo')
  const [gross,setGross]=useState(100),[tare,setTare]=useState(6),[drained,setDrained]=useState(87),[temperature,setTemperature]=useState(4.2),[captured,setCaptured]=useState(false)
  const accepted=Math.max(0,drained-tare), loss=useMemo(()=>gross?((gross-accepted)/gross)*100:0,[gross,accepted])
  if(!open)return null
  function submit(event:FormEvent){event.preventDefault();const initials=supplier.split(' ').map(x=>x[0]).slice(0,2).join('');const sequence=String(Math.floor(Math.random()*90)+10);onSave({id:`ER-260819-${sequence}`,species,supplier,initials,zone,gross,tare,drained,accepted,loss,gonadYield:null,premiumYield:null,temperature,status:'Muestreo',receivedAt:new Date().toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'}),evidenceCount:captured?4:0});onClose()}
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="modal-panel" onSubmit={submit}><header><div><span className="overline teal">Recepción justa</span><h2>Nueva entrega artesanal</h2><p>Registra peso, procedencia y evidencia antes de crear el lote.</p></div><button type="button" className="icon-btn" onClick={onClose} aria-label="Cerrar"><X size={19}/></button></header><div className="step-indicator"><span className="active">1 <b>Datos</b></span><i/><span>2 <b>Muestreo</b></span><i/><span>3 <b>Comprobante</b></span></div><div className="form-grid"><label>Proveedor<select value={supplier} onChange={e=>setSupplier(e.target.value)}><option>Juan Rain</option><option>María Catrilef</option><option>Alexis Paillán</option><option>Cooperativa Lliuco</option></select></label><label>Zona de extracción<select value={zone} onChange={e=>setZone(e.target.value)}><option>Bahía de Ancud</option><option>Canal de Chacao</option><option>Quemchi</option><option>Quinchao</option></select></label><label>Peso bruto (kg)<div className="input-icon"><Scale size={16}/><input type="number" min="0" step=".1" value={gross} onChange={e=>setGross(+e.target.value)}/></div></label><label>Tara (kg)<input type="number" min="0" step=".1" value={tare} onChange={e=>setTare(+e.target.value)}/></label><label>Peso después de escurrido (kg)<input type="number" min="0" step=".1" value={drained} onChange={e=>setDrained(+e.target.value)}/></label><label>Temperatura (°C)<input type="number" step=".1" value={temperature} onChange={e=>setTemperature(+e.target.value)}/></label></div><button type="button" className={`capture-zone ${captured?'captured':''}`} onClick={()=>setCaptured(true)}>{captured?<CheckCircle2 size={25}/>:<Camera size={25}/>}<span><b>{captured?'Evidencia capturada':'Capturar evidencia visual'}</b><small>{captured?'4 imágenes calibradas · calidad correcta':'Vista superior, lateral, calibre y contenedor'}</small></span></button><div className="calculation-strip"><div><small>Peso neto aceptado</small><b>{accepted.toFixed(1)} kg</b></div><div><small>Merma explicada</small><b className={loss>18?'negative':''}>{loss.toFixed(1)}%</b></div><div><small>Confianza de medición</small><b>98,4%</b></div></div><footer><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" type="submit">Crear lote y comprobante</button></footer></form></div>
}
