import {AlertTriangle,Check,Clock3,GitMerge,ShieldCheck} from 'lucide-react'
import {useCallback,useEffect,useMemo,useState} from 'react'
import {useAuth} from '../auth'

type MatchStatus='exact_both'|'guide_only'|'lot_only'|'conflict'|'ambiguous'|'unmatched'
type Block={key:string;sheetName:string;sourceBlock:number;supplier:string;site:string;guide:string|null;lotReference:string|null;matchStatus:MatchStatus;guideCandidateRows:number[];lotCandidateRows:number[]}
type ReconciliationPayload={ok?:boolean;supportBlocks?:Block[];error?:string}
type Resolution={sheet_name:string;source_block:number;selected_main_source_row:number|null;resolution_status:'linked'|'unmatched'|'deferred';resolution_basis:string;review_note:string|null;reviewed_at:string;reviewed_by:string}
type ResolutionPayload={ok?:boolean;status?:'ready'|'migration_required';resolutions?:Resolution[];error?:string}
type SavePayload={ok?:boolean;error?:string}
const keyOf=(sheet:string,block:number)=>`${sheet}|${block}`

export function RollforwardResolutionQueue(){
 const {operator}=useAuth(),[blocks,setBlocks]=useState<Block[]>([]),[resolutions,setResolutions]=useState<Resolution[]>([]),[migrationStatus,setMigrationStatus]=useState<'ready'|'migration_required'|'unknown'>('unknown'),[notes,setNotes]=useState<Record<string,string>>({}),[saving,setSaving]=useState(''),[error,setError]=useState('')
 const load=useCallback(async()=>{try{const [reconciliationResponse,resolutionResponse]=await Promise.all([fetch('/api/rollforward-reconciliation',{cache:'no-store'}),fetch('/api/rollforward-resolutions',{cache:'no-store'})]),reconciliation=await reconciliationResponse.json() as ReconciliationPayload,resolution=await resolutionResponse.json() as ResolutionPayload;if(!reconciliationResponse.ok)throw new Error(reconciliation.error??'No fue posible leer los conflictos');if(!resolutionResponse.ok)throw new Error(resolution.error??'No fue posible leer las resoluciones');setBlocks((reconciliation.supportBlocks??[]).filter(block=>['conflict','ambiguous','unmatched'].includes(block.matchStatus)));setResolutions(resolution.resolutions??[]);setMigrationStatus(resolution.status??'unknown');setError('')}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible cargar la revisión roll-forward')}},[])
 useEffect(()=>{void load()},[load])
 const byKey=useMemo(()=>new Map(resolutions.map(item=>[keyOf(item.sheet_name,item.source_block),item])),[resolutions]),pending=useMemo(()=>blocks.filter(block=>byKey.get(keyOf(block.sheetName,block.sourceBlock))?.resolution_status!=='linked'&&byKey.get(keyOf(block.sheetName,block.sourceBlock))?.resolution_status!=='unmatched'),[blocks,byKey]),linked=resolutions.filter(item=>item.resolution_status==='linked').length,deferred=resolutions.filter(item=>item.resolution_status==='deferred').length,canResolve=operator?.role==='admin'||operator?.role==='quality'
 const save=useCallback(async(block:Block,resolutionStatus:'linked'|'unmatched'|'deferred',selectedMainSourceRow?:number)=>{const key=keyOf(block.sheetName,block.sourceBlock),reviewNote=(notes[key]??'').trim();if(resolutionStatus!=='linked'&&!reviewNote){setError('Escribe una nota antes de posponer o cerrar sin vínculo.');return}setSaving(key);setError('');try{const response=await fetch('/api/rollforward-resolution',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sheetName:block.sheetName,sourceBlock:block.sourceBlock,selectedMainSourceRow,resolutionStatus,reviewNote})}),payload=await response.json() as SavePayload;if(!response.ok)throw new Error(payload.error??'No fue posible guardar la resolución');setNotes(current=>({...current,[key]:''}));await load()}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible guardar la resolución')}finally{setSaving('')}},[load,notes])
 if(!blocks.length&&migrationStatus!=='migration_required'&&!error)return null
 return <section className="panel" aria-label="Revisión humana de conflictos roll-forward" aria-live="polite">
  <div className="section-heading"><div><span className="overline">Calidad · revisión humana</span><h2>Resolver conflictos roll-forward</h2><p className="source-note">La selección humana sólo enlaza evidencia auxiliar con una fila canónica. No modifica kilos, Grade, rendimiento, liquidaciones ni inventario.</p></div><span>{pending.length} pendientes</span></div>
  <div className="signal-grid">
   <article className={`signal-card ${pending.length?'attention':''}`}><span><AlertTriangle size={16}/>Pendientes</span><b>{pending.length}</b><small>conflictos/ausencias sin decisión final</small></article>
   <article className="signal-card"><span><GitMerge size={16}/>Resueltos</span><b>{linked}</b><small>vínculos aprobados por Calidad</small></article>
   <article className="signal-card"><span><Clock3 size={16}/>Pospuestos</span><b>{deferred}</b><small>con nota y trazabilidad</small></article>
  </div>
  {migrationStatus==='migration_required'?<div className="notice warning"><AlertTriangle size={16}/>Migración 031 pendiente. La cola es visible, pero todavía no se pueden guardar decisiones.</div>:null}
  {pending.map(block=>{const key=keyOf(block.sheetName,block.sourceBlock),resolution=byKey.get(key),disabled=saving===key||migrationStatus==='migration_required'||!canResolve;return <details className="supplier-score-row" key={key}><summary><span className="alert-icon warning"><AlertTriangle size={16}/></span><div className="supplier-score-main"><b>{block.sheetName} · bloque {block.sourceBlock}</b><small>{block.supplier} · guía {block.guide??'—'} · lote {block.lotReference??'—'} · {block.matchStatus==='conflict'?'guía y lote contradicen':block.matchStatus==='ambiguous'?'más de un candidato':'sin candidato determinístico'}</small></div><div className="supplier-score-volume"><b>{resolution?.resolution_status==='deferred'?'Pospuesto':'Pendiente'}</b><small>{resolution?.reviewed_by??'revisión requerida'}</small></div></summary><div className="supplier-score-detail">
    <div className="signal-grid"><article className="signal-card"><span>Candidato por guía</span><b>{block.guideCandidateRows.join(', ')||'—'}</b><small>fila(s) de producción principal</small></article><article className="signal-card"><span>Candidato por lote</span><b>{block.lotCandidateRows.join(', ')||'—'}</b><small>fila(s) de producción principal</small></article></div>
    {canResolve?<><label className="field"><span>Nota de revisión</span><input value={notes[key]??''} maxLength={1000} placeholder="Motivo o evidencia adicional" onChange={event=>setNotes(current=>({...current,[key]:event.target.value}))}/></label><div className="actions-row">{block.guideCandidateRows.length===1?<button className="button secondary" type="button" disabled={disabled} onClick={()=>void save(block,'linked',block.guideCandidateRows[0])}><Check size={15}/>Elegir fila {block.guideCandidateRows[0]} por guía</button>:null}{block.lotCandidateRows.length===1?<button className="button secondary" type="button" disabled={disabled} onClick={()=>void save(block,'linked',block.lotCandidateRows[0])}><Check size={15}/>Elegir fila {block.lotCandidateRows[0]} por lote</button>:null}<button className="button secondary" type="button" disabled={disabled} onClick={()=>void save(block,'deferred')}><Clock3 size={15}/>Posponer con nota</button><button className="button secondary" type="button" disabled={disabled} onClick={()=>void save(block,'unmatched')}><ShieldCheck size={15}/>Cerrar sin vínculo</button></div></>:<p className="source-note">Sólo Calidad o Administración pueden registrar una resolución.</p>}
   </div></details>})}
  {resolutions.filter(item=>['linked','unmatched'].includes(item.resolution_status)).length?<details className="supplier-score-row"><summary><span className="alert-icon info"><ShieldCheck size={16}/></span><div className="supplier-score-main"><b>Decisiones cerradas</b><small>Historial auditable del operador y criterio aplicado.</small></div></summary><div className="supplier-score-detail"><div className="table-scroll"><table className="data-table"><thead><tr><th>Hoja / bloque</th><th>Decisión</th><th>Fila</th><th>Criterio</th><th>Revisor</th><th>Nota</th></tr></thead><tbody>{resolutions.filter(item=>['linked','unmatched'].includes(item.resolution_status)).map(item=><tr key={keyOf(item.sheet_name,item.source_block)}><td><b>{item.sheet_name} · {item.source_block}</b></td><td>{item.resolution_status==='linked'?'Vinculado':'Sin vínculo'}</td><td>{item.selected_main_source_row??'—'}</td><td>{item.resolution_basis}</td><td>{item.reviewed_by}</td><td>{item.review_note??'—'}</td></tr>)}</tbody></table></div></div></details>:null}
  {error?<div className="notice error">{error}</div>:null}
 </section>
}
