import {AlertTriangle,Check,Clock3,GitMerge,Route,ShieldCheck} from 'lucide-react'
import {useCallback,useEffect,useMemo,useState} from 'react'
import {useAuth} from '../auth'

type MatchStatus='exact_both'|'guide_only'|'lot_only'|'conflict'|'ambiguous'|'unmatched'
type Candidate={sourceRow:number;eventDate:string|null;guide:string|null;supplier:string;site:string;lot:string|null;guideKg?:number|null;receivedKg:number|null;guideMatch?:boolean;lotMatch?:boolean}
type Chain={observations:Candidate[]}
type Block={key:string;sheetName:string;sourceBlock:number;supplier:string;site:string;guide:string|null;lotReference:string|null;matchStatus:MatchStatus;matchedSourceRow:number|null;guideCandidateRows:number[];lotCandidateRows:number[]}
type ReconciliationPayload={ok?:boolean;summary?:{rows:number};supportBlocks?:Block[];chains?:Chain[];error?:string}
type CandidateSnapshot={version?:string;support?:{sheetName?:string;sourceBlock?:number;familyKey?:string;supplier?:string;guide?:string|null;lotReference?:string|null};guideCandidates?:Candidate[];lotCandidates?:Candidate[];selected?:Candidate|null;priorReview?:{selectedMainSourceRow?:number|null;resolutionStatus?:string;resolutionBasis?:string;reviewNote?:string|null;reviewedByOperatorId?:string;reviewedAt?:string|null;candidateSnapshot?:CandidateSnapshot|null}|null}
type Resolution={sheet_name:string;source_block:number;selected_main_source_row:number|null;resolution_status:'linked'|'unmatched'|'deferred';resolution_basis:string;review_note:string|null;candidate_snapshot?:CandidateSnapshot|null;reviewed_at:string;reviewed_by:string}
type ResolutionPayload={ok?:boolean;status?:'ready'|'migration_required';resolutions?:Resolution[];governance?:{closedDecisionsImmutable?:boolean;deferredDecisionsRevisable?:boolean;priorReviewRetainedInSnapshot?:boolean;writesLive?:boolean};error?:string}
type SavePayload={ok?:boolean;error?:string}
const keyOf=(sheet:string,block:number)=>`${sheet}|${block}`
const pct=(part:number,total:number)=>total?`${new Intl.NumberFormat('es-CL',{maximumFractionDigits:1}).format(part/total*100)}%`:'—'
const kg=(value:number|null)=>value==null?'kg —':`${new Intl.NumberFormat('es-CL',{maximumFractionDigits:1}).format(value)} kg recibidos`
const dateLabel=(value:string|null)=>{if(!value)return 'fecha —';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'UTC'}).format(parsed)}
const candidateLabel=(candidate:Candidate|null|undefined)=>candidate?`Fila ${candidate.sourceRow} · ${candidate.guide?'guía '+candidate.guide:'guía —'} · ${candidate.lot?'lote '+candidate.lot:'lote —'} · ${candidate.site} · ${kg(candidate.receivedKg)}`:'—'
const candidateRowsLabel=(items:Candidate[]|undefined)=>items?.length?items.map(item=>item.sourceRow).join(', '):'—'

export function RollforwardResolutionQueue(){
 const {operator}=useAuth(),[blocks,setBlocks]=useState<Block[]>([]),[candidateRows,setCandidateRows]=useState<Candidate[]>([]),[rollforwardRows,setRollforwardRows]=useState(0),[resolutions,setResolutions]=useState<Resolution[]>([]),[migrationStatus,setMigrationStatus]=useState<'ready'|'migration_required'|'unknown'>('unknown'),[notes,setNotes]=useState<Record<string,string>>({}),[saving,setSaving]=useState(''),[error,setError]=useState('')
 const load=useCallback(async()=>{try{const [reconciliationResponse,resolutionResponse]=await Promise.all([fetch('/api/rollforward-reconciliation',{cache:'no-store'}),fetch('/api/rollforward-resolutions',{cache:'no-store'})]),reconciliation=await reconciliationResponse.json() as ReconciliationPayload,resolution=await resolutionResponse.json() as ResolutionPayload;if(!reconciliationResponse.ok)throw new Error(reconciliation.error??'No fue posible leer los conflictos');if(!resolutionResponse.ok)throw new Error(resolution.error??'No fue posible leer las resoluciones');setBlocks(reconciliation.supportBlocks??[]);setCandidateRows((reconciliation.chains??[]).flatMap(chain=>chain.observations??[]));setRollforwardRows(reconciliation.summary?.rows??0);setResolutions(resolution.resolutions??[]);setMigrationStatus(resolution.status??'unknown');setError('')}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible cargar la revisión roll-forward')}},[])
 useEffect(()=>{void load()},[load])
 const candidateByRow=useMemo(()=>new Map(candidateRows.map(row=>[row.sourceRow,row])),[candidateRows]),reviewBlocks=useMemo(()=>blocks.filter(block=>['conflict','ambiguous','unmatched'].includes(block.matchStatus)),[blocks]),byKey=useMemo(()=>new Map(resolutions.map(item=>[keyOf(item.sheet_name,item.source_block),item])),[resolutions]),pending=useMemo(()=>reviewBlocks.filter(block=>byKey.get(keyOf(block.sheetName,block.sourceBlock))?.resolution_status!=='linked'&&byKey.get(keyOf(block.sheetName,block.sourceBlock))?.resolution_status!=='unmatched'),[reviewBlocks,byKey]),reviewKeys=useMemo(()=>new Set(reviewBlocks.map(block=>keyOf(block.sheetName,block.sourceBlock))),[reviewBlocks]),linkedResolutions=useMemo(()=>resolutions.filter(item=>item.resolution_status==='linked'&&reviewKeys.has(keyOf(item.sheet_name,item.source_block))),[resolutions,reviewKeys]),closedUnmatched=useMemo(()=>resolutions.filter(item=>item.resolution_status==='unmatched'&&reviewKeys.has(keyOf(item.sheet_name,item.source_block))),[resolutions,reviewKeys]),deferred=useMemo(()=>resolutions.filter(item=>item.resolution_status==='deferred'&&reviewKeys.has(keyOf(item.sheet_name,item.source_block))),[resolutions,reviewKeys]),autoLinked=useMemo(()=>blocks.filter(block=>['exact_both','guide_only','lot_only'].includes(block.matchStatus)),[blocks]),effectiveLinkedBlocks=autoLinked.length+linkedResolutions.length,effectiveMainRows=useMemo(()=>{const rows=new Set<number>();for(const block of autoLinked)if(block.matchedSourceRow!=null)rows.add(block.matchedSourceRow);for(const item of linkedResolutions)if(item.selected_main_source_row!=null)rows.add(item.selected_main_source_row);return rows.size},[autoLinked,linkedResolutions]),canResolve=operator?.role==='admin'||operator?.role==='quality'
 const save=useCallback(async(block:Block,resolutionStatus:'linked'|'unmatched'|'deferred',selectedMainSourceRow?:number)=>{const key=keyOf(block.sheetName,block.sourceBlock),reviewNote=(notes[key]??'').trim();if(resolutionStatus!=='linked'&&!reviewNote){setError('Escribe una nota antes de posponer o cerrar sin vínculo.');return}setSaving(key);setError('');try{const response=await fetch('/api/rollforward-resolution',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sheetName:block.sheetName,sourceBlock:block.sourceBlock,selectedMainSourceRow,resolutionStatus,reviewNote})}),payload=await response.json() as SavePayload;if(!response.ok)throw new Error(payload.error??'No fue posible guardar la resolución');setNotes(current=>({...current,[key]:''}));window.dispatchEvent(new Event('pescamar:data-updated'));await load()}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible guardar la resolución')}finally{setSaving('')}},[load,notes])
 const candidateCards=(label:string,ids:number[],basis:'guía'|'lote')=><div><p className="source-note"><b>{label}</b></p><div className="signal-grid">{ids.length?ids.map(id=>{const row=candidateByRow.get(id);return <article className="signal-card" key={`${basis}-${id}`}><span>Fila {id} · {dateLabel(row?.eventDate??null)}</span><b>{row?`${row.guide?'Guía '+row.guide:'Guía —'} · ${row.lot?'lote '+row.lot:'lote —'}`:`Fila ${id}`}</b><small>{row?`${row.site} · ${kg(row.receivedKg)}`:'Detalle canónico no disponible'}</small></article>}):<article className="signal-card"><span>Sin candidato</span><b>—</b><small>No existe una fila única por {basis}.</small></article>}</div></div>
 if(!reviewBlocks.length&&migrationStatus!=='migration_required'&&!error)return null
 const closed=resolutions.filter(item=>['linked','unmatched'].includes(item.resolution_status))
 return <section className="panel" aria-label="Revisión humana de conflictos roll-forward" aria-live="polite">
  <div className="section-heading"><div><span className="overline">Calidad · revisión humana</span><h2>Resolver conflictos roll-forward</h2><p className="source-note">La selección humana sólo enlaza evidencia auxiliar con una fila canónica. No modifica kilos, Grade, rendimiento, liquidaciones ni inventario.</p></div><span>{pending.length} pendientes</span></div>
  <div className="signal-grid">
   <article className={`signal-card ${pending.length?'attention':''}`}><span><AlertTriangle size={16}/>Pendientes reales</span><b>{pending.length}</b><small>{reviewBlocks.length} bloques originalmente requerían revisión</small></article>
   <article className="signal-card"><span><GitMerge size={16}/>Cobertura efectiva</span><b>{pct(effectiveLinkedBlocks,blocks.length)}</b><small>{effectiveLinkedBlocks}/{blocks.length} bloques enlazados tras revisión</small></article>
   <article className="signal-card"><span><Route size={16}/>Filas con evidencia</span><b>{pct(effectiveMainRows,rollforwardRows)}</b><small>{effectiveMainRows}/{rollforwardRows} filas roll-forward cubiertas</small></article>
   <article className="signal-card"><span><Clock3 size={16}/>Revisión cerrada</span><b>{linkedResolutions.length+closedUnmatched.length}</b><small>{linkedResolutions.length} vinculados · {closedUnmatched.length} sin vínculo · {deferred.length} pospuestos</small></article>
  </div>
  {migrationStatus!=='migration_required'?<div className="notice"><ShieldCheck size={16}/>Las decisiones finales vinculadas o cerradas sin vínculo son inmutables. Un estado pospuesto puede revisarse y conserva la revisión previa dentro de su evidencia congelada.</div>:null}
  {migrationStatus==='migration_required'?<div className="notice warning"><AlertTriangle size={16}/>Migración 031 pendiente. La cola es visible, pero todavía no se pueden guardar decisiones.</div>:null}
  {pending.map(block=>{const key=keyOf(block.sheetName,block.sourceBlock),resolution=byKey.get(key),disabled=saving===key||migrationStatus==='migration_required'||!canResolve;return <details className="supplier-score-row" key={key}><summary><span className="alert-icon warning"><AlertTriangle size={16}/></span><div className="supplier-score-main"><b>{block.sheetName} · bloque {block.sourceBlock}</b><small>{block.supplier} · guía {block.guide??'—'} · lote {block.lotReference??'—'} · {block.matchStatus==='conflict'?'guía y lote contradicen':block.matchStatus==='ambiguous'?'más de un candidato':'sin candidato determinístico'}</small></div><div className="supplier-score-volume"><b>{resolution?.resolution_status==='deferred'?'Pospuesto':'Pendiente'}</b><small>{resolution?.reviewed_by??'revisión requerida'}</small></div></summary><div className="supplier-score-detail">
    <div className="notice warning"><AlertTriangle size={16}/>Compara la evidencia de ambos candidatos antes de vincular. La guía y el lote pueden apuntar a recepciones distintas.</div>
    {candidateCards('Candidato(s) por guía',block.guideCandidateRows,'guía')}
    {candidateCards('Candidato(s) por lote',block.lotCandidateRows,'lote')}
    {canResolve?<><label className="field"><span>Nota de revisión</span><input value={notes[key]??''} maxLength={1000} placeholder="Motivo o evidencia adicional" onChange={event=>setNotes(current=>({...current,[key]:event.target.value}))}/></label><div className="actions-row">{block.guideCandidateRows.length===1?<button className="button secondary" type="button" disabled={disabled} onClick={()=>void save(block,'linked',block.guideCandidateRows[0])}><Check size={15}/>Elegir fila {block.guideCandidateRows[0]} por guía</button>:null}{block.lotCandidateRows.length===1?<button className="button secondary" type="button" disabled={disabled} onClick={()=>void save(block,'linked',block.lotCandidateRows[0])}><Check size={15}/>Elegir fila {block.lotCandidateRows[0]} por lote</button>:null}<button className="button secondary" type="button" disabled={disabled} onClick={()=>void save(block,'deferred')}><Clock3 size={15}/>Posponer con nota</button><button className="button secondary" type="button" disabled={disabled} onClick={()=>void save(block,'unmatched')}><ShieldCheck size={15}/>Cerrar sin vínculo</button></div></>:<p className="source-note">Sólo Calidad o Administración pueden registrar una resolución.</p>}
   </div></details>})}
  {closed.length?<details className="supplier-score-row"><summary><span className="alert-icon info"><ShieldCheck size={16}/></span><div className="supplier-score-main"><b>Decisiones cerradas</b><small>Decisiones finales inmutables con evidencia congelada al momento de decidir.</small></div></summary><div className="supplier-score-detail"><div className="table-scroll"><table className="data-table"><thead><tr><th>Hoja / bloque</th><th>Decisión</th><th>Evidencia congelada</th><th>Criterio</th><th>Revisor</th><th>Nota</th></tr></thead><tbody>{closed.map(item=>{const snapshot=item.candidate_snapshot;return <tr key={keyOf(item.sheet_name,item.source_block)}><td><b>{item.sheet_name} · {item.source_block}</b></td><td>{item.resolution_status==='linked'?'Vinculado':'Sin vínculo'}</td><td><b>{candidateLabel(snapshot?.selected)}</b><small className="source-note">Comparados: guía [{candidateRowsLabel(snapshot?.guideCandidates)}] · lote [{candidateRowsLabel(snapshot?.lotCandidates)}]</small>{snapshot?.priorReview?<small className="source-note">Revisión previa conservada: {snapshot.priorReview.resolutionStatus??'—'} · {snapshot.priorReview.reviewNote??'sin nota'}</small>:null}</td><td>{item.resolution_basis}</td><td>{item.reviewed_by}</td><td>{item.review_note??'—'}</td></tr>})}</tbody></table></div></div></details>:null}
  {error?<div className="notice error">{error}</div>:null}
 </section>
}
