import {AlertTriangle,Database,GitBranch,MapPin,Route,ShieldCheck,Upload} from 'lucide-react'
import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {useAuth} from '../auth'

type Grade={grade:string;kg:number|null;boxes:number|null}
type Observation={sourceRow:number;eventDate:string|null;guide:string|null;supplier:string;extractionZone:string|null;site:string;lot:string;guideKg:number|null;receivedKg:number|null;grades:Grade[];destination:string|null;notes:string|null;familyKey:string;familyLabel:string}
type Chain={key:string;familyKey:string;familyLabel:string;supplier:string;site:string;rows:number;lots:number;guides:number;receivedKg:number;destinationCoveragePct:number|null;guideCoveragePct:number|null;gradeCoveragePct:number|null;destinations:string[];grades:string[];gradeObservationCount:number;status:'ready_for_reconciliation'|'needs_destination'|'needs_evidence';observations:Observation[]}
type SupportGrade={sourceRow:number;grade:string;guideKg:number|null;acceptedKg:number|null;destinedKg:number|null;flags:string[]}
type SupportMatch='exact_both'|'guide_only'|'lot_only'|'conflict'|'ambiguous'|'unmatched'
type SupportBlock={key:string;sheetName:string;sourceBlock:number;familyKey:string;eventDate:string|null;supplier:string;site:string;guide:string|null;lotReference:string|null;notes:string|null;grades:SupportGrade[];matchStatus:SupportMatch;matchedSourceRow:number|null;guideCandidateRows:number[];lotCandidateRows:number[]}
type SupportSummary={status:'ready'|'not_imported'|'migration_required';parserVersion:string;rows:number;blocks:number;autoLinkedBlocks:number;exactBoth:number;guideOnly:number;lotOnly:number;conflicts:number;ambiguous:number;unmatched:number;matchCoveragePct:number|null;matchedMainRows:number;mainCoveragePct:number|null}
type Payload={ok?:boolean;method?:{version:string;rule:string};summary?:{rows:number;chains:number;uniqueLots:number;uniqueGuides:number;receivedKg:number;destinationRows:number;destinationCoveragePct:number|null;gradeRows:number;gradeCoveragePct:number|null;gradeObservationCount:number;unresolvedDestinationRows:number};support?:SupportSummary;supportBlocks?:SupportBlock[];chains?:Chain[];error?:string}
type ImportResult={ok?:boolean;rows?:number;blocks?:number;flagged?:number;error?:string}
const nf=new Intl.NumberFormat('es-CL',{maximumFractionDigits:1})
const kg=(value:number)=>`${nf.format(value)} kg`
const pct=(value:number|null|undefined)=>value==null?'—':`${nf.format(value)}%`
const statusLabel=(status:Chain['status'])=>status==='ready_for_reconciliation'?'Lista para conciliar':status==='needs_destination'?'Falta destino':'Falta evidencia'
const statusClass=(status:Chain['status'])=>status==='ready_for_reconciliation'?'info':'warning'
const gradeText=(grades:Grade[])=>grades.length?grades.map(item=>`${item.grade}${item.kg==null?'':` ${nf.format(item.kg)} kg`}`).join(' · '):'Sin grado explícito'
const supportLabel=(status:SupportMatch)=>({exact_both:'Guía + lote',guide_only:'Sólo guía',lot_only:'Sólo lote',conflict:'Conflicto',ambiguous:'Ambiguo',unmatched:'Sin vínculo'}[status])
const supportClass=(status:SupportMatch)=>['exact_both','guide_only','lot_only'].includes(status)?'info':'warning'

export function RollforwardReconciliation(){
 const {operator}=useAuth(),inputRef=useRef<HTMLInputElement>(null)
 const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[importing,setImporting]=useState(false),[importResult,setImportResult]=useState<ImportResult|null>(null)
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const response=await fetch('/api/rollforward-reconciliation',{cache:'no-store'}),payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error??'No fue posible cargar conciliación roll-forward');setData(payload);setError('')}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible cargar conciliación roll-forward')}finally{if(!silent)setLoading(false)}},[])
 useEffect(()=>{void load();const refresh=()=>void load(true),timer=window.setInterval(()=>{if(document.visibilityState==='visible')refresh()},60_000);window.addEventListener('pescamar:data-updated',refresh);return()=>{window.clearInterval(timer);window.removeEventListener('pescamar:data-updated',refresh)}},[load])
 const uploadSupport=useCallback(async(file:File)=>{if(file.name!=='planilla de produccion 2026.xlsx'){setImportResult({ok:false,error:'Selecciona exactamente planilla de produccion 2026.xlsx'});return}if(file.size>15*1024*1024){setImportResult({ok:false,error:'El archivo supera 15 MB'});return}setImporting(true);setImportResult(null);try{const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('No fue posible leer el archivo'));reader.onload=()=>resolve(String(reader.result??''));reader.readAsDataURL(file)}),response=await fetch('/api/production-support-import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileName:file.name,base64})}),payload=await response.json() as ImportResult;if(!response.ok)throw new Error(payload.error??'No fue posible publicar las hojas auxiliares');setImportResult(payload);window.dispatchEvent(new Event('pescamar:data-updated'));await load(true)}catch(cause){setImportResult({ok:false,error:cause instanceof Error?cause.message:'No fue posible publicar las hojas auxiliares'})}finally{setImporting(false);if(inputRef.current)inputRef.current.value=''}},[load])
 const chains=useMemo(()=>data?.chains??[],[data?.chains]),supportBlocks=useMemo(()=>data?.supportBlocks??[],[data?.supportBlocks]),reviewBlocks=useMemo(()=>supportBlocks.filter(block=>['conflict','ambiguous','unmatched'].includes(block.matchStatus)),[supportBlocks]),summary=data?.summary,support=data?.support,canImport=operator?.role==='admin'||operator?.role==='operations'
 if(loading&&!data)return <section className="panel"><div className="empty-inline"><GitBranch size={20}/><div><b>Reconstruyendo roll-forward</b><small>Enlazando lote, grado y destino sin convertir arrastres en rendimiento.</small></div></div></section>
 if(error&&!data)return <section className="panel"><div className="notice error">{error}</div></section>
 if(!data)return null
 return <section className="panel" aria-label="Conciliación roll-forward" aria-live="polite">
  <div className="section-heading"><div><span className="overline">Producción canónica · trazabilidad roll-forward</span><h2>Lote → grado → destino</h2><p className="source-note">Reconstrucción auditable de los registros con arrastre entre lotes. La evidencia auxiliar enlaza guía/lote con los bloques de Isla Guafo, Diaz termiando y Cesar; los kg aceptados o D/RGA no se convierten en rendimiento.</p></div><span>{data.method?.version??'rollforward-linkage-v2'}</span></div>
  <div className="signal-grid">
   <article className="signal-card"><span><GitBranch size={16}/>Filas roll-forward</span><b>{summary?.rows??0}</b><small>{summary?.chains??0} cadenas de conciliación</small></article>
   <article className="signal-card"><span><Route size={16}/>Lotes / guías</span><b>{summary?.uniqueLots??0}</b><small>{summary?.uniqueGuides??0} guías identificadas</small></article>
   <article className="signal-card"><span><MapPin size={16}/>Destino explícito</span><b>{pct(summary?.destinationCoveragePct)}</b><small>{summary?.destinationRows??0} filas con cliente/destino</small></article>
   <article className={`signal-card ${(summary?.unresolvedDestinationRows??0)>0?'attention':''}`}><span><AlertTriangle size={16}/>Destino pendiente</span><b>{summary?.unresolvedDestinationRows??0}</b><small>No se infiere: requiere evidencia explícita</small></article>
  </div>
  <div className="section-heading"><div><span className="overline teal">Hojas auxiliares</span><h3>Vínculo determinístico contra producción</h3></div>{canImport?<><input ref={inputRef} type="file" hidden accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event=>{const file=event.target.files?.[0];if(file)void uploadSupport(file)}}/><button className="button secondary" type="button" disabled={importing||support?.status==='migration_required'} onClick={()=>inputRef.current?.click()}><Upload size={15}/>{importing?'Publicando…':'Publicar evidencia auxiliar'}</button></>:null}</div>
  {support?.status==='migration_required'?<div className="notice warning"><AlertTriangle size={16}/>Migración 030 pendiente. El código está preparado, pero Neon todavía no tiene el staging de hojas auxiliares.</div>:support?.status==='not_imported'?<div className="governance-note"><Database size={19}/><div><b>Evidencia auxiliar aún no publicada</b><p>Vuelve a seleccionar la misma planilla canónica de producción. Se validará su SHA-256 y sólo se cargarán Isla Guafo, Diaz termiando y Cesar en staging.</p></div></div>:support?<div className="signal-grid">
   <article className="signal-card"><span><Database size={16}/>Bloques auxiliares</span><b>{support.blocks}</b><small>{support.rows} observaciones por grado</small></article>
   <article className="signal-card"><span><ShieldCheck size={16}/>Auto-vinculados</span><b>{pct(support.matchCoveragePct)}</b><small>{support.autoLinkedBlocks}/{support.blocks} bloques sin contradicción</small></article>
   <article className={`signal-card ${support.conflicts?'attention':''}`}><span><AlertTriangle size={16}/>Conflictos</span><b>{support.conflicts}</b><small>{support.ambiguous} ambiguos · {support.unmatched} sin vínculo</small></article>
   <article className="signal-card"><span><Route size={16}/>Cobertura principal</span><b>{pct(support.mainCoveragePct)}</b><small>{support.matchedMainRows}/{summary?.rows??0} filas roll-forward con evidencia auxiliar</small></article>
  </div>:null}
  {importResult?<div className={`notice ${importResult.ok?'':'error'}`}>{importResult.ok?<><ShieldCheck size={16}/>{importResult.blocks} bloques / {importResult.rows} observaciones auxiliares publicadas.</>:<><AlertTriangle size={16}/>{importResult.error}</>}</div>:null}
  {support?.status==='ready'&&reviewBlocks.length?<><div className="section-heading"><div><span className="overline">Revisión humana</span><h3>Conflictos que no se auto-resuelven</h3></div><span>{reviewBlocks.length} bloques</span></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Hoja</th><th>Bloque</th><th>Proveedor</th><th>Guía auxiliar</th><th>Lote auxiliar</th><th>Candidato guía</th><th>Candidato lote</th><th>Estado</th></tr></thead><tbody>{reviewBlocks.map(block=><tr key={block.key}><td><b>{block.sheetName}</b></td><td>{block.sourceBlock}</td><td>{block.supplier}</td><td>{block.guide??'—'}</td><td>{block.lotReference??'—'}</td><td>{block.guideCandidateRows.join(', ')||'—'}</td><td>{block.lotCandidateRows.join(', ')||'—'}</td><td><span className={`status-badge ${supportClass(block.matchStatus)}`}>{supportLabel(block.matchStatus)}</span></td></tr>)}</tbody></table></div></>:null}
  {support?.status==='ready'?supportBlocks.filter(block=>['exact_both','guide_only','lot_only'].includes(block.matchStatus)).slice(0,8).map(block=><details className="supplier-score-row" key={`support-${block.key}`}><summary><span className="alert-icon info"><ShieldCheck size={16}/></span><div className="supplier-score-main"><b>{block.sheetName} · {block.guide??block.lotReference??`bloque ${block.sourceBlock}`}</b><small>{block.supplier} · {supportLabel(block.matchStatus)} · fila principal {block.matchedSourceRow}</small></div><div className="supplier-score-volume"><b>{block.grades.length} grados</b><small>evidencia auxiliar</small></div></summary><div className="supplier-score-detail"><div className="table-scroll"><table className="data-table"><thead><tr><th>Grado fuente</th><th className="numeric">Kg guía</th><th className="numeric">Kg aceptados</th><th className="numeric">D/RGA kg</th><th>Flags</th></tr></thead><tbody>{block.grades.map(item=><tr key={`${block.key}-${item.sourceRow}`}><td><b>{item.grade}</b></td><td className="numeric">{item.guideKg==null?'—':nf.format(item.guideKg)}</td><td className="numeric">{item.acceptedKg==null?'—':nf.format(item.acceptedKg)}</td><td className="numeric">{item.destinedKg==null?'—':nf.format(item.destinedKg)}</td><td>{item.flags.join(' · ')||'—'}</td></tr>)}</tbody></table></div>{block.notes?<p className="source-note">{block.notes}</p>:null}</div></details>):null}
  {chains.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Cadena</th><th>Proveedor</th><th>Planta</th><th className="numeric">Filas</th><th className="numeric">Lotes</th><th className="numeric">Recibido</th><th className="numeric">Guía</th><th className="numeric">Destino</th><th>Grados observados</th><th>Estado</th></tr></thead><tbody>{chains.map(chain=><tr key={chain.key}><td><b>{chain.familyLabel}</b></td><td>{chain.supplier}</td><td>{chain.site}</td><td className="numeric">{chain.rows}</td><td className="numeric">{chain.lots}</td><td className="numeric">{kg(chain.receivedKg)}</td><td className="numeric">{pct(chain.guideCoveragePct)}</td><td className="numeric">{pct(chain.destinationCoveragePct)}</td><td>{chain.grades.join(' · ')||'—'}</td><td><span className={`status-badge ${statusClass(chain.status)}`}>{statusLabel(chain.status)}</span></td></tr>)}</tbody></table></div>:<div className="empty-inline"><ShieldCheck size={20}/><div><b>Sin filas roll-forward</b><small>No hay cadenas pendientes en la fuente canónica activa.</small></div></div>}
  {chains.map(chain=><details className="supplier-score-row" key={`detail-${chain.key}`}><summary><span className={`alert-icon ${statusClass(chain.status)}`}>{chain.status==='ready_for_reconciliation'?<ShieldCheck size={16}/>:<AlertTriangle size={16}/>}</span><div className="supplier-score-main"><b>{chain.familyLabel} · {chain.supplier}</b><small>{chain.rows} filas · {chain.lots} lotes · destino {pct(chain.destinationCoveragePct)}</small></div><div className="supplier-score-volume"><b>{kg(chain.receivedKg)}</b><small>{chain.gradeObservationCount} observaciones de grado</small></div></summary><div className="supplier-score-detail"><div className="table-scroll"><table className="data-table"><thead><tr><th>Fila</th><th>Fecha</th><th>Lote</th><th>Guía</th><th>Grado</th><th>Destino</th><th>Observación</th></tr></thead><tbody>{chain.observations.map(row=><tr key={`${chain.key}-${row.sourceRow}`}><td>{row.sourceRow}</td><td>{row.eventDate??'—'}</td><td><b>{row.lot}</b></td><td>{row.guide??'—'}</td><td>{gradeText(row.grades)}</td><td>{row.destination??'Pendiente'}</td><td>{row.notes??'—'}</td></tr>)}</tbody></table></div></div></details>)}
  <p className="source-note">{data.method?.rule}</p>
  {error?<div className="notice error">{error}</div>:null}
 </section>
}
