import {Camera,CheckCircle2,ChevronRight,ExternalLink,Link2,Send,ShieldCheck,Sparkles,Target,X} from 'lucide-react'
import {useEffect,useMemo,useRef,useState,type ChangeEvent,type ClipboardEvent,type DragEvent,type FormEvent} from 'react'
import {Link,useLocation,useSearchParams} from 'react-router-dom'
import {useAuth} from '../auth'
import {analyzeSegmentedCanvas} from '../lib/uniVisionSegmentation'
import {useLots} from '../store'
import './sea-urchin-assistant.css'
import './sea-urchin-visual-twin.css'

type EvidenceClass='live_observation'|'derived_live'|'canonical_reference'|'canonical_history'|'partial_financial'
type Source={id:string;label:string;path:string;rows:number;freshness:string|null;evidenceClass?:EvidenceClass}
type Scope={plantId:string|null;plantIds:string[];role:string;organizationId?:string}
type Turn={id:string;question:string;answer:string;sources:Source[];generatedAt:string;scope:Scope;engine:string;policyVersion:string;suggestedQuestions:string[]}
type Payload={answer?:string;engine?:string;policyVersion?:string;generatedAt?:string;scope?:Scope;sources?:Source[];suggestedQuestions?:string[];visualTwin?:boolean;error?:string}
type ControlCard={ok?:boolean;process?:{id?:string;grade?:string|null;colorStatus?:string|null;xrayStatus?:string|null}|null;diagnosis?:{state?:string;blockers?:string[];nextAction?:string;unknowns?:string[]}|null;summary?:{japanReleasable?:boolean|null;deviations?:number;blockingHolds?:number}|null;error?:string}
type VisualMeasurement={confidence:'good'|'review';usableRatio:number;borderCandidateRatio:number;rMean:number;gMean:number;rgbBMean:number;lMean:number;aMean:number;bMean:number;lStd:number;aStd:number;bStd:number;dispersion:number;chroma:number;hueDeg:number;pixelCount:number}
type EvidenceRef={captureId:string;evidenceUrl:string|null}
type Photo={id:string;name:string;dataUrl:string;sourceImageSha256:string;visual:VisualMeasurement|null;visualError:string|null;evidence:EvidenceRef|null}
type QualityCapture={id:string;evidence_file_id?:string|null;l_mean:number|string;a_mean:number|string;b_mean:number|string;suggested_grade:string|null;delta_e:number|string|null;operator_grade:string|null;decision:string|null;confirmed_at?:string|null;created_at:string}
type QualityPayload={captures?:QualityCapture[];permissions?:{canConfirm?:boolean};error?:string}

const grades=['A','B','C','D','E'] as const
const fmt=(value:number,digits=1)=>value.toLocaleString('es-CL',{maximumFractionDigits:digits})

function Answer({text,sources}:{text:string;sources:Source[]}){const lookup=new Map(sources.map(source=>[source.id,source])),parts=text.split(/(\[(?:receptions|production|quality|inventory|orders|canonical_sources|canonical_inventory|historical_lineage|canonical_intelligence|finance|urchin_graph|photo_observation)\])/g);return <div className="urchin-assistant-answer">{parts.map((part,index)=>{const match=/^\[([^\]]+)\]$/.exec(part),source=match?lookup.get(match[1]):null;return source?<Link key={`${part}-${index}`} to={source.path} className="urchin-assistant-citation" title={`Abrir ${source.label}`}>{part}</Link>:<span key={index}>{part}</span>})}</div>}
async function sha256File(file:File){if(!globalThis.crypto?.subtle)return'';const digest=await globalThis.crypto.subtle.digest('SHA-256',await file.arrayBuffer());return Array.from(new Uint8Array(digest)).map(value=>value.toString(16).padStart(2,'0')).join('')}
async function preparePhoto(file:File):Promise<Photo>{const [source,sourceImageSha256]=await Promise.all([new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)}),sha256File(file)]),image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Imagen inválida'));img.src=source}),max=1280,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)throw new Error('Canvas no disponible');context.drawImage(image,0,0,width,height);let visual:VisualMeasurement|null=null,visualError:string|null=null;try{const result=analyzeSegmentedCanvas(canvas),m=result.metrics;visual={confidence:result.confidence,usableRatio:result.usableRatio,borderCandidateRatio:result.borderCandidateRatio,rMean:m.rMean,gMean:m.gMean,rgbBMean:m.bMean,lMean:m.lMean,aMean:m.aMean,bMean:m.labBMean,lStd:m.lStd,aStd:m.aStd,bStd:m.bStd,dispersion:Math.sqrt(m.lStd**2+m.aStd**2+m.bStd**2),chroma:m.chroma,hueDeg:m.hueDeg,pixelCount:m.pixelCount}}catch(cause){visualError=cause instanceof Error?cause.message:'Medición objetiva no disponible'}return{id:crypto.randomUUID(),name:file.name,dataUrl:canvas.toDataURL('image/jpeg',.72),sourceImageSha256,visual,visualError,evidence:null}}

export function SeaUrchinAssistant(){
 const {pathname}=useLocation(),[params]=useSearchParams(),{operator}=useAuth(),{lots}=useLots(),visible=pathname.startsWith('/proceso-erizo'),urlReceptionId=params.get('receptionId')??''
 const erizoLots=useMemo(()=>lots.filter(lot=>String(lot.species).toLowerCase().includes('eriz')&&Boolean(lot.receptionId)),[lots])
 const [open,setOpen]=useState(false),[showLots,setShowLots]=useState(false),[receptionId,setReceptionId]=useState(''),[question,setQuestion]=useState(''),[turns,setTurns]=useState<Turn[]>([]),[photos,setPhotos]=useState<Photo[]>([]),[loading,setLoading]=useState(false),[photoLoading,setPhotoLoading]=useState(false),[evidenceBusy,setEvidenceBusy]=useState(false),[evidenceMessage,setEvidenceMessage]=useState(''),[quality,setQuality]=useState<QualityPayload|null>(null),[qualityGrade,setQualityGrade]=useState(''),[qualityBusy,setQualityBusy]=useState(false),[error,setError]=useState(''),[card,setCard]=useState<ControlCard|null>(null),[cardLoading,setCardLoading]=useState(false)
 const inputRef=useRef<HTMLTextAreaElement>(null),threadRef=useRef<HTMLDivElement>(null),photoInputRef=useRef<HTMLInputElement>(null),autoAnalyzeRef=useRef(false)
 useEffect(()=>{if(!visible){setOpen(false);return}if(urlReceptionId&&erizoLots.some(lot=>lot.receptionId===urlReceptionId)&&urlReceptionId!==receptionId){setReceptionId(urlReceptionId);setShowLots(false);setTurns([]);setEvidenceMessage('');setQuality(null);setError('')}},[visible,urlReceptionId,erizoLots,receptionId])
 useEffect(()=>{if(open)requestAnimationFrame(()=>inputRef.current?.focus())},[open]);useEffect(()=>{threadRef.current?.scrollTo({top:threadRef.current.scrollHeight,behavior:'smooth'})},[turns,loading]);useEffect(()=>{if(!open)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[open])
 useEffect(()=>{let active=true;if(!receptionId){setCard(null);setCardLoading(false);return()=>{active=false}}setCardLoading(true);void fetch(`/api/sea-urchin-control-card?receptionId=${encodeURIComponent(receptionId)}`,{cache:'no-store'}).then(async response=>{const payload=await response.json() as ControlCard;if(!response.ok)throw new Error(payload.error??'No fue posible construir el preflight');if(active)setCard(payload)}).catch(()=>{if(active)setCard(null)}).finally(()=>{if(active)setCardLoading(false)});return()=>{active=false}},[receptionId])
 const selectedLot=erizoLots.find(lot=>lot.receptionId===receptionId),plantId=selectedLot?.plantId??null,releasable=card?.summary?.japanReleasable===true,blocked=card?.summary?.japanReleasable===false,runId=card?.process?.id??''
 const canPromoteEvidence=Boolean(operator&&['admin','operations','quality'].includes(operator.role)),measuredPhotos=photos.filter(photo=>photo.visual),promotablePhotos=photos.filter(photo=>photo.visual&&!photo.evidence),pendingCapture=quality?.captures?.find(capture=>!capture.confirmed_at)??null,canConfirmQuality=quality?.permissions?.canConfirm===true
 useEffect(()=>{let active=true;if(!runId){setQuality(null);return()=>{active=false}}void fetch(`/api/sea-urchin-color?runId=${encodeURIComponent(runId)}`,{cache:'no-store'}).then(async response=>{const payload=await response.json() as QualityPayload;if(!response.ok)throw new Error(payload.error??'No fue posible cargar evidencia de Calidad');if(active)setQuality(payload)}).catch(()=>{if(active)setQuality(null)});return()=>{active=false}},[runId])
 useEffect(()=>{if(!pendingCapture){setQualityGrade('');return}const candidate=pendingCapture.operator_grade??pendingCapture.suggested_grade??card?.process?.grade??'';setQualityGrade(grades.includes(candidate as typeof grades[number])?candidate:'')},[pendingCapture?.id,pendingCapture?.operator_grade,pendingCapture?.suggested_grade,card?.process?.grade])
 const initialPrompts=useMemo(()=>photos.length?(selectedLot?['¿Coincide esta foto con el lote?','¿Esta foto cambia algo para Japón?']:['¿Qué calidad visual observas?','¿Qué dato falta para decidir?']):(selectedLot?['¿Está listo para Japón?','¿Qué lo bloquea ahora?']:['¿Qué exige Japón?','¿Qué debería fotografiar?']),[photos.length,selectedLot]),latestSuggestions=turns.at(-1)?.suggestedQuestions??[],prompts=(latestSuggestions.length?latestSuggestions:initialPrompts).slice(0,2)
 async function loadQuality(targetRunId=runId){if(!targetRunId){setQuality(null);return}const response=await fetch(`/api/sea-urchin-color?runId=${encodeURIComponent(targetRunId)}`,{cache:'no-store'}),payload=await response.json() as QualityPayload;if(!response.ok)throw new Error(payload.error??'No fue posible cargar evidencia de Calidad');setQuality(payload)}
 async function refreshControlCard(){if(!receptionId)return;const response=await fetch(`/api/sea-urchin-control-card?receptionId=${encodeURIComponent(receptionId)}`,{cache:'no-store'}),payload=await response.json() as ControlCard;if(response.ok)setCard(payload)}
 async function ask(value=question){const clean=value.trim()||(photos.length?'Analiza estas fotos y dime qué ves, qué significa y qué debería revisar después.':'');if(!clean||loading)return;setLoading(true);setError('');setQuestion('');try{const response=await fetch('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'sea_urchin_senior',question:clean,plantId,receptionId:receptionId||null,images:photos.map(photo=>photo.dataUrl),visualMeasurements:photos.map((photo,index)=>photo.visual?{index,name:photo.name,...photo.visual}:null),history:turns.slice(-6).map(turn=>({question:turn.question,answer:turn.answer}))})}),payload=await response.json() as Payload;if(!response.ok||!payload.answer||!payload.generatedAt||!payload.scope)throw new Error(payload.error??'No fue posible consultar el proceso');setTurns(current=>[...current,{id:crypto.randomUUID(),question:clean,answer:payload.answer!,sources:payload.sources??[],generatedAt:payload.generatedAt!,scope:payload.scope!,engine:payload.engine??'IA Erizo',policyVersion:payload.policyVersion??'seafood.ai.evidence.v3',suggestedQuestions:(payload.suggestedQuestions??[]).slice(0,2)}])}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible consultar el proceso')}finally{setLoading(false);requestAnimationFrame(()=>inputRef.current?.focus())}}
 useEffect(()=>{if(!autoAnalyzeRef.current||!photos.length||loading)return;autoAnalyzeRef.current=false;void ask('Analiza estas fotos. Dime qué ves, qué mide la huella visual y qué debería revisar ahora.')},[photos.length])
 function submit(event:FormEvent){event.preventDefault();void ask()} function changeLot(value:string){setReceptionId(value);setShowLots(false);setTurns([]);setEvidenceMessage('');setQuality(null);setError('');setCard(null)}
 async function ingestFiles(files:File[]){const usable=files.filter(file=>file.type.startsWith('image/')).slice(0,3-photos.length);if(!usable.length)return;setPhotoLoading(true);setEvidenceMessage('');setError('');try{const prepared=await Promise.all(usable.map(preparePhoto));autoAnalyzeRef.current=true;setPhotos(current=>[...current,...prepared].slice(0,3));setTurns([])}catch{setError('No fue posible preparar una de las fotos.')}finally{setPhotoLoading(false)}}
 async function addPhotos(event:ChangeEvent<HTMLInputElement>){const files=[...(event.target.files??[])];event.target.value='';await ingestFiles(files)} function pastePhotos(event:ClipboardEvent<HTMLTextAreaElement>){const files=[...event.clipboardData.files];if(!files.some(file=>file.type.startsWith('image/')))return;event.preventDefault();void ingestFiles(files)} function dropPhotos(event:DragEvent<HTMLElement>){event.preventDefault();void ingestFiles([...event.dataTransfer.files])}
 async function promoteEvidence(){if(!selectedLot){setShowLots(true);return}if(!runId){setEvidenceMessage('Inicia el proceso de erizo antes de guardar evidencia.');return}if(!canPromoteEvidence||!promotablePhotos.length)return;setEvidenceBusy(true);setEvidenceMessage('');setError('');const saved=new Map<string,EvidenceRef>();let duplicates=0;try{for(const photo of promotablePhotos){const m=photo.visual;if(!m)continue;const response=await fetch('/api/sea-urchin-color',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'capture',runId,fileName:`ia-erizo-${photo.id}.jpg`,mimeType:'image/jpeg',dataBase64:photo.dataUrl,captureSource:'upload',deviceLabel:'IA Erizo · Visual Twin',sourceImageSha256:photo.sourceImageSha256||null,metrics:{pixelCount:m.pixelCount,rMean:m.rMean,gMean:m.gMean,bMean:m.rgbBMean,lMean:m.lMean,aMean:m.aMean,labBMean:m.bMean,lStd:m.lStd,aStd:m.aStd,bStd:m.bStd,chroma:m.chroma,hueDeg:m.hueDeg}})}),payload=await response.json() as {capture?:{id?:string};evidenceUrl?:string;error?:string};if(response.status===409){duplicates++;continue}if(!response.ok||!payload.capture?.id)throw new Error(payload.error??'No fue posible guardar evidencia');saved.set(photo.id,{captureId:payload.capture.id,evidenceUrl:payload.evidenceUrl??null})}if(saved.size)setPhotos(current=>current.map(photo=>saved.has(photo.id)?{...photo,evidence:saved.get(photo.id)!}:photo));const parts=[] as string[];if(saved.size)parts.push(`${saved.size} foto${saved.size===1?'':'s'} guardada${saved.size===1?'':'s'} como evidencia canónica`);if(duplicates)parts.push(`${duplicates} ya registrada${duplicates===1?'':'s'}`);setEvidenceMessage(`${parts.join(' · ')}. Pendiente de confirmación humana.`);await loadQuality(runId);window.dispatchEvent(new Event('pescamar:data-updated'))}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible promover la evidencia')}finally{setEvidenceBusy(false)}}
 async function confirmQuality(decision:'accepted'|'review'|'ng'){if(!pendingCapture||!canConfirmQuality||qualityBusy)return;if(decision==='accepted'&&!qualityGrade){setEvidenceMessage('Calidad debe seleccionar Grade A–E antes de aceptar.');return}setQualityBusy(true);setEvidenceMessage('');setError('');try{const response=await fetch('/api/sea-urchin-color',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'confirm',captureId:pendingCapture.id,grade:decision==='accepted'?qualityGrade:null,decision})}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??'No fue posible confirmar evidencia');setEvidenceMessage(decision==='accepted'?`Calidad confirmó Color / Grade ${qualityGrade}.`:decision==='ng'?'Calidad marcó la evidencia como NG.':'Calidad dejó la evidencia en revisión.');await Promise.all([loadQuality(runId),refreshControlCard()]);window.dispatchEvent(new Event('pescamar:data-updated'))}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible confirmar evidencia')}finally{setQualityBusy(false)}}
 if(!visible||!operator)return null
 return <><button type="button" className={`urchin-assistant-trigger ${open?'is-open':''}`} onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-controls="urchin-assistant-panel" aria-label="Abrir IA Erizo"><span className="urchin-assistant-trigger-mark"><Sparkles size={18}/></span><span><b>IA Erizo</b><small>{selectedLot?selectedLot.id:photos.length?`${photos.length} foto${photos.length===1?'':'s'}`:'Pregunta o fotografía'}</small></span></button>{open?<><button className="urchin-assistant-backdrop" type="button" onClick={()=>setOpen(false)} aria-label="Cerrar asistente"/><aside id="urchin-assistant-panel" className="urchin-assistant-panel" aria-label="IA Erizo" onDragOver={event=>event.preventDefault()} onDrop={dropPhotos}>
 <header className="urchin-assistant-head"><div><span className="urchin-assistant-icon"><Sparkles size={18}/></span><div><small>Seafood AI</small><b>IA Erizo</b></div></div><button type="button" onClick={()=>setOpen(false)} aria-label="Cerrar"><X size={18}/></button></header>
 <div className="urchin-assistant-tools"><button type="button" onClick={()=>photoInputRef.current?.click()} disabled={photos.length>=3||photoLoading}><Camera size={16}/>{photoLoading?'Midiendo…':'Foto'}</button><button type="button" className={selectedLot?'is-linked':''} onClick={()=>setShowLots(value=>!value)}><Link2 size={15}/>{selectedLot?'Lote vinculado':'Agregar lote'}</button><input ref={photoInputRef} className="sr-only" type="file" accept="image/*" capture="environment" multiple onChange={addPhotos}/></div>
 {showLots?<div className="urchin-assistant-lot-picker"><select autoFocus value={receptionId} onChange={event=>changeLot(event.target.value)}><option value="">Sin lote</option>{erizoLots.map(lot=><option key={lot.receptionId} value={lot.receptionId}>{lot.id} · {lot.supplier}</option>)}</select></div>:null}
 {selectedLot?<div className={`urchin-assistant-mini-status ${releasable?'ready':blocked?'blocked':''}`}><strong>{cardLoading?'Verificando…':releasable?'APTO JAPÓN':blocked?'NO LIBERADO':'Estado pendiente'}</strong><span>{selectedLot.id} · Grade {card?.process?.grade??'—'} · {card?.diagnosis?.blockers?.length??0} bloqueo{card?.diagnosis?.blockers?.length===1?'':'s'}</span></div>:null}
 {photos.length?<><div className="urchin-assistant-photos">{photos.map(photo=><figure key={photo.id}><img src={photo.dataUrl} alt="Foto adjunta para análisis"/><button type="button" onClick={()=>{setPhotos(current=>current.filter(item=>item.id!==photo.id));setTurns([]);setEvidenceMessage('')}} aria-label="Quitar foto"><X size={12}/></button></figure>)}<small>Análisis instantáneo · pega o arrastra más fotos.</small></div><details className="urchin-visual-twin"><summary><Target size={14}/><span>Visual Twin</span><b>{measuredPhotos.length?`${measuredPhotos.length}/${photos.length} huella${measuredPhotos.length===1?'':'s'} objetiva${measuredPhotos.length===1?'':'s'}`:'sólo observación visual'}</b></summary><div>{photos.map((photo,index)=>photo.visual?<p key={photo.id}><strong>Foto {index+1}</strong><span>LAB {fmt(photo.visual.lMean)} / {fmt(photo.visual.aMean)} / {fmt(photo.visual.bMean)} · dispersión {fmt(photo.visual.dispersion)} · roe {Math.round(photo.visual.usableRatio*100)}% · {photo.visual.confidence==='good'?'medición estable':'revisar captura'}{photo.evidence?' · evidencia guardada':''}</span></p>:<p key={photo.id}><strong>Foto {index+1}</strong><span>{photo.visualError??'Huella objetiva no disponible'}; la IA visual igual puede describirla.</span></p>)}<div className="urchin-visual-twin-actions">{selectedLot?(runId?(canPromoteEvidence&&promotablePhotos.length?<button type="button" onClick={()=>void promoteEvidence()} disabled={evidenceBusy}><ShieldCheck size={14}/>{evidenceBusy?'Guardando…':`Guardar evidencia${promotablePhotos.length>1?` · ${promotablePhotos.length}`:''}`}</button>:<small>{promotablePhotos.length?'Tu rol puede consultar, pero no registrar evidencia.':'Visual Twin ya registrado como evidencia.'}</small>):<small>Inicia el proceso de erizo para promover la foto a evidencia canónica.</small>):measuredPhotos.length?<button type="button" onClick={()=>setShowLots(true)}><Link2 size={14}/>Vincular lote para guardar evidencia</button>:null}{evidenceMessage?<small className="is-success">{evidenceMessage}</small>:null}</div></div></details></>:null}
 {selectedLot&&pendingCapture&&canConfirmQuality?<section className="urchin-quality-decision" aria-label="Decisión de Calidad"><div className="urchin-quality-evidence">{pendingCapture.evidence_file_id?<img src={`/api/reception-evidence-file?id=${encodeURIComponent(pendingCapture.evidence_file_id)}`} alt="Evidencia pendiente de Calidad"/>:<span><ShieldCheck size={18}/></span>}<div><small>Calidad · evidencia pendiente</small><strong>{pendingCapture.suggested_grade?`Referencia más cercana: Grade ${pendingCapture.suggested_grade}`:'Sin Grade sugerido'}</strong><p>LAB {fmt(Number(pendingCapture.l_mean))} / {fmt(Number(pendingCapture.a_mean))} / {fmt(Number(pendingCapture.b_mean))}{pendingCapture.delta_e!=null?` · ΔE ${fmt(Number(pendingCapture.delta_e))}`:''}</p></div></div><div className="urchin-quality-controls"><label>Grade<select value={qualityGrade} onChange={event=>setQualityGrade(event.target.value)} disabled={qualityBusy}><option value="">—</option>{grades.map(grade=><option value={grade} key={grade}>{grade}</option>)}</select></label><button type="button" className="is-primary" onClick={()=>void confirmQuality('accepted')} disabled={qualityBusy||!qualityGrade}><CheckCircle2 size={14}/>{qualityBusy?'Guardando…':`Confirmar${qualityGrade?` ${qualityGrade}`:''}`}</button><button type="button" onClick={()=>void confirmQuality('review')} disabled={qualityBusy}>Revisión</button><button type="button" onClick={()=>void confirmQuality('ng')} disabled={qualityBusy}>NG</button></div><small className="urchin-quality-note">Confirmación humana. Cambia Color / Grade del lote, pero no libera Japón por sí sola.</small></section>:null}
 <div ref={threadRef} className="urchin-assistant-thread" aria-live="polite">{turns.length?turns.map(turn=><article className="urchin-assistant-turn" key={turn.id}><div className="urchin-assistant-user">{turn.question}</div><div className="urchin-assistant-response"><span><Sparkles size={15}/></span><div><Answer text={turn.answer} sources={turn.sources}/>{turn.sources.length?<details><summary>Ver evidencia</summary><div className="urchin-assistant-sources">{turn.sources.map(source=><Link key={source.id} to={source.path}>{source.label}<ExternalLink size={12}/></Link>)}</div></details>:null}</div></div></article>):<div className="urchin-assistant-empty"><h3>{photos.length?'Construyendo Visual Twin…':'Pregunta o agrega una foto'}</h3><p>{selectedLot?'Cruzaré observación, huella CIELAB y Digital Twin del lote.':'La foto se analiza visualmente y, si contiene roe medible, genera una huella CIELAB objetiva. El lote sigue siendo opcional.'}</p></div>}{loading?<div className="urchin-assistant-thinking"><span/><span/><span/>Analizando…</div>:null}{error?<div className="urchin-assistant-error" role="alert">{error}</div>:null}</div>
 <div className="urchin-assistant-prompts">{prompts.map(prompt=><button type="button" key={prompt} onClick={()=>void ask(prompt)} disabled={loading}>{prompt}<ChevronRight size={13}/></button>)}</div>
 <form className="urchin-assistant-composer" onSubmit={submit}><textarea ref={inputRef} rows={2} maxLength={1800} value={question} onChange={event=>setQuestion(event.target.value)} onPaste={pastePhotos} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void ask()}}} placeholder="Pregunta o pega una foto…" disabled={loading}/><button type="submit" disabled={loading||(!question.trim()&&!photos.length)} aria-label="Enviar"><Send size={17}/></button></form>
 </aside></>:null}</>}
