import {Camera,ChevronRight,ExternalLink,Send,Sparkles,X} from 'lucide-react'
import {useEffect,useMemo,useRef,useState,type ChangeEvent,type FormEvent} from 'react'
import {Link,useLocation,useSearchParams} from 'react-router-dom'
import {useAuth} from '../auth'
import {useLots} from '../store'
import './sea-urchin-assistant.css'

type EvidenceClass='live_observation'|'derived_live'|'canonical_reference'|'canonical_history'|'partial_financial'
type Source={id:string;label:string;path:string;rows:number;freshness:string|null;evidenceClass?:EvidenceClass}
type Scope={plantId:string|null;plantIds:string[];role:string;organizationId?:string}
type Turn={id:string;question:string;answer:string;sources:Source[];generatedAt:string;scope:Scope;engine:string;policyVersion:string;suggestedQuestions:string[]}
type Payload={answer?:string;engine?:string;policyVersion?:string;generatedAt?:string;scope?:Scope;sources?:Source[];suggestedQuestions?:string[];error?:string}
type ControlCard={ok?:boolean;process?:{grade?:string|null;colorStatus?:string|null;xrayStatus?:string|null}|null;diagnosis?:{state?:string;blockers?:string[];nextAction?:string;unknowns?:string[]}|null;summary?:{japanReleasable?:boolean|null;deviations?:number;blockingHolds?:number}|null;error?:string}
type Photo={id:string;name:string;dataUrl:string}

function Answer({text,sources}:{text:string;sources:Source[]}){const lookup=new Map(sources.map(source=>[source.id,source])),parts=text.split(/(\[(?:receptions|production|quality|inventory|orders|canonical_sources|canonical_inventory|historical_lineage|canonical_intelligence|finance|urchin_graph|photo_observation)\])/g);return <div className="urchin-assistant-answer">{parts.map((part,index)=>{const match=/^\[([^\]]+)\]$/.exec(part),source=match?lookup.get(match[1]):null;return source?<Link key={`${part}-${index}`} to={source.path} className="urchin-assistant-citation" title={`Abrir ${source.label}`}>{part}</Link>:<span key={index}>{part}</span>})}</div>}

async function preparePhoto(file:File):Promise<Photo>{
 const source=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})
 const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Imagen inválida'));img.src=source})
 const max=1280,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d')?.drawImage(image,0,0,width,height)
 const dataUrl=canvas.toDataURL('image/jpeg',.72)
 return{id:crypto.randomUUID(),name:file.name,dataUrl}
}

export function SeaUrchinAssistant(){
 const {pathname}=useLocation(),[params]=useSearchParams(),{operator}=useAuth(),{lots}=useLots(),visible=pathname.startsWith('/proceso-erizo'),urlReceptionId=params.get('receptionId')??''
 const erizoLots=useMemo(()=>lots.filter(lot=>String(lot.species).toLowerCase().includes('eriz')&&Boolean(lot.receptionId)),[lots])
 const [open,setOpen]=useState(false),[receptionId,setReceptionId]=useState(''),[question,setQuestion]=useState(''),[turns,setTurns]=useState<Turn[]>([]),[photos,setPhotos]=useState<Photo[]>([]),[loading,setLoading]=useState(false),[photoLoading,setPhotoLoading]=useState(false),[error,setError]=useState(''),[card,setCard]=useState<ControlCard|null>(null),[cardLoading,setCardLoading]=useState(false)
 const inputRef=useRef<HTMLTextAreaElement>(null),threadRef=useRef<HTMLDivElement>(null),photoInputRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{if(!visible){setOpen(false);return}if(urlReceptionId&&erizoLots.some(lot=>lot.receptionId===urlReceptionId)&&urlReceptionId!==receptionId){setReceptionId(urlReceptionId);setTurns([]);setError('')}},[visible,urlReceptionId,erizoLots,receptionId])
 useEffect(()=>{if(open)requestAnimationFrame(()=>inputRef.current?.focus())},[open])
 useEffect(()=>{threadRef.current?.scrollTo({top:threadRef.current.scrollHeight,behavior:'smooth'})},[turns,loading])
 useEffect(()=>{if(!open)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[open])
 useEffect(()=>{let active=true;if(!receptionId){setCard(null);setCardLoading(false);return()=>{active=false}}setCardLoading(true);void fetch(`/api/sea-urchin-control-card?receptionId=${encodeURIComponent(receptionId)}`,{cache:'no-store'}).then(async response=>{const payload=await response.json() as ControlCard;if(!response.ok)throw new Error(payload.error??'No fue posible construir el preflight');if(active)setCard(payload)}).catch(()=>{if(active)setCard(null)}).finally(()=>{if(active)setCardLoading(false)});return()=>{active=false}},[receptionId])
 const selectedLot=erizoLots.find(lot=>lot.receptionId===receptionId),plantId=selectedLot?.plantId??null,releasable=card?.summary?.japanReleasable===true,blocked=card?.summary?.japanReleasable===false
 const initialPrompts=useMemo(()=>photos.length?(selectedLot?['¿Qué ves y cómo se compara con este lote?','¿Ves defectos o señales de riesgo?','¿Esta foto cambia algo para Japón?']:['¿Qué ves en esta foto?','¿Qué calidad parece tener?','¿Qué dato falta para poder decidir?']):(selectedLot?['¿Está listo para Japón?','¿Qué lo bloquea ahora?','Descríbeme este lote en simple']:['¿Qué exige Japón?','¿Qué evidencia debería fotografiar?','¿Qué debería revisar primero?']),[photos.length,selectedLot])
 const latestSuggestions=turns.at(-1)?.suggestedQuestions??[]
 const prompts=latestSuggestions.length?latestSuggestions:initialPrompts
 async function ask(value=question){const clean=value.trim()||(photos.length?'Analiza estas fotos y dime qué ves, qué significa y qué debería revisar después.':'');if(!clean||loading)return;setLoading(true);setError('');setQuestion('');try{const response=await fetch('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'sea_urchin_senior',question:clean,plantId,receptionId:receptionId||null,images:photos.map(photo=>photo.dataUrl),history:turns.slice(-6).map(turn=>({question:turn.question,answer:turn.answer}))})}),payload=await response.json() as Payload;if(!response.ok||!payload.answer||!payload.generatedAt||!payload.scope)throw new Error(payload.error??'No fue posible consultar el proceso');setTurns(current=>[...current,{id:crypto.randomUUID(),question:clean,answer:payload.answer!,sources:payload.sources??[],generatedAt:payload.generatedAt!,scope:payload.scope!,engine:payload.engine??'IA Erizo',policyVersion:payload.policyVersion??'seafood.ai.evidence.v3',suggestedQuestions:(payload.suggestedQuestions??[]).slice(0,3)}])}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible consultar el proceso')}finally{setLoading(false);requestAnimationFrame(()=>inputRef.current?.focus())}}
 function submit(event:FormEvent){event.preventDefault();void ask()}
 function changeLot(value:string){setReceptionId(value);setTurns([]);setError('');setCard(null)}
 async function addPhotos(event:ChangeEvent<HTMLInputElement>){const files=[...(event.target.files??[])].filter(file=>file.type.startsWith('image/')).slice(0,3-photos.length);event.target.value='';if(!files.length)return;setPhotoLoading(true);setError('');try{const prepared=await Promise.all(files.map(preparePhoto));setPhotos(current=>[...current,...prepared].slice(0,3));setTurns([])}catch{setError('No fue posible preparar una de las fotos.')}finally{setPhotoLoading(false)}}
 if(!visible||!operator)return null
 return <>
  <button type="button" className={`urchin-assistant-trigger ${open?'is-open':''}`} onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-controls="urchin-assistant-panel" aria-label="Abrir IA Erizo"><span className="urchin-assistant-trigger-mark"><Sparkles size={18}/></span><span><b>IA Erizo</b><small>{selectedLot?selectedLot.id:photos.length?`${photos.length} foto${photos.length===1?'':'s'}`:'Pregunta o fotografía'}</small></span></button>
  {open?<><button className="urchin-assistant-backdrop" type="button" onClick={()=>setOpen(false)} aria-label="Cerrar asistente"/><aside id="urchin-assistant-panel" className="urchin-assistant-panel" aria-label="IA Erizo">
   <header className="urchin-assistant-head"><div><span className="urchin-assistant-icon"><Sparkles size={18}/></span><div><small>Seafood AI</small><b>IA Erizo</b></div></div><button type="button" onClick={()=>setOpen(false)} aria-label="Cerrar"><X size={18}/></button></header>
   <div className="urchin-assistant-tools"><label><span>Lote <em>opcional</em></span><select value={receptionId} onChange={event=>changeLot(event.target.value)}><option value="">Sin lote</option>{erizoLots.map(lot=><option key={lot.receptionId} value={lot.receptionId}>{lot.id} · {lot.supplier}</option>)}</select></label><button type="button" onClick={()=>photoInputRef.current?.click()} disabled={photos.length>=3||photoLoading}><Camera size={16}/>{photoLoading?'Preparando…':'Agregar foto'}</button><input ref={photoInputRef} className="sr-only" type="file" accept="image/*" capture="environment" multiple onChange={addPhotos}/></div>
   {selectedLot?<div className={`urchin-assistant-mini-status ${releasable?'ready':blocked?'blocked':''}`}><strong>{cardLoading?'Verificando…':releasable?'APTO JAPÓN':blocked?'NO LIBERADO':'Estado pendiente'}</strong><span>Grade {card?.process?.grade??'—'} · {card?.diagnosis?.blockers?.length??0} bloqueo{card?.diagnosis?.blockers?.length===1?'':'s'}</span></div>:null}
   {photos.length?<div className="urchin-assistant-photos">{photos.map(photo=><figure key={photo.id}><img src={photo.dataUrl} alt="Foto adjunta para análisis"/><button type="button" onClick={()=>{setPhotos(current=>current.filter(item=>item.id!==photo.id));setTurns([])}} aria-label="Quitar foto"><X size={12}/></button></figure>)}<small>Las fotos se analizan en esta conversación; no reemplazan controles ni liberaciones.</small></div>:null}
   <div ref={threadRef} className="urchin-assistant-thread" aria-live="polite">{turns.length?turns.map(turn=><article className="urchin-assistant-turn" key={turn.id}><div className="urchin-assistant-user">{turn.question}</div><div className="urchin-assistant-response"><span><Sparkles size={15}/></span><div><Answer text={turn.answer} sources={turn.sources}/>{turn.sources.length?<details><summary>Ver evidencia</summary><div className="urchin-assistant-sources">{turn.sources.map(source=><Link key={source.id} to={source.path}>{source.label}<ExternalLink size={12}/></Link>)}</div></details>:null}</div></div></article>):<div className="urchin-assistant-empty"><h3>{photos.length?'Analizo tus fotos y la operación':'Pregunta, fotografía o elige un lote'}</h3><p>{selectedLot?'Tengo el Digital Twin de este lote.':'El lote es opcional. Puedo trabajar con fotos y data canónica; para liberar Japón necesito un lote específico.'}</p></div>}{loading?<div className="urchin-assistant-thinking"><span/><span/><span/>Analizando…</div>:null}{error?<div className="urchin-assistant-error" role="alert">{error}</div>:null}</div>
   <div className="urchin-assistant-prompts"><small>{latestSuggestions.length?'Siguiente pregunta sugerida':'Puedes empezar por aquí'}</small>{prompts.map(prompt=><button type="button" key={prompt} onClick={()=>void ask(prompt)} disabled={loading}>{prompt}<ChevronRight size={13}/></button>)}</div>
   <form className="urchin-assistant-composer" onSubmit={submit}><textarea ref={inputRef} rows={2} maxLength={1800} value={question} onChange={event=>setQuestion(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void ask()}}} placeholder={photos.length?'Pregunta por estas fotos…':'Pregunta lo que necesites…'} disabled={loading}/><button type="submit" disabled={loading||(!question.trim()&&!photos.length)} aria-label="Enviar"><Send size={17}/></button></form>
  </aside></>:null}
 </>
}
