import {AlertTriangle,CheckCircle2,MapPin,Scale,ShieldCheck,TrendingUp} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import type {Species} from '../types'
import './supplier-reception-decision.css'

type ScoreZone={zone:string;lots:number;receivedKg:number;gradeAYieldPct:number|null;totalYieldPct:number|null}
type SupplierScore={supplier:string;score:number|null;label:string;confidence:'alta'|'media'|'baja';coverage:number;lots:number;receivedKg:number;zones:ScoreZone[];explanation:string}
type ScorePayload={suppliers?:SupplierScore[];error?:string}
type PricePayload={matched?:boolean;supplier?:string;suggestions?:string[];price?:{observations:number;receivedKg:number;avgPriceClp:number|null;latestPriceClp:number|null;minPriceClp:number|null;maxPriceClp:number|null};zone?:{name:string;observations:number;receivedKg:number;supplierAvgPriceClp:number|null;peerAvgPriceClp:number|null;relativeToZonePct:number|null}|null;error?:string}
const normalize=(value:string)=>value.trim().replace(/\s+/g,' ').toLocaleLowerCase('es')
const clp=(value:number|null|undefined)=>value==null?'—':new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(value)
function decisionFor(score:SupplierScore|null,relative:number|null|undefined){
 if(!score||score.score==null||score.coverage<40)return {label:'Evidencia insuficiente',tone:'neutral',detail:'Registrar la recepción; el sistema seguirá aprendiendo del proveedor.'}
 if(score.score>=85&&score.confidence!=='baja'&&(relative==null||relative<=10))return {label:'Priorizar',tone:'good',detail:'Desempeño sólido y evidencia suficiente para favorecer este proveedor.'}
 if(score.score>=75)return {label:'Favorable',tone:'good',detail:'Buen desempeño histórico; validar calidad del lote recibido.'}
 if(score.score>=60)return {label:'Comprar con control',tone:'watch',detail:'Proveedor utilizable, pero conviene reforzar revisión de calidad y rendimiento.'}
 return {label:'Revisar antes de comprar',tone:'risk',detail:'El desempeño observado justifica revisar condiciones y calidad antes de ampliar compra.'}
}
export function SupplierReceptionDecision({supplier,zone,species,onUseSupplier}:{supplier:string;zone:string;species:Species;onUseSupplier?:(supplier:string)=>void}){
 const [scoreData,setScoreData]=useState<ScorePayload|null>(null),[priceData,setPriceData]=useState<PricePayload|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(species!=='Erizo'||supplier.trim().length<2){setScoreData(null);setPriceData(null);setError('');return}let active=true;const timer=window.setTimeout(()=>{setLoading(true);setError('');void Promise.all([fetch('/api/supplier-intelligence',{cache:'no-store'}).then(async response=>{const payload=await response.json() as ScorePayload;if(!response.ok)throw new Error(payload.error??'No fue posible calcular el score');return payload}),fetch(`/api/supplier-price-context?supplier=${encodeURIComponent(supplier.trim())}&zone=${encodeURIComponent(zone.trim())}`,{cache:'no-store'}).then(async response=>{const payload=await response.json() as PricePayload;if(!response.ok)throw new Error(payload.error??'No fue posible calcular el precio relativo');return payload})]).then(([scores,prices])=>{if(active){setScoreData(scores);setPriceData(prices)}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'No fue posible cargar Supplier Intelligence')}).finally(()=>{if(active)setLoading(false)})},320);return()=>{active=false;window.clearTimeout(timer)}},[supplier,zone,species])
 const score=useMemo(()=>scoreData?.suppliers?.find(item=>normalize(item.supplier)===normalize(supplier))??null,[scoreData,supplier])
 const zoneScore=useMemo(()=>score?.zones.find(item=>normalize(item.zone)===normalize(zone))??null,[score,zone])
 if(species!=='Erizo'||supplier.trim().length<2)return null
 if(loading&&!scoreData&&!priceData)return <section className="supplier-reception-decision loading"><ShieldCheck size={17}/><div><b>Consultando Supplier Intelligence</b><small>Calidad, rendimiento, zona y precio histórico.</small></div></section>
 if(error)return <section className="supplier-reception-decision error"><AlertTriangle size={17}/><div><b>Supplier Intelligence no disponible</b><small>{error}. La recepción puede continuar.</small></div></section>
 if(!score&&priceData?.matched===false){const suggestions=priceData.suggestions??[];return <section className="supplier-reception-decision neutral"><ShieldCheck size={17}/><div className="supplier-decision-empty"><b>Proveedor sin coincidencia exacta</b><small>La recepción puede continuar, pero no asignaremos un score a una identidad dudosa.</small>{suggestions.length?<div className="supplier-suggestions"><span>¿Corresponde a:</span>{suggestions.slice(0,3).map(item=><button type="button" key={item} onClick={()=>onUseSupplier?.(item)}>{item}</button>)}</div>:null}</div></section>}
 if(!score)return <section className="supplier-reception-decision neutral"><ShieldCheck size={17}/><div><b>Proveedor nuevo o sin historia comparable</b><small>Se registrará la recepción y el score comenzará a construirse con evidencia real.</small></div></section>
 const relative=priceData?.zone?.relativeToZonePct,decision=decisionFor(score,relative),Icon=decision.tone==='good'?CheckCircle2:decision.tone==='risk'?AlertTriangle:ShieldCheck
 return <section className={`supplier-reception-decision ${decision.tone}`} aria-label="Recomendación de proveedor"><div className="supplier-decision-head"><div className="supplier-decision-verdict"><Icon size={18}/><div><span className="overline">Supplier Intelligence · decisión de compra</span><h3>{decision.label}</h3><small>{decision.detail}</small></div></div><div className="supplier-decision-score"><b>{score.score==null?'—':score.score.toFixed(0)}</b><span>/100</span><small>{score.label} · confianza {score.confidence}</small></div></div><div className="supplier-decision-grid"><article><ShieldCheck size={15}/><div><small>Cobertura</small><b>{score.coverage}%</b><span>{score.lots} lotes · {score.explanation}</span></div></article><article><MapPin size={15}/><div><small>{zone.trim()?`Zona ${zone.trim()}`:'Zona'}</small><b>{zoneScore?.gradeAYieldPct==null?'Sin muestra':`${zoneScore.gradeAYieldPct.toFixed(1)}% Grade A`}</b><span>{zoneScore?`${zoneScore.lots} lotes · ${zoneScore.receivedKg.toLocaleString('es-CL',{maximumFractionDigits:0})} kg`:'Aún no existe evidencia comparable en esta zona.'}</span></div></article><article><Scale size={15}/><div><small>Precio histórico proveedor</small><b>{clp(priceData?.price?.avgPriceClp)} / kg</b><span>{priceData?.price?.observations?`${priceData.price.observations} registros con precio`:'Sin precio histórico suficiente'}</span></div></article><article><TrendingUp size={15}/><div><small>Precio relativo en zona</small><b>{relative==null?'Sin comparación':`${relative>0?'+':''}${relative.toFixed(1)}%`}</b><span>{priceData?.zone?.peerAvgPriceClp==null?'Falta referencia de pares en esta zona.':`Proveedor ${clp(priceData.zone.supplierAvgPriceClp)} vs zona ${clp(priceData.zone.peerAvgPriceClp)} / kg`}</span></div></article></div><p className="supplier-decision-footnote">Recomendación explicable basada en datos históricos y live. No bloquea la recepción ni reemplaza el control de calidad del lote.</p></section>
}
