import {AlertTriangle,Camera,CheckCircle2,Database,ImagePlus,ScanLine,ShieldCheck,Target} from 'lucide-react'
import {useEffect,useRef,useState,type ChangeEvent} from 'react'

type Metrics={pixelCount:number;rMean:number;gMean:number;bMean:number;lMean:number;aMean:number;labBMean:number;lStd:number;aStd:number;bStd:number;chroma:number;hueDeg:number}
type Capture={id:string;evidence_file_id:string;l_mean:number|string;a_mean:number|string;b_mean:number|string;l_std:number|string;a_std:number|string;b_std:number|string;chroma:number|string;hue_deg:number|string;suggested_grade:string|null;delta_e:number|string|null;operator_grade:string|null;decision:string;created_at:string}
type Reference={id:string;grade:string;label:string|null;l_mean:number|string;a_mean:number|string;b_mean:number|string;created_at:string}
type Payload={captures?:Capture[];references?:Reference[];permissions?:{canWrite:boolean;canManageReferences:boolean};error?:string}
type SavedCapture=Capture&{evidenceUrl?:string}
const grades=['A','B','C','D','E'] as const
const fmt=(value:unknown,digits=1)=>Number(value??0).toLocaleString('es-CL',{maximumFractionDigits:digits})

export function UniVisionStation({runId,plantId,currentGrade,onChanged}:{runId:string;plantId:string|null;currentGrade:string|null;onChanged:()=>Promise<void>}){
 const videoRef=useRef<HTMLVideoElement|null>(null),streamRef=useRef<MediaStream|null>(null),fileRef=useRef<HTMLInputElement|null>(null)
 const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[cameraOn,setCameraOn]=useState(false),[deviceLabel,setDeviceLabel]=useState('')
 const [preview,setPreview]=useState(''),[metrics,setMetrics]=useState<Metrics|null>(null),[source,setSource]=useState<'camera'|'upload'>('camera'),[saved,setSaved]=useState<SavedCapture|null>(null)
 const [grade,setGrade]=useState(currentGrade??''),[decision,setDecision]=useState<'accepted'|'review'|'ng'>('review'),[referenceLabel,setReferenceLabel]=useState('')
 async function load(){try{const response=await fetch(`/api/sea-urchin-color?runId=${encodeURIComponent(runId)}`,{cache:'no-store'}),payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error??'No fue posible cargar Uni Vision');setData(payload);setError('')}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible cargar Uni Vision')}}
 useEffect(()=>{void load();return()=>stopCamera()},[runId])
 useEffect(()=>{if(currentGrade)setGrade(currentGrade)},[currentGrade])
 function stopCamera(){streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setCameraOn(false)}
 async function startCamera(){setError('');try{stopCamera();const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});streamRef.current=stream;const video=videoRef.current;if(!video)throw new Error('Cámara no disponible');video.srcObject=stream;await video.play();setDeviceLabel(stream.getVideoTracks()[0]?.label??'Cámara');setCameraOn(true);setSource('camera')}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible abrir la cámara')}}
 function captureCamera(){const video=videoRef.current;if(!video||!video.videoWidth||!video.videoHeight)return setError('La cámara aún no está lista');const canvas=drawToCanvas(video,video.videoWidth,video.videoHeight),result=analyzeCanvas(canvas);setPreview(canvas.toDataURL('image/jpeg',0.86));setMetrics(result);setSource('camera');setSaved(null);setError('')}
 async function chooseFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type))return setError('Usa JPG, PNG o WebP');setBusy('file');try{const image=await readImage(file),canvas=drawToCanvas(image,image.naturalWidth,image.naturalHeight),result=analyzeCanvas(canvas);setPreview(canvas.toDataURL('image/jpeg',0.86));setMetrics(result);setSource('upload');setDeviceLabel(file.name);setSaved(null);setError('')}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible leer la imagen')}finally{setBusy('');if(fileRef.current)fileRef.current.value=''}}
 async function saveMeasurement(){if(!preview||!metrics)return;setBusy('save');setError('');try{const response=await fetch('/api/sea-urchin-color',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'capture',runId,fileName:`uni-${runId.slice(0,8)}-${Date.now()}.jpg`,mimeType:'image/jpeg',dataBase64:preview,captureSource:source,deviceLabel,metrics})}),payload=await response.json() as {capture?:Capture;evidenceUrl?:string;error?:string};if(!response.ok)throw new Error(payload.error??'No fue posible guardar medición');const capture=payload.capture?{...payload.capture,evidenceUrl:payload.evidenceUrl}:null;setSaved(capture);if(capture?.suggested_grade&&!grade)setGrade(capture.suggested_grade);await load()}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible guardar medición')}finally{setBusy('')}}
 async function saveReference(){if(!saved?.id||!grade)return;setBusy('reference');setError('');try{const response=await fetch('/api/sea-urchin-color',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reference',captureId:saved.id,grade,label:referenceLabel||`Referencia ${grade}`})}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??'No fue posible guardar referencia');setReferenceLabel('');await load()}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible guardar referencia')}finally{setBusy('')}}
 async function confirm(){if(!saved?.id||decision==='accepted'&&!grade)return;setBusy('confirm');setError('');try{const response=await fetch('/api/sea-urchin-color',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'confirm',captureId:saved.id,grade:grade||null,decision})}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??'No fue posible confirmar color');window.dispatchEvent(new Event('pescamar:data-updated'));await Promise.all([load(),onChanged()])}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible confirmar color')}finally{setBusy('')}}
 const latest=saved??data?.captures?.[0]??null,references=data?.references??[]
 return <section className="panel" aria-label="Uni Vision Station">
  <div className="section-heading"><div><span className="overline">Uni Vision Station · color objetivo</span><h2>Medir antes de clasificar</h2></div><ScanLine size={20}/></div>
  <div className="notice"><ShieldCheck size={16}/><div><b>La medición no libera el lote por sí sola</b><small>Usa luz y distancia fijas. El sistema mide CIELAB y ΔE; un operador confirma el resultado antes de actualizar Color/Grade.</small></div></div>
  {error?<div className="notice error"><AlertTriangle size={16}/><div><b>Uni Vision</b><small>{error}</small></div></div>:null}
  <div className="commercial-form-grid">
   <div><video ref={videoRef} muted playsInline style={{display:cameraOn?'block':'none',width:'100%',maxHeight:340,objectFit:'cover',background:'#111'}}/>{!cameraOn&&preview?<img src={preview} alt="Muestra de roe para medición" style={{width:'100%',maxHeight:340,objectFit:'cover'}}/>:!cameraOn?<div className="empty-inline"><Camera size={24}/><div><b>Estación lista</b><small>Centra el roe ocupando la zona media del cuadro.</small></div></div>:null}</div>
   <div><div className="row-actions"><button type="button" className="button" onClick={()=>void startCamera()} disabled={!!busy}><Camera size={15}/>{cameraOn?'Reiniciar cámara':'Abrir cámara'}</button>{cameraOn?<button type="button" className="button primary" onClick={captureCamera}><Target size={15}/>Capturar y medir</button>:null}<input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>void chooseFile(event)}/><button type="button" className="button" onClick={()=>fileRef.current?.click()} disabled={!!busy}><ImagePlus size={15}/>Usar foto</button></div>{plantId?<p className="source-note">Referencia por planta: {plantId}</p>:<p className="source-note">Este lote no tiene planta explícita; no se sugerirá grade por referencia.</p>}</div>
  </div>
  {metrics?<><div className="signal-grid"><article className="signal-card"><span><Database size={16}/>L*</span><b>{fmt(metrics.lMean,2)}</b><small>Luminosidad</small></article><article className="signal-card"><span><Database size={16}/>a*</span><b>{fmt(metrics.aMean,2)}</b><small>verde ↔ rojo</small></article><article className="signal-card"><span><Database size={16}/>b*</span><b>{fmt(metrics.labBMean,2)}</b><small>azul ↔ amarillo</small></article><article className="signal-card"><span><Target size={16}/>Dispersión</span><b>{fmt(Math.sqrt(metrics.lStd**2+metrics.aStd**2+metrics.bStd**2),2)}</b><small>{metrics.pixelCount.toLocaleString('es-CL')} píxeles muestreados</small></article></div>{data?.permissions?.canWrite?<button type="button" className="button primary" disabled={!!busy} onClick={()=>void saveMeasurement()}>{busy==='save'?'Guardando…':'Guardar medición y evidencia'}</button>:null}</>:null}
  {latest?<div className="notice"><Target size={16}/><div><b>{latest.suggested_grade?`Referencia más cercana: Grade ${latest.suggested_grade}`:'Medición sin referencia de planta'}</b><small>LAB {fmt(latest.l_mean,2)} / {fmt(latest.a_mean,2)} / {fmt(latest.b_mean,2)}{latest.delta_e!=null?` · ΔE ${fmt(latest.delta_e,2)}`:''}. Es una sugerencia explicable, no una aprobación automática.</small></div></div>:null}
  {saved&&data?.permissions?.canWrite?<div className="commercial-form-grid"><label>Grade confirmado<select value={grade} onChange={event=>setGrade(event.target.value)}><option value="">Sin grade aún</option>{grades.map(value=><option value={value} key={value}>{value}</option>)}</select></label><label>Decisión color<select value={decision} onChange={event=>setDecision(event.target.value as 'accepted'|'review'|'ng')}><option value="accepted">Aceptado</option><option value="review">Revisión</option><option value="ng">NG</option></select></label><button type="button" className="button primary" disabled={!!busy||decision==='accepted'&&!grade} onClick={()=>void confirm()}><CheckCircle2 size={15}/>{busy==='confirm'?'Confirmando…':'Confirmar control de color'}</button>{data.permissions.canManageReferences?<><label>Nombre referencia<input value={referenceLabel} onChange={event=>setReferenceLabel(event.target.value)} placeholder="Ej. A dorado turno AM"/></label><button type="button" className="button" disabled={!!busy||!grade} onClick={()=>void saveReference()}><Target size={15}/>{busy==='reference'?'Guardando…':`Fijar como referencia ${grade||''}`}</button></>:null}</div>:null}
  <div className="section-heading"><div><span className="overline">Referencias reales</span><h3>Biblioteca de planta</h3></div><span>{references.length}</span></div>{references.length?<div className="compact-ledger">{references.map(reference=><div key={reference.id} className="alert-row static"><span><ShieldCheck size={15}/></span><div><b>Grade {reference.grade} · {reference.label??'Referencia aprobada'}</b><small>LAB {fmt(reference.l_mean,2)} / {fmt(reference.a_mean,2)} / {fmt(reference.b_mean,2)}</small></div></div>)}</div>:<div className="empty-inline"><Database size={20}/><div><b>Sin referencias aprobadas</b><small>La estación operará sólo como instrumento de medición hasta que Calidad fije muestras reales A–E.</small></div></div>}
 </section>
}

function drawToCanvas(source:CanvasImageSource,width:number,height:number){const maxWidth=1280,maxHeight=960,scale=Math.min(1,maxWidth/width,maxHeight/height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)throw new Error('Canvas no disponible');context.drawImage(source,0,0,canvas.width,canvas.height);return canvas}
function readImage(file:File){return new Promise<HTMLImageElement>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('No fue posible leer la foto'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('Imagen inválida'));image.onload=()=>resolve(image);image.src=String(reader.result??'')};reader.readAsDataURL(file)})}
function analyzeCanvas(canvas:HTMLCanvasElement):Metrics{const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)throw new Error('Canvas no disponible');const marginX=Math.floor(canvas.width*0.15),marginY=Math.floor(canvas.height*0.15),width=Math.max(1,canvas.width-marginX*2),height=Math.max(1,canvas.height-marginY*2),image=context.getImageData(marginX,marginY,width,height),stride=Math.max(1,Math.floor(Math.sqrt((width*height)/120000)));let count=0,r=0,g=0,b=0,l=0,a=0,labB=0,l2=0,a2=0,b2=0;for(let y=0;y<height;y+=stride){for(let x=0;x<width;x+=stride){const index=(y*width+x)*4;if(image.data[index+3]<200)continue;const rr=image.data[index],gg=image.data[index+1],bb=image.data[index+2],[ll,aa,bbb]=rgbToLab(rr,gg,bb);count++;r+=rr;g+=gg;b+=bb;l+=ll;a+=aa;labB+=bbb;l2+=ll*ll;a2+=aa*aa;b2+=bbb*bbb}}if(count<100)throw new Error('La muestra visible es insuficiente');const rMean=r/count,gMean=g/count,bMean=b/count,lMean=l/count,aMean=a/count,labBMean=labB/count,lStd=Math.sqrt(Math.max(0,l2/count-lMean*lMean)),aStd=Math.sqrt(Math.max(0,a2/count-aMean*aMean)),bStd=Math.sqrt(Math.max(0,b2/count-labBMean*labBMean)),chroma=Math.sqrt(aMean*aMean+labBMean*labBMean),hueDeg=(Math.atan2(labBMean,aMean)*180/Math.PI+360)%360;return{pixelCount:count,rMean,gMean,bMean,lMean,aMean,labBMean,lStd,aStd,bStd,chroma,hueDeg}}
function rgbToLab(r:number,g:number,b:number){const linear=(value:number)=>{const v=value/255;return v<=0.04045?v/12.92:((v+0.055)/1.055)**2.4},rr=linear(r),gg=linear(g),bb=linear(b),x=(rr*0.4124564+gg*0.3575761+bb*0.1804375)/0.95047,y=(rr*0.2126729+gg*0.7151522+bb*0.0721750),z=(rr*0.0193339+gg*0.1191920+bb*0.9503041)/1.08883,f=(value:number)=>value>0.008856?Math.cbrt(value):7.787*value+16/116,fx=f(x),fy=f(y),fz=f(z);return[116*fy-16,500*(fx-fy),200*(fy-fz)] as const}
