import {AlertTriangle,Camera,CheckCircle2,Database,ImagePlus,ScanLine,ShieldCheck,Target} from 'lucide-react'
import {useEffect,useRef,useState,type ChangeEvent} from 'react'
import {analyzeSegmentedCanvas,type UniVisionMetrics,type UniVisionSegmentation} from '../lib/uniVisionSegmentation'

type Metrics=UniVisionMetrics
type Capture={id:string;evidence_file_id:string;l_mean:number|string;a_mean:number|string;b_mean:number|string;l_std:number|string;a_std:number|string;b_std:number|string;chroma:number|string;hue_deg:number|string;suggested_grade:string|null;delta_e:number|string|null;operator_grade:string|null;decision:string;created_at:string}
type Reference={id:string;grade:string;label:string|null;l_mean:number|string;a_mean:number|string;b_mean:number|string;created_at:string}
type Payload={captures?:Capture[];references?:Reference[];permissions?:{canWrite:boolean;canManageReferences:boolean};error?:string}
type SavedCapture=Capture&{evidenceUrl?:string}
const grades=['A','B','C','D','E'] as const
const fmt=(value:unknown,digits=1)=>Number(value??0).toLocaleString('es-CL',{maximumFractionDigits:digits})

export function UniVisionStation({runId,plantId,currentGrade,onChanged}:{runId:string;plantId:string|null;currentGrade:string|null;onChanged:()=>Promise<void>}){
 const videoRef=useRef<HTMLVideoElement|null>(null),streamRef=useRef<MediaStream|null>(null),fileRef=useRef<HTMLInputElement|null>(null)
 const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[cameraOn,setCameraOn]=useState(false),[deviceLabel,setDeviceLabel]=useState('')
 const [preview,setPreview]=useState(''),[metrics,setMetrics]=useState<Metrics|null>(null),[segmentation,setSegmentation]=useState<UniVisionSegmentation|null>(null),[source,setSource]=useState<'camera'|'upload'>('camera'),[sourceImageSha256,setSourceImageSha256]=useState(''),[saved,setSaved]=useState<SavedCapture|null>(null)
 const [grade,setGrade]=useState(currentGrade??''),[decision,setDecision]=useState<'accepted'|'review'|'ng'>('review'),[referenceLabel,setReferenceLabel]=useState('')
 function stopCamera(){streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setCameraOn(false)}
 async function load(){try{const response=await fetch(`/api/sea-urchin-color?runId=${encodeURIComponent(runId)}`,{cache:'no-store'}),payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error??'No fue posible cargar Uni Vision');setData(payload);setError('')}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible cargar Uni Vision')}}
 useEffect(()=>{void load();return()=>stopCamera()},[runId])
 useEffect(()=>{if(currentGrade)setGrade(currentGrade)},[currentGrade])
 async function startCamera(){setError('');try{stopCamera();const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});streamRef.current=stream;const video=videoRef.current;if(!video)throw new Error('Cámara no disponible');video.srcObject=stream;await video.play();setDeviceLabel(stream.getVideoTracks()[0]?.label??'Cámara');setCameraOn(true);setSource('camera');setSourceImageSha256('');setSegmentation(null)}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible abrir la cámara')}}
 function captureCamera(){const video=videoRef.current;if(!video||!video.videoWidth||!video.videoHeight)return setError('La cámara aún no está lista');try{const canvas=drawToCanvas(video,video.videoWidth,video.videoHeight),result=analyzeSegmentedCanvas(canvas);setPreview(canvas.toDataURL('image/jpeg',0.86));setMetrics(result.metrics);setSegmentation(result);setSource('camera');setSourceImageSha256('');setSaved(null);setDecision('review');setError('')}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible segmentar la muestra')}}
 async function chooseFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type))return setError('Usa JPG, PNG o WebP');setBusy('file');try{const [image,sourceHash]=await Promise.all([readImage(file),sha256File(file)]),canvas=drawToCanvas(image,image.naturalWidth,image.naturalHeight),result=analyzeSegmentedCanvas(canvas);setPreview(canvas.toDataURL('image/jpeg',0.86));setMetrics(result.metrics);setSegmentation(result);setSource('upload');setSourceImageSha256(sourceHash);setDeviceLabel(file.name);setSaved(null);setDecision('review');setError('')}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible leer o segmentar la imagen')}finally{setBusy('');if(fileRef.current)fileRef.current.value=''}}
 async function saveMeasurement(){if(!preview||!metrics)return;setBusy('save');setError('');try{const response=await fetch('/api/sea-urchin-color',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'capture',runId,fileName:`uni-${runId.slice(0,8)}-${Date.now()}.jpg`,mimeType:'image/jpeg',dataBase64:preview,captureSource:source,deviceLabel,sourceImageSha256:source==='upload'?sourceImageSha256:null,metrics})}),payload=await response.json() as {capture?:Capture;evidenceUrl?:string;error?:string};if(!response.ok)throw new Error(payload.error??'No fue posible guardar medición');const capture=payload.capture?{...payload.capture,evidenceUrl:payload.evidenceUrl}:null;setSaved(capture);if(capture?.suggested_grade&&!grade)setGrade(capture.suggested_grade);await load()}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible guardar medición')}finally{setBusy('')}}
 async function saveReference(){if(!saved?.id||!grade)return;setBusy('reference');setError('');try{const response=await fetch('/api/sea-urchin-color',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reference',captureId:saved.id,grade,label:referenceLabel||`Referencia ${grade}`})}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??'No fue posible guardar referencia');setReferenceLabel('');await load()}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible guardar referencia')}finally{setBusy('')}}
 async function confirm(){if(!saved?.id||decision==='accepted'&&!grade)return;setBusy('confirm');setError('');try{const response=await fetch('/api/sea-urchin-color',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'confirm',captureId:saved.id,grade:grade||null,decision})}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error??'No fue posible confirmar color');window.dispatchEvent(new Event('pescamar:data-updated'));await Promise.all([load(),onChanged()])}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible confirmar color')}finally{setBusy('')}}
 const latest=saved??data?.captures?.[0]??null,references=data?.references??[]
 return <section className="panel" aria-label="Uni Vision Station">
  <div className="section-heading"><div><span className="overline">Uni Vision Station · color objetivo</span><h2>Medir antes de clasificar</h2></div><ScanLine size={20}/></div>
  <div className="notice"><ShieldCheck size={16}/><div><b>La medición no libera el lote por sí sola</b><small>Usa luz y distancia fijas. El sistema aísla el roe del fondo, mide CIELAB y ΔE; un operador confirma el resultado antes de actualizar Color/Grade.</small></div></div>
  {error?<div className="notice error"><AlertTriangle size={16}/><div><b>Uni Vision</b><small>{error}</small></div></div>:null}
  <div className="commercial-form-grid">
   <div><video ref={videoRef} muted playsInline style={{display:cameraOn?'block':'none',width:'100%',maxHeight:340,objectFit:'cover',background:'#111'}}/>{!cameraOn&&preview?<img src={segmentation?.previewDataUrl||preview} alt="Máscara de roe usada para medición" style={{width:'100%',maxHeight:340,objectFit:'cover'}}/>:!cameraOn?<div className="empty-inline"><Camera size={24}/><div><b>Estación lista</b><small>Centra el roe y deja visible parte del fondo alrededor de la muestra.</small></div></div>:null}</div>
   <div><div className="row-actions"><button type="button" className="button" onClick={()=>void startCamera()} disabled={!!busy}><Camera size={15}/>{cameraOn?'Reiniciar cámara':'Abrir cámara'}</button>{cameraOn?<button type="button" className="button primary" onClick={captureCamera}><Target size={15}/>Capturar y medir</button>:null}<input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>void chooseFile(event)}/><button type="button" className="button" onClick={()=>fileRef.current?.click()} disabled={!!busy}><ImagePlus size={15}/>Usar foto</button></div>{plantId?<p className="source-note">Referencia por planta: {plantId}</p>:<p className="source-note">Este lote no tiene planta explícita; no se sugerirá grade por referencia.</p>}{source==='upload'&&sourceImageSha256?<p className="source-note">Huella SHA-256 original preservada antes de reescalar la foto.</p>:null}</div>
  </div>
  {segmentation?<div className="notice">{segmentation.confidence==='review'?<AlertTriangle size={16}/>:<ScanLine size={16}/>}<div><b>Segmentación automática · {Math.round(segmentation.usableRatio*100)}% roe aislado</b><small>{segmentation.confidence==='review'?'La separación fondo/producto es poco estable. Revisa encuadre, sombras o reflejos antes de confirmar.':'La máscara LAB es deliberadamente amplia para separar bandejas, canastos y hardware sin usar umbrales de Grade A–E; admite tonos dorados, pálidos y marrones.'}</small></div></div>:null}
  {metrics?<><div className="signal-grid"><article className="signal-card"><span><Database size={16}/>L*</span><b>{fmt(metrics.lMean,2)}</b><small>Luminosidad</small></article><article className="signal-card"><span><Database size={16}/>a*</span><b>{fmt(metrics.aMean,2)}</b><small>verde ↔ rojo</small></article><article className="signal-card"><span><Database size={16}/>b*</span><b>{fmt(metrics.labBMean,2)}</b><small>azul ↔ amarillo</small></article><article className="signal-card"><span><Target size={16}/>Dispersión</span><b>{fmt(Math.sqrt(metrics.lStd**2+metrics.aStd**2+metrics.bStd**2),2)}</b><small>{metrics.pixelCount.toLocaleString('es-CL')} píxeles de producto</small></article></div>{data?.permissions?.canWrite?<button type="button" className="button primary" disabled={!!busy} onClick={()=>void saveMeasurement()}>{busy==='save'?'Guardando…':'Guardar medición y evidencia'}</button>:null}</>:null}
  {latest?<div className="notice"><Target size={16}/><div><b>{latest.suggested_grade?`Referencia más cercana: Grade ${latest.suggested_grade}`:'Medición sin referencia de planta'}</b><small>LAB {fmt(latest.l_mean,2)} / {fmt(latest.a_mean,2)} / {fmt(latest.b_mean,2)}{latest.delta_e!=null?` · ΔE ${fmt(latest.delta_e,2)}`:''}. Es una sugerencia explicable, no una aprobación automática.</small></div></div>:null}
  {saved&&data?.permissions?.canWrite?<div className="commercial-form-grid"><label>Grade confirmado<select value={grade} onChange={event=>setGrade(event.target.value)}><option value="">Sin grade aún</option>{grades.map(value=><option value={value} key={value}>{value}</option>)}</select></label><label>Decisión color<select value={decision} onChange={event=>setDecision(event.target.value as 'accepted'|'review'|'ng')}><option value="accepted">Aceptado</option><option value="review">Revisión</option><option value="ng">NG</option></select></label><button type="button" className="button primary" disabled={!!busy||decision==='accepted'&&!grade} onClick={()=>void confirm()}><CheckCircle2 size={15}/>{busy==='confirm'?'Confirmando…':'Confirmar control de color'}</button>{data.permissions.canManageReferences?<><label>Nombre referencia<input value={referenceLabel} onChange={event=>setReferenceLabel(event.target.value)} placeholder="Ej. A dorado turno AM"/></label><button type="button" className="button" disabled={!!busy||!grade} onClick={()=>void saveReference()}><Target size={15}/>{busy==='reference'?'Guardando…':`Fijar como referencia ${grade||''}`}</button></>:null}</div>:null}
  <div className="section-heading"><div><span className="overline">Referencias reales</span><h3>Biblioteca de planta</h3></div><span>{references.length}</span></div>{references.length?<div className="compact-ledger">{references.map(reference=><div key={reference.id} className="alert-row static"><span><ShieldCheck size={15}/></span><div><b>Grade {reference.grade} · {reference.label??'Referencia aprobada'}</b><small>LAB {fmt(reference.l_mean,2)} / {fmt(reference.a_mean,2)} / {fmt(reference.b_mean,2)}</small></div></div>)}</div>:<div className="empty-inline"><Database size={20}/><div><b>Sin referencias aprobadas</b><small>La estación operará sólo como instrumento de medición hasta que Calidad fije muestras reales A–E.</small></div></div>}
 </section>
}

function drawToCanvas(source:CanvasImageSource,width:number,height:number){const maxWidth=1280,maxHeight=960,scale=Math.min(1,maxWidth/width,maxHeight/height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)throw new Error('Canvas no disponible');context.drawImage(source,0,0,canvas.width,canvas.height);return canvas}
function readImage(file:File){return new Promise<HTMLImageElement>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('No fue posible leer la foto'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('Imagen inválida'));image.onload=()=>resolve(image);image.src=String(reader.result??'')};reader.readAsDataURL(file)})}
async function sha256File(file:File){if(!globalThis.crypto?.subtle)throw new Error('Este navegador no permite validar la huella de la foto');const digest=await globalThis.crypto.subtle.digest('SHA-256',await file.arrayBuffer());return Array.from(new Uint8Array(digest),value=>value.toString(16).padStart(2,'0')).join('')}
