import {AlertTriangle,CheckCircle2,FlaskConical} from 'lucide-react'
import {useEffect,useMemo,useState} from 'react'
import {Link,useLocation} from 'react-router-dom'
import './urchin-progress-rail.css'

type Stage={stage:string;sequenceNo:number;status:string}
type Label={status:string}
type Run={reception_id:string;reception_number:string|number;status:string;color_status?:string;xray_status?:string;stages:Stage[];labels?:Label[]}
type Payload={runs?:Run[]}
type Diagnosis={state:'clear'|'attention';observableCauses:string[];blockers:string[];nextAction:string;unknowns:string[];rule:string}
type ControlCard={diagnosis?:Diagnosis|null}
const labels:Record<string,string>={pinching:'Pinzado',blanching:'Escaldado',thermal_shock:'Shock',sanitary_break:'Sanitario',dripping:'DRI',draining:'Drenado',molding:'Moldeo',color:'Color',xray:'RX',freezing:'Congelado',packing:'Packing'}

export function UrchinProgressRail(){
 const {pathname,search}=useLocation();const params=useMemo(()=>new URLSearchParams(search),[search]);const receptionId=params.get('receptionId')??'',plantId=params.get('plantId')??'';const [run,setRun]=useState<Run|null>(null),[card,setCard]=useState<ControlCard|null>(null)
 useEffect(()=>{if(pathname==='/proceso-erizo'||!pathname.startsWith('/proceso-erizo')){setRun(null);setCard(null);return}let active=true;const q=plantId?`?plantId=${encodeURIComponent(plantId)}`:'';void fetch(`/api/sea-urchin-process${q}`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(async(payload:Payload|null)=>{if(!active)return;const runs=payload?.runs??[];const selected=receptionId?runs.find(item=>item.reception_id===receptionId)??null:runs.filter(item=>item.status!=='closed')[0]??null;setRun(selected);if(selected){try{const response=await fetch(`/api/sea-urchin-control-card?receptionId=${encodeURIComponent(selected.reception_id)}`,{cache:'no-store'}),control=await response.json() as ControlCard;if(active)setCard(response.ok?control:null)}catch{if(active)setCard(null)}}else if(active)setCard(null)}).catch(()=>{if(active){setRun(null);setCard(null)}});return()=>{active=false}},[pathname,receptionId,plantId])
 if(pathname==='/proceso-erizo'||!pathname.startsWith('/proceso-erizo')||!run)return null
 const stages=[...(run.stages??[])].sort((a,b)=>a.sequenceNo-b.sequenceNo),next=stages.find(stage=>!['ok','not_applicable'].includes(stage.status)),done=stages.filter(stage=>['ok','not_applicable'].includes(stage.status)).length,blocked=next?.status==='hold'||next?.status==='deviation'
 if(card?.diagnosis&&receptionId){const diagnosis=card.diagnosis,query=new URLSearchParams();if(plantId)query.set('plantId',plantId);query.set('receptionId',run.reception_id);const detail=`/proceso-erizo/detalle?${query.toString()}`;return <div className={`urchin-progress-rail ${diagnosis.state==='attention'?'attention':''}`}><div className="urchin-progress-summary"><FlaskConical size={17}/><div><span>REC-{run.reception_number} · siguiente acción</span><b>{diagnosis.nextAction}</b><small>{diagnosis.blockers.length?diagnosis.blockers[0]:'Sin bloqueo observable.'} {diagnosis.unknowns.length?`· ${diagnosis.unknowns.length} dato${diagnosis.unknowns.length===1?'':'s'} pendiente${diagnosis.unknowns.length===1?'':'s'}`:''}</small><small><Link className="source-link compact" to={detail}>Abrir lote</Link></small></div></div></div>}
 return <div className={`urchin-progress-rail ${blocked?'attention':''}`}><div className="urchin-progress-summary"><FlaskConical size={17}/><div><span>REC-{run.reception_number} · proceso de erizo</span><b>{next?`${blocked?'Resolver':'Ahora'}: ${labels[next.stage]??next.stage}`:'Proceso técnico completo'}</b><small>{done}/{stages.length} etapas conformes{next?` · ${next.status}`:''}</small></div></div><div className="urchin-step-track" aria-label="Progreso de proceso de erizo">{stages.map(stage=><span key={stage.stage} className={['ok','not_applicable'].includes(stage.status)?'done':stage===next?'current':''} title={`${labels[stage.stage]??stage.stage}: ${stage.status}`}>{['ok','not_applicable'].includes(stage.status)?<CheckCircle2 size={13}/>:stage===next&&blocked?<AlertTriangle size={13}/>:null}<em>{labels[stage.stage]??stage.stage}</em></span>)}</div></div>
}
