export type AppRole="admin"|"operations"|"finance"|"quality"|"viewer";

const access:Record<string,AppRole[]|"all">={
  "/":"all",
  "/timeline":"all",
  "/comunicaciones":["admin","operations","finance","quality","viewer"],
  "/auditoria":["admin","operations"],
  "/observabilidad":["admin","operations","quality"],
  "/rollout":["admin","operations"],
  "/floor":["admin","operations","quality"],
  "/pallets":["admin","operations","quality","viewer"],
  "/frio":["admin","operations","quality","viewer"],
  "/control-regulatorio":["admin","operations","quality","viewer"],
  "/estaciones":["admin"],
  "/planificacion":["admin","operations","finance","viewer"],
  "/etiquetas":["admin","operations","quality","viewer"],
  "/proceso-erizo":["admin","operations","quality","viewer"],
  "/plantas":"all",
  "/identidades-plantas":["admin","operations"],
  "/lineas":"all",
  "/operacion-2025":"all",
  "/recepciones":"all",
  "/despachos-ventas":"all",
  "/ordenes-venta":["admin","operations","finance","viewer"],
  "/inventario":"all",
  "/inventario-materiales":["admin","operations","finance","viewer"],
  "/proveedores-clientes":["admin","operations","finance","viewer"],
  "/rentabilidad":["admin","operations","finance","viewer"],
  "/costos-transformacion":["admin","operations","finance","viewer"],
  "/cierre-diario":["admin","operations","finance","viewer"],
  "/aprobaciones":["admin","operations","finance","quality"],
  "/creditos":["admin","finance","operations"],
  "/liquidaciones":["admin","finance","operations"],
  "/importaciones":["admin","operations"],
  "/operadores":["admin","operations"],
  "/modulos":["admin","operations"],
};

export function canAccessPath(role:AppRole,path:string){const key=Object.keys(access).filter(candidate=>candidate==="/"?path==="/":path===candidate||path.startsWith(`${candidate}/`)).sort((a,b)=>b.length-a.length)[0];if(!key)return false;const roles=access[key];return roles==="all"||roles.includes(role)}
export function canCreateReception(role:AppRole){return ["admin","operations","quality"].includes(role)}