import { useState } from 'react'
import { Navigate, Route, Routes } from 'react-router-dom'
import { AppShell } from './components/AppShell'
import { ReceptionModal } from './components/ReceptionModal'
import { Approvals } from './pages/Approvals'
import { Canonical2025 } from './pages/Canonical2025'
import { Credits } from './pages/Credits'
import { Dashboard } from './pages/Dashboard'
import { Modules } from './pages/Modules'
import { Placeholder } from './pages/Placeholder'
import { ProductionLines } from './pages/ProductionLines'
import { Receptions } from './pages/Receptions'
import { Standards } from './pages/Standards'
import { useLots } from './store'
export default function App(){const [modalOpen,setModalOpen]=useState(false);const {lots,addLot}=useLots();const open=()=>setModalOpen(true);return <AppShell onNewReception={open}><Routes><Route path="/" element={<Dashboard lots={lots} onNew={open}/>}/><Route path="/operacion-2025" element={<Canonical2025/>}/><Route path="/creditos" element={<Credits/>}/><Route path="/aprobaciones" element={<Approvals/>}/><Route path="/modulos" element={<Modules/>}/><Route path="/lineas" element={<ProductionLines/>}/><Route path="/recepciones" element={<Receptions lots={lots} onNew={open}/>}/><Route path="/estandares" element={<Standards/>}/><Route path="/clasificacion" element={<Placeholder title="UniGrade IA" description="Visión transversal para color, calibre, forma e integridad, configurable por recurso y producto."/>}/><Route path="/trazabilidad" element={<Placeholder title="Lotes y trazabilidad" description="Genealogía completa desde el origen artesanal hasta el producto exportado."/>}/><Route path="/proveedores" element={<Placeholder title="Proveedores artesanales" description="Origen, calidad, rendimiento y liquidaciones con reglas transparentes."/>}/><Route path="/configuracion" element={<Placeholder title="Configuración operacional" description="Plantas, líneas, productos, equipos, usuarios y reglas de excepción."/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes><ReceptionModal open={modalOpen} onClose={()=>setModalOpen(false)} onSave={addLot}/></AppShell>}
