import { lazy, Suspense, useState, type ReactNode } from "react";
import { Navigate, Route, Routes } from "react-router-dom";
import { canAccessPath, canCreateReception } from "./access";
import { useAuth, LoginScreen } from "./auth";
import { AppShell } from "./components/AppShell";
import { CanonicalCategoryMix } from "./components/CanonicalCategoryMix";
import { CanonicalIntelligencePanel } from "./components/CanonicalIntelligencePanel";
import { ExecutiveDecisionBrief } from "./components/ExecutiveDecisionBrief";
import { Lot360Provider } from "./components/Lot360Context";
import { OperationalHealthPanel } from "./components/OperationalHealthPanel";
import { ReceptionModal } from "./components/ReceptionModal";
import { RollforwardReconciliation } from "./components/RollforwardReconciliation";
import { RollforwardResolutionQueue } from "./components/RollforwardResolutionQueue";
import { UrchinProgressRail } from "./components/UrchinProgressRail";
import { useLots } from "./store";

const Approvals=lazy(()=>import("./pages/Approvals").then(module=>({default:module.Approvals})));
const Audit=lazy(()=>import("./pages/Audit").then(module=>({default:module.Audit})));
const Commercial=lazy(()=>import("./pages/Commercial").then(module=>({default:module.Commercial})));
const CommunicationsFocus=lazy(()=>import("./pages/CommunicationsFocus").then(module=>({default:module.CommunicationsFocus})));
const Communications=lazy(()=>import("./pages/Communications").then(module=>({default:module.Communications})));
const Credits=lazy(()=>import("./pages/Credits").then(module=>({default:module.Credits})));
const DailyClose=lazy(()=>import("./pages/DailyClose").then(module=>({default:module.DailyClose})));
const EdgeVision=lazy(()=>import("./pages/EdgeVision").then(module=>({default:module.EdgeVision})));
const OrganizationContext=lazy(()=>import("./pages/OrganizationContext").then(module=>({default:module.OrganizationContext})));
const Integrations=lazy(()=>import("./pages/Integrations").then(module=>({default:module.Integrations})));
const FloorFocus=lazy(()=>import("./pages/FloorFocus").then(module=>({default:module.FloorFocus})));
const FloorStation=lazy(()=>import("./pages/FloorStation").then(module=>({default:module.FloorStation})));
const PalletsFocus=lazy(()=>import("./pages/PalletsFocus").then(module=>({default:module.PalletsFocus})));
const PalletsControl=lazy(()=>import("./pages/PlantExecutionControl").then(module=>({default:module.PalletsControl})));
const ColdChainFocus=lazy(()=>import("./pages/ColdChainFocus").then(module=>({default:module.ColdChainFocus})));
const ColdChainControl=lazy(()=>import("./pages/ColdChainControl").then(module=>({default:module.ColdChainControl})));
const RegulatoryControl=lazy(()=>import("./pages/RegulatoryControl").then(module=>({default:module.RegulatoryControl})));
const PlantStationsFocus=lazy(()=>import("./pages/PlantStationsFocus").then(module=>({default:module.PlantStationsFocus})));
const PlantStations=lazy(()=>import("./pages/PlantStations").then(module=>({default:module.PlantStations})));
const LabelPrintFocus=lazy(()=>import("./pages/LabelPrintFocus").then(module=>({default:module.LabelPrintFocus})));
const LabelPrintControl=lazy(()=>import("./pages/LabelPrintControl").then(module=>({default:module.LabelPrintControl})));
const InventoryFocus=lazy(()=>import("./pages/InventoryFocus").then(module=>({default:module.InventoryFocus})));
const Inventory=lazy(()=>import("./pages/Inventory").then(module=>({default:module.Inventory})));
const Lineage=lazy(()=>import("./pages/Lineage").then(module=>({default:module.Lineage})));
const Lot360=lazy(()=>import("./pages/Lot360").then(module=>({default:module.Lot360})));
const MaterialsFocus=lazy(()=>import("./pages/MaterialsFocus").then(module=>({default:module.MaterialsFocus})));
const MaterialsInventory=lazy(()=>import("./pages/MaterialsInventory").then(module=>({default:module.MaterialsInventory})));
const Partners=lazy(()=>import("./pages/Partners").then(module=>({default:module.Partners})));
const ProfitabilityFocus=lazy(()=>import("./pages/ProfitabilityFocus").then(module=>({default:module.ProfitabilityFocus})));
const Profitability=lazy(()=>import("./pages/Profitability").then(module=>({default:module.Profitability})));
const Modules=lazy(()=>import("./pages/Modules").then(module=>({default:module.Modules})));
const Imports=lazy(()=>import("./pages/Imports").then(module=>({default:module.Imports})));
const Observability=lazy(()=>import("./pages/Observability").then(module=>({default:module.Observability})));
const Planning=lazy(()=>import("./pages/Planning").then(module=>({default:module.Planning})));
const ProductLabels=lazy(()=>import("./pages/ProductLabels").then(module=>({default:module.ProductLabels})));
const Rollout=lazy(()=>import("./pages/Rollout").then(module=>({default:module.Rollout})));
const PlantControl=lazy(()=>import("./pages/PlantControl").then(module=>({default:module.PlantControl})));
const PlantIdentities=lazy(()=>import("./pages/PlantIdentities").then(module=>({default:module.PlantIdentities})));
const ProductionFocus=lazy(()=>import("./pages/ProductionFocus").then(module=>({default:module.ProductionFocus})));
const ProductionLines=lazy(()=>import("./pages/ProductionLines").then(module=>({default:module.ProductionLines})));
const Receptions=lazy(()=>import("./pages/Receptions").then(module=>({default:module.Receptions})));
const SalesOrders=lazy(()=>import("./pages/SalesOrders").then(module=>({default:module.SalesOrders})));
const SeaUrchinFocus=lazy(()=>import("./pages/SeaUrchinFocus").then(module=>({default:module.SeaUrchinFocus})));
const SeaUrchinProcess=lazy(()=>import("./pages/SeaUrchinProcess").then(module=>({default:module.SeaUrchinProcess})));
const SeaUrchinMobileCapture=lazy(()=>import("./pages/SeaUrchinMobileCapture").then(module=>({default:module.SeaUrchinMobileCapture})));
const SeaUrchinGraph=lazy(()=>import("./pages/SeaUrchinGraph").then(module=>({default:module.SeaUrchinGraph})));
const Settlements=lazy(()=>import("./pages/Settlements").then(module=>({default:module.Settlements})));
const TransformationCostsFocus=lazy(()=>import("./pages/TransformationCostsFocus").then(module=>({default:module.TransformationCostsFocus})));
const TransformationCosts=lazy(()=>import("./pages/TransformationCosts").then(module=>({default:module.TransformationCosts})));
const Operators=lazy(()=>import("./pages/Operators").then(module=>({default:module.Operators})));
const Timeline=lazy(()=>import("./pages/Timeline").then(module=>({default:module.Timeline})));
const Copilot=lazy(()=>import("./pages/Copilot").then(module=>({default:module.Copilot})));
function RouteFallback(){return <div className="system-banner">Cargando módulo…</div>}
export default function App(){const {operator,loading:authLoading}=useAuth();if(authLoading)return <div className="login-shell"><div className="system-banner">Validando sesión…</div></div>;if(!operator)return <LoginScreen/>;return <AuthenticatedApp/>}
function AuthenticatedApp(){const {operator}=useAuth();const [modalOpen,setModalOpen]=useState(false);const {lots,loading,error,addLot}=useLots();if(!operator)return null;const mayCreate=canCreateReception(operator.role),open=()=>{if(mayCreate)setModalOpen(true)},gate=(path:string,node:ReactNode)=>canAccessPath(operator.role,path)?node:<Navigate to="/" replace/>;return <Lot360Provider><AppShell onNewReception={open}>{loading?<div className="system-banner">Sincronizando recepciones…</div>:error?<div className="system-banner error" role="alert">{error}</div>:null}<UrchinProgressRail/><Suspense fallback={<RouteFallback/>}><Routes><Route path="/" element={<><DailyClose/><ExecutiveDecisionBrief/></>}/><Route path="/inicio/detalle" element={<><OperationalHealthPanel/><CanonicalIntelligencePanel/><CanonicalCategoryMix/><RollforwardReconciliation/><RollforwardResolutionQueue/></>}/><Route path="/pescamar-ia" element={gate("/pescamar-ia",<Copilot/>)}/><Route path="/timeline" element={<Timeline/>}/><Route path="/lineage" element={gate("/lineage",<Lineage/>)}/><Route path="/lotes/:receptionId" element={<Lot360/>}/><Route path="/edgevision" element={gate("/edgevision",<EdgeVision/>)}/><Route path="/organization" element={gate("/organization",<OrganizationContext/>)}/><Route path="/integrations" element={gate("/integrations",<Integrations/>)}/><Route path="/comunicaciones" element={gate("/comunicaciones",<CommunicationsFocus/>)}/><Route path="/comunicaciones/detalle" element={gate("/comunicaciones",<Communications/>)}/><Route path="/auditoria" element={gate("/auditoria",<Audit/>)}/><Route path="/observabilidad" element={gate("/observabilidad",<Observability/>)}/><Route path="/rollout" element={gate("/rollout",<Rollout/>)}/><Route path="/floor" element={gate("/floor",<FloorFocus/>)}/><Route path="/floor/detalle" element={gate("/floor",<FloorStation/>)}/><Route path="/pallets" element={gate("/pallets",<PalletsFocus/>)}/><Route path="/pallets/detalle" element={gate("/pallets",<PalletsControl/>)}/><Route path="/frio" element={gate("/frio",<ColdChainFocus/>)}/><Route path="/frio/detalle" element={gate("/frio",<ColdChainControl/>)}/><Route path="/control-regulatorio" element={gate("/control-regulatorio",<RegulatoryControl/>)}/><Route path="/estaciones" element={gate("/estaciones",<PlantStationsFocus/>)}/><Route path="/estaciones/detalle" element={gate("/estaciones",<PlantStations/>)}/><Route path="/impresion-etiquetas" element={gate("/impresion-etiquetas",<LabelPrintFocus/>)}/><Route path="/impresion-etiquetas/detalle" element={gate("/impresion-etiquetas",<LabelPrintControl/>)}/><Route path="/operacion-2025" element={<Navigate to="/timeline" replace/>}/><Route path="/planificacion" element={gate("/planificacion",<Planning/>)}/><Route path="/etiquetas" element={gate("/etiquetas",<ProductLabels/>)}/><Route path="/proceso-erizo" element={gate("/proceso-erizo",<SeaUrchinFocus/>)}/><Route path="/proceso-erizo/detalle" element={gate("/proceso-erizo",<SeaUrchinProcess/>)}/><Route path="/proceso-erizo/grafo" element={gate("/proceso-erizo",<SeaUrchinGraph/>)}/><Route path="/erizo/camara" element={gate("/proceso-erizo",<SeaUrchinMobileCapture/>)}/><Route path="/plantas" element={<PlantControl/>}/><Route path="/plantas/:plantId" element={<PlantControl/>}/><Route path="/identidades-plantas" element={gate("/identidades-plantas",<PlantIdentities/>)}/><Route path="/importaciones" element={gate("/importaciones",<Imports/>)}/><Route path="/creditos" element={gate("/creditos",<Credits/>)}/><Route path="/liquidaciones" element={gate("/liquidaciones",<Settlements/>)}/><Route path="/despachos-ventas" element={gate("/despachos-ventas",<Commercial/>)}/><Route path="/ordenes-venta" element={gate("/ordenes-venta",<SalesOrders/>)}/><Route path="/inventario" element={gate("/inventario",<InventoryFocus/>)}/><Route path="/inventario/detalle" element={gate("/inventario",<Inventory/>)}/><Route path="/inventario-materiales" element={gate("/inventario-materiales",<MaterialsFocus/>)}/><Route path="/inventario-materiales/detalle" element={gate("/inventario-materiales",<MaterialsInventory/>)}/><Route path="/proveedores-clientes" element={gate("/proveedores-clientes",<Partners/>)}/><Route path="/rentabilidad" element={gate("/rentabilidad",<ProfitabilityFocus/>)}/><Route path="/rentabilidad/detalle" element={gate("/rentabilidad",<Profitability/>)}/><Route path="/costos-transformacion" element={gate("/costos-transformacion",<TransformationCostsFocus/>)}/><Route path="/costos-transformacion/detalle" element={gate("/costos-transformacion",<TransformationCosts/>)}/><Route path="/cierre-diario" element={<Navigate to="/" replace/>}/><Route path="/aprobaciones" element={gate("/aprobaciones",<Approvals/>)}/><Route path="/modulos" element={gate("/modulos",<Modules/>)}/><Route path="/operadores" element={gate("/operadores",<Operators/>)}/><Route path="/lineas" element={<ProductionFocus lots={lots}/>}/><Route path="/lineas/detalle" element={<ProductionLines lots={lots}/>}/><Route path="/recepciones" element={<Receptions lots={lots} onNew={open}/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Suspense>{mayCreate?<ReceptionModal open={modalOpen} onClose={()=>setModalOpen(false)} onSave={addLot}/>:null}</AppShell></Lot360Provider>}
