import { createContext, useCallback, useContext, useEffect, useState, type FormEvent, type ReactNode } from "react";

type Operator = {id:string;fullName:string;email:string;role:"admin"|"operations"|"finance"|"quality"|"viewer";plantIds:string[]};
type AuthContextValue={operator:Operator|null;loading:boolean;login:(email:string,password:string)=>Promise<void>;logout:()=>Promise<void>;revalidate:()=>Promise<boolean>};
type AuthPayload={ok?:boolean;operator?:Operator;error?:string};
const AuthContext=createContext<AuthContextValue|null>(null);const SESSION_REVALIDATE_MS=5*60*1000;
async function authRequest(input:RequestInfo|URL,init?:RequestInit){const response=await fetch(input,{credentials:"same-origin",cache:"no-store",...init,headers:{"Content-Type":"application/json",...(init?.headers??{})}});const payload=(await response.json().catch(()=>({}))) as AuthPayload;return{response,payload}}
export function AuthProvider({children}:{children:ReactNode}){const[operator,setOperator]=useState<Operator|null>(null),[loading,setLoading]=useState(true);const revalidate=useCallback(async()=>{try{const{response,payload}=await authRequest("/api/auth");if(response.ok&&payload.operator){setOperator(payload.operator);return true}if(response.status===401)setOperator(null);return false}catch{return false}},[]);useEffect(()=>{let active=true;void revalidate().finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[revalidate]);useEffect(()=>{const onFocus=()=>{if(document.visibilityState==="visible")void revalidate()};const interval=window.setInterval(()=>{if(document.visibilityState==="visible")void revalidate()},SESSION_REVALIDATE_MS);window.addEventListener("focus",onFocus);document.addEventListener("visibilitychange",onFocus);return()=>{window.clearInterval(interval);window.removeEventListener("focus",onFocus);document.removeEventListener("visibilitychange",onFocus)}},[revalidate]);const login=useCallback(async(email:string,password:string)=>{const{response,payload}=await authRequest("/api/auth",{method:"POST",body:JSON.stringify({email,password})});if(!response.ok||!payload.operator){if(response.status===429){const retryAfter=Number(response.headers.get("Retry-After")??"0"),minutes=retryAfter>0?Math.max(1,Math.ceil(retryAfter/60)):null;throw new Error(minutes?`Demasiados intentos. Intenta nuevamente en ${minutes} min.`:payload.error||"Demasiados intentos. Intenta nuevamente más tarde.")}throw new Error(payload.error||"No fue posible iniciar sesión")}setOperator(payload.operator)},[]);const logout=useCallback(async()=>{try{await authRequest("/api/auth",{method:"DELETE"})}finally{setOperator(null)}},[]);return <AuthContext.Provider value={{operator,loading,login,logout,revalidate}}>{children}</AuthContext.Provider>}
export function useAuth(){const value=useContext(AuthContext);if(!value)throw new Error("AuthProvider requerido");return value}
function PescamarMark(){return <span className="pescamar-symbol" aria-hidden="true"><svg viewBox="0 0 52 34"><path d="M4 17c8-8 17-12 27-10 5 1 10 4 15 10-5 6-10 9-15 10-10 2-19-2-27-10Z"/><path d="M36 11c4-4 8-6 12-6-1 5-1 8 0 12-4 0-8-2-12-6Z"/><circle cx="14" cy="15" r="1.35"/><path className="brand-wave" d="M3 27c8-3 15-3 22 0s15 3 24-1"/></svg></span>}
export function LoginScreen(){const{login}=useAuth();const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[submitting,setSubmitting]=useState(false),[error,setError]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setSubmitting(true);try{await login(email.trim(),password)}catch(cause){setError(cause instanceof Error?cause.message:"No fue posible iniciar sesión")}finally{setSubmitting(false)}}return <main className="login-shell"><div className="login-frame"><section className="login-intro" aria-label="Pescamar Control Operacional"><div className="login-brand-lockup"><PescamarMark/><div><b>PESCAMAR</b><small>CONTROL OPERACIONAL</small></div></div><div className="login-intro-copy"><span className="overline">UNA OPERACIÓN · UNA VERDAD</span><h2>Cada kilo tiene una historia. Pescamar la conecta.</h2><p>Desde que entra la materia prima hasta que sale el producto, cada recepción, proceso, etiqueta, movimiento y decisión queda conectado al mismo lote.</p></div><div className="login-proof" aria-label="Flujo operacional de la plataforma"><div><b>Recibir</b><span>Origen y materia prima</span></div><div><b>Transformar</b><span>Proceso, calidad e inventario</span></div><div><b>Cumplir</b><span>Pedido, etiqueta y despacho</span></div></div></section><section className="login-card panel" aria-labelledby="login-title"><div className="overline">TU OPERACIÓN EMPIEZA AQUÍ</div><h1 id="login-title">Entra a Pescamar</h1><p>Ve lo que necesita tu cargo, actúa sobre tus plantas y continúa el trabajo desde el último evento registrado.</p><form onSubmit={submit}><label>Correo<input type="email" autoComplete="username" inputMode="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="nombre@pescamarchile.cl" required maxLength={254} disabled={submitting} autoFocus/></label><label>Contraseña<input type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="••••••••" required minLength={8} maxLength={256} disabled={submitting}/></label>{error?<p className="form-error" role="alert" aria-live="polite">{error}</p>:null}<button className="button primary" type="submit" disabled={submitting}>{submitting?"Abriendo tu operación…":"Entrar a mi operación"}</button></form><div className="login-security-note"><span className="live-dot"/>Información y acciones según tu cargo y plantas</div></section></div></main>}
