import type {Locale} from './i18n'

export type TechnicalTermId=
 |'gs1'|'gtin'|'gln'|'sscc'|'gs1_ai'|'digital_link'
 |'gdst'|'epcis'|'cte'|'kde'|'json_ld'
 |'api'|'rest'|'webhook'|'mqtt'|'opc_ua'|'modbus'|'rtsp'|'onvif'

type Localized={es:string;en:string}
export type TechnicalTerm={code:string;name:Localized;plain:Localized;use:Localized}

export const technicalTerms:Record<TechnicalTermId,TechnicalTerm>={
 gs1:{code:'GS1',name:{es:'Estándares globales de identificación',en:'Global identification standards'},plain:{es:'Lenguaje común para identificar productos, empresas, ubicaciones y unidades logísticas en una cadena de suministro.',en:'A common language for identifying products, companies, locations and logistics units across a supply chain.'},use:{es:'Permite que Pescamar intercambie identidades sin depender de códigos internos propios.',en:'Lets Pescamar exchange identities without depending on its own internal codes.'}},
 gtin:{code:'GTIN',name:{es:'Global Trade Item Number · código global de producto',en:'Global Trade Item Number'},plain:{es:'Código que identifica de forma única un producto o presentación comercial.',en:'Code that uniquely identifies a product or trade-item presentation.'},use:{es:'En Pescamar se vincula a una especificación de packing; no identifica por sí solo un pallet físico.',en:'In Pescamar it links to a packing specification; it does not by itself identify a physical pallet.'}},
 gln:{code:'GLN',name:{es:'Global Location Number · código global de ubicación o empresa',en:'Global Location Number'},plain:{es:'Código de 13 dígitos para identificar una ubicación física o una parte de la cadena, como una empresa.',en:'13-digit code used to identify a physical location or a supply-chain party such as a company.'},use:{es:'Puede representar una planta, una ubicación de inventario, un proveedor o un cliente, según su uso.',en:'It can represent a plant, inventory location, supplier or customer depending on how it is used.'}},
 sscc:{code:'SSCC',name:{es:'Serial Shipping Container Code · código único de unidad logística',en:'Serial Shipping Container Code'},plain:{es:'Código de 18 dígitos que identifica una unidad logística individual, por ejemplo un pallet.',en:'18-digit code that identifies one individual logistics unit, for example a pallet.'},use:{es:'En Pescamar sirve para seguir un pallet físico durante almacenamiento, despacho y recepción.',en:'In Pescamar it can follow one physical pallet through storage, dispatch and receiving.'}},
 gs1_ai:{code:'AI',name:{es:'Application Identifier · identificador de aplicación GS1',en:'Application Identifier'},plain:{es:'Prefijo que indica qué tipo de dato GS1 viene a continuación. Aquí AI no significa inteligencia artificial.',en:'Prefix that tells a scanner what kind of GS1 data follows. Here AI does not mean artificial intelligence.'},use:{es:'Ejemplos: 01 para GTIN, 414 para ubicación física, 417 para una parte y 00 para SSCC.',en:'Examples: 01 for GTIN, 414 for physical location, 417 for a party and 00 for SSCC.'}},
 digital_link:{code:'GS1 Digital Link',name:{es:'Enlace web para identificadores GS1',en:'Web link for GS1 identifiers'},plain:{es:'Forma estándar de expresar un identificador GS1 como una dirección web que puede llevar a información relacionada.',en:'Standard way to express a GS1 identifier as a web address that can lead to related information.'},use:{es:'Pescamar puede construir la referencia; un resolver público propio sólo se declarará cuando exista realmente.',en:'Pescamar can construct the reference; a public resolver will only be claimed when one actually exists.'}},
 gdst:{code:'GDST',name:{es:'Global Dialogue on Seafood Traceability',en:'Global Dialogue on Seafood Traceability'},plain:{es:'Estándar de interoperabilidad para compartir trazabilidad de productos del mar entre empresas y sistemas.',en:'Interoperability standard for sharing seafood traceability data across companies and systems.'},use:{es:'Define qué información debe poder compartirse y cómo intercambiarla de forma compatible.',en:'Defines what information must be shareable and how systems exchange it compatibly.'}},
 epcis:{code:'EPCIS',name:{es:'Electronic Product Code Information Services',en:'Electronic Product Code Information Services'},plain:{es:'Estándar GS1 que registra eventos reales: qué ocurrió, cuándo, dónde y en qué contexto.',en:'GS1 standard for real-world events: what happened, when, where and in what business context.'},use:{es:'Es la forma técnica en que Pescamar podrá compartir eventos de trazabilidad con otros sistemas.',en:'It is the technical form Pescamar can use to share traceability events with other systems.'}},
 cte:{code:'CTE',name:{es:'Critical Tracking Event · evento crítico de trazabilidad',en:'Critical Tracking Event'},plain:{es:'Momento del flujo donde debe quedar registro, por ejemplo recibir, transformar o despachar.',en:'A point in the flow where traceability must be recorded, for example receiving, transforming or shipping.'},use:{es:'Ayuda a saber cuándo capturar evidencia para que la historia del producto no tenga saltos.',en:'It tells the system when evidence must be captured so product history has no gaps.'}},
 kde:{code:'KDE',name:{es:'Key Data Element · dato clave de trazabilidad',en:'Key Data Element'},plain:{es:'Dato específico que debe registrarse en un evento crítico, como lote, fecha, ubicación u origen.',en:'A specific data point that must be recorded at a critical event, such as lot, date, location or origin.'},use:{es:'Pescamar debe obtenerlo de evidencia real o dejarlo como faltante; nunca inventarlo.',en:'Pescamar must obtain it from real evidence or leave it missing; never fabricate it.'}},
 json_ld:{code:'JSON-LD',name:{es:'JSON for Linked Data · JSON para datos enlazados',en:'JSON for Linked Data'},plain:{es:'Formato de datos legible por sistemas que además conserva significado y relaciones entre entidades.',en:'Machine-readable data format that also preserves meaning and relationships between entities.'},use:{es:'GDST y EPCIS lo usan para intercambiar eventos de trazabilidad de manera interoperable.',en:'GDST and EPCIS use it to exchange traceability events interoperably.'}},
 api:{code:'API',name:{es:'Application Programming Interface · interfaz entre sistemas',en:'Application Programming Interface'},plain:{es:'Puerta controlada para que un sistema consulte o envíe información a otro.',en:'A controlled doorway for one system to query or send information to another.'},use:{es:'Permite integrar Pescamar sin copiar datos manualmente entre aplicaciones.',en:'Lets Pescamar integrate without manually copying data between applications.'}},
 rest:{code:'REST',name:{es:'Representational State Transfer',en:'Representational State Transfer'},plain:{es:'Forma común de construir APIs usando solicitudes web simples y predecibles.',en:'Common way to build APIs using simple, predictable web requests.'},use:{es:'Se usa para integraciones de software, sensores y servicios cuando existe un endpoint real.',en:'Used for software, sensor and service integrations when a real endpoint exists.'}},
 webhook:{code:'Webhook',name:{es:'Aviso automático entre sistemas',en:'Automatic system-to-system notification'},plain:{es:'Un sistema envía un aviso a otro cuando ocurre un evento, sin esperar una consulta manual.',en:'One system sends another a notification when an event occurs, without waiting for a manual query.'},use:{es:'Útil para recibir cambios externos en Pescamar de forma inmediata y controlada.',en:'Useful for receiving external changes in Pescamar immediately and in a controlled way.'}},
 mqtt:{code:'MQTT',name:{es:'Protocolo liviano de mensajería para dispositivos',en:'Lightweight device messaging protocol'},plain:{es:'Canal eficiente para que sensores y equipos pequeños publiquen mediciones o estados.',en:'Efficient channel for sensors and small devices to publish measurements or status.'},use:{es:'Candidato para temperatura, telemetría y equipos de planta cuando exista hardware real.',en:'Candidate for temperature, telemetry and plant equipment when real hardware exists.'}},
 opc_ua:{code:'OPC UA',name:{es:'Open Platform Communications Unified Architecture',en:'Open Platform Communications Unified Architecture'},plain:{es:'Estándar industrial para que máquinas y software compartan variables, estados y eventos de forma estructurada.',en:'Industrial standard for machines and software to share variables, states and events in a structured way.'},use:{es:'Sirve para integrar equipos industriales sin acoplar Pescamar a una marca específica.',en:'Useful for integrating industrial equipment without tying Pescamar to one vendor.'}},
 modbus:{code:'Modbus',name:{es:'Protocolo industrial Modbus',en:'Modbus industrial protocol'},plain:{es:'Protocolo muy usado para leer registros de sensores, PLC y equipos industriales.',en:'Widely used protocol for reading registers from sensors, PLCs and industrial equipment.'},use:{es:'Sólo se habilita cuando exista un equipo y mapa de registros real.',en:'Enabled only when a real device and register map exist.'}},
 rtsp:{code:'RTSP',name:{es:'Real-Time Streaming Protocol · transmisión de video',en:'Real-Time Streaming Protocol'},plain:{es:'Protocolo para recibir video en tiempo real desde cámaras o servidores de video.',en:'Protocol for receiving live video from cameras or video servers.'},use:{es:'Puede alimentar Uni / EdgeVision cuando exista una cámara industrial conectada.',en:'Can feed Uni / EdgeVision when an industrial camera is actually connected.'}},
 onvif:{code:'ONVIF',name:{es:'Estándar abierto de interoperabilidad para cámaras IP',en:'Open interoperability standard for IP cameras'},plain:{es:'Permite descubrir y controlar cámaras compatibles sin depender de un fabricante.',en:'Lets compatible cameras be discovered and controlled without depending on one manufacturer.'},use:{es:'Complementa RTSP para integrar cámaras de visión de planta.',en:'Complements RTSP when integrating plant vision cameras.'}},
}

export function technicalTerm(id:TechnicalTermId,locale:Locale){return technicalTerms[id][locale]}
