export type SeaUrchinExternalReferenceV3={
  id:string
  title:string
  sourcePage:string
  imageUrl:string
  sourceType:'commercial_reference'|'research_reference'
  license:string
  attribution:string|null
  scene:'pre_shipment_tray'|'saltwater'|'mixed_product'
  intendedUse:'visual_variability'|'segmentation_qa'|'defect_variability'
  qualityStatus:'unlabeled'
  officialGrade:null
  notes:string
  provenance:{researchBasis:string[];sourceClaim?:string}
}

// Hard-case external references for Uni Vision robustness. These remain external,
// unlabeled and non-operational until an explicit Pescamar Quality decision exists.
export const SEA_URCHIN_EXTERNAL_REFERENCE_SET_3:SeaUrchinExternalReferenceV3[]=[
  {id:'ext-shiki-mixed-bafun',title:'Bafun Uni Bara Red & Yellow',sourcePage:'https://shiki.sg/products/bafun-uni-red-and-yellow',imageUrl:'https://shiki.sg/cdn/shop/products/BafunUniBara250g_Yellow.jpg?v=1586699004&width=1214',sourceType:'commercial_reference',license:'Reference-only; source terms apply',attribution:'Shiki Oishii',scene:'pre_shipment_tray',intendedUse:'defect_variability',qualityStatus:'unlabeled',officialGrade:null,notes:'Mezcla amplia de tonos amarillo a naranja y piezas con distinta forma. Útil para heterogeneidad; el claim comercial de grade no se adopta como label Pescamar.',provenance:{researchBasis:['https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecs2.4911','https://doi.org/10.1038/s41538-025-00579-5'],sourceClaim:'commercial grade claim ignored for Pescamar labeling'}},
  {id:'ext-foraged-uniform-tray',title:'Fresh Sea Urchin Roe (Uni)',sourcePage:'https://www.foraged.com/products/fresh-sea-urchin-roe-%28uni%29',imageUrl:'https://www.foraged.com/_next/image?q=75&url=https%3A%2F%2Fforaged.nyc3.cdn.digitaloceanspaces.com%2FUntitleddesign_12-1695927732875.png&w=1200',sourceType:'commercial_reference',license:'Reference-only; source terms apply',attribution:'Foraged',scene:'pre_shipment_tray',intendedUse:'segmentation_qa',qualityStatus:'unlabeled',officialGrade:null,notes:'Bandeja muy ordenada y uniforme; útil como contraste de forma y segmentación, no como patrón aprobado.',provenance:{researchBasis:['https://repository.library.noaa.gov/view/noaa/3020/noaa_3020_DS1.pdf']}},
  {id:'ext-isse-ensui',title:'Murasaki Ensui Gold Grade 100g',sourcePage:'https://www.issejapan.com/product/murasaki-ensui-gold-grade-100g',imageUrl:'https://static.wixstatic.com/media/88be06_c11b4a09d8274f33bdc147c52f23ab3d~mv2.jpg/v1/fit/w_500%2Ch_500%2Cq_90/file.jpg',sourceType:'commercial_reference',license:'Reference-only; source terms apply',attribution:'ISSé JAPAN',scene:'saltwater',intendedUse:'visual_variability',qualityStatus:'unlabeled',officialGrade:null,notes:'Uni en agua salada dentro de contenedor transparente. Caso importante para distinguir reflejos/líquido del tejido.',provenance:{researchBasis:['https://academic.oup.com/ijfst/article/47/12/2545/7866116'],sourceClaim:'commercial gold-grade claim ignored for Pescamar labeling'}},
  {id:'ext-yama-santa-barbara',title:'Santa Barbara Uni',sourcePage:'https://www.yamaseafood.com/product-category/sea-urchin-uni',imageUrl:'https://assets-global.website-files.com/6532ebd13188d8eaabb5536f/658c36b1e245d2797d619854_Santa%20Barbara%20Uni.png',sourceType:'commercial_reference',license:'Reference-only; source terms apply',attribution:'Yama Seafood',scene:'pre_shipment_tray',intendedUse:'segmentation_qa',qualityStatus:'unlabeled',officialGrade:null,notes:'Caja de madera con tonos amarillos claros y lobos grandes; útil para variación de luminancia.',provenance:{researchBasis:['https://repository.library.noaa.gov/view/noaa/3020/noaa_3020_DS1.pdf']}},
  {id:'ext-champion-pocket-tray',title:'Pocket tray uni',sourcePage:'https://championfood.com.my/pages/about-us',imageUrl:'https://championfood.com.my/cdn/shop/files/Copy_of_Sushi_1200_x_328_px_800_x_800_px_3.png?v=1750382658&width=3840',sourceType:'commercial_reference',license:'Reference-only; source terms apply',attribution:'Global Champion Food',scene:'pre_shipment_tray',intendedUse:'segmentation_qa',qualityStatus:'unlabeled',officialGrade:null,notes:'Bandeja blanca con compartimentos y pocas piezas grandes; sirve para validar separación del plástico blanco.',provenance:{researchBasis:['https://santamonicaseafood.com/wp-content/uploads/2026/04/Sea-Urchin-Roe-Uni_POS_Product-Guide.pdf']}},
  {id:'ext-hachimenroppi-alum',title:'Uni tray with alum',sourcePage:'https://hachimenroppi.com/detail/141843/',imageUrl:'https://img.hachimenroppi.com/images/item/85/61/46185/CIDseRbW',sourceType:'commercial_reference',license:'Reference-only; source terms apply',attribution:'Hachimenroppi',scene:'pre_shipment_tray',intendedUse:'visual_variability',qualityStatus:'unlabeled',officialGrade:null,notes:'Bandeja con fondo verde y tejido anaranjado, útil para interferencia de vegetación y tratamiento/presentación externa.',provenance:{researchBasis:['https://academic.oup.com/ijfst/article/47/12/2545/7866116']}},
  {id:'ext-project-umami-dark-bg',title:'Uni Tray 130g',sourcePage:'https://projectumami.ca/products/uni-tray-130g',imageUrl:'https://projectumami.ca/cdn/shop/files/Umami-60_c061a3a8-791c-4818-a382-3053081fe4a7.jpg?v=1755176275&width=1946',sourceType:'commercial_reference',license:'Reference-only; source terms apply',attribution:'Project Umami',scene:'pre_shipment_tray',intendedUse:'defect_variability',qualityStatus:'unlabeled',officialGrade:null,notes:'Caja sobre fondo negro con piezas menos definidas y color más oscuro; buen caso duro de límites y sombras.',provenance:{researchBasis:['https://academic.oup.com/ijfst/article/47/12/2545/7866116','https://www.scmp.com/article/586284/sea-urchin-roe']}},
  {id:'ext-tabelog-brown-mixed',title:'Mixed darker uni tray',sourcePage:'https://tabelog.com/hokkaido/A0106/A010604/1038390/',imageUrl:'https://tblg.k-img.com/restaurant/images/Rvw/136853/640x640_rect_136853351.jpg',sourceType:'commercial_reference',license:'Reference-only; source terms apply',attribution:'Tabelog source page',scene:'pre_shipment_tray',intendedUse:'defect_variability',qualityStatus:'unlabeled',officialGrade:null,notes:'Variación visible desde amarillo a marrón con piezas rotas/irregulares. No se etiqueta como rechazo sin Calidad.',provenance:{researchBasis:['https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecs2.4911','https://projects.sare.org/project-reports/fne24-093/']}},
  {id:'ext-hakodate-saltwater-mixed',title:'Saltwater uni mixed colors',sourcePage:'https://hakoaru.net/archives/33510697.html',imageUrl:'https://livedoor.blogimg.jp/hakoaru/imgs/9/3/93830c9b.jpg',sourceType:'commercial_reference',license:'Reference-only; source terms apply',attribution:'Hakoaru',scene:'saltwater',intendedUse:'defect_variability',qualityStatus:'unlabeled',officialGrade:null,notes:'Uni sumergido en líquido con alta variación de color y forma; caso duro para segmentación y apariencia acuosa.',provenance:{researchBasis:['https://academic.oup.com/ijfst/article/47/12/2545/7866116']}},
  {id:'ext-tabelog-dense-tray',title:'Dense uni tray',sourcePage:'https://tabelog.com/fukuoka/A4001/A400101/40064452/dtlphotolst/smp2/',imageUrl:'https://tblg.k-img.com/restaurant/images/Rvw/307825/a74fe05a725b6533aa429d28881439a6.jpg',sourceType:'commercial_reference',license:'Reference-only; source terms apply',attribution:'Tabelog source page',scene:'pre_shipment_tray',intendedUse:'visual_variability',qualityStatus:'unlabeled',officialGrade:null,notes:'Bandeja densa y poco ordenada con lobos superpuestos; útil para oclusión y conteo/segmentación imperfecta.',provenance:{researchBasis:['https://spo.nmfs.noaa.gov/sites/default/files/pdf-content/MFR/mfr473/mfr4731.pdf']}}
]
