import {requireOperator,type SessionOperator} from './_auth.js'
import {hasPlantAccess} from './_plants.js'
import {getSql} from './_db.js'

type Request={method?:string;body?:unknown;query?:Record<string,string|string[]|undefined>;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type Input={date?:unknown;plantId?:unknown;notes?:unknown}
const text=(v:unknown,max=500)=>String(v??'').trim().slice(0,max)
function one(v:string|string[]|undefined){return Array.isArray(v)?v[0]:v}
function validDate(v:string){return /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(v)}
function visible(o:SessionOperator,plantId:unknown){return o.role==='admin'||typeof plantId!=='string'||!plantId||hasPlantAccess(o,plantId)}
function canClose(o:SessionOperator){return ['admin','operations'].includes(o.role)}
type MetricRow={plant_id:string|null;count?:string|number;kg?:string|number;input_kg?:string|number;output_kg?:string|number;revenue?:string|number;contribution?:string|number;known?:string|number;allocated?:string|number;produced?:string|number;cost?:string|number}
function sum(rows:MetricRow[],key:keyof MetricRow,plantId:string|null){return rows.filter(r=>!plantId||r.plant_id===plantId).reduce((a,r)=>a+Number(r[key]??0),0)}
async function build(operator:SessionOperator,date:string,plantId:string|null){const sql=getSql(),admin=operator.role==='admin',plantIds=operator.plantIds;const [receptions,production,dispatches,sales,orders,settlements,alerts,inventory,costs]=await Promise.all([
 sql`select plant_id,count(*) count,coalesce(sum(coalesce(accepted_kg,greatest(0,gross_kg-tare_kg))),0) kg from receptions where (received_at at time zone 'America/Santiago')::date=${date}::date and (${admin} or plant_id=any(${plantIds}::text[])) group by plant_id`,
 sql`select r.plant_id,count(*) count,coalesce(sum((le.metrics->>'inputKg')::numeric),0) input_kg,coalesce(sum((le.metrics->>'outputKg')::numeric),0) output_kg from lot_events le join receptions r on r.id=le.reception_id where le.event_type='production' and (le.occurred_at at time zone 'America/Santiago')::date=${date}::date and (${admin} or r.plant_id=any(${plantIds}::text[])) group by r.plant_id`,
 sql`select r.plant_id,count(*) count,coalesce(sum(d.dispatched_kg),0) kg from lot_dispatches d join receptions r on r.id=d.reception_id where d.status='confirmed' and (d.dispatched_at at time zone 'America/Santiago')::date=${date}::date and (${admin} or r.plant_id=any(${plantIds}::text[])) group by r.plant_id`,
 sql`select r.plant_id,count(*) count,coalesce(sum(s.sold_kg*s.price_per_kg_clp),0) revenue,coalesce(sum(case when st.gross_amount_clp is not null and base.physical_kg>0 then s.sold_kg*s.price_per_kg_clp-((st.gross_amount_clp+coalesce(tc.total_cost,0))*(s.sold_kg/base.physical_kg)) else 0 end),0) contribution,count(*) filter(where st.gross_amount_clp is not null and base.physical_kg>0) known from lot_sales s join receptions r on r.id=s.reception_id left join settlements st on st.reception_id=r.id left join lateral (select coalesce(sum(amount_clp),0) total_cost from transformation_costs where reception_id=r.id) tc on true left join lateral (select coalesce((select (le.metrics->>'outputKg')::numeric from lot_events le where le.reception_id=r.id and le.event_type='production' and le.metrics ? 'outputKg' order by le.occurred_at desc limit 1),r.accepted_kg,greatest(0,r.gross_kg-r.tare_kg)) physical_kg) base on true where s.status='confirmed' and (s.sold_at at time zone 'America/Santiago')::date=${date}::date and (${admin} or r.plant_id=any(${plantIds}::text[])) group by r.plant_id`,
 sql`select o.plant_id,count(*) count,coalesce(sum(o.committed_kg),0) kg,coalesce(sum((select coalesce(sum(a.allocated_kg),0) from sales_order_allocations a where a.order_id=o.id)),0) allocated,coalesce(sum((select coalesce(sum(least(a.allocated_kg,coalesce((select (le.metrics->>'outputKg')::numeric from lot_events le where le.reception_id=a.reception_id and le.event_type='production' and le.metrics ? 'outputKg' order by le.occurred_at desc limit 1),0))),0) from sales_order_allocations a where a.order_id=o.id)),0) produced from sales_orders o where o.status in ('pending','prepared') and o.delivery_date<=${date}::date and (${admin} or o.plant_id=any(${plantIds}::text[]) or o.plant_id is null) group by o.plant_id`,
 sql`select r.plant_id,count(*) count from settlements st join receptions r on r.id=st.reception_id where st.status in ('draft','pending') and (${admin} or r.plant_id=any(${plantIds}::text[])) group by r.plant_id`,
 sql`select plant_id,count(*) count from receptions where quality_status in ('Revisión','Alerta calibre') and (${admin} or plant_id=any(${plantIds}::text[])) group by plant_id`,
 sql`select r.plant_id,coalesce(sum(case when im.to_location_id is not null then im.moved_kg else 0 end)-sum(case when im.from_location_id is not null then im.moved_kg else 0 end),0) kg from receptions r left join inventory_movements im on im.reception_id=r.id where (${admin} or r.plant_id=any(${plantIds}::text[])) group by r.plant_id`,
 sql`select r.plant_id,coalesce(sum(tc.amount_clp),0) cost from transformation_costs tc join receptions r on r.id=tc.reception_id where (tc.occurred_at at time zone 'America/Santiago')::date=${date}::date and (${admin} or r.plant_id=any(${plantIds}::text[])) group by r.plant_id`
]);const rr=receptions as MetricRow[],pr=production as MetricRow[],dr=dispatches as MetricRow[],sr=sales as MetricRow[],or=orders as MetricRow[],str=settlements as MetricRow[],ar=alerts as MetricRow[],ir=inventory as MetricRow[],cr=costs as MetricRow[];const input=sum(pr,'input_kg',plantId),output=sum(pr,'output_kg',plantId),dueKg=sum(or,'kg',plantId),allocatedKg=sum(or,'allocated',plantId),producedCoverageKg=sum(or,'produced',plantId);return {date,plantId,generatedAt:new Date().toISOString(),receptions:{count:sum(rr,'count',plantId),kg:sum(rr,'kg',plantId)},production:{events:sum(pr,'count',plantId),inputKg:input,outputKg:output,yieldPct:input>0?Number((output/input*100).toFixed(2)):null},dispatches:{count:sum(dr,'count',plantId),kg:sum(dr,'kg',plantId)},sales:{count:sum(sr,'count',plantId),revenueClp:sum(sr,'revenue',plantId),knownContributionClp:sum(sr,'contribution',plantId),knownContributionSales:sum(sr,'known',plantId)},commitments:{dueOrders:sum(or,'count',plantId),dueKg,allocatedKg,producedCoverageKg,allocationCoveragePct:dueKg>0?Number((allocatedKg/dueKg*100).toFixed(1)):null,producedCoveragePct:dueKg>0?Number((producedCoverageKg/dueKg*100).toFixed(1)):null},pending:{settlements:sum(str,'count',plantId),qualityAlerts:sum(ar,'count',plantId)},inventory:{locatedKg:sum(ir,'kg',plantId)},transformation:{costClp:sum(cr,'cost',plantId)}}}
export default async function handler(req:Request,res:Response){res.setHeader('Cache-Control','no-store');try{const operator=await requireOperator(req);if(!operator)return res.status(401).json({ok:false,error:'Sesión requerida'});if(req.method==='GET'){const date=text(one(req.query?.date),20)||new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),plantId=text(one(req.query?.plantId),80)||null;if(!validDate(date)||plantId&&!visible(operator,plantId))return res.status(400).json({ok:false,error:'Alcance de cierre inválido'});const snapshot=await build(operator,date,plantId);const saved=operator.role==='admin'||plantId?await getSql()`select id,generated_by,generated_at,notes from daily_closes where close_date=${date}::date and coalesce(plant_id,'')=coalesce(${plantId},'') and (${operator.role==='admin'} or plant_id=any(${operator.plantIds}::text[])) limit 1`:[];return res.status(200).json({ok:true,snapshot,saved:Array.isArray(saved)?saved[0]??null:null,permissions:{canClose:canClose(operator)}})}if(req.method==='POST'){if(!canClose(operator))return res.status(403).json({ok:false,error:'Acción no autorizada'});const input=(req.body??{}) as Input,date=text(input.date,20),plantId=text(input.plantId,80)||null,notes=text(input.notes,1000)||null;if(!validDate(date)||plantId&&!visible(operator,plantId)||operator.role!=='admin'&&!plantId)return res.status(400).json({ok:false,error:'El cierre corporativo requiere rol Admin; selecciona una planta autorizada'});const snapshot=await build(operator,date,plantId),encoded=JSON.stringify(snapshot);const rows=await getSql()`insert into daily_closes(close_date,plant_id,snapshot,notes,generated_by) values(${date}::date,${plantId},${encoded}::jsonb,${notes},${operator.fullName}) on conflict(close_date,(coalesce(plant_id,'__corporate__'))) do update set snapshot=excluded.snapshot,notes=excluded.notes,generated_by=excluded.generated_by,generated_at=now() returning id,generated_by,generated_at`;return res.status(201).json({ok:true,close:Array.isArray(rows)?rows[0]:null,snapshot})}res.setHeader('Allow','GET, POST');return res.status(405).json({ok:false,error:'Método no permitido'})}catch(error){const message=error instanceof Error?error.message:'';return res.status(message.includes('daily_closes')||message.includes('transformation_costs')?503:500).json({ok:false,error:message.includes('transformation_costs')?'Falta aplicar 010_transformation_costs.sql':message.includes('daily_closes')?'Falta aplicar 009_sales_orders_inventory_daily_close.sql':'No fue posible construir el cierre diario'})}}
