import {requireOperator,type SessionOperator} from './_auth.js'
import {getSql} from './_db.js'

type Request={method?:string;headers?:Record<string,string|string[]|undefined>;query?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type Row=Record<string,unknown>
type NodeStatus='pass'|'attention'|'pending'|'info'
type GraphNode={id:string;group:string;label:string;status:NodeStatus;detail:string;at:string|null;metrics?:Record<string,unknown>}
type GraphEdge={from:string;to:string;kind:'flow'|'trace'}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const one=(value:string|string[]|undefined)=>Array.isArray(value)?value[0]:value
const rows=(value:unknown)=>Array.isArray(value)?value as Row[]:[]
const text=(value:unknown)=>value==null?'':String(value)
const num=(value:unknown)=>{if(value==null||value==='')return null;const parsed=Number(value);return Number.isFinite(parsed)?parsed:null}
const record=(value:unknown)=>value&&typeof value==='object'&&!Array.isArray(value)?value as Row:null
const moneyRole=(operator:SessionOperator)=>['admin','finance','operations'].includes(operator.role)

export default async function handler(req:Request,res:Response){
 res.setHeader('Cache-Control','no-store')
 if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({ok:false,error:'Método no permitido'})}
 try{
  const operator=await requireOperator(req);if(!operator)return res.status(401).json({ok:false,error:'Sesión requerida'})
  const receptionId=String(one(req.query?.receptionId)??'').trim();if(!uuid.test(receptionId))return res.status(400).json({ok:false,error:'Lote inválido'})
  const sql=getSql(),admin=operator.role==='admin',money=moneyRole(operator)
  const receptionRaw=await sql`select r.id,r.reception_number,r.plant_id,r.species,r.extraction_zone,r.accepted_kg,r.quality_status,r.status,r.received_at,p.legal_name supplier from receptions r join parties p on p.id=r.supplier_id where r.id=${receptionId}::uuid and (${admin} or r.plant_id=any(${operator.plantIds}::text[])) limit 1`
  const reception=rows(receptionRaw)[0];if(!reception)return res.status(404).json({ok:false,error:'Lote fuera de alcance'})
  const [eventsRaw,packingRaw,palletRaw,coldRaw,holdsRaw,dispatchRaw,salesRaw,costsRaw,settlementRaw]=await Promise.all([
   sql`select id,event_type,title,detail,metrics,occurred_at from lot_events where reception_id=${receptionId}::uuid order by occurred_at`,
   sql`select id,packing_unit_code,status,grade,format,net_kg,packed_at from packing_units where reception_id=${receptionId}::uuid order by packed_at`,
   sql`select distinct p.id,p.pallet_code,p.status,p.grade,p.destination,p.box_count,p.net_kg,p.created_at,p.closed_at from pallets p join pallet_packing_units i on i.pallet_id=p.id join packing_units u on u.id=i.packing_unit_id where u.reception_id=${receptionId}::uuid order by p.created_at`,
   sql`select distinct r.id,r.run_code,r.status,r.last_observed_c,r.deviation_count,r.started_at,r.completed_at,a.name asset_name from cold_runs r join cold_assets a on a.id=r.asset_id join cold_run_loads l on l.run_id=r.id left join pallet_packing_units pi on pi.pallet_id=l.pallet_id and pi.removed_at is null left join packing_units pu on pu.id=pi.packing_unit_id where l.reception_id=${receptionId}::uuid or pu.reception_id=${receptionId}::uuid order by r.started_at`,
   sql`select id,authority,status,reason,opened_at,resolved_at from regulatory_holds h where h.reception_id=${receptionId}::uuid or exists(select 1 from packing_units u where u.id=h.packing_unit_id and u.reception_id=${receptionId}::uuid) or exists(select 1 from pallet_packing_units i join packing_units u on u.id=i.packing_unit_id where i.pallet_id=h.pallet_id and u.reception_id=${receptionId}::uuid) order by opened_at`,
   sql`select id,dispatch_number,destination,dispatched_kg,status,dispatched_at from lot_dispatches where reception_id=${receptionId}::uuid order by dispatched_at`,
   money?sql`select id,sold_kg,price_per_kg_clp,status,sold_at from lot_sales where reception_id=${receptionId}::uuid order by sold_at`:Promise.resolve([]),
   money?sql`select coalesce(sum(amount_clp),0) total from transformation_costs where reception_id=${receptionId}::uuid`:Promise.resolve([]),
   money?sql`select gross_amount_clp,status,created_at from settlements where reception_id=${receptionId}::uuid order by created_at desc limit 1`:Promise.resolve([]),
  ])
  const nodes:GraphNode[]=[],edges:GraphEdge[]=[];const add=(node:GraphNode)=>nodes.push(node),link=(from:string,to:string,kind:'flow'|'trace'='flow')=>edges.push({from,to,kind})
  add({id:'origin',group:'Origen',label:text(reception.supplier)||'Proveedor',status:'pass',detail:[text(reception.extraction_zone),num(reception.accepted_kg)!=null?`${num(reception.accepted_kg)} kg aceptados`:null].filter(Boolean).join(' · '),at:text(reception.received_at)||null})
  add({id:'reception',group:'Recepción',label:`REC-${text(reception.reception_number)}`,status:'pass',detail:`${text(reception.species)} · ${text(reception.plant_id)}`,at:text(reception.received_at)||null});link('origin','reception')
  const events=rows(eventsRaw),qualityEvents=events.filter(row=>row.event_type==='quality'),productionEvents=events.filter(row=>row.event_type==='production')
  if(qualityEvents.length){const latest=qualityEvents[qualityEvents.length-1],metrics=record(latest.metrics),qualityStatus=text(metrics?.qualityStatus)||text(reception.quality_status),attention=['Revisión','Alerta calibre'].includes(qualityStatus);add({id:'quality',group:'Proceso',label:'Calidad',status:attention?'attention':qualityStatus==='Clasificado'?'pass':'pending',detail:[qualityStatus,metrics?.temperatureC!=null?`${num(metrics.temperatureC)} °C`:null,metrics?.acceptedKg!=null?`${num(metrics.acceptedKg)} kg aceptados`:null].filter(Boolean).join(' · '),at:text(latest.occurred_at)||null});link('reception','quality')}
  if(productionEvents.length){const latest=productionEvents[productionEvents.length-1],metrics=record(latest.metrics),input=num(metrics?.inputKg),output=num(metrics?.outputKg),yieldPct=input!=null&&input>0&&output!=null?output/input*100:null;add({id:'production',group:'Proceso',label:text(latest.title)||'Producción',status:'pass',detail:[metrics?.lineName?text(metrics.lineName):null,output!=null?`${output} kg salida`:null,yieldPct!=null?`${yieldPct.toLocaleString('es-CL',{maximumFractionDigits:1})}% yield`:null].filter(Boolean).join(' · '),at:text(latest.occurred_at)||null});link(qualityEvents.length?'quality':'reception','production')}
  const packing=rows(packingRaw),packedKg=packing.reduce((sum,row)=>sum+(num(row.net_kg)??0),0);if(packing.length){const attention=packing.some(row=>['held','voided'].includes(text(row.status)));add({id:'packing',group:'Packing',label:`${packing.length} caja${packing.length===1?'':'s'}`,status:attention?'attention':'pass',detail:`${packedKg.toLocaleString('es-CL',{maximumFractionDigits:2})} kg · ${packing.map(row=>text(row.format)).filter(Boolean).slice(0,2).join(' / ')}`,at:text(packing[packing.length-1].packed_at)||null});link(productionEvents.length?'production':qualityEvents.length?'quality':'reception','packing')}
  const pallets=rows(palletRaw);if(pallets.length){const attention=pallets.some(row=>text(row.status)==='held');add({id:'pallet',group:'Logística',label:`${pallets.length} pallet${pallets.length===1?'':'s'}`,status:attention?'attention':pallets.every(row=>['closed','released','dispatched'].includes(text(row.status)))?'pass':'pending',detail:pallets.map(row=>`${text(row.pallet_code)} · ${text(row.status)}`).join(' | '),at:text(pallets[pallets.length-1].closed_at)||text(pallets[pallets.length-1].created_at)||null});link(packing.length?'packing':productionEvents.length?'production':'reception','pallet')}
  const cold=rows(coldRaw);if(cold.length){const attention=cold.some(row=>text(row.status)==='deviation'||Number(row.deviation_count??0)>0);add({id:'cold',group:'Frío',label:`Cadena de frío · ${cold.length} ciclo${cold.length===1?'':'s'}`,status:attention?'attention':cold.every(row=>text(row.status)==='completed')?'pass':'pending',detail:cold.map(row=>`${text(row.run_code)} · ${text(row.status)}${row.last_observed_c!=null?` · ${num(row.last_observed_c)} °C`:''}`).join(' | '),at:text(cold[cold.length-1].completed_at)||text(cold[cold.length-1].started_at)||null});link(pallets.length?'pallet':packing.length?'packing':productionEvents.length?'production':'reception','cold')}
  const holds=rows(holdsRaw),blocking=holds.filter(row=>['open','rejected'].includes(text(row.status)));add({id:'regulatory',group:'Regulatorio',label:blocking.length?`${blocking.length} hold${blocking.length===1?'':'s'} vigente${blocking.length===1?'':'s'}`:'Sin holds vigentes',status:blocking.length?'attention':'pass',detail:holds.length?holds.map(row=>`${text(row.authority)} · ${text(row.status)}`).join(' | '):'Control regulatorio sin bloqueo observado',at:holds.length?text(holds[holds.length-1].resolved_at)||text(holds[holds.length-1].opened_at)||null:null});link(cold.length?'cold':pallets.length?'pallet':packing.length?'packing':productionEvents.length?'production':'reception','regulatory')
  const dispatches=rows(dispatchRaw);if(dispatches.length){const latest=dispatches[dispatches.length-1],pending=dispatches.some(row=>text(row.status)!=='confirmed');add({id:'dispatch',group:'Despacho',label:`${dispatches.length} despacho${dispatches.length===1?'':'s'}`,status:pending?'pending':'pass',detail:dispatches.map(row=>`${text(row.destination)} · ${num(row.dispatched_kg)??0} kg · ${text(row.status)}`).join(' | '),at:text(latest.dispatched_at)||null});link('regulatory','dispatch')}
  if(money){const sales=rows(salesRaw),confirmedSales=sales.filter(row=>text(row.status)==='confirmed'),revenue=confirmedSales.reduce((sum,row)=>sum+(num(row.sold_kg)??0)*(num(row.price_per_kg_clp)??0),0),transform=num(rows(costsRaw)[0]?.total)??0,purchase=num(rows(settlementRaw)[0]?.gross_amount_clp);if(sales.length||transform>0||purchase!=null){add({id:'economics',group:'Economía',label:'Resultado económico',status:confirmedSales.length?'info':'pending',detail:[revenue>0?`Ingresos $${Math.round(revenue).toLocaleString('es-CL')}`:null,purchase!=null?`Compra $${Math.round(purchase).toLocaleString('es-CL')}`:null,transform>0?`Transformación $${Math.round(transform).toLocaleString('es-CL')}`:null].filter(Boolean).join(' · ')||'Economía aún incompleta',at:confirmedSales.length?text(confirmedSales[confirmedSales.length-1].sold_at)||null:null});link(dispatches.length?'dispatch':'regulatory','economics','trace')}}
  return res.status(200).json({ok:true,schemaVersion:'seafood.event-graph.live.v1',reception:{id:receptionId,receptionNumber:reception.reception_number,plantId:reception.plant_id,supplier:reception.supplier,species:reception.species},nodes,edges,summary:{nodes:nodes.length,attention:nodes.filter(node=>node.status==='attention').length,pending:nodes.filter(node=>node.status==='pending').length,japanReleasable:null},permissions:{canSeeMoney:money}})
 }catch(error){console.error('lot_graph_error',error instanceof Error?error.message:'unknown');return res.status(500).json({ok:false,error:'No fue posible construir la trazabilidad del lote'})}
}
