import {requireOperator,type SessionOperator} from './_auth.js'
import {getSql} from './_db.js'

type Request={method?:string;query?:Record<string,string|string[]|undefined>;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
function one(v:string|string[]|undefined){return Array.isArray(v)?v[0]:v}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
async function access(id:string,o:SessionOperator){const sql=getSql(),rows=o.role==='admin'?await sql`select id,plant_id from receptions where id=${id}::uuid limit 1`:await sql`select id,plant_id from receptions where id=${id}::uuid and plant_id=any(${o.plantIds}::text[]) limit 1`;return Array.isArray(rows)?rows[0] as {id?:string;plant_id?:string|null}|undefined:undefined}
export default async function handler(req:Request,res:Response){res.setHeader('Cache-Control','no-store');if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({ok:false,error:'Método no permitido'})}try{const operator=await requireOperator(req);if(!operator)return res.status(401).json({ok:false,error:'Sesión requerida'});const receptionId=String(one(req.query?.receptionId)??'').trim();if(!uuid.test(receptionId)||!await access(receptionId,operator))return res.status(404).json({ok:false,error:'Lote no disponible'});const sql=getSql(),commercialRole=['admin','operations','finance'].includes(operator.role),costRole=['admin','operations','finance'].includes(operator.role);const [orders,movements,costs]=await Promise.all([commercialRole?sql`select o.id,o.order_number,o.product,o.delivery_date,o.status,c.legal_name customer,a.allocated_kg,a.created_at,a.created_by from sales_order_allocations a join sales_orders o on o.id=a.order_id join parties c on c.id=o.customer_id where a.reception_id=${receptionId}::uuid order by o.delivery_date,o.order_number`:Promise.resolve([]),sql`select m.id,m.movement_type,m.moved_kg,m.reason,m.occurred_at,m.created_by,fl.name from_location,tl.name to_location from inventory_movements m left join inventory_locations fl on fl.id=m.from_location_id left join inventory_locations tl on tl.id=m.to_location_id where m.reception_id=${receptionId}::uuid order by m.occurred_at desc`,costRole?sql`select id,category,amount_clp,quantity,unit,note,occurred_at,created_by from transformation_costs where reception_id=${receptionId}::uuid order by occurred_at desc`:Promise.resolve([])]);const costRows=Array.isArray(costs)?costs:[],total=costRows.reduce((sum,row)=>sum+Number((row as {amount_clp?:unknown}).amount_clp??0),0);return res.status(200).json({ok:true,orders:Array.isArray(orders)?orders:[],inventoryMovements:Array.isArray(movements)?movements:[],costs:costRows,totalTransformationCostClp:costRole?total:null,permissions:{canSeeCommercial:commercialRole,canSeeCosts:costRole}})}catch{return res.status(500).json({ok:false,error:'No fue posible cargar continuidad del lote'})}}
