import {requireOperator,type SessionOperator} from './_auth.js'
import {hasPlantAccess} from './_plants.js'
import {getSql} from './_db.js'

type Request={method?:string;body?:unknown;query?:Record<string,string|string[]|undefined>;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type EventInput={receptionId?:unknown;eventType?:unknown;title?:unknown;detail?:unknown;metrics?:unknown}
type ReceptionAccess={id:string;plant_id:string|null;gross_kg:string|number|null}
type Metrics=Record<string,unknown>
const allowedTypes=new Set(['quality','production','note'])
const qualityStatuses=new Set(['Muestreo','Clasificado','Revisión','Alerta calibre'])
function readId(request:Request){const value=request.query?.receptionId;return Array.isArray(value)?value[0]:value}
function canWrite(operator:SessionOperator,eventType:string){if(operator.role==='admin')return true;if(eventType==='quality')return ['operations','quality'].includes(operator.role);if(eventType==='production')return operator.role==='operations';return ['operations','quality'].includes(operator.role)}
async function accessibleReception(receptionId:string,operator:SessionOperator){const rows=await getSql()`select id,plant_id,gross_kg from receptions where id=${receptionId}::uuid limit 1`;const row=Array.isArray(rows)?rows[0] as ReceptionAccess|undefined:undefined;if(!row?.id)return null;if(operator.role!=='admin'&&(!row.plant_id||!hasPlantAccess(operator,row.plant_id)))return null;return row}
function objectMetrics(value:unknown):Metrics{return value&&typeof value==='object'&&!Array.isArray(value)?value as Metrics:{}}
function finite(value:unknown){const number=Number(value);return Number.isFinite(number)?number:null}
function qualityMetrics(input:Metrics,reception:ReceptionAccess){const qualityStatus=String(input.qualityStatus??'').trim();const temperatureC=input.temperatureC==null?null:finite(input.temperatureC);const acceptedKg=input.acceptedKg==null?null:finite(input.acceptedKg);const defectPct=input.defectPct==null?null:finite(input.defectPct);const sampleCount=input.sampleCount==null?null:finite(input.sampleCount);const gross=Number(reception.gross_kg??0);if(!qualityStatuses.has(qualityStatus)||temperatureC!=null&&(temperatureC< -5||temperatureC>30)||acceptedKg!=null&&(acceptedKg<0||(gross>0&&acceptedKg>gross))||defectPct!=null&&(defectPct<0||defectPct>100)||sampleCount!=null&&(!Number.isInteger(sampleCount)||sampleCount<0||sampleCount>10000))return null;return {qualityStatus,temperatureC,acceptedKg,defectPct,sampleCount}}
async function productionMetrics(input:Metrics){const lineId=String(input.lineId??'').trim(),stage=String(input.stage??'').trim().slice(0,120),inputKg=finite(input.inputKg),outputKg=finite(input.outputKg);if(!lineId||inputKg==null||outputKg==null||inputKg<=0||outputKg<0||outputKg>inputKg*1.1)return null;const lines=await getSql()`select id,name,destination from production_lines where id=${lineId} and status='Activa' limit 1`;const line=Array.isArray(lines)?lines[0] as {id?:string;name?:string;destination?:string}|undefined:undefined;if(!line?.id)return null;return {lineId:line.id,lineName:line.name??line.id,destination:line.destination??null,stage:stage||null,inputKg,outputKg,yieldPct:inputKg>0?Number(((outputKg/inputKg)*100).toFixed(2)):null}}
export default async function handler(request:Request,response:Response){response.setHeader('Cache-Control','no-store');try{const operator=await requireOperator(request);if(!operator)return response.status(401).json({ok:false,error:'Sesión requerida'});if(request.method==='GET')return getLot(request,response,operator);if(request.method==='POST')return addEvent(request,response,operator);response.setHeader('Allow','GET, POST');return response.status(405).json({ok:false,error:'Método no permitido'})}catch(error){const message=error instanceof Error?error.message:'';return response.status(message.includes('lot_events')?503:500).json({ok:false,error:message.includes('lot_events')?'Falta aplicar la migración 007_live_lot_memory.sql':'No fue posible cargar la memoria del lote'})}}
async function getLot(request:Request,response:Response,operator:SessionOperator){const receptionId=String(readId(request)??'').trim();if(!/^[0-9a-f-]{36}$/i.test(receptionId))return response.status(400).json({ok:false,error:'Recepción inválida'});if(!await accessibleReception(receptionId,operator))return response.status(404).json({ok:false,error:'Recepción no disponible'});const sql=getSql();const [receptionRaw,eventsRaw,approvalsRaw,settlementRaw,linesRaw]=await Promise.all([
 sql`select r.id,r.reception_number,r.plant_id,r.species,r.extraction_zone,r.guide_kg,r.gross_kg,r.tare_kg,r.drained_kg,r.accepted_kg,r.temperature_c,r.quality_status,r.status,r.source,r.received_at,r.created_at,p.legal_name supplier,coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'kind',e.kind,'label',e.label,'url',e.url,'note',e.note,'createdBy',e.created_by,'createdAt',e.created_at) order by e.created_at) from reception_evidence e where e.reception_id=r.id),'[]'::jsonb) evidence from receptions r join parties p on p.id=r.supplier_id where r.id=${receptionId}::uuid`,
 sql`select id,event_type,title,detail,metrics,created_by,occurred_at from lot_events where reception_id=${receptionId}::uuid order by occurred_at desc`,
 sql`select id,entity_type,entity_id,action,comment,acted_by,acted_at from approval_actions where entity_id=${receptionId}::uuid or entity_id in (select id from settlements where reception_id=${receptionId}::uuid) order by acted_at desc`,
 sql`select s.id,s.gross_amount_clp,s.other_deductions_clp,s.net_amount_clp,s.status,s.settled_at,s.created_at,s.price_per_kg_clp,s.credit_recovery_clp,s.created_by,s.approved_by,s.calculation_snapshot,coalesce((select jsonb_agg(jsonb_build_object('id',cm.id,'kind',cm.kind,'amountClp',cm.amount_clp,'occurredAt',cm.occurred_at,'comment',cm.comment,'createdBy',cm.created_by) order by cm.occurred_at) from credit_movements cm where cm.settlement_id=s.id),'[]'::jsonb) credit_movements from settlements s where s.reception_id=${receptionId}::uuid order by s.created_at desc limit 1`,
 sql`select id,name,family,destination from production_lines where status='Activa' order by name`
]);return response.status(200).json({ok:true,reception:Array.isArray(receptionRaw)?receptionRaw[0]:null,events:Array.isArray(eventsRaw)?eventsRaw:[],approvals:Array.isArray(approvalsRaw)?approvalsRaw:[],settlement:Array.isArray(settlementRaw)?settlementRaw[0]??null:null,productionLines:Array.isArray(linesRaw)?linesRaw:[],permissions:{canAddQuality:canWrite(operator,'quality'),canAddProduction:canWrite(operator,'production'),canAddNote:canWrite(operator,'note')}})}
async function addEvent(request:Request,response:Response,operator:SessionOperator){const input=(request.body??{}) as EventInput;const receptionId=String(input.receptionId??'').trim(),eventType=String(input.eventType??'').trim(),title=String(input.title??'').trim().slice(0,120),detail=String(input.detail??'').trim().slice(0,1000);if(!/^[0-9a-f-]{36}$/i.test(receptionId)||!allowedTypes.has(eventType)||title.length<2||!canWrite(operator,eventType))return response.status(400).json({ok:false,error:'Evento de lote inválido'});const reception=await accessibleReception(receptionId,operator);if(!reception)return response.status(404).json({ok:false,error:'Recepción no disponible'});const raw=objectMetrics(input.metrics);let metrics:Metrics;if(eventType==='quality'){const normalized=qualityMetrics(raw,reception);if(!normalized)return response.status(400).json({ok:false,error:'Métricas de calidad inválidas'});metrics=normalized}else if(eventType==='production'){const normalized=await productionMetrics(raw);if(!normalized)return response.status(400).json({ok:false,error:'Métricas de producción inválidas'});metrics=normalized}else metrics=raw;const encoded=JSON.stringify(metrics).slice(0,4000);if(eventType==='quality'){const quality=metrics as {qualityStatus:string;temperatureC:number|null;acceptedKg:number|null};const rows=await getSql()`with event as (insert into lot_events(reception_id,event_type,title,detail,metrics,created_by) values(${receptionId}::uuid,${eventType},${title},${detail||null},${encoded}::jsonb,${operator.fullName}) returning id,event_type,title,detail,metrics,created_by,occurred_at),updated as (update receptions set quality_status=${quality.qualityStatus},temperature_c=coalesce(${quality.temperatureC},temperature_c),accepted_kg=coalesce(${quality.acceptedKg},accepted_kg) where id=${receptionId}::uuid returning id) select * from event`;return response.status(201).json({ok:true,event:Array.isArray(rows)?rows[0]:null})}const rows=await getSql()`insert into lot_events(reception_id,event_type,title,detail,metrics,created_by) values(${receptionId}::uuid,${eventType},${title},${detail||null},${encoded}::jsonb,${operator.fullName}) returning id,event_type,title,detail,metrics,created_by,occurred_at`;return response.status(201).json({ok:true,event:Array.isArray(rows)?rows[0]:null})}
