import {requireOperator,type SessionOperator} from './_auth.js'
import {getSql} from './_db.js'
type Request={method?:string;body?:unknown;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type Input={action?:unknown;itemId?:unknown;sku?:unknown;name?:unknown;category?:unknown;unit?:unknown;minimumStock?:unknown;preferredSupplierId?:unknown;notes?:unknown;plantId?:unknown;locationId?:unknown;supplierId?:unknown;movementType?:unknown;quantity?:unknown;unitCostClp?:unknown;documentRef?:unknown;occurredAt?:unknown}
const text=(v:unknown,max=500)=>String(v??'').trim().slice(0,max)
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const finite=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:null}
const canWrite=(o:SessionOperator)=>['admin','operations'].includes(o.role)
const signed=(type:string,q:number)=>['receipt','transfer_in','adjustment_in'].includes(type)?q:-q
export default async function handler(req:Request,res:Response){res.setHeader('Cache-Control','no-store');try{const operator=await requireOperator(req);if(!operator)return res.status(401).json({ok:false,error:'Sesión requerida'});if(req.method==='GET')return list(res,operator);if(req.method==='POST')return mutate(req,res,operator);res.setHeader('Allow','GET, POST');return res.status(405).json({ok:false,error:'Método no permitido'})}catch(error){const m=error instanceof Error?error.message:'';return res.status(m.includes('inventory_items')?503:500).json({ok:false,error:m.includes('inventory_items')?'Falta aplicar la migración de inventario de insumos':'No fue posible cargar inventario de insumos'})}}
async function list(res:Response,operator:SessionOperator){const sql=getSql(),admin=operator.role==='admin',plantIds=operator.plantIds;const [itemsRaw,movementsRaw,suppliersRaw]=await Promise.all([sql`select i.id,i.sku,i.name,i.category,i.unit,i.minimum_stock,i.active,i.notes,p.legal_name preferred_supplier,coalesce(sum(case when m.movement_type in ('receipt','transfer_in','adjustment_in') then m.quantity else -m.quantity end),0) stock,coalesce(sum(case when m.movement_type in ('receipt','transfer_in','adjustment_in') then m.quantity*m.unit_cost_clp else 0 end),0) inbound_value_clp from inventory_items i left join parties p on p.id=i.preferred_supplier_id left join inventory_item_movements m on m.item_id=i.id and (${admin} or m.plant_id=any(${plantIds}::text[])) where i.active group by i.id,p.legal_name order by i.category,i.name`,sql`select m.id,m.item_id,i.name item,i.unit,m.plant_id,m.movement_type,m.quantity,m.unit_cost_clp,m.document_ref,m.occurred_at,m.created_by,p.legal_name supplier from inventory_item_movements m join inventory_items i on i.id=m.item_id left join parties p on p.id=m.supplier_id where ${admin} or m.plant_id=any(${plantIds}::text[]) order by m.occurred_at desc limit 500`,sql`select id,legal_name from parties where kind='supplier'::party_kind and active order by legal_name`]);const items=(Array.isArray(itemsRaw)?itemsRaw:[]).map((r:any)=>({...r,belowMinimum:Number(r.stock)<Number(r.minimum_stock)}));return res.status(200).json({ok:true,items,movements:movementsRaw,suppliers:suppliersRaw,permissions:{canWrite:canWrite(operator)}})}
async function mutate(req:Request,res:Response,operator:SessionOperator){if(!canWrite(operator))return res.status(403).json({ok:false,error:'Acción no autorizada'});const input=(req.body??{}) as Input,action=text(input.action,30),sql=getSql();if(action==='item'){const id=text(input.itemId,40),name=text(input.name,160),category=text(input.category,40),unit=text(input.unit,40),min=finite(input.minimumStock)??0,supplier=text(input.preferredSupplierId,40)||null;if(!name||!unit||min<0||!['raw_material','ingredient','packaging','consumable','spare_part','other'].includes(category)||supplier&&!uuid.test(supplier))return res.status(400).json({ok:false,error:'Artículo inválido'});const rows=id&&uuid.test(id)?await sql`update inventory_items set sku=${text(input.sku,80)||null},name=${name},category=${category},unit=${unit},minimum_stock=${min},preferred_supplier_id=${supplier}::uuid,notes=${text(input.notes,1000)||null},updated_at=now() where id=${id}::uuid returning id`:await sql`insert into inventory_items(sku,name,category,unit,minimum_stock,preferred_supplier_id,notes) values(${text(input.sku,80)||null},${name},${category},${unit},${min},${supplier}::uuid,${text(input.notes,1000)||null}) returning id`;return res.status(200).json({ok:true,itemId:(rows as any[])[0]?.id})}if(action==='movement'){const itemId=text(input.itemId,40),plantId=text(input.plantId,80),location=text(input.locationId,40)||null,supplier=text(input.supplierId,40)||null,type=text(input.movementType,32),q=finite(input.quantity),cost=finite(input.unitCostClp),date=new Date(text(input.occurredAt,64)||Date.now());if(!uuid.test(itemId)||!plantId||operator.role!=='admin'&&!operator.plantIds.includes(plantId)||location&&!uuid.test(location)||supplier&&!uuid.test(supplier)||q==null||q<=0||!['receipt','consume','transfer_in','transfer_out','adjustment_in','adjustment_out'].includes(type)||Number.isNaN(date.getTime()))return res.status(400).json({ok:false,error:'Movimiento inválido'});if(signed(type,q)<0){const rows=await sql`select coalesce(sum(case when movement_type in ('receipt','transfer_in','adjustment_in') then quantity else -quantity end),0) stock from inventory_item_movements where item_id=${itemId}::uuid and plant_id=${plantId}`;if(Number((rows as any[])[0]?.stock??0)<q)return res.status(409).json({ok:false,error:'Stock insuficiente para este movimiento'})}await sql`insert into inventory_item_movements(item_id,plant_id,location_id,supplier_id,movement_type,quantity,unit_cost_clp,document_ref,occurred_at,created_by,created_by_operator_id) values(${itemId}::uuid,${plantId},${location}::uuid,${supplier}::uuid,${type},${q},${cost},${text(input.documentRef,120)||null},${date.toISOString()}::timestamptz,${operator.fullName},${operator.id}::uuid)`;return res.status(201).json({ok:true})}return res.status(400).json({ok:false,error:'Acción inválida'})}
