import {requireOperator,type SessionOperator} from './_auth.js'
import {getSql} from './_db.js'

type Request={method?:string;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type ReceptionRow={id:string;reception_number:string|number;plant_id:string|null;species:string;quality_status:string;status:string;received_at:string;supplier:string;has_quality:boolean;has_production:boolean;has_settlement:boolean;settlement_status:string|null;latest_event_at:string|null}
type BalanceRow={scope:string;plant:string;supplier:string;line:string;input_kg:string|number;output_kg:string|number;records:string|number}
function allowed(operator:SessionOperator,plantId:string|null){return operator.role==='admin'||!plantId||operator.plantIds.includes(plantId)}
function lifecycle(row:ReceptionRow){if(row.settlement_status==='settled'||row.settlement_status==='approved')return 'cerrado';if(row.has_settlement)return 'liquidacion';if(row.has_production)return 'produccion';if(row.has_quality)return 'calidad';return 'recepcion'}
function nextAction(row:ReceptionRow){if(row.quality_status==='Alerta calibre'||row.quality_status==='Revisión')return {priority:'attention',label:'Resolver observación de calidad'};if(!row.has_quality)return {priority:'normal',label:'Registrar control de calidad'};if(!row.has_production)return {priority:'normal',label:'Registrar avance de producción'};if(!row.has_settlement)return {priority:'normal',label:'Preparar liquidación'};if(row.settlement_status!=='settled'&&row.settlement_status!=='approved')return {priority:'normal',label:'Cerrar liquidación'};return {priority:'done',label:'Lote cerrado'} }
export default async function handler(request:Request,response:Response){response.setHeader('Cache-Control','no-store');if(request.method!=='GET'){response.setHeader('Allow','GET');return response.status(405).json({ok:false,error:'Método no permitido'})}try{const operator=await requireOperator(request);if(!operator)return response.status(401).json({ok:false,error:'Sesión requerida'});const sql=getSql();const [receptionsRaw,liveBalanceRaw,historicalBalanceRaw]=await Promise.all([
 sql`select r.id,r.reception_number,r.plant_id,r.species,r.quality_status,r.status,r.received_at,p.legal_name supplier,exists(select 1 from lot_events le where le.reception_id=r.id and le.event_type='quality') has_quality,exists(select 1 from lot_events le where le.reception_id=r.id and le.event_type='production') has_production,exists(select 1 from settlements s where s.reception_id=r.id) has_settlement,(select s.status from settlements s where s.reception_id=r.id order by s.created_at desc limit 1) settlement_status,(select max(le.occurred_at) from lot_events le where le.reception_id=r.id) latest_event_at from receptions r join parties p on p.id=r.supplier_id order by r.received_at desc limit 500`,
 sql`select 'vivo' scope,coalesce(r.plant_id,'sin-planta') plant,p.legal_name supplier,coalesce(le.metrics->>'lineName','Sin línea') line,sum(coalesce((le.metrics->>'inputKg')::numeric,0)) input_kg,sum(coalesce((le.metrics->>'outputKg')::numeric,0)) output_kg,count(*) records from lot_events le join receptions r on r.id=le.reception_id join parties p on p.id=r.supplier_id where le.event_type='production' group by r.plant_id,p.legal_name,coalesce(le.metrics->>'lineName','Sin línea') order by input_kg desc`,
 sql`select 'historico' scope,coalesce(plant_id,process_site_original,'Sin planta') plant,coalesce(supplier_name,supplier_original,'Proveedor no identificado') supplier,'Histórico 2025' line,sum(coalesce(received_kg,0)) input_kg,sum(coalesce(received_kg,0)*coalesce((yields->>'total')::numeric,0)) output_kg,count(*) records from historical_production_records where record_status='operational' and received_kg is not null and yields ? 'total' group by coalesce(plant_id,process_site_original,'Sin planta'),coalesce(supplier_name,supplier_original,'Proveedor no identificado') order by input_kg desc`
]);const receptions=(Array.isArray(receptionsRaw)?receptionsRaw:[]) as ReceptionRow[];const visible=receptions.filter(row=>allowed(operator,row.plant_id));const queue=visible.map(row=>{const action=nextAction(row);return {receptionId:row.id,receptionNumber:Number(row.reception_number),plantId:row.plant_id,supplier:row.supplier,species:row.species,lifecycle:lifecycle(row),qualityStatus:row.quality_status,nextAction:action.label,priority:action.priority,receivedAt:row.received_at,lastActivityAt:row.latest_event_at??row.received_at}}).filter(item=>item.priority!=='done').sort((a,b)=>a.priority===b.priority?Date.parse(a.receivedAt)-Date.parse(b.receivedAt):a.priority==='attention'?-1:1);const liveBalance=((Array.isArray(liveBalanceRaw)?liveBalanceRaw:[]) as BalanceRow[]).filter(row=>operator.role==='admin'||row.plant==='sin-planta'||operator.plantIds.includes(row.plant));const historicalBalance=(Array.isArray(historicalBalanceRaw)?historicalBalanceRaw:[]) as BalanceRow[];const balances=[...liveBalance,...historicalBalance].map(row=>{const input=Number(row.input_kg??0),output=Number(row.output_kg??0);return {...row,inputKg:input,outputKg:output,yieldPct:input>0?Number(((output/input)*100).toFixed(1)):null,records:Number(row.records??0)}});const lifecycleCounts={recepcion:0,calidad:0,produccion:0,liquidacion:0,cerrado:0};for(const row of visible)lifecycleCounts[lifecycle(row)]++;return response.status(200).json({ok:true,lifecycle:lifecycleCounts,queue,balances,summary:{openLots:queue.length,attention:queue.filter(item=>item.priority==='attention').length,liveProductionKg:liveBalance.reduce((sum,row)=>sum+Number(row.input_kg??0),0),historicalProductionKg:historicalBalance.reduce((sum,row)=>sum+Number(row.input_kg??0),0)}})}catch(error){const message=error instanceof Error?error.message:'';return response.status(message.includes('DATABASE_URL')?503:500).json({ok:false,error:message.includes('DATABASE_URL')?'Base de datos no conectada':'No fue posible construir el control operacional'})}}
