import {requireOperator} from './_auth.js'
import {getSql} from './_db.js'
import {resolveRequestOrganization} from './_organization.js'
import {seafoodEvent,sortSeafoodEvents,type SeafoodEvent} from './_seafood-event.js'
import {buildOperationalIntelligence,type OperationalSignal} from './_operational-intelligence.js'

type Request={method?:string;headers?:Record<string,string|string[]|undefined>;query?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type Row=Record<string,unknown>
const rows=(value:unknown)=>Array.isArray(value)?value as Row[]:[]
const text=(value:unknown)=>value==null?null:String(value)
const numberOrNull=(value:unknown)=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:null}
const group=(input:Row[],key:string)=>{const map=new Map<string,Row[]>();for(const row of input){const id=String(row[key]??'');if(!id)continue;const current=map.get(id)??[];current.push(row);map.set(id,current)}return map}
async function optionalVisionRows(ids:string[]){const sql=getSql();try{return await sql`select u.reception_id,c.id,c.evidence_file_id,c.capture_source,c.device_label,c.image_sha256,c.source_image_sha256,c.pixel_count,c.l_mean,c.a_mean,c.b_mean,c.l_std,c.a_std,c.b_std,c.chroma,c.hue_deg,c.suggested_grade,c.delta_e,c.operator_grade,c.decision,c.confirmed_by,c.confirmed_at,c.created_by,c.created_at from sea_urchin_color_captures c join sea_urchin_process_runs u on u.id=c.run_id where u.reception_id=any(${ids}::uuid[]) order by c.created_at`}catch(error){const message=error instanceof Error?error.message:'';if(message.includes('sea_urchin_color_captures')||message.includes('sea_urchin_process_runs'))return[];throw error}}

export default async function handler(request:Request,response:Response){
 response.setHeader('Cache-Control','no-store')
 if(request.method!=='GET'){response.setHeader('Allow','GET');return response.status(405).json({ok:false,error:'Método no permitido'})}
 try{
  const operator=await requireOperator(request)
  if(!operator)return response.status(401).json({ok:false,error:'Sesión requerida'})
  const organization=resolveRequestOrganization(request.headers,operator.organizationId)
  if(!organization)return response.status(409).json({ok:false,code:'ORGANIZATION_CONTEXT_UNSUPPORTED',error:'La organización solicitada no está habilitada'})
  const sql=getSql(),admin=operator.role==='admin',commercialRole=['admin','operations','finance'].includes(operator.role)
  const rawPlant=Array.isArray(request.query?.plantId)?request.query?.plantId[0]:request.query?.plantId
  const plantId=typeof rawPlant==='string'&&rawPlant.trim()?rawPlant.trim():null
  if(plantId&&!admin&&!operator.plantIds.includes(plantId))return response.status(403).json({ok:false,error:'Planta fuera de alcance'})
  const receptionRaw=plantId
   ?await sql`select r.id,r.reception_number,r.plant_id,r.species,r.extraction_zone,r.source_reference,r.source,r.guide_kg,r.gross_kg,r.tare_kg,r.drained_kg,r.accepted_kg,r.received_at,r.created_at,r.created_by_operator_id,p.legal_name supplier from receptions r join parties p on p.id=r.supplier_id where r.plant_id=${plantId} order by coalesce(r.received_at,r.created_at) desc limit 30`
   :admin
    ?await sql`select r.id,r.reception_number,r.plant_id,r.species,r.extraction_zone,r.source_reference,r.source,r.guide_kg,r.gross_kg,r.tare_kg,r.drained_kg,r.accepted_kg,r.received_at,r.created_at,r.created_by_operator_id,p.legal_name supplier from receptions r join parties p on p.id=r.supplier_id order by coalesce(r.received_at,r.created_at) desc limit 30`
    :await sql`select r.id,r.reception_number,r.plant_id,r.species,r.extraction_zone,r.source_reference,r.source,r.guide_kg,r.gross_kg,r.tare_kg,r.drained_kg,r.accepted_kg,r.received_at,r.created_at,r.created_by_operator_id,p.legal_name supplier from receptions r join parties p on p.id=r.supplier_id where r.plant_id=any(${operator.plantIds}::text[]) order by coalesce(r.received_at,r.created_at) desc limit 30`
  const receptions=rows(receptionRaw),ids=receptions.map(row=>String(row.id)).filter(Boolean)
  if(!ids.length)return response.status(200).json({ok:true,schemaVersion:'seafood.operational-intelligence.overview.v1',organizationId:organization.organizationId,scope:{plantId,role:operator.role},generatedAt:new Date().toISOString(),lots:0,counts:{p1:0,p2:0,p3:0},topSignals:[],boundary:{writesOperationalState:false,liveOnly:true,historicalIncluded:false}})
  const [evidenceRaw,lotEventsRaw,visionRaw,movementsRaw,ordersRaw,dispatchRaw,salesRaw]=await Promise.all([
   sql`select reception_id,id,kind,label,note,created_by,created_at from reception_evidence where reception_id=any(${ids}::uuid[]) order by created_at`,
   sql`select reception_id,id,event_type,title,detail,metrics,created_by,occurred_at from lot_events where reception_id=any(${ids}::uuid[]) order by occurred_at`,
   optionalVisionRows(ids),
   sql`select m.reception_id,m.id,m.movement_type,m.moved_kg,m.reason,m.occurred_at,m.created_by,fl.name from_location,tl.name to_location from inventory_movements m left join inventory_locations fl on fl.id=m.from_location_id left join inventory_locations tl on tl.id=m.to_location_id where m.reception_id=any(${ids}::uuid[]) order by m.occurred_at`,
   commercialRole?sql`select a.reception_id,a.id allocation_id,a.allocated_kg,a.created_at,a.created_by,o.id order_id,o.order_number,o.product,o.delivery_date,o.status,c.legal_name customer from sales_order_allocations a join sales_orders o on o.id=a.order_id join parties c on c.id=o.customer_id where a.reception_id=any(${ids}::uuid[]) order by a.created_at`:Promise.resolve([]),
   sql`select d.reception_id,d.id,d.dispatch_number,d.destination,d.dispatched_kg,d.document_ref,d.vehicle_ref,d.status,d.dispatched_at,d.created_by,c.legal_name customer from lot_dispatches d left join parties c on c.id=d.customer_id where d.reception_id=any(${ids}::uuid[]) order by d.dispatched_at`,
   commercialRole?sql`select s.reception_id,s.id,s.dispatch_id,s.sold_kg,s.price_per_kg_clp,s.invoice_ref,s.status,s.sold_at,s.created_by,c.legal_name customer from lot_sales s join parties c on c.id=s.customer_id where s.reception_id=any(${ids}::uuid[]) order by s.sold_at`:Promise.resolve([]),
  ])
  const evidence=group(rows(evidenceRaw),'reception_id'),lotEvents=group(rows(lotEventsRaw),'reception_id'),vision=group(rows(visionRaw),'reception_id'),movements=group(rows(movementsRaw),'reception_id'),orders=group(rows(ordersRaw),'reception_id'),dispatches=group(rows(dispatchRaw),'reception_id'),sales=group(rows(salesRaw),'reception_id')
  const lotResults=receptions.map(reception=>{
   const id=String(reception.id),siteId=text(reception.plant_id),events:SeafoodEvent[]=[]
   events.push(seafoodEvent({id:`reception:${id}`,siteId,lotId:id,type:'reception',occurredAt:text(reception.received_at)??text(reception.created_at),title:`Recepción ${text(reception.reception_number)??id.slice(0,8)}`,detail:text(reception.species),actor:text(reception.created_by_operator_id),metrics:{species:text(reception.species),supplier:text(reception.supplier),extractionZone:text(reception.extraction_zone),sourceReference:text(reception.source_reference),source:text(reception.source),guideKg:numberOrNull(reception.guide_kg),grossKg:numberOrNull(reception.gross_kg),tareKg:numberOrNull(reception.tare_kg),drainedKg:numberOrNull(reception.drained_kg),acceptedKg:numberOrNull(reception.accepted_kg)},source:{entityType:'reception',entityId:id}},organization))
   for(const row of evidence.get(id)??[]){const eventId=String(row.id);events.push(seafoodEvent({id:`evidence:${eventId}`,siteId,lotId:id,type:'evidence',occurredAt:text(row.created_at),title:`Evidencia · ${text(row.label)??text(row.kind)??'Documento'}`,detail:text(row.note),actor:text(row.created_by),metrics:{kind:text(row.kind),label:text(row.label)},source:{entityType:'reception_evidence',entityId:eventId}},organization))}
   for(const row of lotEvents.get(id)??[]){const eventId=String(row.id),rawType=String(row.event_type??'note'),type=rawType==='quality'||rawType==='production'?rawType:'note';events.push(seafoodEvent({id:`lot_event:${eventId}`,siteId,lotId:id,type,occurredAt:text(row.occurred_at),title:text(row.title)??'Evento operacional',detail:text(row.detail),actor:text(row.created_by),metrics:row.metrics&&typeof row.metrics==='object'&&!Array.isArray(row.metrics)?row.metrics as Record<string,unknown>:{},source:{entityType:'lot_event',entityId:eventId}},organization))}
   for(const row of vision.get(id)??[]){const eventId=String(row.id);events.push(seafoodEvent({id:`vision:${eventId}`,siteId,lotId:id,type:'vision',occurredAt:text(row.created_at),title:'Vision · Uni Vision color',detail:text(row.decision),actor:text(row.created_by),metrics:{suggestedGrade:text(row.suggested_grade),operatorGrade:text(row.operator_grade),decision:text(row.decision),confirmedBy:text(row.confirmed_by),confirmedAt:text(row.confirmed_at),deltaE:numberOrNull(row.delta_e)},source:{entityType:'sea_urchin_color_capture',entityId:eventId}},organization))}
   for(const row of movements.get(id)??[]){const eventId=String(row.id),movementType=text(row.movement_type)??'movimiento';events.push(seafoodEvent({id:`inventory:${eventId}`,siteId,lotId:id,type:'inventory',occurredAt:text(row.occurred_at),title:`Inventario · ${movementType}`,detail:text(row.reason),actor:text(row.created_by),metrics:{movementType,movedKg:numberOrNull(row.moved_kg),fromLocation:text(row.from_location),toLocation:text(row.to_location)},source:{entityType:'inventory_movement',entityId:eventId}},organization))}
   for(const row of orders.get(id)??[]){const eventId=String(row.allocation_id);events.push(seafoodEvent({id:`commercial_commitment:${eventId}`,siteId,lotId:id,type:'commercial_commitment',occurredAt:text(row.created_at),title:`Compromiso · ${text(row.order_number)??eventId.slice(0,8)}`,detail:text(row.product),actor:text(row.created_by),metrics:{customer:text(row.customer),allocatedKg:numberOrNull(row.allocated_kg),status:text(row.status)},source:{entityType:'sales_order_allocation',entityId:eventId}},organization))}
   for(const row of dispatches.get(id)??[]){const eventId=String(row.id);events.push(seafoodEvent({id:`dispatch:${eventId}`,siteId,lotId:id,type:'dispatch',occurredAt:text(row.dispatched_at),title:`Despacho · ${text(row.dispatch_number)??eventId.slice(0,8)}`,detail:text(row.destination),actor:text(row.created_by),metrics:{customer:text(row.customer),dispatchedKg:numberOrNull(row.dispatched_kg),status:text(row.status)},source:{entityType:'lot_dispatch',entityId:eventId}},organization))}
   for(const row of sales.get(id)??[]){const eventId=String(row.id);events.push(seafoodEvent({id:`sale:${eventId}`,siteId,lotId:id,type:'sale',occurredAt:text(row.sold_at),title:`Venta · ${text(row.invoice_ref)??text(row.customer)??eventId.slice(0,8)}`,detail:text(row.customer),actor:text(row.created_by),metrics:{customer:text(row.customer),soldKg:numberOrNull(row.sold_kg),status:text(row.status)},source:{entityType:'lot_sale',entityId:eventId}},organization))}
   const ordered=sortSeafoodEvents(events),intelligence=buildOperationalIntelligence(ordered)
   return {receptionId:id,receptionNumber:text(reception.reception_number),plantId:siteId,species:text(reception.species),supplier:text(reception.supplier),latestAt:ordered.at(-1)?.occurredAt??null,intelligence}
  })
  const counts=lotResults.reduce((acc,lot)=>({p1:acc.p1+lot.intelligence.counts.p1,p2:acc.p2+lot.intelligence.counts.p2,p3:acc.p3+lot.intelligence.counts.p3}),{p1:0,p2:0,p3:0})
  const topSignals=lotResults.flatMap(lot=>lot.intelligence.signals.map((signal:OperationalSignal)=>({receptionId:lot.receptionId,receptionNumber:lot.receptionNumber,plantId:lot.plantId,species:lot.species,supplier:lot.supplier,latestAt:lot.latestAt,path:`/trazabilidad?mode=live&receptionId=${encodeURIComponent(lot.receptionId)}`,signal}))).sort((a,b)=>a.signal.priority-b.signal.priority||String(b.latestAt??'').localeCompare(String(a.latestAt??''))||a.signal.title.localeCompare(b.signal.title)).slice(0,8)
  return response.status(200).json({ok:true,schemaVersion:'seafood.operational-intelligence.overview.v1',organizationId:organization.organizationId,scope:{plantId,role:operator.role},generatedAt:new Date().toISOString(),lots:lotResults.length,counts,topSignals,boundary:{writesOperationalState:false,liveOnly:true,historicalIncluded:false,rule:'Resumen batch de señales determinísticas generadas por buildOperationalIntelligence sobre Seafood Event Graph live accesible.'}})
 }catch(error){console.error('operational_intelligence_overview_failed',error instanceof Error?error.message:'unknown');return response.status(500).json({ok:false,error:'No fue posible construir prioridades operacionales'})}
}
