import {requireOperator,type SessionOperator} from './_auth.js'
import {getSql} from './_db.js'
type Request={method?:string;body?:unknown;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type Input={partyId?:unknown;kind?:unknown;legalName?:unknown;taxId?:unknown;phone?:unknown;contactName?:unknown;email?:unknown;address?:unknown;city?:unknown;country?:unknown;paymentTerms?:unknown;notes?:unknown;tags?:unknown}
const txt=(v:unknown,max=500)=>String(v??'').trim().slice(0,max)
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const canWrite=(o:SessionOperator)=>o.role==='admin'||o.role==='finance'||o.role==='operations'
export default async function handler(req:Request,res:Response){res.setHeader('Cache-Control','no-store');try{const operator=await requireOperator(req);if(!operator)return res.status(401).json({ok:false,error:'Sesión requerida'});if(req.method==='GET')return list(res,operator);if(req.method==='POST')return save(req,res,operator);res.setHeader('Allow','GET, POST');return res.status(405).json({ok:false,error:'Método no permitido'})}catch(error){const m=error instanceof Error?error.message:'';return res.status(m.includes('business_partner_profiles')?503:500).json({ok:false,error:m.includes('business_partner_profiles')?'Falta aplicar la migración de proveedores y clientes':'No fue posible cargar proveedores y clientes'})}}
async function list(res:Response,operator:SessionOperator){const sql=getSql();const [parties,suppliers,customers,purchases,invoices]=await Promise.all([sql`select p.id,p.kind,p.legal_name,p.tax_id,p.phone,p.active,pr.contact_name,pr.email,pr.address,pr.city,pr.country,pr.payment_terms,pr.notes,pr.tags from parties p left join business_partner_profiles pr on pr.party_id=p.id where p.kind in ('supplier'::party_kind,'customer'::party_kind) order by p.kind,p.legal_name`,sql`select * from supplier_profitability order by contribution_clp desc nulls last`,sql`select * from customer_profitability order by revenue_clp desc nulls last`,sql`select po.id,po.order_number,po.issue_date,po.currency,po.net_amount,po.tax_amount,po.total_amount,po.status,p.legal_name supplier,po.plant_id,po.notes from purchase_orders po join parties p on p.id=po.supplier_id order by po.issue_date desc limit 100`,sql`select i.id,i.invoice_number,i.issue_date,i.currency,i.goods_amount,i.freight_amount,i.total_amount,i.destination,i.incoterm,p.legal_name customer,i.net_weight_kg,i.gross_weight_kg from export_invoices i left join parties p on p.id=i.customer_id order by i.issue_date desc limit 100`]);return res.status(200).json({ok:true,parties,suppliers,customers,purchases,invoices,permissions:{canWrite:canWrite(operator)}})}
async function save(req:Request,res:Response,operator:SessionOperator){if(!canWrite(operator))return res.status(403).json({ok:false,error:'Acción no autorizada'});const input=(req.body??{}) as Input,kind=txt(input.kind,20),legalName=txt(input.legalName,180),partyId=txt(input.partyId,40),tags=Array.isArray(input.tags)?input.tags.map(x=>txt(x,60)).filter(Boolean).slice(0,20):[];if(!['supplier','customer'].includes(kind)||legalName.length<2||partyId&&!uuid.test(partyId))return res.status(400).json({ok:false,error:'Proveedor/cliente inválido'});const sql=getSql();const collisions=partyId?await sql`select id,legal_name from parties where kind=${kind}::party_kind and lower(trim(legal_name))=lower(trim(${legalName})) and id<>${partyId}::uuid limit 2`:await sql`select id,legal_name from parties where kind=${kind}::party_kind and lower(trim(legal_name))=lower(trim(${legalName})) limit 2`;if((collisions as unknown[]).length)return res.status(409).json({ok:false,error:'Ya existe una ficha maestra con el mismo nombre normalizado. Revisa la entidad existente antes de crear o renombrar.'});const rows=partyId?await sql`update parties set legal_name=${legalName},tax_id=${txt(input.taxId,40)||null},phone=${txt(input.phone,80)||null},active=true,updated_at=now() where id=${partyId}::uuid returning id`:await sql`insert into parties(kind,legal_name,tax_id,phone) values(${kind}::party_kind,${legalName},${txt(input.taxId,40)||null},${txt(input.phone,80)||null}) on conflict(kind,legal_name) do update set tax_id=excluded.tax_id,phone=excluded.phone,active=true,updated_at=now() returning id`;const id=String((rows as Array<{id:string}>)[0]?.id??'');if(!id)return res.status(404).json({ok:false,error:'Entidad no encontrada'});await sql`insert into business_partner_profiles(party_id,contact_name,email,address,city,country,payment_terms,notes,tags,updated_at,updated_by_operator_id) values(${id}::uuid,${txt(input.contactName,160)||null},${txt(input.email,254)||null},${txt(input.address,240)||null},${txt(input.city,120)||null},${txt(input.country,100)||null},${txt(input.paymentTerms,160)||null},${txt(input.notes,1200)||null},${JSON.stringify(tags)}::jsonb,now(),${operator.id}::uuid) on conflict(party_id) do update set contact_name=excluded.contact_name,email=excluded.email,address=excluded.address,city=excluded.city,country=excluded.country,payment_terms=excluded.payment_terms,notes=excluded.notes,tags=excluded.tags,updated_at=now(),updated_by_operator_id=excluded.updated_by_operator_id`;return res.status(200).json({ok:true,partyId:id})}
