import {requireOperator,type SessionOperator} from './_auth.js'
import {hasPlantAccess} from './_plants.js'
import {getSql} from './_db.js'

type Request={method?:string;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type PlanLot={id:string;reception_number:string|number;plant_id:string|null;species:string;received_at:string;supplier:string;raw_kg:string|number|null;produced_kg:string|number|null;dispatched_kg:string|number;reserved_kg:string|number;urchin_run_id:string|null;urchin_status:string|null;urchin_grade:string|null;urchin_finger_class:string|null;urchin_color_status:string|null;urchin_xray_status:string|null;urchin_packing_format:string|null;urchin_pending_stages:string|number;urchin_packing_ok:string|number;urchin_label_count:string|number;urchin_blocked_labels:string|number;urchin_missing_evidence:string|number;confirmedAvailableKg:number;potentialAvailableKg:number;isProduced:boolean;planningBlocked:boolean;planningBlockReasons:string[]}
function visible(o:SessionOperator,plantId:unknown){return o.role==='admin'||typeof plantId!=='string'||!plantId||hasPlantAccess(o,plantId)}
function isUrchin(species:unknown){return String(species??'').toLowerCase().includes('eriz')}
function urchinBlockReasons(r:Omit<PlanLot,'confirmedAvailableKg'|'potentialAvailableKg'|'isProduced'|'planningBlocked'|'planningBlockReasons'>){if(!isUrchin(r.species))return [];const reasons:string[]=[];if(!r.urchin_run_id)reasons.push('Proceso de erizo no iniciado');if(r.urchin_status==='hold')reasons.push('Proceso bloqueado');if(Number(r.urchin_pending_stages??0)>0)reasons.push(`${Number(r.urchin_pending_stages)} etapas pendientes o con desviación`);if(Number(r.urchin_packing_ok??0)===0)reasons.push('Packing no liberado');if(!r.urchin_finger_class)reasons.push('Dedo sin clasificar');if(!r.urchin_grade)reasons.push('Grade sin definir');if(r.urchin_color_status!=='accepted')reasons.push('Color no aceptado');if(r.urchin_xray_status!=='passed')reasons.push('Rayos X no aprobado');if(Number(r.urchin_label_count??0)===0)reasons.push('Sin etiquetas validadas');if(Number(r.urchin_blocked_labels??0)>0)reasons.push('Etiqueta pendiente, bloqueada o no coincide');if(Number(r.urchin_missing_evidence??0)>0)reasons.push('Etiqueta sin documento/evidencia');return reasons}
export default async function handler(req:Request,res:Response){res.setHeader('Cache-Control','no-store');if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({ok:false,error:'Método no permitido'})}try{const operator=await requireOperator(req);if(!operator)return res.status(401).json({ok:false,error:'Sesión requerida'});const sql=getSql();const [ordersRaw,lotsRaw,yieldRaw]=await Promise.all([
 sql`select o.id,o.order_number,o.plant_id,o.species,o.product,o.committed_kg,o.price_per_kg_clp,o.delivery_date,o.status,c.legal_name customer,coalesce((select sum(a.allocated_kg) from sales_order_allocations a where a.order_id=o.id),0) allocated_kg from sales_orders o join parties c on c.id=o.customer_id where o.status in ('pending','prepared') order by o.delivery_date,o.order_number`,
 sql`select r.id,r.reception_number,r.plant_id,r.species,r.received_at,p.legal_name supplier,coalesce(r.accepted_kg,greatest(0,r.gross_kg-r.tare_kg)) raw_kg,coalesce(u.output_kg,(select (le.metrics->>'outputKg')::numeric from lot_events le where le.reception_id=r.id and le.event_type='production' and le.metrics ? 'outputKg' order by le.occurred_at desc limit 1)) produced_kg,coalesce((select sum(d.dispatched_kg) from lot_dispatches d where d.reception_id=r.id and d.status='confirmed'),0) dispatched_kg,coalesce((select sum(a.allocated_kg) from sales_order_allocations a join sales_orders o on o.id=a.order_id where a.reception_id=r.id and o.status in ('pending','prepared')),0) reserved_kg,u.id urchin_run_id,u.status urchin_status,u.grade urchin_grade,u.finger_class urchin_finger_class,u.color_status urchin_color_status,u.xray_status urchin_xray_status,u.packing_format urchin_packing_format,coalesce((select count(*) from sea_urchin_stage_checks s where s.run_id=u.id and s.status not in ('ok','not_applicable')),0) urchin_pending_stages,coalesce((select count(*) from sea_urchin_stage_checks s where s.run_id=u.id and s.stage='packing' and s.status='ok'),0) urchin_packing_ok,coalesce((select count(*) from sea_urchin_labels l where l.run_id=u.id),0) urchin_label_count,coalesce((select count(*) from sea_urchin_labels l where l.run_id=u.id and l.status<>'validated'),0) urchin_blocked_labels,coalesce((select count(*) from sea_urchin_labels l where l.run_id=u.id and l.status='validated' and l.source_message_id is null and nullif(trim(l.source_document_url),'') is null),0) urchin_missing_evidence from receptions r join parties p on p.id=r.supplier_id left join sea_urchin_process_runs u on u.reception_id=r.id order by r.received_at`,
 sql`select coalesce(sum(received_kg*(yields->>'total')::numeric)/nullif(sum(received_kg),0),0.4841) yield_ratio,count(*) rows from historical_production_records where record_status='operational' and received_kg>0 and yields ? 'total' and (yields->>'total')::numeric between 0.2 and 1.05`
 ]);const y=Array.isArray(yieldRaw)&&yieldRaw[0]?Number((yieldRaw[0] as {yield_ratio?:unknown}).yield_ratio??0.4841):0.4841;const orders=(Array.isArray(ordersRaw)?ordersRaw:[]).filter(r=>visible(operator,(r as {plant_id?:unknown}).plant_id));const lots:PlanLot[]=(Array.isArray(lotsRaw)?lotsRaw:[]).filter(r=>visible(operator,(r as {plant_id?:unknown}).plant_id)).map(row=>{const r=row as Omit<PlanLot,'confirmedAvailableKg'|'potentialAvailableKg'|'isProduced'|'planningBlocked'|'planningBlockReasons'>,raw=Number(r.raw_kg??0),produced=r.produced_kg==null?null:Number(r.produced_kg),dispatched=Number(r.dispatched_kg??0),reserved=Number(r.reserved_kg??0),reasons=urchinBlockReasons(r),blocked=reasons.length>0,confirmed=produced==null||blocked?0:Math.max(0,produced-dispatched-reserved),potential=produced==null&&!blocked?Math.max(0,raw*y-dispatched-reserved):confirmed;return {...r,confirmedAvailableKg:confirmed,potentialAvailableKg:potential,isProduced:produced!=null,planningBlocked:blocked,planningBlockReasons:reasons}});const recommendations=orders.map(order=>{const o=order as Record<string,unknown>,remaining=Math.max(0,Number(o.committed_kg??0)-Number(o.allocated_kg??0)),plant=o.plant_id as string|null,species=String(o.species??'').toLowerCase();const candidates=lots.filter(l=>!l.planningBlocked&&(!plant||l.plant_id===plant)&&l.species.toLowerCase()===species&&(l.confirmedAvailableKg>0||l.potentialAvailableKg>0)).map(l=>({...l,score:(l.isProduced?100:50)+Math.min(30,(l.confirmedAvailableKg||l.potentialAvailableKg)/Math.max(remaining,1)*20)})).sort((a,b)=>b.score-a.score||a.received_at.localeCompare(b.received_at));return {orderId:o.id,orderNumber:o.order_number,customer:o.customer,product:o.product,species:o.species,deliveryDate:o.delivery_date,remainingKg:remaining,candidates:candidates.slice(0,5)}});const blockedLots=lots.filter(l=>l.planningBlocked).map(l=>({id:l.id,receptionNumber:l.reception_number,plantId:l.plant_id,species:l.species,supplier:l.supplier,producedKg:l.produced_kg==null?null:Number(l.produced_kg),reasons:l.planningBlockReasons}));return res.status(200).json({ok:true,historicalYieldPct:Number((y*100).toFixed(2)),historicalRows:Array.isArray(yieldRaw)&&yieldRaw[0]?Number((yieldRaw[0] as {rows?:unknown}).rows??0):0,recommendations,blockedLots})}catch{return res.status(500).json({ok:false,error:'No fue posible construir el plan'})}}
