import { requireOperator } from "./_auth.js";
import { allowedPlantIds, filterPlants, normalizePlantIds } from "./_plants.js";
import { getSql } from "./_db.js";

type Request={method?:string;body?:unknown;headers?:Record<string,string|string[]|undefined>};
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void};
type PlantRecord={id:string}&Record<string,unknown>;
type ImportBatch={id:string;fileName:string;periods:string[];plantIds:string[];rowCount:number;publishedAt:string;previousPlants:unknown[];resultingPlants:unknown[]};
const isBatch=(value:unknown):value is ImportBatch=>{if(!value||typeof value!=="object")return false;const b=value as Partial<ImportBatch>;return typeof b.id==="string"&&b.id.length<=80&&typeof b.fileName==="string"&&b.fileName.length<=255&&Array.isArray(b.periods)&&Array.isArray(b.plantIds)&&Number.isInteger(b.rowCount)&&Number(b.rowCount)>0&&typeof b.publishedAt==="string"&&!Number.isNaN(Date.parse(b.publishedAt))&&Array.isArray(b.previousPlants)&&Array.isArray(b.resultingPlants)};
function plantRecords(value:unknown):PlantRecord[]{if(!Array.isArray(value))return[];return value.filter((item):item is PlantRecord=>Boolean(item)&&typeof item==="object"&&typeof(item as {id?:unknown}).id==="string")}
function mergePlantUpdates(current:PlantRecord[],incoming:PlantRecord[],plantIds:string[]){const updates=new Map(incoming.map(plant=>[plant.id,plant]));if(plantIds.some(id=>!updates.has(id)))return null;const target=new Set(plantIds),merged=current.map(plant=>target.has(plant.id)?updates.get(plant.id)??plant:plant),existing=new Set(current.map(plant=>plant.id));for(const id of plantIds)if(!existing.has(id))merged.push(updates.get(id)!);return merged}
export default async function handler(request:Request,response:Response){response.setHeader("Cache-Control","no-store");try{const operator=await requireOperator(request);if(!operator)return response.status(401).json({ok:false,error:"Sesión requerida"});const sql=getSql();if(request.method==="GET"){const[state,history]=await Promise.all([sql`select plants,updated_at from plant_current_state where state_key='current'`,sql`select id,file_name,periods,plant_ids,row_count,published_at,published_by,previous_plants,resulting_plants,reverted_at from plant_import_batches order by published_at desc limit 20`]);const stateRows=state as Array<Record<string,unknown>>,historyRows=history as Array<Record<string,unknown>>,currentPlants=plantRecords(stateRows[0]?.plants),admin=operator.role==="admin",allowed=new Set(allowedPlantIds(operator));const visibleHistory=historyRows.map(row=>{const plantIds=normalizePlantIds(row.plant_ids).filter(id=>admin||allowed.has(id));if(!plantIds.length)return null;return{id:row.id,fileName:row.file_name,periods:row.periods,plantIds,rowCount:row.row_count,publishedAt:row.published_at,publishedBy:row.published_by,previousPlants:filterPlants(plantRecords(row.previous_plants),operator),resultingPlants:filterPlants(plantRecords(row.resulting_plants),operator),revertedAt:row.reverted_at??undefined}}).filter(Boolean).slice(0,10);return response.status(200).json({ok:true,plants:filterPlants(currentPlants,operator),updatedAt:stateRows[0]?.updated_at??null,history:visibleHistory})}
if(!["admin","operations"].includes(operator.role))return response.status(403).json({ok:false,error:"Tu rol no puede publicar plantas"});if(request.method==="POST"){const batch=(request.body as {batch?:unknown}|undefined)?.batch;if(!isBatch(batch))return response.status(400).json({ok:false,error:"Lote de importación inválido"});const raw=batch.plantIds.map(v=>String(v).trim()).filter(Boolean),plantIds=normalizePlantIds(raw);if(!plantIds.length||plantIds.length!==raw.length)return response.status(400).json({ok:false,error:"El lote contiene plantas inválidas"});const allowed=new Set(allowedPlantIds(operator));if(operator.role!=="admin"&&plantIds.some(id=>!allowed.has(id)))return response.status(403).json({ok:false,error:"El lote incluye una planta fuera de tu alcance"});const currentRows=await sql`select plants from plant_current_state where state_key='current'`,current=plantRecords((currentRows as Array<Record<string,unknown>>)[0]?.plants),resulting=mergePlantUpdates(current,plantRecords(batch.resultingPlants),plantIds);if(!resulting)return response.status(400).json({ok:false,error:"Faltan plantas declaradas dentro del resultado importado"});await sql.transaction([sql`insert into plant_import_batches(id,file_name,periods,plant_ids,row_count,published_at,published_by,previous_plants,resulting_plants) values(${batch.id},${batch.fileName},${batch.periods},${plantIds},${batch.rowCount},${batch.publishedAt},${operator.fullName},${JSON.stringify(current)},${JSON.stringify(resulting)})`,sql`insert into plant_current_state(state_key,plants,latest_batch_id,updated_at) values('current',${JSON.stringify(resulting)},${batch.id},now()) on conflict(state_key) do update set plants=excluded.plants,latest_batch_id=excluded.latest_batch_id,updated_at=now()`]);return response.status(201).json({ok:true,batchId:batch.id})}
if(request.method==="PATCH"){if(operator.role!=="admin")return response.status(403).json({ok:false,error:"Solo Administración puede revertir una publicación global"});const batchId=(request.body as {batchId?:unknown}|undefined)?.batchId;if(typeof batchId!=="string"||!batchId)return response.status(400).json({ok:false,error:"Lote inválido"});const result=await sql`with reverted as (update plant_import_batches set reverted_at=now() where id=${batchId} and reverted_at is null returning previous_plants) insert into plant_current_state(state_key,plants,latest_batch_id,updated_at) select 'current',previous_plants,null,now() from reverted on conflict(state_key) do update set plants=excluded.plants,latest_batch_id=null,updated_at=now() returning plants`;const rows=result as Array<Record<string,unknown>>;if(!rows.length)return response.status(409).json({ok:false,error:"La publicación ya no se puede revertir"});return response.status(200).json({ok:true,plants:filterPlants(plantRecords(rows[0].plants),operator)})}response.setHeader("Allow","GET, POST, PATCH");return response.status(405).json({ok:false,error:"Método no permitido"})}catch(error){const message=error instanceof Error?error.message:"",configuration=message.includes("DATABASE_URL"),migration=message.includes("operator_sessions");return response.status(configuration||migration?503:500).json({ok:false,error:configuration?"Base de datos no conectada":migration?"Falta aplicar la migración 003_operator_auth.sql":"No fue posible persistir el estado de plantas"})}}
