import {requireOperator} from './_auth.js'
import {normalizePlantIds} from './_plants.js'
import {getSql} from './_db.js'

type Request={method?:string;body?:unknown;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type PlantRecord={id:string}&Record<string,unknown>
type PlantInput={id?:unknown;name?:unknown;location?:unknown;mode?:unknown;products?:unknown;photoUrl?:unknown;description?:unknown;active?:unknown}
type Body={plant?:unknown;bootstrapPlants?:unknown}
const modes=new Set(['Propia','Maquila','Maquila y producto terminado','Producto terminado'])
const clean=(value:unknown,max:number)=>String(value??'').trim().replace(/\s+/g,' ').slice(0,max)
function records(value:unknown):PlantRecord[]{return Array.isArray(value)?value.filter((item):item is PlantRecord=>Boolean(item)&&typeof item==='object'&&typeof (item as {id?:unknown}).id==='string'):[]}
function normalizePhoto(value:unknown){const text=String(value??'').trim();if(!text)return null;if(/^https:\/\//i.test(text)&&text.length<=2048)return text;if(/^data:image\/(?:jpeg|png|webp);base64,[a-z0-9+/=]+$/i.test(text)&&text.length<=950000)return text;return undefined}
function normalizePlant(value:unknown){const input=(value??{}) as PlantInput;const rawId=clean(input.id,50).toLowerCase(),ids=normalizePlantIds([rawId]),name=clean(input.name,120),location=clean(input.location,180),mode=clean(input.mode,60),description=clean(input.description,600)||null,photoUrl=normalizePhoto(input.photoUrl),products=Array.isArray(input.products)?Array.from(new Set(input.products.map(item=>clean(item,120)).filter(Boolean))).slice(0,30):[];if(ids.length!==1||!name||!location||!modes.has(mode)||!products.length||photoUrl===undefined)return null;return{id:ids[0],name,location,mode,products,photoUrl,description,active:input.active!==false}}
export default async function handler(req:Request,res:Response){res.setHeader('Cache-Control','no-store');try{const operator=await requireOperator(req,['admin']);if(!operator)return res.status(403).json({ok:false,error:'Administración requerida'});if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({ok:false,error:'Método no permitido'})}const body=(req.body??{}) as Body,plant=normalizePlant(body.plant);if(!plant)return res.status(400).json({ok:false,error:'Datos de planta inválidos'});const sql=getSql(),rows=await sql`select plants from plant_current_state where state_key='current'`,stored=records(Array.isArray(rows)?(rows[0] as {plants?:unknown}|undefined)?.plants:undefined);let current=stored;if(!current.length){const bootstrap=records(body.bootstrapPlants).map(item=>normalizePlant(item)).filter((item):item is NonNullable<ReturnType<typeof normalizePlant>>=>Boolean(item));if(!bootstrap.length)return res.status(409).json({ok:false,error:'No existe estado de plantas y falta catálogo inicial'});current=bootstrap as PlantRecord[]}const existing=current.find(item=>item.id===plant.id);const next=current.map(item=>item.id===plant.id?{...item,...plant}:item);if(!existing)next.push({...plant,sourceStatus:'unlinked'});await sql`insert into plant_current_state(state_key,plants,latest_batch_id,updated_at) values('current',${JSON.stringify(next)},null,now()) on conflict(state_key) do update set plants=excluded.plants,updated_at=now()`;return res.status(existing?200:201).json({ok:true,plant:next.find(item=>item.id===plant.id),plants:next})}catch(error){const message=error instanceof Error?error.message:'';return res.status(message.includes('operator_sessions')?503:500).json({ok:false,error:message.includes('operator_sessions')?'Faltan migraciones de autenticación':'No fue posible guardar la planta'})}}
