import {requireOperator} from './_auth.js'
import {getSql} from './_db.js'

declare const process:{env:Record<string,string|undefined>}
declare const fetch:(input:string,init?:Record<string,unknown>)=>Promise<{ok:boolean;status:number;json:()=>Promise<unknown>}>

type Request={method?:string;headers?:Record<string,string|string[]|undefined>;body?:unknown}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type Review={decision:'accepted'|'rejected';rejection_reason:string|null;note:string|null;reviewed_by:string;reviewed_at:string}|null
type VisionTest={status:string;analyzed_at:string;engine:string;provider?:string;model?:string;mask_mode?:string;usable_ratio?:number;l_mean?:number;a_mean?:number;b_mean?:number;dispersion?:number;border_candidate_ratio?:number;confidence:string;recommendation:string;observed?:Record<string,unknown>;summary?:string;operational_evidence:boolean;automatic_training:boolean;human_decision_required:boolean}|null
type ReferenceRow={id:string;title:string;source_page:string;image_url:string|null;source_type:string;license:string;attribution:string|null;scene:string;intended_use:string;quality_status:string;official_grade:null;notes:string;provenance:Record<string,unknown>|null;created_at:string;updated_at:string;latest_review:Review}

const rejectionReasons=new Set(['color_fuera_objetivo','color_poco_uniforme','dano_visual','apariencia_no_conforme','material_extrano_visible','presentacion_no_conforme','otro'])
const analysisPrompt=`Analiza exclusivamente lo visible en esta imagen de uni/roe de erizo para preparar una revisión humana de Calidad. No decidas si el producto es bueno o malo, no asignes Grade, origen, especie, inocuidad ni cumplimiento. Devuelve SOLO JSON válido con exactamente estas claves: visibleProduct, colorFamily, colorUniformity, structure, surfaceMoisture, presentation, foreignMaterialVisible, contextRisk, summary, confidence. Todos salvo confidence son string. confidence es número 0..1. Usa "no_determinado" cuando no sea inequívoco. colorUniformity debe ser uniforme, variable o no_determinado. structure debe describir sólo integridad visual. contextRisk debe indicar si sushi, concha, agua, guarnición, reflejos u otros elementos pueden contaminar la lectura. foreignMaterialVisible sólo describe material extraño claramente visible; no infieras contaminación.`

function visionTest(row:ReferenceRow):VisionTest{const value=row.provenance?.vision_test;return value&&typeof value==='object'?value as VisionTest:null}
function reviewPriority(row:ReferenceRow){let score=0;const reasons:string[]=[];const analysis=visionTest(row);if(row.latest_review)score-=200;if(analysis?.status==='pending_quality_review'){score+=80;reasons.push('análisis Vision listo para decisión de Calidad')}if(row.intended_use==='defect_variability'){score+=50;reasons.push('posible defecto/variabilidad difícil')}if(row.intended_use==='segmentation_qa'){score+=35;reasons.push('útil para validar segmentación')}if(row.scene==='mixed_product'){score+=20;reasons.push('contexto visual ambiguo')}if(row.scene==='saltwater'){score+=20;reasons.push('agua/reflejos alteran apariencia')}if(row.scene==='shell'){score+=15;reasons.push('producto dentro de concha')}if(row.source_type==='commercial_reference'){score+=10;reasons.push('referencia comercial externa')}if(row.source_type==='research_reference'){score+=5;reasons.push('referencia externa no operacional')}if(!row.image_url){score-=100;reasons.push('sin imagen directa')}if(row.latest_review)reasons.unshift('ya revisada por Calidad');return{reviewPriority:score,reviewReason:reasons.join(' · ')||'variabilidad visual general',visionTest:analysis}}
function parseBody(body:unknown){if(typeof body==='string'){try{return JSON.parse(body) as Record<string,unknown>}catch{return {}}}return body&&typeof body==='object'?body as Record<string,unknown>:{} }
function chatOutput(payload:unknown){const data=payload as {choices?:Array<{message?:{content?:string}}>};return data.choices?.[0]?.message?.content??''}
function parseVisualAnalysis(text:string){const normalized=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const raw=JSON.parse(normalized) as Record<string,unknown>;const clean=(key:string,max=500)=>typeof raw[key]==='string'?String(raw[key]).trim().replace(/\s+/g,' ').slice(0,max):'no_determinado';const confidence=typeof raw.confidence==='number'&&Number.isFinite(raw.confidence)?Math.max(0,Math.min(1,raw.confidence)):0;return{visibleProduct:clean('visibleProduct'),colorFamily:clean('colorFamily'),colorUniformity:clean('colorUniformity'),structure:clean('structure'),surfaceMoisture:clean('surfaceMoisture'),presentation:clean('presentation'),foreignMaterialVisible:clean('foreignMaterialVisible'),contextRisk:clean('contextRisk',800),summary:clean('summary',1000),confidence}}
function textValue(value:unknown){return typeof value==='string'?value.trim().toLowerCase():''}
function countLabels(values:string[]){const counts=new Map<string,number>();for(const value of values){if(!value)continue;counts.set(value,(counts.get(value)??0)+1)}return[...counts.entries()].map(([label,count])=>({label,count})).sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label)).slice(0,6)}
function deriveVisionIntel(references:Array<ReferenceRow&{visionTest:VisionTest}>){
 const analyzed=references.filter(item=>item.visionTest)
 if(!analyzed.length)return null
 let uniform=0,variable=0,undetermined=0,wetVisible=0,numericConfidenceCount=0,confidenceTotal=0,contextComplex=0
 const colors:string[]=[],contexts:string[]=[]
 for(const item of analyzed){
  const test=item.visionTest
  const observed=test?.observed??{}
  const uniformity=textValue(observed.colorUniformity)
  if(uniformity==='uniforme')uniform++;else if(uniformity==='variable')variable++;else undetermined++
  const moisture=textValue(observed.surfaceMoisture)
  if(moisture.includes('mojad')||moisture.includes('húmed')||moisture.includes('humed'))wetVisible++
  const color=textValue(observed.colorFamily)
  if(color)colors.push(color)
  const context=textValue(observed.contextRisk)
  if(context){contexts.push(context);if(context!=='no_determinado'&&context!=='ninguno'&&context!=='no')contextComplex++}
  const confidence=Number(test?.confidence)
  if(typeof test?.confidence!=='undefined'&&String(test.confidence).trim()!==''&&Number.isFinite(confidence)){numericConfidenceCount++;confidenceTotal+=Math.max(0,Math.min(1,confidence))}
 }
 return{analyzed:analyzed.length,numericConfidenceCount,averageNumericConfidence:numericConfidenceCount?confidenceTotal/numericConfidenceCount:null,uniformity:{uniform,variable,undetermined},wetVisible,contextComplex,colorFamilies:countLabels(colors),contexts:countLabels(contexts),basis:'persisted_external_vision_observations',interpretation:'Resumen derivado únicamente de observaciones Vision persistidas sobre referencias externas. Describe variabilidad visual y contexto de revisión; no es aceptación de Calidad, Grade, accuracy ni evidencia operacional.',operationalEvidence:false,qualityDecision:false,automaticTraining:false}
}
async function analyzePendingReferences(sql:ReturnType<typeof getSql>,limit:number){const apiKey=process.env.OPENAI_API_KEY;const model=process.env.OPENAI_VISION_MODEL||'gpt-4o-mini';if(!apiKey)return{configured:false,model,processed:0,succeeded:0,failed:0,remaining:null,failures:[] as Array<{id:string;error:string}>};const candidates=await sql`select id,title,image_url,provenance from sea_urchin_external_references where image_url is not null and coalesce(provenance ? 'vision_test',false)=false order by case intended_use when 'defect_variability' then 0 when 'segmentation_qa' then 1 else 2 end,created_at,id limit ${limit}` as Array<{id:string;title:string;image_url:string;provenance:Record<string,unknown>|null}>;let succeeded=0,failed=0;const failures:Array<{id:string;error:string}>=[];for(const row of candidates){try{const ai=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model,temperature:0,messages:[{role:'user',content:[{type:'text',text:analysisPrompt},{type:'image_url',image_url:{url:row.image_url,detail:'high'}}]}]})});if(!ai.ok){failed++;failures.push({id:row.id,error:`OpenAI ${ai.status}`});continue}const parsed=parseVisualAnalysis(chatOutput(await ai.json()));const vision={status:'pending_quality_review',analyzed_at:new Date().toISOString(),engine:'openai_external_uni_review_v1',provider:'openai',model,confidence:parsed.confidence,recommendation:'ready_for_quality_review',observed:{visibleProduct:parsed.visibleProduct,colorFamily:parsed.colorFamily,colorUniformity:parsed.colorUniformity,structure:parsed.structure,surfaceMoisture:parsed.surfaceMoisture,presentation:parsed.presentation,foreignMaterialVisible:parsed.foreignMaterialVisible,contextRisk:parsed.contextRisk},summary:parsed.summary,operational_evidence:false,automatic_training:false,human_decision_required:true};await sql`update sea_urchin_external_references set provenance=coalesce(provenance,'{}'::jsonb)||jsonb_build_object('vision_test',${JSON.stringify(vision)}::jsonb),updated_at=now() where id=${row.id}`;succeeded++}catch(error){failed++;failures.push({id:row.id,error:error instanceof Error?error.message:'analysis_failed'})}}const remainingRows=await sql`select count(*)::int as n from sea_urchin_external_references where image_url is not null and coalesce(provenance ? 'vision_test',false)=false` as Array<{n:number}>;return{configured:true,model,processed:candidates.length,succeeded,failed,remaining:Number(remainingRows[0]?.n??0),failures}}

export default async function handler(req:Request,res:Response){
 res.setHeader('Cache-Control','no-store')
 try{
  const operator=await requireOperator(req)
  if(!operator)return res.status(401).json({ok:false,error:'Sesión requerida'})
  if(!['admin','quality'].includes(operator.role))return res.status(403).json({ok:false,error:'Sólo Calidad o Administración puede revisar referencias externas'})
  const body=parseBody(req.body)
  if(req.method==='POST'&&body.action==='analyze_pending'){
   const requested=typeof body.limit==='number'&&Number.isFinite(body.limit)?Math.round(body.limit):5
   const result=await analyzePendingReferences(getSql(),Math.max(1,Math.min(5,requested)))
   if(!result.configured)return res.status(503).json({ok:false,error:'OPENAI_API_KEY no está configurada para preparar resultados Vision',analysis:result})
   return res.status(200).json({ok:true,analysis:result,semantics:{derivedEvidence:true,humanDecisionRequired:true,operationalEvidence:false,automaticTraining:false}})
  }
  if(req.method==='POST'){
   const referenceId=typeof body.referenceId==='string'?body.referenceId.trim():''
   const decision=body.decision==='accepted'||body.decision==='rejected'?body.decision:null
   const rejectionReason=typeof body.rejectionReason==='string'&&body.rejectionReason.trim()?body.rejectionReason.trim():null
   const note=typeof body.note==='string'&&body.note.trim()?body.note.trim().slice(0,1000):null
   if(!referenceId||!decision)return res.status(400).json({ok:false,error:'Referencia y decisión son obligatorias'})
   if(decision==='rejected'&&(!rejectionReason||!rejectionReasons.has(rejectionReason)))return res.status(400).json({ok:false,error:'Selecciona un motivo de rechazo válido'})
   if(decision==='accepted'&&rejectionReason)return res.status(400).json({ok:false,error:'Una aprobación no debe registrar motivo de rechazo'})
   if(decision==='rejected'&&rejectionReason==='otro'&&!note)return res.status(400).json({ok:false,error:'Describe el motivo cuando seleccionas Otro'})
   const exists=await getSql()`select id from sea_urchin_external_references where id=${referenceId} limit 1`
   if(!Array.isArray(exists)||!exists[0])return res.status(404).json({ok:false,error:'Referencia Uni no encontrada'})
   const provenance={source:'quality_human_review',operatorEmail:operator.email,operatorName:operator.fullName,operationalEvidence:false,automaticTraining:false}
   const rows=await getSql()`insert into sea_urchin_external_reference_reviews(reference_id,decision,rejection_reason,note,reviewed_by,provenance) values (${referenceId},${decision},${rejectionReason},${note},${operator.id},${JSON.stringify(provenance)}::jsonb) returning id,reference_id,decision,rejection_reason,note,reviewed_by,reviewed_at,provenance`
   return res.status(201).json({ok:true,review:Array.isArray(rows)?rows[0]:null,semantics:{humanDecision:true,operationalEvidence:false,automaticTraining:false}})
  }
  if(req.method!=='GET'){res.setHeader('Allow','GET, POST');return res.status(405).json({ok:false,error:'Método no permitido'})}
  const rows=await getSql()`select r.id,r.title,r.source_page,r.image_url,r.source_type,r.license,r.attribution,r.scene,r.intended_use,r.quality_status,r.official_grade,r.notes,r.provenance,r.created_at,r.updated_at,case when rv.id is null then null else jsonb_build_object('decision',rv.decision,'rejection_reason',rv.rejection_reason,'note',rv.note,'reviewed_by',rv.reviewed_by,'reviewed_at',rv.reviewed_at) end as latest_review from sea_urchin_external_references r left join lateral (select id,decision,rejection_reason,note,reviewed_by,reviewed_at from sea_urchin_external_reference_reviews where reference_id=r.id order by reviewed_at desc,id desc limit 1) rv on true order by r.created_at,r.id` as ReferenceRow[]
  const references=(Array.isArray(rows)?rows:[]).map(row=>({...row,...reviewPriority(row)})).sort((a,b)=>b.reviewPriority-a.reviewPriority||a.id.localeCompare(b.id))
  const pending=references.filter(item=>!item.latest_review),reviewed=references.filter(item=>item.latest_review),accepted=reviewed.filter(item=>item.latest_review?.decision==='accepted').length,rejected=reviewed.filter(item=>item.latest_review?.decision==='rejected').length,analyzed=references.filter(item=>item.visionTest?.status==='pending_quality_review'),unanalyzed=references.filter(item=>item.image_url&&!item.visionTest)
  const reasonCounts=new Map<string,number>();for(const item of reviewed){const reason=item.latest_review?.rejection_reason;if(reason)reasonCounts.set(reason,(reasonCounts.get(reason)??0)+1)}
  const rejectionReasonsObserved=[...reasonCounts.entries()].map(([reason,count])=>({reason,count})).sort((a,b)=>b.count-a.count||a.reason.localeCompare(b.reason))
  const qualityKnowledge=reviewed.length?{reviewed:reviewed.length,accepted,rejected,acceptanceRate:accepted/reviewed.length,rejectionReasons:rejectionReasonsObserved,basis:'latest_human_quality_review_per_reference',interpretation:'Resumen derivado exclusivamente desde decisiones humanas de Calidad/Admin. No mide accuracy del modelo ni define Grade.',automaticTraining:false}:null
  const compared=reviewed.filter(item=>item.visionTest),compatible=compared.filter(item=>item.visionTest?.recommendation==='visually_consistent_with_test_reference'),cautious=compared.filter(item=>item.visionTest?.recommendation!=='visually_consistent_with_test_reference')
  const visionQualityComparison=compared.length?{compared:compared.length,compatibleAccepted:compatible.filter(item=>item.latest_review?.decision==='accepted').length,compatibleRejected:compatible.filter(item=>item.latest_review?.decision==='rejected').length,cautionAccepted:cautious.filter(item=>item.latest_review?.decision==='accepted').length,cautionRejected:cautious.filter(item=>item.latest_review?.decision==='rejected').length,basis:'same_external_reference_with_persisted_vision_test_and_latest_human_quality_review',interpretation:'Matriz observada entre recomendación visual y decisión humana. "Requiere revisión" es una señal de cautela, no una predicción de rechazo; por eso esto no es accuracy, sensibilidad ni especificidad.',authority:'human_quality',automaticTraining:false}:null
  const visionIntel=deriveVisionIntel(references)
  return res.status(200).json({ok:true,references,reviewQueue:{total:references.length,pending:pending.length,reviewed:reviewed.length,analyzedPending:pending.filter(item=>item.visionTest?.status==='pending_quality_review').length,analyzed:analyzed.length,unanalyzed:unanalyzed.length,highPriority:pending.filter(item=>item.reviewPriority>=50).length,firstBatch:pending.slice(0,12).map(item=>item.id),rule:'Prioridad derivada sólo desde contexto/provenance; no implica calidad, Grade ni rechazo.'},visionIntel,qualityKnowledge,visionQualityComparison,semantics:{operationalEvidence:false,humanQualityLabels:true,derivedKnowledge:qualityKnowledge!==null,visionIntel:visionIntel!==null,visionComparison:visionQualityComparison!==null,derivedVisionEvidence:analyzed.length>0,automaticTraining:false,note:'Vision prepara evidencia visual y puede resumir patrones observados del dataset; sólo Calidad/Admin crea accepted/rejected. Ningún agregado Vision equivale a Grade, aceptación o evidencia operacional.'}})
 }catch(error){const message=error instanceof Error?error.message:'';const missingSchema=message.includes('sea_urchin_external_references')||message.includes('sea_urchin_external_reference_reviews');return res.status(missingSchema?503:500).json({ok:false,error:missingSchema?'Falta aplicar la migración de referencias externas Uni':'No fue posible procesar referencias externas Uni'})}
}
