import {requireOperator,type SessionOperator} from './_auth.js'
import {hasPlantAccess} from './_plants.js'
import {getSql} from './_db.js'

type Request={method?:string;body?:unknown;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type Input={action?:unknown;receptionId?:unknown;runId?:unknown;stage?:unknown;actualTemperatureC?:unknown;actualDurationSeconds?:unknown;status?:unknown;note?:unknown;grade?:unknown;fingerClass?:unknown;colorCode?:unknown;colorStatus?:unknown;xrayStatus?:unknown;packingFormat?:unknown;outputKg?:unknown;labelCode?:unknown;product?:unknown;lotCode?:unknown;netKg?:unknown;destination?:unknown;salesOrderId?:unknown;mismatchReason?:unknown;sourceMessageId?:unknown;sourceDocumentUrl?:unknown}
const text=(v:unknown,max=500)=>String(v??'').trim().slice(0,max)
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const finite=(v:unknown)=>{if(v==null||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
function canWrite(o:SessionOperator){return ['admin','operations','quality'].includes(o.role)}
function visible(o:SessionOperator,plantId:unknown){return o.role==='admin'||typeof plantId!=='string'||!plantId||hasPlantAccess(o,plantId)}
async function accessibleRun(runId:string,o:SessionOperator){const sql=getSql(),rows=await sql`select u.id,r.plant_id from sea_urchin_process_runs u join receptions r on r.id=u.reception_id where u.id=${runId}::uuid limit 1`;const row=Array.isArray(rows)?rows[0] as {id?:string;plant_id?:unknown}|undefined:undefined;return row&&visible(o,row.plant_id)?row:null}
export default async function handler(req:Request,res:Response){res.setHeader('Cache-Control','no-store');try{const operator=await requireOperator(req);if(!operator)return res.status(401).json({ok:false,error:'Sesión requerida'});if(req.method==='GET')return list(res,operator);if(req.method==='POST')return mutate(req,res,operator);res.setHeader('Allow','GET, POST');return res.status(405).json({ok:false,error:'Método no permitido'})}catch(error){const message=error instanceof Error?error.message:'';return res.status(message.includes('sea_urchin_')?503:500).json({ok:false,error:message.includes('sea_urchin_')?'Falta aplicar la migración de proceso de erizo':'No fue posible cargar proceso de erizo'})}}
async function list(res:Response,operator:SessionOperator){const sql=getSql(),admin=operator.role==='admin',plantIds=operator.plantIds;const [runsRaw,candidatesRaw]=await Promise.all([
 sql`select u.id,u.reception_id,u.status,u.grade,u.finger_class,u.color_code,u.color_status,u.xray_status,u.packing_format,u.output_kg,u.notes,u.updated_at,r.reception_number,r.plant_id,r.species,r.received_at,p.legal_name supplier,coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'stage',s.stage,'sequenceNo',s.sequence_no,'targetTemperatureC',s.target_temperature_c,'targetDurationSeconds',s.target_duration_seconds,'actualTemperatureC',s.actual_temperature_c,'actualDurationSeconds',s.actual_duration_seconds,'status',s.status,'note',s.note,'evidenceUrl',s.evidence_url,'checkedAt',s.checked_at) order by s.sequence_no) from sea_urchin_stage_checks s where s.run_id=u.id),'[]'::jsonb) stages,coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'labelCode',l.label_code,'product',l.product,'grade',l.grade,'lotCode',l.lot_code,'netKg',l.net_kg,'destination',l.destination,'status',l.status,'mismatchReason',l.mismatch_reason,'sourceDocumentUrl',l.source_document_url) order by l.created_at desc) from sea_urchin_labels l where l.run_id=u.id),'[]'::jsonb) labels from sea_urchin_process_runs u join receptions r on r.id=u.reception_id join parties p on p.id=r.supplier_id where ${admin} or r.plant_id=any(${plantIds}::text[]) order by r.received_at desc`,
 sql`select r.id,r.reception_number,r.plant_id,r.species,r.received_at,p.legal_name supplier,coalesce(r.accepted_kg,greatest(0,r.gross_kg-r.tare_kg)) available_kg from receptions r join parties p on p.id=r.supplier_id where lower(r.species) like '%eriz%' and not exists(select 1 from sea_urchin_process_runs u where u.reception_id=r.id) and (${admin} or r.plant_id=any(${plantIds}::text[])) order by r.received_at desc limit 200`
]);return res.status(200).json({ok:true,runs:Array.isArray(runsRaw)?runsRaw:[],candidates:Array.isArray(candidatesRaw)?candidatesRaw:[],permissions:{canWrite:canWrite(operator)}})}
async function mutate(req:Request,res:Response,operator:SessionOperator){if(!canWrite(operator))return res.status(403).json({ok:false,error:'Acción no autorizada'});const input=(req.body??{}) as Input,action=text(input.action,40),sql=getSql();
 if(action==='start'){const receptionId=text(input.receptionId,40);if(!uuid.test(receptionId))return res.status(400).json({ok:false,error:'Recepción inválida'});const scope=await sql`select id,plant_id,species from receptions where id=${receptionId}::uuid limit 1`;const r=Array.isArray(scope)?scope[0] as {id?:string;plant_id?:unknown;species?:unknown}|undefined:undefined;if(!r||!visible(operator,r.plant_id)||!String(r.species??'').toLowerCase().includes('eriz'))return res.status(404).json({ok:false,error:'Recepción de erizo no disponible'});const rows=await sql`insert into sea_urchin_process_runs(reception_id,created_by,created_by_operator_id) values(${receptionId}::uuid,${operator.fullName},${operator.id}::uuid) on conflict(reception_id) do update set updated_at=now() returning id`;const run=Array.isArray(rows)?rows[0] as {id?:string}|undefined:undefined;if(!run?.id)return res.status(500).json({ok:false,error:'No fue posible iniciar proceso'});await sql`select ensure_sea_urchin_stage_checks(${run.id}::uuid)`;return res.status(201).json({ok:true,runId:run.id})}
 const runId=text(input.runId,40);if(!uuid.test(runId)||!await accessibleRun(runId,operator))return res.status(404).json({ok:false,error:'Proceso no disponible'});
 if(action==='stage'){const stage=text(input.stage,40),status=text(input.status,24),temp=finite(input.actualTemperatureC),duration=finite(input.actualDurationSeconds),note=text(input.note,700);if(!['pinching','blanching','thermal_shock','sanitary_break','dripping','draining','molding','color','xray','freezing','packing'].includes(stage)||!['pending','ok','deviation','hold','not_applicable'].includes(status))return res.status(400).json({ok:false,error:'Control de etapa inválido'});await sql`update sea_urchin_stage_checks set actual_temperature_c=${temp},actual_duration_seconds=${duration},status=${status},note=${note||null},checked_by=${operator.fullName},checked_by_operator_id=${operator.id}::uuid,checked_at=now() where run_id=${runId}::uuid and stage=${stage}`;await sql`update sea_urchin_process_runs set status=case when ${status} in ('deviation','hold') then 'hold' else status end,updated_at=now() where id=${runId}::uuid`;return res.status(200).json({ok:true})}
 if(action==='classification'){const grade=text(input.grade,2)||null,finger=text(input.fingerClass,2)||null,colorCode=text(input.colorCode,20)||null,colorStatus=text(input.colorStatus,20),xrayStatus=text(input.xrayStatus,20),packingFormat=text(input.packingFormat,80)||null,outputKg=finite(input.outputKg);if(grade&&!['A','B','C','D','E'].includes(grade)||finger&&!['A','B','C','D','E'].includes(finger)||!['pending','accepted','ng','review'].includes(colorStatus)||!['pending','passed','failed','review'].includes(xrayStatus))return res.status(400).json({ok:false,error:'Clasificación inválida'});const blocked=colorStatus==='ng'||xrayStatus==='failed';await sql`update sea_urchin_process_runs set grade=${grade},finger_class=${finger},color_code=${colorCode},color_status=${colorStatus},xray_status=${xrayStatus},packing_format=${packingFormat},output_kg=${outputKg},status=case when ${blocked} then 'hold' when ${colorStatus}='accepted' and ${xrayStatus}='passed' and ${grade} is not null then 'ready_for_packing' else status end,updated_at=now() where id=${runId}::uuid`;return res.status(200).json({ok:true})}
 if(action==='label'){const labelCode=text(input.labelCode,120),product=text(input.product,160)||null,grade=text(input.grade,2)||null,lotCode=text(input.lotCode,120)||null,netKg=finite(input.netKg),destination=text(input.destination,180)||null,salesOrderId=text(input.salesOrderId,40)||null,status=text(input.status,20),mismatch=text(input.mismatchReason,500)||null,sourceMessageId=text(input.sourceMessageId,40)||null,sourceDocumentUrl=text(input.sourceDocumentUrl,1000)||null;if(!labelCode||grade&&!['A','B','C','D','E'].includes(grade)||!['pending','validated','mismatch','blocked'].includes(status)||salesOrderId&&!uuid.test(salesOrderId)||sourceMessageId&&!uuid.test(sourceMessageId))return res.status(400).json({ok:false,error:'Etiqueta inválida'});await sql`insert into sea_urchin_labels(run_id,label_code,product,grade,lot_code,net_kg,destination,sales_order_id,status,mismatch_reason,source_message_id,source_document_url,validated_by,validated_by_operator_id,validated_at) values(${runId}::uuid,${labelCode},${product},${grade},${lotCode},${netKg},${destination},${salesOrderId}::uuid,${status},${mismatch},${sourceMessageId}::uuid,${sourceDocumentUrl},${operator.fullName},${operator.id}::uuid,case when ${status}='pending' then null else now() end) on conflict(run_id,label_code) do update set product=excluded.product,grade=excluded.grade,lot_code=excluded.lot_code,net_kg=excluded.net_kg,destination=excluded.destination,sales_order_id=excluded.sales_order_id,status=excluded.status,mismatch_reason=excluded.mismatch_reason,source_message_id=excluded.source_message_id,source_document_url=excluded.source_document_url,validated_by=excluded.validated_by,validated_by_operator_id=excluded.validated_by_operator_id,validated_at=excluded.validated_at`;if(status==='mismatch'||status==='blocked')await sql`update sea_urchin_process_runs set status='hold',updated_at=now() where id=${runId}::uuid`;return res.status(200).json({ok:true})}
 return res.status(400).json({ok:false,error:'Acción inválida'})}
