import {requireOperator,type SessionOperator} from './_auth.js'
import {getSql} from './_db.js'

type Request={method?:string;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type Event={id:string;occurredAt:string;module:string;kind:string;title:string;detail:string;plantId?:string;actor?:string;historical?:boolean;severity?:'normal'|'attention'|'critical';metrics?:Record<string,number|string|null>}
type ReceptionRow={id:string;reception_number:string|number;plant_id:string|null;species:string;guide_kg:string|number|null;accepted_kg:string|number|null;status:string;received_at:string;supplier:string}
type SettlementRow={id:string;status:string;gross_amount_clp:string|number;net_amount_clp:string|number|null;created_at:string;settled_at:string|null;created_by:string|null;reception_number:string|number;plant_id:string|null;supplier:string}
type CreditRow={id:string;request_number:string|number;amount_clp:string|number;reason:string;status:string;requested_at:string;requested_by:string|null;supplier:string}
type MovementRow={id:string;kind:string;amount_clp:string|number;occurred_at:string;created_by:string|null;supplier:string}
type ApprovalRow={id:string;entity_type:string;action:string;comment:string|null;acted_by:string;acted_at:string}
type ImportRow={id:string;file_name:string;periods:string[];plant_ids:string[];row_count:number;published_at:string;published_by:string;reverted_at:string|null}
type LineRow={id:string;name:string;family:string;status:string;updated_at:string}
type OperatorRow={id:string;full_name:string;role:string;created_at:string;updated_at:string}
type HistoricalRow={source_row:number;record_status:'operational'|'void';event_date:string|null;guide_number:string|null;supplier_name:string|null;supplier_original:string|null;extraction_zone:string|null;process_site_original:string|null;plant_id:string|null;lot_code:string;guide_kg:string|number|null;received_kg:string|number|null;difference_kg:string|number|null;client:string|null;observations:string|null}
type HistoricalStats={total:string|number;voids:string|number;first_event_date:string|null;last_event_date:string|null}
function allowed(operator:SessionOperator,plantId?:unknown){return operator.role==='admin'||typeof plantId!=='string'||!plantId||operator.plantIds.includes(plantId)}
function rows<T>(value:unknown){return (Array.isArray(value)?value:[]) as T[]}
function historicalSeverity(row:HistoricalRow):Event['severity']{const guide=Number(row.guide_kg??0),received=Number(row.received_kg??0),text=(row.observations??'').toLowerCase();if((guide>0&&received>guide)||/(vidrio|tijereta|plastico|plástico)/.test(text))return 'critical';if(/(rechaz|mala calidad|respaldo|sin producto|devuel|deshidrat)/.test(text)||row.guide_number?.toLowerCase()==='sin guia'||(guide>0&&Math.abs(guide-received)/guide>.15))return 'attention';return 'normal'}
function historicalDetail(row:HistoricalRow){const parts=[`Guía ${row.guide_number??'s/n'}`];if(row.guide_kg!=null)parts.push(`${Number(row.guide_kg).toLocaleString('es-CL',{maximumFractionDigits:1})} kg guía`);if(row.received_kg!=null)parts.push(`${Number(row.received_kg).toLocaleString('es-CL',{maximumFractionDigits:1})} kg recibidos`);if(row.process_site_original)parts.push(`Proceso ${row.process_site_original}`);if(row.client)parts.push(`Cliente ${row.client}`);if(row.observations)parts.push(row.observations);return parts.join(' · ')}
export default async function handler(request:Request,response:Response){response.setHeader('Cache-Control','no-store');if(request.method!=='GET'){response.setHeader('Allow','GET');return response.status(405).json({ok:false,error:'Método no permitido'})}try{const operator=await requireOperator(request);if(!operator)return response.status(401).json({ok:false,error:'Sesión requerida'});const sql=getSql();const [historicalRaw,historicalStatsRaw,receptionsRaw,settlementsRaw,creditsRaw,movementsRaw,approvalsRaw,importsRaw,linesRaw,operatorsRaw]=await Promise.all([
 sql`select source_row,record_status,event_date,guide_number,supplier_name,supplier_original,extraction_zone,process_site_original,plant_id,lot_code,guide_kg,received_kg,difference_kg,client,observations from historical_production_records order by event_date desc nulls last,source_row desc limit 1000`,
 sql`select count(*) total,count(*) filter(where record_status='void') voids,min(event_date) first_event_date,max(event_date) last_event_date from historical_production_records`,
 sql`select r.id,r.reception_number,r.plant_id,r.species,r.guide_kg,r.accepted_kg,r.status,r.received_at,p.legal_name supplier from receptions r join parties p on p.id=r.supplier_id order by r.received_at desc limit 500`,
 sql`select s.id,s.status,s.gross_amount_clp,s.net_amount_clp,s.created_at,s.settled_at,s.created_by,r.reception_number,r.plant_id,p.legal_name supplier from settlements s join receptions r on r.id=s.reception_id join parties p on p.id=s.supplier_id order by s.created_at desc limit 500`,
 sql`select cr.id,cr.request_number,cr.amount_clp,cr.reason,cr.status,cr.requested_at,cr.requested_by,p.legal_name supplier from credit_requests cr join credit_accounts ca on ca.id=cr.account_id join parties p on p.id=ca.party_id order by cr.requested_at desc limit 500`,
 sql`select cm.id,cm.kind,cm.amount_clp,cm.occurred_at,cm.created_by,p.legal_name supplier from credit_movements cm join credit_accounts ca on ca.id=cm.account_id join parties p on p.id=ca.party_id order by cm.occurred_at desc limit 500`,
 sql`select id,entity_type,action,comment,acted_by,acted_at from approval_actions order by acted_at desc limit 500`,
 sql`select id,file_name,periods,plant_ids,row_count,published_at,published_by,reverted_at from plant_import_batches order by published_at desc limit 300`,
 sql`select id,name,family,status,updated_at from production_lines order by updated_at desc limit 100`,
 sql`select id,full_name,role,created_at,updated_at from operators order by created_at desc limit 100`
]);const events:Event[]=[];
for(const row of rows<HistoricalRow>(historicalRaw)){if(row.record_status!=='operational'||!row.event_date)continue;if(row.plant_id&&!allowed(operator,row.plant_id))continue;const supplier=row.supplier_name??row.supplier_original??'Proveedor no identificado';events.push({id:`historical-${row.source_row}`,occurredAt:`${String(row.event_date).slice(0,10)}T12:00:00Z`,module:'recepcion',kind:'lote-historico',title:`${row.lot_code} · ${supplier}`,detail:historicalDetail(row),plantId:row.plant_id??undefined,historical:true,severity:historicalSeverity(row),metrics:{guideKg:row.guide_kg==null?null:Number(row.guide_kg),receivedKg:row.received_kg==null?null:Number(row.received_kg),differenceKg:row.difference_kg==null?null:Number(row.difference_kg)}})}
for(const row of rows<ReceptionRow>(receptionsRaw)){if(!allowed(operator,row.plant_id))continue;events.push({id:`reception-${row.id}`,occurredAt:row.received_at,module:'recepcion',kind:'recepcion',title:`Recepción REC-${row.reception_number} · ${row.supplier}`,detail:`${row.species} · ${Number(row.accepted_kg??0).toLocaleString('es-CL')} kg aceptados`,plantId:row.plant_id??undefined,severity:row.status==='rejected'?'attention':'normal',metrics:{guideKg:Number(row.guide_kg??0),acceptedKg:Number(row.accepted_kg??0)}})}
if(['admin','finance','operations'].includes(operator.role))for(const row of rows<SettlementRow>(settlementsRaw)){if(!allowed(operator,row.plant_id))continue;events.push({id:`settlement-${row.id}`,occurredAt:row.settled_at??row.created_at,module:'liquidaciones',kind:'liquidacion',title:`Liquidación REC-${row.reception_number} · ${row.supplier}`,detail:`${row.status} · bruto $${Number(row.gross_amount_clp??0).toLocaleString('es-CL')}${row.net_amount_clp!=null?` · neto $${Number(row.net_amount_clp).toLocaleString('es-CL')}`:''}`,plantId:row.plant_id??undefined,actor:row.created_by??undefined,severity:row.status==='rejected'?'attention':'normal'})}
if(['admin','finance','operations'].includes(operator.role))for(const row of rows<CreditRow>(creditsRaw))events.push({id:`credit-${row.id}`,occurredAt:row.requested_at,module:'creditos',kind:'anticipo',title:`Anticipo ANT-${row.request_number} · ${row.supplier}`,detail:`$${Number(row.amount_clp).toLocaleString('es-CL')} · ${row.reason} · ${row.status}`,actor:row.requested_by??undefined,severity:row.status==='rejected'?'attention':'normal'})
if(['admin','finance','operations'].includes(operator.role))for(const row of rows<MovementRow>(movementsRaw))events.push({id:`movement-${row.id}`,occurredAt:row.occurred_at,module:'creditos',kind:'movimiento',title:`Movimiento de crédito · ${row.supplier}`,detail:`${row.kind} · $${Number(row.amount_clp).toLocaleString('es-CL')}`,actor:row.created_by??undefined})
for(const row of rows<ApprovalRow>(approvalsRaw))events.push({id:`approval-${row.id}`,occurredAt:row.acted_at,module:'decisiones',kind:'decision',title:`${row.action} · ${row.entity_type}`,detail:row.comment||'Decisión registrada',actor:row.acted_by,severity:row.action==='rejected'?'attention':'normal'})
for(const row of rows<ImportRow>(importsRaw)){const visiblePlants=(row.plant_ids??[]).filter(id=>allowed(operator,id));if(operator.role!=='admin'&&!visiblePlants.length)continue;events.push({id:`import-${row.id}`,occurredAt:row.reverted_at??row.published_at,module:'datos',kind:row.reverted_at?'reversion':'importacion',title:row.reverted_at?`Importación revertida · ${row.file_name}`:`Datos publicados · ${row.file_name}`,detail:`${row.row_count} filas · ${(row.periods??[]).join(', ')}`,actor:row.published_by,severity:row.reverted_at?'attention':'normal'})}
for(const row of rows<LineRow>(linesRaw))events.push({id:`line-${row.id}`,occurredAt:row.updated_at,module:'produccion',kind:'linea',title:`${row.name} · ${row.status}`,detail:row.family})
if(operator.role==='admin'||operator.role==='operations')for(const row of rows<OperatorRow>(operatorsRaw))events.push({id:`operator-${row.id}`,occurredAt:row.updated_at??row.created_at,module:'equipo',kind:'identidad',title:`${row.full_name} · ${row.role}`,detail:'Identidad operacional registrada o actualizada'})
events.sort((a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt));const stats=rows<HistoricalStats>(historicalStatsRaw)[0];return response.status(200).json({ok:true,events,continuity:{historicalStart:stats?.first_event_date??null,historicalEnd:stats?.last_event_date??null,historicalRecords:Number(stats?.total??0),voidRecords:Number(stats?.voids??0),live:true,total:events.length}})}catch(error){const message=error instanceof Error?error.message:'';const migration=message.includes('historical_production_records');return response.status(message.includes('DATABASE_URL')||migration?503:500).json({ok:false,error:message.includes('DATABASE_URL')?'Base de datos no conectada':migration?'Falta aplicar la migración 006_historical_production.sql':'No fue posible construir la línea operacional'})}}
