import {requireOperator,type SessionOperator} from './_auth.js'
import {getSql} from './_db.js'

type Request={method?:string;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type Event={id:string;occurredAt:string;module:string;kind:string;title:string;detail:string;plantId?:string;actor?:string;historical?:boolean;severity?:'normal'|'attention'|'critical';metrics?:Record<string,number|string|null>}
const history=[
 ['2025-03-31','Marzo 2025',255,244,4.31],['2025-04-30','Abril 2025',9280.2,8888.5,4.22],['2025-05-31','Mayo 2025',13130.1,12579.7,4.19],['2025-06-30','Junio 2025',12570.2,12183.6,3.08],['2025-07-31','Julio 2025',14510.4,13847.4,4.57],['2025-08-31','Agosto 2025',22843.1,22205.3,2.79],['2025-09-30','Septiembre 2025',8631.2,8231.5,4.63],['2025-10-31','Octubre 2025',1922.2,1865.6,2.94],
] as const
const historicalExceptions:Event[]=[
 {id:'hist-ex-377',occurredAt:'2025-09-08T12:00:00Z',module:'calidad',kind:'excepcion',title:'Peso recibido mayor a guía',detail:'Lote md330080925 · 399,6 kg guía · 482,0 kg recibidos',historical:true,severity:'critical'},
 {id:'hist-ex-143',occurredAt:'2025-06-17T12:00:00Z',module:'recepcion',kind:'documentacion',title:'Respaldo documental',detail:'Lote md137170625 · guía usada para reempacar, sin producto nuevo',historical:true,severity:'attention'},
 {id:'hist-ex-365',occurredAt:'2025-09-05T12:00:00Z',module:'calidad',kind:'rechazo',title:'Lote solo de rechazo',detail:'Lote fbc320050925 · 144,0 kg sin kilos recibidos conciliados',historical:true,severity:'attention'},
 {id:'hist-ex-006',occurredAt:'2025-04-08T12:00:00Z',module:'calidad',kind:'inocuidad',title:'Hallazgo de inocuidad',detail:'Lote mo04080425 · vidrio y tijereta reportados',historical:true,severity:'critical'},
]
function allowed(operator:SessionOperator,plantId?:unknown){return operator.role==='admin'||typeof plantId!=='string'||!plantId||operator.plantIds.includes(plantId)}
export default async function handler(request:Request,response:Response){response.setHeader('Cache-Control','no-store');if(request.method!=='GET'){response.setHeader('Allow','GET');return response.status(405).json({ok:false,error:'Método no permitido'})}try{const operator=await requireOperator(request);if(!operator)return response.status(401).json({ok:false,error:'Sesión requerida'});const sql=getSql();const [receptions,settlements,credits,movements,approvals,imports,lines,operators]=await Promise.all([
 sql`select r.id,r.reception_number,r.plant_id,r.species,r.guide_kg,r.accepted_kg,r.status,r.received_at,p.legal_name supplier from receptions r join parties p on p.id=r.supplier_id order by r.received_at desc limit 500`,
 sql`select s.id,s.status,s.gross_amount_clp,s.net_amount_clp,s.created_at,s.settled_at,s.created_by,r.reception_number,r.plant_id,p.legal_name supplier from settlements s join receptions r on r.id=s.reception_id join parties p on p.id=s.supplier_id order by s.created_at desc limit 500`,
 sql`select cr.id,cr.request_number,cr.amount_clp,cr.reason,cr.status,cr.requested_at,cr.requested_by,p.legal_name supplier from credit_requests cr join credit_accounts ca on ca.id=cr.account_id join parties p on p.id=ca.party_id order by cr.requested_at desc limit 500`,
 sql`select cm.id,cm.kind,cm.amount_clp,cm.occurred_at,cm.created_by,p.legal_name supplier from credit_movements cm join credit_accounts ca on ca.id=cm.account_id join parties p on p.id=ca.party_id order by cm.occurred_at desc limit 500`,
 sql`select id,entity_type,action,comment,acted_by,acted_at from approval_actions order by acted_at desc limit 500`,
 sql`select id,file_name,periods,plant_ids,row_count,published_at,published_by,reverted_at from plant_import_batches order by published_at desc limit 300`,
 sql`select id,name,family,status,updated_at from production_lines order by updated_at desc limit 100`,
 sql`select id,full_name,role,created_at,updated_at from operators order by created_at desc limit 100`
 ]);const events:Event[]=[];
 for(const row of receptions as any[]){if(!allowed(operator,row.plant_id))continue;events.push({id:`reception-${row.id}`,occurredAt:row.received_at,module:'recepcion',kind:'recepcion',title:`Recepción REC-${row.reception_number} · ${row.supplier}`,detail:`${row.species} · ${Number(row.accepted_kg??0).toLocaleString('es-CL')} kg aceptados`,plantId:row.plant_id,severity:row.status==='rejected'?'attention':'normal',metrics:{guideKg:Number(row.guide_kg??0),acceptedKg:Number(row.accepted_kg??0)}})}
 if(['admin','finance','operations'].includes(operator.role))for(const row of settlements as any[]){if(!allowed(operator,row.plant_id))continue;events.push({id:`settlement-${row.id}`,occurredAt:row.settled_at??row.created_at,module:'liquidaciones',kind:'liquidacion',title:`Liquidación REC-${row.reception_number} · ${row.supplier}`,detail:`${row.status} · bruto $${Number(row.gross_amount_clp??0).toLocaleString('es-CL')}${row.net_amount_clp!=null?` · neto $${Number(row.net_amount_clp).toLocaleString('es-CL')}`:''}`,plantId:row.plant_id,actor:row.created_by,severity:row.status==='rejected'?'attention':'normal'})}
 if(['admin','finance','operations'].includes(operator.role))for(const row of credits as any[])events.push({id:`credit-${row.id}`,occurredAt:row.requested_at,module:'creditos',kind:'anticipo',title:`Anticipo ANT-${row.request_number} · ${row.supplier}`,detail:`$${Number(row.amount_clp).toLocaleString('es-CL')} · ${row.reason} · ${row.status}`,actor:row.requested_by,severity:row.status==='rejected'?'attention':'normal'})
 if(['admin','finance','operations'].includes(operator.role))for(const row of movements as any[])events.push({id:`movement-${row.id}`,occurredAt:row.occurred_at,module:'creditos',kind:'movimiento',title:`Movimiento de crédito · ${row.supplier}`,detail:`${row.kind} · $${Number(row.amount_clp).toLocaleString('es-CL')}`,actor:row.created_by})
 for(const row of approvals as any[])events.push({id:`approval-${row.id}`,occurredAt:row.acted_at,module:'decisiones',kind:'decision',title:`${row.action} · ${row.entity_type}`,detail:row.comment||'Decisión registrada',actor:row.acted_by,severity:row.action==='rejected'?'attention':'normal'})
 for(const row of imports as any[]){const visiblePlants=(row.plant_ids??[]).filter((id:string)=>allowed(operator,id));if(operator.role!=='admin'&&!visiblePlants.length)continue;events.push({id:`import-${row.id}`,occurredAt:row.reverted_at??row.published_at,module:'datos',kind:row.reverted_at?'reversion':'importacion',title:row.reverted_at?`Importación revertida · ${row.file_name}`:`Datos publicados · ${row.file_name}`,detail:`${row.row_count} filas · ${(row.periods??[]).join(', ')}`,actor:row.published_by,severity:row.reverted_at?'attention':'normal'})}
 for(const row of lines as any[])events.push({id:`line-${row.id}`,occurredAt:row.updated_at,module:'produccion',kind:'linea',title:`${row.name} · ${row.status}`,detail:row.family})
 if(operator.role==='admin'||operator.role==='operations')for(const row of operators as any[])events.push({id:`operator-${row.id}`,occurredAt:row.updated_at??row.created_at,module:'equipo',kind:'identidad',title:`${row.full_name} · ${row.role}`,detail:'Identidad operacional registrada o actualizada'})
 for(const [date,label,guide,received,difference] of history)events.push({id:`hist-${date}`,occurredAt:`${date}T23:59:59Z`,module:'recepcion',kind:'periodo',title:`${label} · operación consolidada`,detail:`${guide.toLocaleString('es-CL')} kg guía · ${received.toLocaleString('es-CL')} kg recibidos · ${difference.toFixed(2)}% diferencia`,historical:true,metrics:{guideKg:guide,receivedKg:received,differencePct:difference}});events.push(...historicalExceptions);events.sort((a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt));return response.status(200).json({ok:true,events,continuity:{historicalStart:'2025-03-01',historicalEnd:'2025-10-31',live:true,total:events.length}})}catch(error){const message=error instanceof Error?error.message:'';return response.status(message.includes('DATABASE_URL')?503:500).json({ok:false,error:message.includes('DATABASE_URL')?'Base de datos no conectada':'No fue posible construir la línea operacional'})}}
