import {requireOperator,type SessionOperator} from './_auth.js'
import {hasPlantAccess} from './_plants.js'
import {getSql} from './_db.js'

type Request={method?:string;body?:unknown;query?:Record<string,string|string[]|undefined>;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
type Input={receptionId?:unknown;category?:unknown;amountClp?:unknown;quantity?:unknown;unit?:unknown;note?:unknown;occurredAt?:unknown}
const categories=new Set(['labor','energy','ice','packaging','transport','processing','other'])
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const text=(v:unknown,max=500)=>String(v??'').trim().slice(0,max)
const finite=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:null}
function one(v:string|string[]|undefined){return Array.isArray(v)?v[0]:v}
function canWrite(o:SessionOperator){return ['admin','operations','finance'].includes(o.role)}
async function access(receptionId:string,o:SessionOperator){const rows=await getSql()`select id,plant_id from receptions where id=${receptionId}::uuid limit 1`;const row=Array.isArray(rows)?rows[0] as {id?:string;plant_id?:string|null}|undefined:undefined;if(!row?.id)return null;if(o.role!=='admin'&&(!row.plant_id||!hasPlantAccess(o,row.plant_id)))return null;return row}
export default async function handler(req:Request,res:Response){res.setHeader('Cache-Control','no-store');try{const operator=await requireOperator(req);if(!operator)return res.status(401).json({ok:false,error:'Sesión requerida'});if(req.method==='GET'){const receptionId=text(one(req.query?.receptionId),40);if(!uuid.test(receptionId)||!await access(receptionId,operator))return res.status(404).json({ok:false,error:'Lote no disponible'});const rows=await getSql()`select id,reception_id,category,amount_clp,quantity,unit,note,occurred_at,created_by from transformation_costs where reception_id=${receptionId}::uuid order by occurred_at desc`;return res.status(200).json({ok:true,costs:Array.isArray(rows)?rows:[],permissions:{canWrite:canWrite(operator)}})}if(req.method==='POST'){if(!canWrite(operator))return res.status(403).json({ok:false,error:'Acción no autorizada'});const input=(req.body??{}) as Input,receptionId=text(input.receptionId,40),category=text(input.category,40),amount=finite(input.amountClp),quantity=input.quantity==null||input.quantity===''?null:finite(input.quantity),unit=text(input.unit,40)||null,note=text(input.note,1000)||null,occurredAt=text(input.occurredAt,40)||null;if(!uuid.test(receptionId)||!categories.has(category)||amount==null||amount<=0||quantity!=null&&quantity<0||!await access(receptionId,operator))return res.status(400).json({ok:false,error:'Costo de transformación inválido'});const rows=await getSql()`insert into transformation_costs(reception_id,category,amount_clp,quantity,unit,note,occurred_at,created_by) values(${receptionId}::uuid,${category},${amount},${quantity},${unit},${note},coalesce(${occurredAt}::timestamptz,now()),${operator.fullName}) returning id,category,amount_clp,quantity,unit,note,occurred_at,created_by`;return res.status(201).json({ok:true,cost:Array.isArray(rows)?rows[0]:null})}res.setHeader('Allow','GET, POST');return res.status(405).json({ok:false,error:'Método no permitido'})}catch(error){const message=error instanceof Error?error.message:'';return res.status(message.includes('transformation_costs')?503:500).json({ok:false,error:message.includes('transformation_costs')?'Falta aplicar 010_transformation_costs.sql':'No fue posible procesar costos'})}}
