import {timingSafeEqual} from 'node:crypto'
import {getSql} from './_db.js'
import {allowClientIp} from './_rate-limit.js'

declare const process:{env:Record<string,string|undefined>}
type Request={method?:string;body?:unknown;query?:Record<string,string|string[]|undefined>;headers?:Record<string,string|string[]|undefined>}
type Response={status:(code:number)=>Response;setHeader:(name:string,value:string)=>void;json:(body:unknown)=>void}
const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]:v
const text=(v:unknown,max=4000)=>String(v??'').trim().slice(0,max)
const obj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{}
const WINDOW_MS=60_000
const MAX_EVENTS_PER_WINDOW=120
const headerValue=(req:Request,name:string)=>{const value=req.headers?.[name]??req.headers?.[name.toLowerCase()];return Array.isArray(value)?value[0]??'':String(value??'')}
// The provider historically sends the shared secret as ?secret=; the header is the preferred
// channel because URLs land in access logs. Both stay valid; see docs/SECURITY_NOTES.md.
const suppliedSecret=(req:Request)=>text(headerValue(req,'x-pescamar-webhook-key'),256)||text(one(req.query?.secret),256)
const secretMatches=(configured:string,supplied:string)=>{const a=Buffer.from(configured,'utf8'),b=Buffer.from(supplied,'utf8');return a.length===b.length&&timingSafeEqual(a,b)}
function messageBody(data:Record<string,unknown>){const candidates=[data.textMessageData,obj(data.extendedTextMessageData).text,obj(data.fileMessageData).caption,obj(data.imageMessageData).caption,obj(data.videoMessageData).caption];return candidates.map(v=>text(v)).find(Boolean)??''}
function media(data:Record<string,unknown>){return ['fileMessageData','imageMessageData','videoMessageData','audioMessageData'].flatMap(key=>{const value=obj(data[key]);if(!Object.keys(value).length)return[];return[{type:key.replace('MessageData',''),url:text(value.downloadUrl??value.url,2000)||null,fileName:text(value.fileName,260)||null,mimeType:text(value.mimeType,120)||null,caption:text(value.caption,1000)||null}]})}
export default async function handler(req:Request,res:Response){res.setHeader('Cache-Control','no-store');if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({ok:false,error:'Método no permitido'})}if(!allowClientIp(req,WINDOW_MS,MAX_EVENTS_PER_WINDOW))return res.status(429).json({ok:false,error:'Demasiados eventos de webhook por minuto'});const configured=process.env.WHATSAPP_WEBHOOK_SECRET;const supplied=suppliedSecret(req);if(!configured||!supplied||!secretMatches(configured,supplied))return res.status(401).json({ok:false,error:'Webhook no autorizado'});try{const p=obj(req.body),sender=obj(p.senderData),data=obj(p.messageData),instance=obj(p.instanceData),typeWebhook=text(p.typeWebhook,80),id=text(p.idMessage,180);if(!id)return res.status(200).json({ok:true,ignored:true});const chatId=text(sender.chatId??p.chatId,180)||null,chatName=text(sender.chatName,260)||null,senderId=text(sender.sender??sender.senderId,180)||null,senderName=text(sender.senderName,260)||null,direction=typeWebhook.toLowerCase().includes('outgoing')?'outgoing':'incoming',messageType=text(data.typeMessage??typeWebhook,120)||'unknown',body=messageBody(data),timestamp=Number(p.timestamp),occurredAt=Number.isFinite(timestamp)&&timestamp>0?new Date(timestamp*1000).toISOString():new Date().toISOString(),raw=JSON.stringify({...p,instanceData:instance}),mediaJson=JSON.stringify(media(data));const sql=getSql();let channelId:string|null=null;if(chatId){const existing=await sql`select id from whatsapp_channels where external_chat_id=${chatId} limit 1`;if(Array.isArray(existing)&&existing[0])channelId=String((existing[0] as {id:string}).id);else if(chatName){const byName=await sql`select id from whatsapp_channels where lower(name)=lower(${chatName}) limit 1`;if(Array.isArray(byName)&&byName[0]){channelId=String((byName[0] as {id:string}).id);await sql`update whatsapp_channels set external_chat_id=${chatId},updated_at=now() where id=${channelId}::uuid`}}}const rows=await sql`insert into whatsapp_messages_raw(provider,provider_message_id,external_chat_id,channel_id,sender_id,sender_name,direction,message_type,text_body,media,occurred_at,raw_payload) values('green-api',${id},${chatId},${channelId}::uuid,${senderId},${senderName},${direction},${messageType},${body||null},${mediaJson}::jsonb,${occurredAt}::timestamptz,${raw}::jsonb) on conflict(provider_message_id) do nothing returning id`;return res.status(200).json({ok:true,stored:Array.isArray(rows)&&rows.length>0})}catch(error){const message=error instanceof Error?error.message:'';return res.status(message.includes('whatsapp_')?503:500).json({ok:false,error:message.includes('whatsapp_')?'Falta aplicar migración WhatsApp Intelligence':'No fue posible ingerir el webhook'})}}
